### ISSUE TITLE
爬下来之后显示的是乱码，这该怎么解决？

### ISSUE THREAD

**Issue by bossming** [dataabc/weiboSpider#1]
就像下面这样

用户信息
用户昵称：Ԭ��?
用户id�?1320135280
微博数：2636
关注数：388
粉丝数：25207674

原创微博内容�?
1:�����������ݽ���[Ү]
点赞数：88904	 转发数：10687	 评论数：5493

2:��׽��ֻ����[����]
点赞数：93028	 转发数：10276	 评论数：4415

3:��ˮ������ζ��ʲô��
点赞数：80441	 转发数：11059	 评论数：10604

4:�����⼸�뼦����
点赞数：108673	 转发数：11534	 评论数：5617

**Comment by arctanx** [comment]
中文编码的问题，修改一下encode类型

**Comment by zxu7** [comment]
我这倒是要string.decode('gbk')才能运作

**Comment by lanceyuu** [comment]
把所有encode('gbk') 的gbk都改成utf-8就好了。
