### ISSUE TITLE
需求：可否设置范围，只爬取这个区域中带有定位数据的微博？

### ISSUE THREAD

**Issue by pizzymm** [dataabc/weiboSpider#100]

**Comment by dataabc** [comment]
范围指的是时间范围还是地理范围？
如果是时间范围，可以实现但是代码可能会很复杂。
如果是地理范围，你的意思可能是给定一个位置，只爬用户在这个位置内发的位置微博。目前无法实现，因为可能没有这样的api，只能把用户的所有微博都爬下来，然后作筛选，看是否有位置微博及位置是否在范围内，效率很低。

**Comment by tangbotony** [comment]
请参考https://github.com/tangbotony/weibodata
或者私信我，可以按照时间、圈定的经纬度爬取微博数据
