### ISSUE TITLE
请问能不能把live photo作为视频下载下来啊？

### ISSUE THREAD

**Issue by soilniba** [dataabc/weiboSpider#101]
微博上有很多ios的live photo，就是图片角标上带live字样，点开之后会先动然后再变成静态图片的，
我感觉应该是ios系统会录一段视频附加到图片上，
请问能不能把这段live视频也下载下来和照片放到一起呢？

**Comment by dataabc** [comment]
感谢建议，目前还做不到这点。

live photo貌似只有ios上可以查看，其他设备上看到的都是静态图片。本程序是通过web移动端获取微博信息的，这种方式只能获取live photo 形成的静态图片，不能获取视频。所以，现在只能获取和下载 live photo中的静态图片。

虽然现在还无法实现，还是要感谢热心建议

**Comment by soilniba** [comment]
他确实是把live photo转成了一个mov视频的  不过好像在m.weibo.cn上是看不到的  只有网页版和app上才能播放

**Comment by dataabc** [comment]
是的，m.weibo.cn上没有视频。本程序是解析weibo.cn获取信息的，上面没有视频信息，所以没办法获取视频信息，只能获取live photo生成的照片

**Comment by dataabc** [comment]
我又想了下这个问题，问题已经解决了。

[免cookie版](https://github.com/dataabc/weibo-crawler)已经实现获取live photo中视频的功能了，可以获取live photo的视频url和下载live photo视频。

移动版虽然没有视频地址，但是我发现它有一个“pic_video”属性，是一个列表，每个值都是live photo 视频的关键信息，live photo中有几个视频，列表中就有几个值。视频url的前缀和后缀都是固定的，只要有了这个关键信息，三者就可以组成完整的视频地址。通过这个方法，可以获取live photo中的所有视频信息。

和下载普通视频一样，下载live photo视频的方式也是通过设置config.json文件中的original_video_download和retweet_video_download这两个参数控制的。比如设置original_video_download=1，程序就会下载原创微博中的视频和原创微博live photo中的视频，文件保存在“用户昵称/video/原创微博视频”文件夹中；设置retweet_video_download=1，程序就会下载转发微博中的视频和转发微博live photo中的视频，文件保存在“用户昵称/video/转发微博视频”文件夹中。

如果没有这个issue，我可能不会发现live photo这个问题，正是本issue让我发现并解决了问题，再次感谢热心建议。

**Comment by soilniba** [comment]
非常感谢！顺便我今天下一个微博（李沁\1809054937）的时候有一些报错，不知道是什么意思，发您看看

Progress:  45%|███████████████████████████████▍                                      | 117/261 [08:46<06:11,  2.58s/it]Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\wangr\weiboSpider\weiboSpider.py", line 597, in get_one_page
    info = selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
Progress:  45%|███████████████████████████████▋                                      | 118/261 [08:46<04:24,  1.85s/it]Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\wangr\weiboSpider\weiboSpider.py", line 597, in get_one_page
    info = selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
Progress:  46%|███████████████████████████████▉                                      | 119/261 [08:46<03:10,  1.34s/it]Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\wangr\weiboSpider\weiboSpider.py", line 597, in get_one_page
    info = selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
699条微博写入csv文件完毕,保存路径:
C:\Users\wangr\weiboSpider\weibo\李沁\1809054937.csv
699条微博写入txt文件完毕,保存路径:
C:\Users\wangr\weiboSpider\weibo\李沁\1809054937.txt
Progress:  46%|████████████████████████████████▏                                     | 120/261 [08:46<02:20,  1.01it/s]Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\wangr\weiboSpider\weiboSpider.py", line 597, in get_one_page
    info = selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'

**Comment by dataabc** [comment]
出现这个问题的原因可能是爬的太快，暂时被限制了，大约几小时后限制会自动解除。

为了解决这个问题，可以减慢爬行速度，即每爬若干页，sleep几秒。程序中已经有默认的代码了，具体是在get_weibo_info方法里，代码如下：
```
                if page - page1 == random_pages and page < page_num:
                    sleep(random.randint(6, 10))
                    page1 = page
                    random_pages = random.randint(1, 5)
```
程序默认的是每爬1页到5页，随机暂停6到10秒。你可以增加sleep，也可以加快暂停的频率，比如每爬1到3页暂停一次。这样会降低被限制的概率。

还有如果你还想继续爬（李沁\1809054937）的微博，因为你之前已经爬过很多了，可以手动设置，让程序接着上次的爬，这样会节省时间。可以打开结果文件如csv等，查看时间最久的那条微博，手动查询它所在的页码（因为用户随时都可以发微博，页码是不固定的，所以需要手动查询），然后修改get_weibo_info方法中的如下代码：
```
for page in tqdm(range(1, page_num + 1), desc='Progress'):
```
这个代码表示从第一页爬到最后一页，可以改成从上次出错的页码开始爬，以提高效率。

**Comment by soilniba** [comment]
哈哈不好意思打搅啦  我又发现一个问题   
陈意涵Estelle/2218081121  这个用户的微博又抓不下来了  一开始直接就报错
Error:  'statuses_count'
Traceback (most recent call last):
  File "weibo.py", line 841, in start
    self.get_pages()
  File "weibo.py", line 791, in get_pages
    page_count = self.get_page_count()
  File "weibo.py", line 562, in get_page_count
    weibo_count = self.user['statuses_count']
KeyError: 'statuses_count'

之前的问题我测试了一下应该是总页数太多，抓到后面就一定会报错，改成从出错页开始再抓一遍就ok了

**Comment by soilniba** [comment]
还有一个，是一些一直播的路线回访视频，不能下载下来，但会下下来一个错误的文件（应该是一个分段视频的列表），类似这条，我觉得可以直接过滤掉
https://weibo.com/1792328230/EoQ9Jdf6W?from=page_1005051792328230_profile&wvr=6&mod=weibotime

**Comment by soilniba** [comment]
还有这条微博也会产生一个错误的视频文件
https://weibo.com/1792328230/HbBss4jug?from=page_1005051792328230_profile&wvr=6&mod=weibotime&type=comment#_rnd1577889357735

csv里的信息是这样的

4327656001028224,HbBss4jug,白蛇：缘起 剧情相对粗糙一点，但是画面真的好美啊！！！狐狸的人设真的赞评里揪三个人请你去看白蛇，支持一哈国漫。（想跟朋友一起看的可以帮你多买一张（不折现，告诉我场次影院我帮你买(´･ω･`) ,"https://wx1.sinaimg.cn/large/6ad4c226gy1fz3tba6fmmj21d40nrkcg.jpg,https://wx2.sinaimg.cn/large/6ad4c226gy1fz3tbhq8yij21aw0nuquv.jpg,https://wx2.sinaimg.cn/large/6ad4c226gy1fz3tbnj2y7j21ad0nt4qp.jpg","https://f.us.sinaimg.cn/00237SV0lx07quQf9nny01041200S1vG0E010.mp4?label=mp4_ld&template=640x360.20.0&Expires=1546573107&ssig=nq6pqsMPV%2B&KID=unistore,video&tags=weibocard",,2019-01-12,iPhone X,386,233,16,,

**Comment by dataabc** [comment]
问题已经在免cookie版解决了，再次感谢热心反馈。

第一个问题，解决方案是在免cookie版添加cookie。大部分微博在不添加cookie时都可以正确获取，少部分微博是需要cookie的。原因是，在[移动版](https://m.weibo.cn/)，大部分微博都可以匿名访问，少部分需要登录才能访问。陈意涵Estelle的用户信息就是需要登录才能查看的。现在添加了cookie参数，可填可不填，不填可以获取大部分用户的大部分微博，填了可以获取全部微博，陈意涵Estelle的微博是需要填的，具体cookie设置见<https://github.com/dataabc/weibo-crawler#3程序设置>中的“设置cookie”部分；

第二和第三个问题，其实都是视频url获取的问题，程序把不正确的url当作了视频地址，现在两个问题一块解决了，添加了过滤，可以避免这种情况了。

**Comment by soilniba** [comment]
ok都解决了！非常感谢！
然后我觉得，您这个工具，有一个非常值得推广的点是，
把图片全部下载下来一起看真的是太太太太太太太太爽了！简直是颠覆微博使用体验！
比直接在微博上看图至少爽10倍！只要随便找一个看图软件（比如xnview），然后无论是快速批量浏览、单张图快速来回翻看，
都非常非常非常的，令人愉悦！
我觉得这值得推荐给每个使用微博的人用一下！非常感谢！

**Comment by dataabc** [comment]
感谢支持。
很多功能都是使用者提的需求，比如图片和视频相关的问题。如果大家有需求，而且又可以用代码实现，我会尽量满足大家的需求。很多功能和问题都是热心网友发现的，比如上面几个你提的建议，都非常好。正是因为有大家很多热心的建议，代码才会越来越完善，再次感谢支持。

**Comment by Createitv** [comment]
请问一下live视频下载下载的格式是什么呢：MOV么
