### ISSUE TITLE
微博故事视频，无法获取

### ISSUE THREAD

**Issue by kangbingbing** [dataabc/weiboSpider#105]
微博故事视频，是一个url，点击之后，又重定向一个地址，这个地址里才有视频的url

**Comment by dataabc** [comment]
感谢反馈，暂时还不支持获取微博故事中的视频。
cookie版的微博故事只是文本没有链接，所以是无法获取url的；免cookie版确实是需要重定向才可以获取url，现在还不支持获取微博故事的url
