### ISSUE TITLE
希望增加爬取每个微博阅读量的功能

### ISSUE THREAD

**Issue by huangguangjing** [dataabc/weiboSpider#107]
希望增加爬取每个微博阅读量的功能

**Comment by dataabc** [comment]
感谢反馈，cookie版没有显示阅读量，所以无法获取阅读量；免cookie版微博有一个display_text属性，怀疑是微博展示的次数，然而大V和普通用户微博的这个字段值都是“100万+”，所以应该也不是阅读量字段。暂时没发现有哪个字段代表阅读量，所以无法获取阅读量。如果你发现有什么好的方法可以获取阅读量，也欢迎反馈，再次感谢。

**Comment by CodeArtsSnap** [comment]
准确的阅读量应该是只有发布者能看到，并且附有“推广”按钮
