### ISSUE TITLE
提一个关于window系统设置user_id_list.txt的编码问题

### ISSUE THREAD

**Issue by duangan1** [dataabc/weiboSpider#108]
很多window系统要新建一个user_id_list.txt默认都是使用ANSI编码，所以一开始我设置了user_id_list.txt后运行总是说config.json设置错误，后来发现是编码问题后，将user_id_list.txt另存为UTF-8编码后，发现程序还是运行不了，连错误提示都没有，然后调试了下你的代码，发现将user_id_list.txt另存为UTF-8编码后，文本在前面会自动加了一个\ufeff字符，例如原来文本内容为：
`123456789 XXX 2020-01-20 20:00`
将user_id_list.txt另存为UTF-8编码后，用Pycharm调试，发现其内容变成
`\ufeff123456789 XXX 2020-01-20 20:00`
导致了你后面有一个info[0].isdigit()，由于info[0]变成了“\ufeff123456789”，导致info[0].isdigit()判为否，跳出了if，使程序什么都没提示就跳出了

后来发现将第947行和第1022行的line.decode('utf-8')改成line.decode('utf-8-sig')就可以忽略掉这个\ufeff字符，然后info[0].isdigit()就能为True，爬虫能继续运行

就这个问题可能会对于用window系统设置user_id_list.txt有影响，看您怎么解决这个问题，可能需要强调一下这个user_id_list.txt的编码问题

**Comment by dataabc** [comment]
感谢反馈。
这个提示其实不是user_id_list.txt问题（我本人用的也是windows），而是config.json格式有问题。
程序最开始会读取config.json文件的参数配置，如果config.json格式不正确就会出这个错误，比如将双引号错写成了单引号，或者忘了写逗号等等。
另外，config.json中的user_id_list如果内容为user_id_list.txt路径，这个路径应该是一个字符串，如：
```
"user_id_list":  "user_id_list.txt"
```

**Comment by duangan1** [comment]
我的config.json没有问题，我已经按照你的要求进行设置，我相信在你的电脑里你所设置的user_id_list.txt是无BOM（Byte Order Mark，字节顺序标记，出现在文本文件头部，Unicode编码标准中用于标识文件是采用哪种格式的编码）的UTF-8编码，可能是用notepad++新建的，你可以尝试将user_id_list.txt的UTF-8编码换成其他任意编码（ANSI、Unicode等等），你的程序可能就提示config.json设置有问题，但这个并不是config.json的问题，是user_id_list.txt的编码问题

有些人可能不是用notepad++新建txt，用的是windows自带的txt新建，所以可能txt的默认编码是ANSI，然后很坑的是，就算windows自带的新建txt文本另存为UTF-8编码时，可能会包含了BOM导致文本前面自动加上一个\ufeff，导致你的代码连出错提示都没有，直接跳出（如我之前所说，info[0].isdigit()判为否）

这算是一个比较细节的问题，我也就提出一下这个user_id_list.txt的编码问题可能会导致爬虫运行不了，我觉得可以README强调一下这个user_id_list.txt用notepad++、用utf-8编码去新建，这样可以生成一个无BOM的UTF-8编码的user_id_list.txt，保证爬虫成功运行

顺便提一句，这个项目不错的，专业人做专业事，很赞！新年快乐啊！·

**Comment by dataabc** [comment]
感谢建议，非常好的建议。

确实是程序问题，现在已经修复。现在的思路是如果发现user_id_list文件不是utf-8编码，会给使用者相关提示，并停止程序，免cookie版的这个问题稍后也会修复。

感谢细心、热心、耐心反馈，如果没有这个反馈，我应该会认为是config.json格式错误。正是这个非常细心的issue让我发现并解决了问题。

再次感谢，非常好的建议，新年快乐:smile:

**Comment by dataabc** [comment]
优化了config.json格式检测，现在只有真正config.json格式错误程序才会提示相关错误。

关于更新README，考虑了下，认为不用更新，原因如下：
1.程序已经对user_id_list.txt编码作了检测，出错会有编码相关提示；
2.很多使用者直接创建的txt文件就可以正常使用，添加说明反而会让这些用户不明所以，而运行出错的用户程序会给出提示；
3.每个使用者的系统环境和编辑器各不相同，有的使用系统自带编辑器，有的使用vim，有的使用vs code等等，很多编辑器都可以转换编码，使用者按照自己的编辑器转换编码就好。

**Comment by duangan1** [comment]
上面的做法可以的，但是还有一点，对于windows自带编辑器来说，用另存为转换为utf-8编码还是不行，他会自动在文本面前加上一个\ufeff字符，你那边可能没生成过那样的文件，下面我这边有一个用这样的方法转换过来的user_id_list.txt文件
[user_id_list.txt](https://github.com/dataabc/weiboSpider/files/4117024/user_id_list.txt)
你可以试试，你点开表面上看完全没问题，但运行时程序没有错误提示就跳出了，用Pycharm在1023行设置断点debug了之后你才能看到，微博id的那串数字前面有一些字符，使得1029行的if条件里面的info[0].isdigit()因为那串微博id前面有字符，所以把info[0]认为不是数字，判为FALSE从而跳出

所以我觉得保险一点的话，确保那些用windows自带编辑器的人也能运行，将1023行和947行的line.decode('utf-8')改成line.decode('utf-8-sig')，那样能忽略掉因为windows自带编辑器转编码从而自动加上的\ufeff字符，也保证程序对utf-8编码的检测顺利，我试过可行，1023行处的改动是保证读取的时候顺利，947行那里也要改是因为不改的话，他也会由于同样的原因从而不会更新user_id_list.txt里面上一次爬取的时间

**Comment by dataabc** [comment]
非常感谢，非常棒的建议，不但有建议，还包含很好的代码修改方案。

代码已经测试通过，utf-8-sig确实可以解决问题。本来我已经修改好了代码，非常感激，不知道如何表达感谢。想了想，觉得如果可以，由您修改并pull request到本项目，这样您还可以成为代码贡献者。我目前仅想到用这种方式表达感激之情。如果今天晚上八点之前没有收到您的pull request，我会自己提交本次修改。

再次感谢，非常用心的建议。
