### ISSUE TITLE
问题求助：爬取某特定用户失败

### ISSUE THREAD

**Issue by redMUSCLE** [dataabc/weiboSpider#109]
大佬你好，感谢你的辛苦创作和无私分享。实在是太方便了。辛苦了，春节快乐。

我在爬取个性域名为577559471（实际id为5201991851）的用户的微博时，
发现无论如何也无法成功，换个用户却又能用了。
尝试多次，无果。希望您能帮忙解决下，谢谢！

**Comment by dataabc** [comment]
感谢反馈。
我测试了下，可以爬取。猜测可能是since_date参数不正确。
当config.json文件中的user_id_list为一个文件路径时，程序会优先在user_id_list文件中获取since_date，例如：
```
1669879400 Dear-迪丽热巴 2020-01-27 11:22
1223178222 胡歌 2020-01-27 11:22
1729370543 郭碧婷 2020-01-27 11:22
575447785 悦君看电影 2020-01-27 11:22
577559471 巨鹿猎人 2019-12-25
```
对于577559471用户，第三部分是一个时间，程序会优先用这个时间，也可以像上面那些用户一样，精确到分。如果不是时间，程序会使用config.json文件中since_date。获取完成后程序会自动更新user_id_list.txt中对应用户的since_date部分，变成最新时间。**since_date的意思是程序只获取发布日期新与或等于这个时间的微博**，所以在第一次爬取结束后马上进行第二次，一般是不会获取新内容的，因为用户有很小的可能在刚刚发布了新微博。
**我猜测，如果你使用user_id_list.txt设置用户id，且since_date部分为时间，这个时间可能比用户最新的微博还新。577559471用户的最新一条微博的发布日期是2019-12-25，如果你的since_date时间在这之后，肯定不会获取到微博，因为时间不满足要求；如果你使用列表形式设置user_id_list，since_date只能通过config.json文件设置，since_date参数可能也是太新，比用户最新的微博发布时间还新，不满足要求，所以无法获取新微博。要想获取这个用户的微博，只需要设置一个较早的时间，如果想要获取全部微博，可以把since_date设置成1900-01-01，因为所有微博的发布时间都比它新**
