### ISSUE TITLE
关于写入MySQL数据时，提示错误1406

### ISSUE THREAD

**Issue by SugimitoYuuji** [dataabc/weiboSpider#112]
问题：
写入数据库时提示
DataError: (1406, u"Data too long for column 'original_pictures' at row 1")
导致数据无法正常写入。

检查过程：
根据提示，可得知是original_pictures这个列长度过短，而需要写入的数据过长。
经过检查发现建立weibo数据库时，其下weibo表的original_pictures类型为varchar，长度为1000。
但是被爬的微博部分单条微博的内容包含9张图片，记录是以9条URL以逗号隔开保存在同一个表格中，较容易超过1000。

解决方案：
删除原先建立的weibo数据库。
weiboSpider.py中，第933行，将varchar(1000)改为varchar(3000)。
保存后覆盖到服务器上重新运行，其会创建新的weibo数据库并创建新的weibo表。
此时weibo表的original_pictures长度为3000。
经检验，其写入MySQL功能正常。

**Comment by dataabc** [comment]
感谢反馈和建议。

非常不错的Issue，不但有反馈，还有详细的解决方案。问题已经修复，修改了933和934行原创图片链接和转发图片链接的字段长度。

如果发现其它问题，欢迎再次反馈或pull request，再次感谢热心反馈:smile:
