### ISSUE TITLE
添加动态IP后翻页时卡死的问题

### ISSUE THREAD

**Issue by Nathern001** [dataabc/weiboSpider#116]
你好，我为了加快爬取速度使用了一个代理每隔20s自动更改本机的ip进行爬取。然后我发现如果ip更新的时候程序正在翻页的过程中，后面即使ip更新好了、网络通畅，爬虫也会一直卡在那。请问这可以如何解决？

附图是一直卡住的状态和位置。
![image](https://user-images.githubusercontent.com/37103784/75764168-6dee1680-5d78-11ea-9234-946c6250512d.png)

**Comment by dataabc** [comment]
感谢反馈。

我没有考虑过用代理的情况，刚刚模拟了下网络的情况，即在爬取过程中手动断网，过一段时间在连接网络，看程序是否执行。结果是，断网一段时间后再连上，虽然程序在断网期间出错页码没有爬取外，后面的页面可以正常获取，感觉和代理的情况类似。

上面代理一直卡着怀疑有几个原因：
一、网络虽然是联通的，但是速度很慢，对程序来说是卡顿的；
二、可能账号被限制了，一段时间限制会自动解除；
三、可能程序无法处理更换代理的问题(因为我没有遇到过这种情况，但断网后恢复的情况程序是能处理的)

还有，限制不仅是ip，还有账号。如果爬虫账号不变，仅变ip，还是会被限的。同一个账号在不同的ip下来回变，被限的概率很大。可以使用多个账号的cookie,最好一个cookie对应一个固定的ip。程序每次随机读取一个cookie/ip对，以加快微博获取速度。虽然没有这么做过，但感觉是可行的。
