### ISSUE TITLE
需求：是否可以增加图片爬虫功能

### ISSUE THREAD

**Issue by xiaomingdaily** [dataabc/weiboSpider#12]
需求：像伟大的安妮等这种博主，更有价值的是图片/插图。看是否可以增加图片爬取功能。

**Comment by wwwpf** [comment]
我试着写了一下图片的抓取，但抓取到一定图片的 url 后连接就被关闭了:D

**Comment by ljy123liu** [comment]
新人，自己摸索写了个方法，试试满足吗
    def get_imgs(self, info):
        try:
            while True:
                picGroupList = info.xpath(".//a[contains(text(),'组图')]/@href")
                imgArray = []
                if picGroupList:
                    # 获取多张图片的链接
                    pirGroupLink = picGroupList[0]
                    html = requests.get(pirGroupLink, cookies=self.cookie).content
                    selector = etree.HTML(html)
                    imgArray = selector.xpath("//img/@src")
                else:
                    imgArray = info.xpath(".//img[@class='ib']/@src")
                self.weibo_imgs.append(imgArray)
                return
        except Exception as e:
            print("Error: ", e)
            traceback.print_exc()

**Comment by Ccccche** [comment]
把楼上的方法完整了一下，现在配合着使用可以爬图并保存到本地，没爬太多连接关闭到问题没遇到过
`   def save_img(self):
        try:
            for i in range(len(self.weibo_imgs)):
                for j in range(len(self.weibo_imgs[i])):
                    resource = self.weibo_imgs[i][j]
                    img = requests.get(resource)
                    file_dir = os.path.split(os.path.realpath(__file__))[
                    0] + os.sep + "Picture"
                    if not os.path.isdir(file_dir):
                        os.mkdir(file_dir)
                    file_name = file_dir + os.sep + "%d" % self.user_id_ + str(i) + "_" + str(j) +".jpg"
                    with open(file_name, 'ab') as f:
                        f.write(img.content)
                        print(file_name)
                        f.close()
        except Exception as e:
            print("Error: ",e)
            traceback.print_exc()`

**Comment by PLQin** [comment]
>  while True:

daLao , ` while True:` 是为啥 ？ 为啥要写 ` while True:`

**Comment by PLQin** [comment]
> 新新手，把楼上提供的获取图片方法保存到了本地，没测试爬太多图片，不确定url会不会被关闭
> 
> ```
>     def save_img(self):
>         try:
>             for i in range(len(self.weibo_imgs)):
>                 for j in range(len(self.weibo_imgs[i])):
>                     resource = self.weibo_imgs[i][j]
>                     img = requests.get(resource)
>                     file_dir = os.path.split(os.path.realpath(__file__))[
>                     0] + os.sep + "PIC"
>                     if not os.path.isdir(file_dir):
>                         os.mkdir(file_dir)
>                     file_name = file_dir + os.sep + "%d" % self.user_id_ + str(i) + "_" +str(j) +".jpg"
>                     with open(file_name, 'ab') as f:
>                         f.write(img.content)
>                         print(file_name)
>                         f.close()
>         except Exception as e:
>             print("Error: ",e)
>             traceback.print_exc()
> ```

有个小 bug和小瑕疵 ： 
```python
    def save_img(self):
        """保存图片到本地"""
        print(u"保存图片到本地，保存路径:")
        try:
            for i in range(len(self.weibo_imgs)):
                for j in range(len(self.weibo_imgs[i])):
                    resource = self.weibo_imgs[i][j]
                    img = requests.get(resource)
                    file_dir = os.path.split(
                        os.path.realpath(__file__))[0] + os.sep + "PIC"
                    if not os.path.isdir(file_dir):
                        os.mkdir(file_dir)
                    file_name = file_dir + os.sep + "%d" % self.user_id + str(
                        i) + "_" + str(j) + ".jpg"
                    with open(file_name,
                              'ab+') as f:  # ab+ 在已有文件的情况下， 将不会作出文件改动
                        f.write(img.content)
                        print(file_name)
                        # f.close() # with语句会自动帮我们调用close()方法
        except Exception as e:
            print("Error: ", e)
            traceback.print_exc()
```

**Comment by PLQin** [comment]
> 新人，自己摸索写了个方法
> 
> ```
> def get_imgs(self, info):
>         try:
>             while True:
>                 picGroupArray = info.xpath(".//a[contains(text(),'组图')]/@href")
>                 imgArray = []
>                 if picGroupArray:
>                     # 获取多张图片的链接
>                     picGroupLink = picGroupArray[0]
>                     html = requests.get(picGroupLink, cookies=self.cookie).content
>                     selector = etree.HTML(html)
>                     imgArray = selector.xpath("//img/@src")
>                 else:
>                     imgArray = info.xpath(".//img[@class='ib']/@src")
>                 self.weibo_imgs.append(imgArray)
>                 return
>         except Exception as e:
>             print("Error: ", e)
>             traceback.print_exc()
> ```

稍微优化了一下： 

```python
def get_imgs(self, info):
        try:
            picGroupArray = info.xpath(u".//a[contains(text(),'组图')]/@href")
            if picGroupArray:
                # 获取多张图片的链接
                picGroupLink = picGroupArray[0]
                selector = self.deal_html(pic_url)
                imgArray = selector.xpath("//img/@src")
            else:
                imgArray = info.xpath(".//img[@class='ib']/@src")
            self.weibo_imgs.append(imgArray)
        except Exception as e:
            print("Error: ", e)
            traceback.print_exc()
```

**Comment by cangling** [comment]
> > 新新手，把楼上提供的获取图片方法保存到了本地，没测试爬太多图片，不确定url会不会被关闭
> > ```
> >     def save_img(self):
> >         try:
> >             for i in range(len(self.weibo_imgs)):
> >                 for j in range(len(self.weibo_imgs[i])):
> >                     resource = self.weibo_imgs[i][j]
> >                     img = requests.get(resource)
> >                     file_dir = os.path.split(os.path.realpath(__file__))[
> >                     0] + os.sep + "PIC"
> >                     if not os.path.isdir(file_dir):
> >                         os.mkdir(file_dir)
> >                     file_name = file_dir + os.sep + "%d" % self.user_id_ + str(i) + "_" +str(j) +".jpg"
> >                     with open(file_name, 'ab') as f:
> >                         f.write(img.content)
> >                         print(file_name)
> >                         f.close()
> >         except Exception as e:
> >             print("Error: ",e)
> >             traceback.print_exc()
> > ```
> 
> 有个小 bug和小瑕疵 ：
> 
> ```python
>     def save_img(self):
>         """保存图片到本地"""
>         print(u"保存图片到本地，保存路径:")
>         try:
>             for i in range(len(self.weibo_imgs)):
>                 for j in range(len(self.weibo_imgs[i])):
>                     resource = self.weibo_imgs[i][j]
>                     img = requests.get(resource)
>                     file_dir = os.path.split(
>                         os.path.realpath(__file__))[0] + os.sep + "PIC"
>                     if not os.path.isdir(file_dir):
>                         os.mkdir(file_dir)
>                     file_name = file_dir + os.sep + "%d" % self.user_id + str(
>                         i) + "_" + str(j) + ".jpg"
>                     with open(file_name,
>                               'ab+') as f:  # ab+ 在已有文件的情况下， 将不会作出文件改动
>                         f.write(img.content)
>                         print(file_name)
>                         # f.close() # with语句会自动帮我们调用close()方法
>         except Exception as e:
>             print("Error: ", e)
>             traceback.print_exc()
> ```
> 
> * bug : `user_id_` 改为 `user_id`
> 
> 非常感觉保存图片这个方法， 帮了我的大忙了

普通用户求助，请问，这个怎么用？

**Comment by cangling** [comment]
> > 新人，自己摸索写了个方法
> > ```
> > def get_imgs(self, info):
> >         try:
> >             while True:
> >                 picGroupArray = info.xpath(".//a[contains(text(),'组图')]/@href")
> >                 imgArray = []
> >                 if picGroupArray:
> >                     # 获取多张图片的链接
> >                     picGroupLink = picGroupArray[0]
> >                     html = requests.get(picGroupLink, cookies=self.cookie).content
> >                     selector = etree.HTML(html)
> >                     imgArray = selector.xpath("//img/@src")
> >                 else:
> >                     imgArray = info.xpath(".//img[@class='ib']/@src")
> >                 self.weibo_imgs.append(imgArray)
> >                 return
> >         except Exception as e:
> >             print("Error: ", e)
> >             traceback.print_exc()
> > ```
> 
> 稍微优化了一下：
> 
> ```python
> def get_imgs(self, info):
>         try:
>             picGroupArray = info.xpath(u".//a[contains(text(),'组图')]/@href")
>             if picGroupArray:
>                 # 获取多张图片的链接
>                 picGroupLink = picGroupArray[0]
>                 selector = self.deal_html(pic_url)
>                 imgArray = selector.xpath("//img/@src")
>             else:
>                 imgArray = info.xpath(".//img[@class='ib']/@src")
>             self.weibo_imgs.append(imgArray)
>         except Exception as e:
>             print("Error: ", e)
>             traceback.print_exc()
> ```

这个只能获取图片网址，不保存？怎么用？谢谢！

**Comment by cangling** [comment]
获取图片失败

用户昵称: Dear-迪丽热巴
微博数: 1003
关注数: 224
粉丝数: 63237779
****************************************************************************************************
进度:   0%|                                                                   | 0/101 [00:00<?, ?it/s]#比耶季##高考加油#大家高考加油鸭！！！   [组图共2张][图片] 
微博位置: 无
微博发布时间: 2019-06-07 12:03
微博发布工具: 无
点赞数: 309933
转发数: 406955
评论数: 25394
----------------------------------------------------------------------------------------------------
#蓝天保卫战我是行动者# 我承诺使用环保购物袋代替一次性塑料袋，助力蓝天。#和地球自拍#@联合国环境规划署 @星光公益联盟  [图片] 
('Error: ', IndexError('list index out of range',))
Traceback (most recent call last):
  File "weiboSpider.py", line 351, in get_one_page
    self.get_picture_urls(info[i], is_original)  # 微博图片url
  File "weiboSpider.py", line 321, in get_picture_urls
    original_picture = self.extract_picture_urls(info, weibo_id)
  File "weiboSpider.py", line 311, in extract_picture_urls
    preview_picture = info.xpath("div/a/img/@src")[0]
IndexError: list index out of range

**Comment by dataabc** [comment]
@cangling 
我刚刚测试了下，爬了30页，没有问题。
请问，现在运行程序还出错吗?这个错误是运行刚开始就出现了，还是运行了很久才出现?还有，运行旧版本的程序会出错吗?除了修改cookie外还修改过其它地方吗?
我怀疑是不是爬的太快了，被ban了。如果这样，等一段时间就自动解封了。
你再测试下，有问题再反馈

**Comment by cangling** [comment]
@dataabc 
今天测试，一样出错。换了个账号，一样报错。文字可以正常获取。
我下载了 Commits on Jun 4, 2019 里的两个版本，一样报错。
https://github.com/dataabc/weiboSpider/commits/master/weiboSpider.py

旧版本不获取图片的没报错。

是不是少了什么依赖？
可以在说明了加上需要安装什么依赖吗？
我用 openSUSE。
谢谢！

**Comment by dataabc** [comment]
目前就三个依赖:lxml、requests、tqdm。

每次都是同一个错误吗?一直是’preview_picture = info.xpath("div/a/img/@src")[0]‘这行出错?是否爬的是同一个微博，如"Dear-迪丽热巴"，每次是否都是爬了相同的微博后出错?
’preview_picture = info.xpath("div/a/img/@src")[0]‘报"list index out of range"错，说明'info.xpath("div/a/img/@src")'为空,'info.xpath("div/a/img/@src")[0]'自然报错。然而因为在这之前就已经通过'if first_pic in a_list:'作了判断，只要它成立，说明微博中就有图片,''info.xpath("div/a/img/@src")''就不为空，可以取到图片地址。前后矛盾，非常奇怪。所以我怀疑是不是微博中出现了某些新的格式，导致程序出错。需要知道具体在哪条微博程序停止了，才可以调试。
如果你不想出错，可以把"extract_picture_urls"方法中的’preview_picture = info.xpath("div/a/img/@src")[0]‘替换成:
```python
                img_list = info.xpath("div/a/img/@src")
                if img_list:
                    preview_picture = img_list[0]
                    picture = preview_picture.replace("/wap180/", "/large/")
                else:
                    picture = "无"
```
不过，这样就把无法识别的图片忽略了。

**Comment by cangling** [comment]
python2和python3的依赖我的安装了，测试了热巴和衣柜军团的微博，错误一样。

衣柜军团
https://weibo.cn/3009184157/info

终端输出：
[热巴-p2.txt](https://github.com/dataabc/weiboSpider/files/3268569/-p2.txt)
[衣柜-p2.txt](https://github.com/dataabc/weiboSpider/files/3268570/-p2.txt)

第一行错误不一样
p2：('Error: ', IndexError('list index out of range',))
p3：Error:  list index out of range

写入的文件里没有图片链接。


可否设置保存图片到本地，默认关闭，弄个开关给需要的用户？

谢谢！

**Comment by cangling** [comment]
你后边给的那个代码，if 就一半，不知具体要替换哪里，试了下，提示错误。

**Comment by dataabc** [comment]
把原来的'extract_picture_urls'整体替换成下面的:
```python
    def extract_picture_urls(self, info, weibo_id):
        """提取微博原始图片url"""
        a_list = info.xpath("div/a/@href")
        first_pic = "https://weibo.cn/mblog/pic/" + weibo_id + "?rl=0"
        all_pic = "https://weibo.cn/mblog/picAll/" + weibo_id + "?rl=1"
        if first_pic in a_list:
            if all_pic in a_list:
                selector = self.deal_html(all_pic)
                preview_picture_list = selector.xpath("//img/@src")
                picture_list = [
                    p.replace("/thumb180/", "/large/")
                    for p in preview_picture_list
                ]
                picture = ",".join(picture_list)
            else:
                img_list = info.xpath("div/a/img/@src")
                if img_list:
                    preview_picture = img_list[0]
                    picture = preview_picture.replace("/wap180/", "/large/")
                else:
                    picture = "无"
        else:
            picture = "无"
        return picture
```
注意格式对齐，应该没问题

**Comment by dataabc** [comment]
我又分别在win10和ubuntu测试了几遍,都没有错误。
而且你上传的文件中微博的形式和我的不一样。如果某条微博有图片，你的微博正文内容是:
xxxxxxx [图片] 或者 xxxxxxx [组图共3张][图片]
我的微博正文是:
xxxxxxx 原图 或者 xxxxxxx [组图共3张] 原图 

这些都是爬下的微博的内容，两者形式不一样。也就是说微博在你的系统和我的系统内容形式是不一样的，这可能就是在你系统中出错的原因。

**Comment by dataabc** [comment]
@cangling 
我又修改了代码，现在应该不会出错了，而且可以获取到原始图片url

**Comment by cangling** [comment]
我又测试了下，还是无法获取图片。
我修改了 cookie ，每1页保存一次。

在opensuse 实机和 ubuntu 虚拟机里测试迪丽热巴

('Error: ', IndexError('list index out of range',))
Traceback (most recent call last):
  File "weiboSpider.c2.py", line 319, in extract_picture_urls
    preview_picture = info.xpath(".//img/@src")[-1]
IndexError: list index out of range

[迪丽热巴.ubuntu.txt](https://github.com/dataabc/weiboSpider/files/3285479/ubuntu.txt)
[迪丽热巴-opensuse.txt](https://github.com/dataabc/weiboSpider/files/3285480/-opensuse.txt)
[迪丽热巴-weibo.cn-源码.txt](https://github.com/dataabc/weiboSpider/files/3285525/-weibo.cn-.txt)
这个源码没暴露什么账号信息吧？有的话麻烦你删除。谢谢！

测试的账号，一个没有实名认证。
另一个账号在用第三方客户端，在那个客户端无法发微博，网页端可以。
这些影响获取图片？

**Comment by dataabc** [comment]
@cangling 
我在win10、ubuntu和macOS上测试过，都可以正确运行。如果你在ubuntu 虚拟机里出错，我也不知道原因了。如果不需要图片，可以把
```python
                    preview_picture = info.xpath(".//img/@src")[-1]
                    picture_urls = preview_picture.replace(
                        "/wap180/", "/large/")
```
换成
```python
                    picture_urls = "无"
```
不过这样就无法获取微博中只有一张图片时的图片url了，还是第一次遇到这种情况。

**Comment by dataabc** [comment]
看了下，你的微博源码里也不显示图片，除了显示用户头像和某些特殊表情外，其它图片都不显示。你可以看下，手动浏览微博是不是也没有图片啊?源码里所有的img标签都是头像或者标签等，没有微博图片的url，程序自然就爬不到，我怀疑是不是你的微博账号被设置成"无图模式"了。

**Comment by cangling** [comment]
以前修改为不显示图片了，现在改为显示图片。
下载6.14 脚本，修改了 cookie ，每1页保存一次。
不报错了，没有获取图片 url，也没下载图片。

userid filter 只修改最下边那个 def main(): 里的就行？
谢谢！

[热巴源码.txt](https://github.com/dataabc/weiboSpider/files/3299497/default.txt)
![wbcn显示设置](https://user-images.githubusercontent.com/7885420/59648171-b34dc200-91b0-11e9-85a1-658d436f8947.png)

修改设置后如果无法正常打开微博,请刷新页面.
微博内容中显示图片:
不显示 显示* （选择的显示）

**Comment by dataabc** [comment]
@cangling 
按照你的设置，配置了一遍微博。在图片修改成显示后，可以获取图片url和下载图片啊。mian只是我写的一个用法实例，你可以按照自己的需求修改，比如写数据库什么的，毕竟数据都已经存储到self.weibo里了。写文件、写数据、利用数据分析微博等都可以。main仅是最简单用法的展示。
filter=1表示爬全部微博，pic_download=1表示下载图片，默认是不下载图片，你没有下载图片是不是把pic_download设成0了或者初始化时出错了?另外，图片url保存在csv文件里
