### ISSUE TITLE
您好，能简单实现一下爬取微博评论的功能吗？谢谢

### ISSUE THREAD

**Issue by qq31415926** [dataabc/weiboSpider#120]

**Comment by dataabc** [comment]
感谢反馈。

能爬只是爬不全，最多只能获得几百条评论，而且会降低爬取速度，因此暂时不打算获取评论。现在访问一个网页可以获取大约10条微博，如果获取评论，获取一条带评论的微博，至少要多访问一页微博，如果评论多，还有访问评论第二页第三页等，速度太慢。

虽然暂时无法实现，还是非常感谢。如果有其它问题和建议，欢迎继续反馈:smile:
