### ISSUE TITLE
需求：建议增加微博链接、展示和提醒功能，谢谢！

### ISSUE THREAD

**Issue by modun** [dataabc/weiboSpider#121]
已部署，非常感谢！
1.使用期间发现没有微博的原文链接，建议增加微博原文链接，方便打开链接查看原文微博；
2.希望作者能增加展示功能，可以集中展示爬取的微博内容；
3.建议增加提醒功能，比如每天新发的微博集中邮件提示下，重要的微博或者带有关键字的微博可以通过微信、短信等提醒。
个人建议，供作者参考，如能采纳，非常感谢！
想贡献下个人力量，但代码能力实在有限。

**Comment by dataabc** [comment]
感谢建议。
1.是有微博原文链接的，在运行时每条微博下的url就是微博链接，只是没有把链接指端保存，原因是它是冗余字段，原文链接为<https://weibo.cn/comment/weibo_id>形式，weibo_id已经保存了，就没有保存微博链接；
2.展示功能指的是什么？现在是获取一条微博就打印一条，你说的展示是运行时打印出来还是其它，没有理解这条建议；
3.提醒功能非常好，非常方便使用者获得程序最新动态，下一步有增加提醒的打算，可能会通过邮件提醒。
非常感谢建议，这也是贡献个人力量，是项目不断完善的动力和原因。如果有新的建议或发现问题，也欢迎继续反馈:smile:

**Comment by modun** [comment]
可以把爬取到的所有微博类似表格的形式，以web的方式展示出来，方便集中查看分析，不用每次查询都直接通过数据库查询。同时可以对指定日期、作者或者关键字进行检索。

**Comment by dataabc** [comment]
感觉这个类似于一个网站，展示数据来自数据库，指定日期、作者等也是通过检索数据库实现。这是一个不错的想法，只是感觉代码成本或使用成本较高，短期不会添加这个功能，再次感谢建议
