### ISSUE TITLE
您好，如果要爬取一个用户发出的评论是否可行呢？

### ISSUE THREAD

**Issue by qq31415926** [dataabc/weiboSpider#122]

**Comment by dataabc** [comment]
可行但是效率低且爬不全。

1.效率会下降。对于每条微博都有评论的用户，速度会降低原来的1/11一下。因为原来获取微博，只需要访问一页列表页就能得到10条微博，要得到这些微博的评论，需要访问每条微博的评论页。由原来的1页到后来的11页(1页列表页+10页评论页)，遇到评论较多的，要访问多于11页，效率下降；
2.爬不全。有少量评论可以全部得到，对于明星微博，动辄上万评论，只能得到几百条，剩余评论被限制不能显示。

因此，评论可以获取，但是会大大降低程序效率，且无法得到全部评论。
