### ISSUE TITLE
如何根据用户昵称获取user_id

### ISSUE THREAD

**Issue by zycsola** [dataabc/weiboSpider#123]

**Comment by dataabc** [comment]
可以，不知道有没有程序，说下思路。

以胡歌的微博为例，他的昵称是“胡歌”，访问<https://m.weibo.cn/n/胡歌>，会自动跳到<https://m.weibo.cn/u/1223178222>,其中“1223178222”就是user_id。如果想要获得某昵称对应的id，只需要让程序访问<https://m.weibo.cn/n/昵称>，会得到<https://m.weibo.cn/u/user_id>的形式，这是大致的思路，用程序模拟上面的过程应该可以做到。
