### ISSUE TITLE
可以试试json数据接口

### ISSUE THREAD

**Issue by udbmnm** [dataabc/weiboSpider#124]
从H5页面的json接口可以更方便的拿数据，不用解析dom了
比如https://m.weibo.cn/u/1669879400 的页面
用户信息：https://m.weibo.cn/api/container/getIndex?type=uid&value=1669879400&containerid=1005051669879400
微博列表：
https://m.weibo.cn/api/container/getIndex?type=uid&value=1669879400&containerid=1076031669879400
按时间拉取微博列表：
https://m.weibo.cn/api/container/getIndex?type=uid&value=1669879400&containerid=1076031669879400&since_id=4472610853166585
同样是使用since_id来分页

**Comment by dataabc** [comment]
感谢建议，免cookie版<https://github.com/dataabc/weibo-crawler>就是用数据接口写的，可以不填cookie（可以获取大部分微博），也可以填cookie（可以获取全部微博），获取的信息较多，如话题、艾特用户昵称。
再次感谢建议，如有其它问题或建议，欢迎继续反馈
