### ISSUE TITLE
微博原文抓不全

### ISSUE THREAD

**Issue by gongzhigao** [dataabc/weiboSpider#126]
![image](https://user-images.githubusercontent.com/38653158/76695123-833b3d00-66b6-11ea-88d2-5e9c9326ea5f.png)
全文后面的内容没有抓到

**Comment by dataabc** [comment]
感谢反馈。
程序是可以获取长微博全文的。遇到上面这种情况，会先保存这个不全的内容，然后尝试获取全文，如果获取成功，获取的内容就是微博文本；如果获取失败，就用上面不全的内容代替。
你上面没有得到全文，可能是因为被短暂的限制了或者网络问题，可以通过降低爬取速度避免限制，具体修改get_weibo_info方法：
```
                    if (page - page1) % random_pages == 0 and page < page_num:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
上面意思是每1-5页随机等待6-10秒，你可以适当加快暂停频率，加长等待时间。
如果你一定要获取全文，可以参考#40
