### ISSUE TITLE
关于获取批量id

### ISSUE THREAD

**Issue by xianyushiwo** [dataabc/weiboSpider#127]
大佬您好，我是没学过计算机的纯纯小白，这几天通过您的代码不断学习，从0基础获取到了需要的数据，结果出来的时候都快哭了…真的感谢您。
但是现在有个问题就是，我目前写的毕业论文需要大量微博用户的数据…通过这个方法只能获取一个id的数据，请问大佬从哪里获得批量的id呢…
我的问题可能很白痴…求大佬解答…

**Comment by dataabc** [comment]
有两个方法获得批量id：
1.使用<https://github.com/dataabc/weibo-follow>，这个项目是获取一个用户关注的用户，一个用户可能关注了很多用户，程序可以获得最多200个被关注的用户和id，并写入user_id_list.txt文件，这200个id每个又可以获得200个，共40000个id，以此类推，可以活动很多用户id，结果都写在user_id_list.txt文件里。本程序支持利用user_id_list.txt获取文件中用户的微博，只需要将config.json文件中user_id_list参数的值填成user_id_list.txt，运行程序就好；
2.利用#104中的微博搜索查询，这个程序目的是活动包含用户指定关键字的微博，可以指定时间范围。比如搜索“迪丽热巴”，程序会获取所有包含迪丽热巴的微博，并将信息写入文件，其中用户id、昵称写入user_id_list.txt。一次搜索结果最多有1000个结果，因此最多可获得1000个用户id，程序可以按天搜索，每天最多1000个，10天10000个，100天100000个。同样，可以利用生成的user_id_list.txt和本程序获取这些用户的微博。

因为用户过多，容易被限制，可以通过降低爬行速度避免被限，具体修改get_weibo_info方法：
```
                    if (page - page1) % random_pages == 0 and page < page_num:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
上面意思是每1-5页随机等待6-10秒，你可以适当加快暂停频率，加长等待时间。

**Comment by xianyushiwo** [comment]
> 有两个方法获得批量id：
> 1.使用https://github.com/dataabc/weibo-follow，这个项目是获取一个用户关注的用户，一个用户可能关注了很多用户，程序可以获得最多200个被关注的用户和id，并写入user_id_list.txt文件，这200个id每个又可以获得200个，共40000个id，以此类推，可以活动很多用户id，结果都写在user_id_list.txt文件里。本程序支持利用user_id_list.txt获取文件中用户的微博，只需要将config.json文件中user_id_list参数的值填成user_id_list.txt所在路径，运行程序就好；
> 2.利用#104 中的微博搜索程序，这个程序目的是获得包含用户指定关键字的微博，可以指定时间范围。比如搜索“迪丽热巴”，程序会获取所有包含迪丽热巴的微博，并将信息写入文件，其中用户id、昵称写入user_id_list.txt。一次搜索结果最多有1000个结果，因此最多可获得1000个用户id，程序可以按天搜索，每天最多1000个，10天10000个，100天100000个。同样，可以利用生成的user_id_list.txt和本程序获取这些用户的微博。
> 
> 因为用户过多，容易被限制，可以通过降低爬行速度避免被限，具体修改get_weibo_info方法：
> 
> ```
>                     if (page - page1) % random_pages == 0 and page < page_num:
>                         sleep(random.randint(6, 10))
>                         page1 = page
>                         random_pages = random.randint(1, 5)
> ```
> 
> 上面意思是每1-5页随机等待6-10秒，你可以适当加快暂停频率，加长等待时间。

感谢大佬！我今天上午试一下！谢谢啦啦！

**Comment by xianyushiwo** [comment]
> 有两个方法获得批量id：
> 1.使用https://github.com/dataabc/weibo-follow，这个项目是获取一个用户关注的用户，一个用户可能关注了很多用户，程序可以获得最多200个被关注的用户和id，并写入user_id_list.txt文件，这200个id每个又可以获得200个，共40000个id，以此类推，可以活动很多用户id，结果都写在user_id_list.txt文件里。本程序支持利用user_id_list.txt获取文件中用户的微博，只需要将config.json文件中user_id_list参数的值填成user_id_list.txt所在路径，运行程序就好；
> 2.利用#104 中的微博搜索程序，这个程序目的是获得包含用户指定关键字的微博，可以指定时间范围。比如搜索“迪丽热巴”，程序会获取所有包含迪丽热巴的微博，并将信息写入文件，其中用户id、昵称写入user_id_list.txt。一次搜索结果最多有1000个结果，因此最多可获得1000个用户id，程序可以按天搜索，每天最多1000个，10天10000个，100天100000个。同样，可以利用生成的user_id_list.txt和本程序获取这些用户的微博。
> 
> 因为用户过多，容易被限制，可以通过降低爬行速度避免被限，具体修改get_weibo_info方法：
> 
> ```
>                     if (page - page1) % random_pages == 0 and page < page_num:
>                         sleep(random.randint(6, 10))
>                         page1 = page
>                         random_pages = random.randint(1, 5)
> ```
> 
> 上面意思是每1-5页随机等待6-10秒，你可以适当加快暂停频率，加长等待时间。

大佬您好，我按您说的方法获取到了关注人id的txt，但是再把txt放到之前的程序中运行的时候，出现了  KeyError: 'id' ，请问这样要怎么解决呢……

**Comment by xianyushiwo** [comment]
> > 有两个方法获得批量id：
> > 1.使用[https://github.com/dataabc/weibo-follow，这个项目是获取一个用户关注的用户，一个用户可能关注了很多用户，程序可以获得最多200个被关注的用户和id，并写入user_id_list.txt文件，这200个id每个又可以获得200个，共40000个id，以此类推，可以活动很多用户id，结果都写在user_id_list.txt文件里。本程序支持利用user_id_list.txt获取文件中用户的微博，只需要将config.json文件中user_id_list参数的值填成user_id_list.txt所在路径，运行程序就好；](https://github.com/dataabc/weibo-follow%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E6%98%AF%E8%8E%B7%E5%8F%96%E4%B8%80%E4%B8%AA%E7%94%A8%E6%88%B7%E5%85%B3%E6%B3%A8%E7%9A%84%E7%94%A8%E6%88%B7%EF%BC%8C%E4%B8%80%E4%B8%AA%E7%94%A8%E6%88%B7%E5%8F%AF%E8%83%BD%E5%85%B3%E6%B3%A8%E4%BA%86%E5%BE%88%E5%A4%9A%E7%94%A8%E6%88%B7%EF%BC%8C%E7%A8%8B%E5%BA%8F%E5%8F%AF%E4%BB%A5%E8%8E%B7%E5%BE%97%E6%9C%80%E5%A4%9A200%E4%B8%AA%E8%A2%AB%E5%85%B3%E6%B3%A8%E7%9A%84%E7%94%A8%E6%88%B7%E5%92%8Cid%EF%BC%8C%E5%B9%B6%E5%86%99%E5%85%A5user_id_list.txt%E6%96%87%E4%BB%B6%EF%BC%8C%E8%BF%99200%E4%B8%AAid%E6%AF%8F%E4%B8%AA%E5%8F%88%E5%8F%AF%E4%BB%A5%E8%8E%B7%E5%BE%97200%E4%B8%AA%EF%BC%8C%E5%85%B140000%E4%B8%AAid%EF%BC%8C%E4%BB%A5%E6%AD%A4%E7%B1%BB%E6%8E%A8%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%B4%BB%E5%8A%A8%E5%BE%88%E5%A4%9A%E7%94%A8%E6%88%B7id%EF%BC%8C%E7%BB%93%E6%9E%9C%E9%83%BD%E5%86%99%E5%9C%A8user_id_list.txt%E6%96%87%E4%BB%B6%E9%87%8C%E3%80%82%E6%9C%AC%E7%A8%8B%E5%BA%8F%E6%94%AF%E6%8C%81%E5%88%A9%E7%94%A8user_id_list.txt%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6%E4%B8%AD%E7%94%A8%E6%88%B7%E7%9A%84%E5%BE%AE%E5%8D%9A%EF%BC%8C%E5%8F%AA%E9%9C%80%E8%A6%81%E5%B0%86config.json%E6%96%87%E4%BB%B6%E4%B8%ADuser_id_list%E5%8F%82%E6%95%B0%E7%9A%84%E5%80%BC%E5%A1%AB%E6%88%90user_id_list.txt%E6%89%80%E5%9C%A8%E8%B7%AF%E5%BE%84%EF%BC%8C%E8%BF%90%E8%A1%8C%E7%A8%8B%E5%BA%8F%E5%B0%B1%E5%A5%BD%EF%BC%9B)
> > 2.利用#104 中的微博搜索程序，这个程序目的是获得包含用户指定关键字的微博，可以指定时间范围。比如搜索“迪丽热巴”，程序会获取所有包含迪丽热巴的微博，并将信息写入文件，其中用户id、昵称写入user_id_list.txt。一次搜索结果最多有1000个结果，因此最多可获得1000个用户id，程序可以按天搜索，每天最多1000个，10天10000个，100天100000个。同样，可以利用生成的user_id_list.txt和本程序获取这些用户的微博。
> > 因为用户过多，容易被限制，可以通过降低爬行速度避免被限，具体修改get_weibo_info方法：
> > ```
> >                     if (page - page1) % random_pages == 0 and page < page_num:
> >                         sleep(random.randint(6, 10))
> >                         page1 = page
> >                         random_pages = random.randint(1, 5)
> > ```
> > 
> > 
> > 上面意思是每1-5页随机等待6-10秒，你可以适当加快暂停频率，加长等待时间。
> 
> 大佬您好，我按您说的第一种方法获取到了关注人id的txt，但是再把txt放到之前的程序中运行的时候，出现了 KeyError: 'id' ，请问这样要怎么解决呢……
> （我config.json文件中"user_id_list": 参数的值填的user_id_list，请问大佬这么填对吗，还是要填这个文件的路径呢，如果要赋值路径的话，会显示config.json 格式不正确，有点方……）

**Comment by dataabc** [comment]
要填这个文件的路径，你可以把文件复制到本项目根目录下，config.json的user_id_list值如下：
```
    "user_id_list": "user_id_list.txt",
```
还有， KeyError: 'id'错误有详细信息吗，方便调试

**Comment by xianyushiwo** [comment]
> 要填这个文件的路径，你可以把文件复制到本项目根目录下，config.json的user_id_list值如下：
> 
> ```
>     "user_id_list": "user_id_list.txt",
> ```
> 
> 还有， KeyError: 'id'错误有详细信息吗，方便调试

**Comment by xianyushiwo** [comment]
> 要填这个文件的路径，你可以把文件复制到本项目根目录下，config.json的user_id_list值如下：
> 
> ```
>     "user_id_list": "user_id_list.txt",
> ```
> 
> 还有， KeyError: 'id'错误有详细信息吗，方便调试

啊…大佬我太笨没听太懂…就是把id的文件复制到了根目录（E：）之后，config.json的user_id_list值是要填  "user_id_list.txt"  还是要填  “E：”  呀…  
详细信息有，如下：
E:\Python\python.exe E:/weibo-crawler-master/weibo.py
E:\Python\lib\site-packages\urllib3\util\ssl_.py:380: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning,
E:\Python\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning,
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
用户信息
('Error: ', KeyError('id',))
Traceback (most recent call last):
  File "E:/weibo-crawler-master/weibo.py", line 1013, in start
    self.get_pages()
  File "E:/weibo-crawler-master/weibo.py", line 949, in get_pages
    self.print_user_info()
  File "E:/weibo-crawler-master/weibo.py", line 491, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'

Process finished with exit code 0

**Comment by dataabc** [comment]
项目根目录就是项目所在的目录之下。看上面你用的应该是免cookie版，项目代码放在weibo-crawler-master文件夹下，你把user_id_list.txt也放里面就好。

错误就是因为config没有写对，改过来就可以了。user_id_list.txt放到weibo-crawler-master文件夹后，这样填user_id_list参数：
```
    "user_id_list": "user_id_list.txt",
```

**Comment by xianyushiwo** [comment]
大佬，我刚才把 user_id_list.txt 放在了 E:\weibo-crawler-master 文件夹下 ，weibo.py 也在这个文件夹下，将 config.json的user_id_list 值改为了  user_id_list.txt ，之后运行 weibo.py ，但是还是出现相同的错误，不知道哪里犯了错…烦请大佬解答一下…

**Comment by xianyushiwo** [comment]
> 项目根目录就是项目所在的目录之下。看上面你用的应该是免cookie版，项目代码放在weibo-crawler-master文件夹下，你把user_id_list.txt也放里面就好。
> 
> 错误就是因为config没有写对，改过来就可以了。user_id_list.txt放到weibo-crawler-master文件夹后，这样填user_id_list参数：
> 
> ```
>     "user_id_list": "user_id_list.txt",
> ```

大佬，我刚才把 user_id_list.txt 放在了 E:\weibo-crawler-master 文件夹下 ，weibo.py 也在这个文件夹下，将 config.json的user_id_list 值改为了 user_id_list.txt ，之后运行 weibo.py ，但是还是出现相同的错误，不知道哪里犯了错…烦请大佬解答一下…

**Comment by xianyushiwo** [comment]
> 项目根目录就是项目所在的目录之下。看上面你用的应该是免cookie版，项目代码放在weibo-crawler-master文件夹下，你把user_id_list.txt也放里面就好。
> 
> 错误就是因为config没有写对，改过来就可以了。user_id_list.txt放到weibo-crawler-master文件夹后，这样填user_id_list参数：
> 
> ```
>     "user_id_list": "user_id_list.txt",
> ```

可以了可以了！我知道哪里错了！因为之前的config里面的id带[  ]这个，我把这两个[ ]去掉就成功了！大佬你做的这个爬虫太牛了!谢谢你！！！

**Comment by dataabc** [comment]
更新了免cookie版的代码，问题已经修复了。
应该是user_id_list.txt中有一些不正确的user_id，导致程序出错。这些不正确的user_id可能是个性域名等，免cookie不能获取这些信息对应的用户，本项目是可以获取的。现在免cookie版遇到这些不正确的user_id，虽然还提示出错，但不影响后续正确的user_id，会继续获取。
