### ISSUE TITLE
深圳2019 国庆7天微博数据共享

### ISSUE THREAD

**Issue by tangbotony** [dataabc/weiboSpider#128]
链接:https://pan.baidu.com/s/17v0XBWYzOye3qR48uIGcFA 提取码:dtd1 解压有有1.3G
更多共享数据请加群 537549079（群名：微博爬虫(有共享数据)）

**Comment by barnett2010** [comment]
666

**Comment by modun** [comment]
请问作者在群里吗

**Comment by dataabc** [comment]
@modun 不在

**Comment by modun** [comment]
> @modun 我不在群里

那就不加群了，作者不打算拉个群吗？

**Comment by tangbotony** [comment]
@dataabc 拉一个群，数据交流，避免反复爬取相同数据，给微博服务器增加压力

**Comment by dataabc** [comment]
@modun 
@tangbotony 
主要我属于那种潜水的，也不经常刷群，所以暂时没有建群的打算，后续建不建群还不确定，如果建群应该会在readme里体现，有问题直接发issue就可以
