### ISSUE TITLE
您好，请问爬取用户的一部分关注人的uid是否可行呢？

### ISSUE THREAD

**Issue by eXun-Ma** [dataabc/weiboSpider#129]
我现在有许多用户的主页链接，想要获取这些用户关注的用户的uid，您觉得可行吗？

**Comment by dataabc** [comment]
可行。

可以使用<https://github.com/dataabc/weibo-follow>，这个程序就是获取关注人的id，并写入user_id_list.txt文件。配合本项目，将user_id_list.txt路径填入config.json的user_id_list参数，就可以获取这些人的微博。

很多链接包含user_id，稍作处理，就能得到user_id。如果有不正确的id，<https://github.com/dataabc/weibo-follow>程序会跳过继续执行，因此是可行的

**Comment by eXun-Ma** [comment]
感谢大佬！！

**Comment by dataabc** [comment]
最好用小号作爬虫。

weibo_follow是最近完善的，仅在写代码的时候用过，没有大量使用。猜测控制下速度，用每页用sleep多暂停几秒应该没问题，不过**安全起见，最好还是用小号作爬虫，不管是weibo_follow还是本项目**。
