### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HZzzzy** [dataabc/weiboSpider#13]
第141行获取点赞数出现问题，hml中有不符合规律的片段，即点赞数并非在倒数 第四个a标签中，导致未正确获取元素内容

**Comment by dataabc** [comment]
能否提供一个 "点赞数并非在倒数第四个a标签" 的**微博昵称**或**id**，方便调试，谢谢

**Comment by HZzzzy** [comment]
渣浪的.cn站点今天抽了，登录不进，如果没有弄错的话，当你给某条微博点赞后成功后，元素就会发生改变

**Comment by dataabc** [comment]
已修复
