### ISSUE TITLE
数据库问题 1054

### ISSUE THREAD

**Issue by xianyushiwo** [dataabc/weiboSpider#131]
大佬您好，我还是那个小白
请问在运行weiboSpider时，出现如下错误：

InternalError: (1054, u"Unknown column 'talent' in 'field list'")

pycharm中显示读取到了用户数据，也显示用户数据已写入MySQL数据库完毕，但是在MySQL数据库中就是找不到新增的用户数据，请问大佬是哪里出问题了吗？

**Comment by dataabc** [comment]
感谢反馈。

出现这个问题应该是你开始用的之前的版本，后来新版本我在数据库中加了很多字段。新数据写入数据库时因旧数据库没有那些字段而出错。解决方法是手动为数据库添加那些新增的字段，比如上面的错误上面没有talent字段，因此要手动为数据库添加上，参考user_to_mysql方法的创建数据库部分，可知新字段的类型，使用如下方法为mysql数据表添加talent，首先进入mysql数据库，然后运行如下命令:
```
mysql> use weibo;
mysql> alter table user add talent  varchar(200) default '';
```

如果还有类似错误参考上面方法添加字段就好

**Comment by xianyushiwo** [comment]
> 感谢反馈。
> 
> 出现这个问题应该是你开始用的之前的版本，后来新版本我在数据库中加了很多字段。新数据写入数据库时因旧数据库没有那些字段而出错。解决方法是手动为数据库添加那些新增的字段，比如上面的错误上面没有talent字段，因此要手动为数据库添加上，参考user_to_mysql方法的创建数据库部分，可知新字段的类型，使用如下方法为mysql数据表添加talent，首先进入mysql数据库，然后运行如下命令:
> 
> ```
> mysql> use weibo;
> mysql> alter table user add talent  varchar(200) default '';
> ```
> 
> 如果还有类似错误参考上面方法添加字段就好

解决啦！感谢大佬！
真的太强了吧！
