### ISSUE TITLE
网页解析报错：AttributeError:’ NoneType’ object has no attribute’ xpath’

### ISSUE THREAD

**Issue by jiutiananshu** [dataabc/weiboSpider#134]
Error:’NoneType' object has no attribute’ xpath’
Traceback (most recent call last) :    |421/ 1693 [1:09:17<1:3
      File" weiboSpider. py"，line 683， in get_ one page
             info = selector. xpath(" //div[@class=' c' ]”)
AttributeError:’ NoneType’ object has no attribute’ xpath’
          Error:   ni ckname'
Traceback (most recent call last)   |422/ 1693 [1:09:17<1:0
         File" weiboSpider. py，line 699, in get_ one_ page
 ‘ -’  * 30， self. user [' ni ckname],
       KeyError:’ ni ckname
大佬这个报错怎么回事，有什么建议。能不能同一个cookie运行多个爬虫，我开了好几个窗口就会这样。

**Comment by jiutiananshu** [comment]
还有就是，再次运行的时候会不会从第一个重新开始，还是会跳过已经爬取完毕的user_id。

**Comment by dataabc** [comment]
出现这个错误是因为速度太快了，而且你开了多个窗口，容易被限制。可以降低速度，具体是修改get_weibo_info：
```
                    if (page - page1) % random_pages == 0 and page < page_num:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
上面意思是每1到5页随机暂停6到10秒，你可以适当加快暂停频率，加长等待时间。

如果你想加速，可以在不同电脑上用不同账号的cookie，因为限制包括ip和账号。

如果你使用user_id_list.txt给程序输入user_id，再次运行的时候会继续执行。因为程序获取用户后会在user_id_list.txt文件对应的user_id后更新since_date，下次程序运行读到这个user_id如果上次执行后没有发布新微博就跳过，否则会读取新微博。

**Comment by jiutiananshu** [comment]
谢谢大佬，明白了。

**Comment by jiutiananshu** [comment]
这个报错一段时间后恢复爬取吗？在爬取的时候，一直报这个错，而且重新启动程序，还是出现这样的情况，是限制ip了吗

**Comment by dataabc** [comment]
限制一段时间会自动恢复，大约几小时，这期间暂时不要运行程序。

限制是包括限制账号和ip的，都是一段时间自动恢复，不确定你现在是限制账号还是ip，你可以换个账号试试，如果可以正确运行说明是账号暂时被限制。
