### ISSUE TITLE
爬取不全问题

### ISSUE THREAD

**Issue by glowforyou** [dataabc/weiboSpider#137]
您好，在我运行过程中，发现并不能完全爬取某个用户某天的博文。
例如：央视新闻最近两天有许多关于国家主席和特朗普的博文，但是无论设置cookie与否都不能爬取，想请问有没有解决方法，还是说可以全部爬取，只是我某些东西忘记设置了。感谢！

**Comment by glowforyou** [comment]
问题已解决，如果在使用者filter =1 既筛选原创文章时候，最好把get_one_page里一开始的url设置为'https://weibo.cn/%s?filter=1&page=%d' % (self.user_config['user_uri'], page)的形式，否则爬取到的内容将会少一部分

**Comment by dataabc** [comment]
感谢反馈。

和政府相关的微博要比一般账号要严。在url中开始是有filter的，就是利用这种方式获取原创微博的。只是后来有使用者反馈，只获取到当年的原创微博，以前的很多原创没有获取到，才知道这种方式可能只能获取原创微博的一部分，因此用了现在的方式获取原创微博，即先获取全部微博，然后筛选原创微博。这种方式也有缺点就是速度不如在url中用fiter设置快，还有就是为了获取原创微博，可能要多获取很多没用的转发微博，这样也就提高了被限制的风险。上面说的没有获取全部微博，不知道是否和这个原因有关。

再次感谢，如果其它建议或问题，欢迎继续反馈

**Comment by glowforyou** [comment]
赞。现在的方式爬取的原创内容还是要少一小部分。个人觉得可以加个判断，使用者是否只需要一年内的原创，如果是的话可以在url中加filter。这样得到的博文就是完整的

**Comment by dataabc** [comment]
感谢反馈。

思路不错好，我考虑下，如果觉得可行，近期会加上判断是否在一年内。

再次感谢，如果有其它问题或建议欢迎继续反馈。

**Comment by dataabc** [comment]
刚才测试了一些账号，发现在url中加filter在部分账号还是爬不全，而且是一年之内的也不全，只能通过先爬全部微博，然后在里面筛选原创微博。

再次感谢建议
