### ISSUE TITLE
半个月没更新了

### ISSUE THREAD

**Issue by modun** [dataabc/weiboSpider#139]
半个月没更新了，大佬打算近期更新吗？

**Comment by dataabc** [comment]
有新需求或者bug，就可以更新了，没有的话也不知道更新什么，不能为了更新而更新。（事实上，确实有几个新需求待完成）

还有，最近在写一个微博关键字搜索的项目，可以指定日期获取搜索关键字的微博，24小时的范围内最多能够获得几百万的微博（24小时是能够获得这么多，具体需要多少时间下载到本地，还要看获取的速度）。感觉很有意思，所以先更新关键字项目的功能。

更新的优先级大致为：本项目的bug>其它项目的bug>本项目非常有意义的新需求>搜索关键字项目的新功能>本项目的一般需求。基本上就是按这种顺序写代码，本项目的优先级最高，但是如果没有bug或重要且非常有意义的新需求，可能会先更新关键字搜索项目，同时也会想着本项目的需求的。

**Comment by modun** [comment]
微博关键字搜索的项目 有前端页面吗？如果没有，是否考虑加上。

**Comment by dataabc** [comment]
微博关键字搜索项目地址是<https://github.com/dataabc/weibo-search>

现在只完成了一小部分，暂时没有前端部分，暂时也没有加上的打算。还有很多功能没实现，先把基本功能实现了再考虑其它。项目用的是scrapy实现的，如果需要使用，是需要安装scrapy，还有一些python模块。因为现在比较简单，README暂时还没写使用教程。
