### ISSUE TITLE
爬取自动停止问题

### ISSUE THREAD

**Issue by Archenemy61** [dataabc/weiboSpider#140]
您好，在filter=1情况下我发现在爬取到某一页存在多条连续的非原创微博时会自动停止爬取过程

**Comment by dataabc** [comment]
感谢反馈，程序没有停止。

filter=1即获取原创微博时，程序首先获取当前页面的所有微博，然后筛选出里面的原创微博，并打印原创。因为存在多条转发微博，即这些微博虽然读取到了但是不满足条件，因此不会保存不会打印，才造成程序停止的错觉，其实程序正在正常爬取。

原先在url中通过filter选择原创微博，发现无法获取全部原创，因此才使用上面的方法。

**Comment by Archenemy61** [comment]
在我这里读取了空的一页之后会出现exit code=0，然后程序就停止了，不知道是不是我设置的问题

**Comment by dataabc** [comment]
感谢反馈，能否提供出错的user_id，我测试下

**Comment by Archenemy61** [comment]
0.0 不好意思，我忘记了since_date没有改，还想问一下是否考虑加入ip池或者账号池呢？我刚刚就被sina限制访问了==，感谢回复。

**Comment by dataabc** [comment]
有这个打算，不过现在正在写微博关键词搜索的代码，那个项目获取微博的数量非常大，如果写的话，可能会先在那个项目实现，然后再完善本项目。
