### ISSUE TITLE
能否还原之前版本中的【源微博正文】功能呢？

### ISSUE THREAD

**Issue by redMUSCLE** [dataabc/weiboSpider#141]
您好，一直有使用您的软件。非常感谢您。
原本写入csv的【转发内容】和【原创的内容】是分开的。
而最近的版本您更改了，而是一次性的合并了【转发内容:   ++原始用户: ++转发理由：】
在我大量进行一些新项目时，这个问题对我来说的确是个不小的阻碍。
请问您下次更新能否把它做回原来的模样呢？
或者我应该如何修改代码以达到可以写入的【源微博正文】和【正文】的版本呢？
再次感谢。

**Comment by dataabc** [comment]
感谢反馈，程序现在就是源微博和转发分开的。

你说的【转发内容: ++原始用户: ++转发理由：】应该是cookie版的情况，本版本转发微博的转发部分和原创部分是分开的，可能是你把本程序和cookie版弄混了。本程序满足你的需求，cookie版确实是【转发内容: ++原始用户: ++转发理由：】这种方式存储转发微博的。

如果还有问题，欢迎继续反馈

**Comment by redMUSCLE** [comment]
我下载的的确是本页面中的程序。
不知您说的cookie版是什么呢？
是指在Json里填入cookie之后的版本吗。

**Comment by dataabc** [comment]
刚刚看错了，以为本程序是免cookie版，说反了。
本程序就是cookie版，转发微博会存储为【转发内容: ++原始用户: ++转发理由：】形式；
你想要的是把转发微博分成两条微博即转发部分和原创部分，免cookie版(<https://github.com/dataabc/weibo-crawler>)就是这么做的，满足你的要求，你应该是用过一段时间免cookie版的，然后使用本程序，发现和原来不一样了，应该是把它们搞混了。
本程序（cookie版）的正文是以【转发内容: ++原始用户: ++转发理由：】存储的；
免cookie版是分为【源微博正文】和【正文】单独存储的，你之前用的应该是免cookie版，现在继续用免cookie版就解决问题了
