### ISSUE TITLE
如何爬取自己的微博

### ISSUE THREAD

**Issue by coolsocket** [dataabc/weiboSpider#142]
我号没了，别人都看不了我的首页，所以注册小号爬是办不到的。 但是我自己可以看到自己的内容，这样的情况有办法使用爬虫吗？

**Comment by dataabc** [comment]
感谢反馈，可以获取。

可以参考 #113 ，修改url可以获取自己的微博。

**Comment by coolsocket** [comment]
很感谢你的帮助！解决了我的问题！
