### ISSUE TITLE
关键字搜索运行失败

### ISSUE THREAD

**Issue by yaoshazixingche123** [dataabc/weiboSpider#143]
在cmd中运行scrapy crawl search -s JOBDIR=crawls/search这段代码显示

Scrapy 2.0.1 - no active project
unknown command : crawl
ues "scrapy" to see available commands

scrapy.cfg也重新编辑过了，但是还是不行

**Comment by dataabc** [comment]
cd到项目文件夹(weibo-search)下，运行命令就好

**Comment by yaoshazixingche123** [comment]
好了，谢谢大佬
