### ISSUE TITLE
since date设计的2020.1.1，但爬到微博的20页就停止了

### ISSUE THREAD

**Issue by Wuxingxing-Megan** [dataabc/weiboSpider#145]
设置的转载=1，也没有出现error，就是显示爬取完毕，爬到5月7日，共192条微博就停了～
不知道是什么原因，求问作者大大，超级感谢您！！

**Comment by dataabc** [comment]
感谢反馈。

config.json文件的user_id_list的值是txt文件路径还是user_id列表？
如果是文件路径，txt也会包含一个since_date，它是程序自动生成的，是上次执行程序的时间。如果是这种情况，程序使用的是这个生成的since_date而不是config.json中的since_date。这样的优点是可以为每个user_id设置不同的since_date，且自动更新，更方便灵活。

不知道是不是上面的原因，如果还有问题，欢迎继续反馈

**Comment by Wuxingxing-Megan** [comment]
谢谢您的解答～
我是用的是user id列表（就是在网址中抽取的一串数字），刚刚我又试了一下，发现是只能爬取20页就自动停止了，开始下载图片了，不知道是什么原因～

**Comment by Wuxingxing-Megan** [comment]
噢噢，原来是20页一写，我明白啦～
再次感谢作者大大（我有点小白），辛苦啦！！
