### ISSUE TITLE
微博含emoji表情爬取

### ISSUE THREAD

**Issue by dianxiangege** [dataabc/weiboSpider#147]
请问一下大大，爬取含有表情符号的博文时出现这个错误UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 1-1: Non-BMP character not supported in Tk
有什么解决方法么
谢谢大大

**Comment by dataabc** [comment]
感谢反馈，能否提供出错的微博id，方便调试，感谢

**Comment by dianxiangege** [comment]
只要含有emoji的微博，用idle运行会报错，可以以英国大使馆微博为例，1663026093，时间设置为2020-5月开始即可。是不是idle编译器的问题呢？想问下大大用什么来运行爬虫？

**Comment by dataabc** [comment]
我直接在win10下用
```
python3 weiboSpider.py
```
命令执行的，微博就是1663026093，没有出错，换成python2也一样。感觉是idle的原因<https://www.jianshu.com/p/e0fad3bd35d1>，你应该可以通过把print语句注释掉来避免这个错误

**Comment by dianxiangege** [comment]
确实是idle的问题，我用命令执行没有问题，谢谢大大！
