### ISSUE TITLE
网页解析报错：AttributeError:’ NoneType’ object has no attribute’ xpath’

### ISSUE THREAD

**Issue by dianxiangege** [dataabc/weiboSpider#149]
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "weiboSpider.py", line 703, in get_one_page
    info = selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
大大我在爬取数据的时候发现了这样的错误，这是什么问题呢？

**Comment by dianxiangege** [comment]
使用的是苹果自带的命令行工具
python3 weibospider.py

**Comment by dataabc** [comment]
说明你速度太快了，暂时被限制了，限制一段时间会自动解除。可以通过降低速度避免被限制，修改get_weibo_info方法：
```
                    if (page - page1) % random_pages == 0 and page < page_num:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
上面的意思是每1到5页随机sleep 6到10秒，你可以适当加快sleep频率或加长等待时间。

**Comment by songzy12** [comment]
duplicate: 134
