### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wwwpf** [dataabc/weiboSpider#15]
只有1条微博的时候抓不到数据，99行应该可以改成>=3。
微博内容在末尾多了4字符：20, E2 80 8B, E2 80 8B, E2 80 8B

**Comment by dataabc** [comment]
已修复

**Comment by wwwpf** [comment]
0条微博确实没有测试过，抱歉，但多余的4个字符确实是有的，1个空格+3个无宽度的字符，请看图：

![1](https://user-images.githubusercontent.com/24772538/36935084-9b57ccbe-1f2d-11e8-9567-11528b14fe7f.PNG)
![2](https://user-images.githubusercontent.com/24772538/36935085-9b920578-1f2d-11e8-9a13-c056806a855f.PNG)

图1因为[:-1]去掉最后1字符，所以还剩空格+2个多余字符。
另外，未显示全文的微博似乎没有特别处理？

**Comment by xnzmc** [comment]
至于空白字符，我的解决办法是解析时直接正则替换掉 `u200B+`和`u202F+`

**Comment by wwwpf** [comment]
@xnzmc 请问你延时怎么加的，我加不加延时，到了60页都是403，不过我还抓了图片url，如果不抓url倒是还没出现403。

**Comment by dataabc** [comment]
可以提供下4字符的微博id吗，方便调试

**Comment by wwwpf** [comment]
@dataabc 4字符的不在少数呀，你之前代码里的那个id好像就有。

**Comment by xnzmc** [comment]
@wwwpf 我只爬取了140字消息，全文和图片等都没有爬取。不过一个思路是：将某条微博的图片和全文页面链接保存，然后后续再次爬取。至于延迟，我大致的速度是一小时8k消息左右
