### ISSUE TITLE
关于爬微博底下评论的提问

### ISSUE THREAD

**Issue by 5m17h** [dataabc/weiboSpider#151]
请问要爬取一条火热微博底下的所有评论，是不是难度很大？
我没看到github有人做出来，但是这个需求，对研究真人/水军 想法，很有用

**Comment by dataabc** [comment]
感谢反馈。

我只能获取部分评论，无法获取全部。如果想研究水军，我作了另一个项目，不知道适不适合你。项目的作用是搜索包含某些关键词的微博，可以指定要搜索的微博的发布时间，对于一天的筛选范围，最多可以获得1000万条微博。可以搜索要研究的关键词，如某某明星，判断这些微博是不是真人所发布，项目地址<https://github.com/dataabc/weibo-search>。

如果还有其它问题或建议，欢迎继续反馈

**Comment by arrogant-create** [comment]
请教一下如何获取前几页的评论和下面的子评论还有图片？

**Comment by dataabc** [comment]
@arrogant-create 

<https://weibo.cn/comment/weibo_id?page=1>是微博的第一页评论，page为2是第二页评论，以此类推，weibo_id是微博的id。解析页面就可以得到每一页的评论和图片，可以解析多页获取多条评论。

**Comment by arrogant-create** [comment]
weibo_id是这条微博的id还是微博用户的id？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 中午12:46
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 关于爬微博底下评论的提问 (#151)





 
@arrogant-create
 
https://weibo.cn/comment/weibo_id?page=1是微博的第一页评论，page为2是第二页评论，以此类推，weibo_id是微博的id。解析页面就可以得到每一页的评论和图片，可以解析多页获取多条评论。

**Comment by arrogant-create** [comment]
修改id后会显示页面不存在然年自动跳转到其他页面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 中午12:46
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 关于爬微博底下评论的提问 (#151)





 
@arrogant-create
 
https://weibo.cn/comment/weibo_id?page=1是微博的第一页评论，page为2是第二页评论，以此类推，weibo_id是微博的id。解析页面就可以得到每一页的评论和图片，可以解析多页获取多条评论。

**Comment by dataabc** [comment]
@arrogant-create 

是这条微博的id

**Comment by arrogant-create** [comment]
修改了还是显示不存在，然后跳转到其他页面------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Chen&amp;nbsp;Lei&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月10日(星期五) 中午1:29
收件人:&nbsp;&quot;dataabc/weiboSpider&quot;<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;&quot;arrogant-create&quot;<1246051548@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 关于爬微博底下评论的提问 (#151)

**Comment by dataabc** [comment]
@arrogant-create 

比如迪丽热巴的这条微博，weibo_id是J74OAhxtL，url就是<https://weibo.cn/comment/J74OAhxtL>

**Comment by arrogant-create** [comment]
本条微博的id是爬取出来的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 下午2:59
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 关于爬微博底下评论的提问 (#151)





 
@arrogant-create
 
比如迪丽热巴的这条微博，weibo_id是J74OAhxtL，url就是https://weibo.cn/comment/J74OAhxtL

**Comment by arrogant-create** [comment]
我发现了，是bid，谢谢大大，能用代码实现吗，还是直接点击网页察看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 下午2:59
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 关于爬微博底下评论的提问 (#151)





 
@arrogant-create
 
比如迪丽热巴的这条微博，weibo_id是J74OAhxtL，url就是https://weibo.cn/comment/J74OAhxtL

**Comment by dataabc** [comment]
@arrogant-create 

weibo_id就是本程序获取到的id，在免cookie版对应的是bid，我目前没有实现这个的打算，你可以自己解析页面，不过评论获取不全

**Comment by arrogant-create** [comment]
有位大大写了一个，不过我运行出来显示以下错误：
Traceback (most recent call last):
&nbsp; File "weibo_comment.py", line 98, in <module&gt;
&nbsp; &nbsp; resp = requests.get(URL, params=params, headers=headers)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 76, in get
&nbsp; &nbsp; return request('get', url, params=params, **kwargs)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 61, in request
&nbsp; &nbsp; return session.request(method=method, url=url, **kwargs)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 530, in request
&nbsp; &nbsp; resp = self.send(prep, **send_kwargs)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 643, in send
&nbsp; &nbsp; r = adapter.send(request, **kwargs)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
&nbsp; &nbsp; resp = conn.urlopen(
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
&nbsp; &nbsp; httplib_response = self._make_request(
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
&nbsp; &nbsp; conn.request(method, url, **httplib_request_kw)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1230, in request
&nbsp; &nbsp; self._send_request(method, url, body, headers, encode_chunked)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1271, in _send_request
&nbsp; &nbsp; self.putheader(hdr, value)
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1203, in putheader
&nbsp; &nbsp; values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 下午3:53
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 关于爬微博底下评论的提问 (#151)





 
@arrogant-create
 
weibo_id就是本程序获取到的id，在免cookie版对应的是bid，我目前没有实现这个的打算，你可以自己解析页面，不过评论获取不全

**Comment by dataabc** [comment]
@arrogant-create 

这是编码错误，可以请教下作者

**Comment by arrogant-create** [comment]
好的谢谢大大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 下午4:46
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 关于爬微博底下评论的提问 (#151)





 
@arrogant-create
 
这是编码错误，可以请教下作者
