### ISSUE TITLE
你们能爬取到视频么？我的有时候可以有时候不行，

### ISSUE THREAD

**Issue by luofengda** [dataabc/weiboSpider#152]

**Comment by dataabc** [comment]
感谢反馈。

视频有时候下载确实会失败，经常是一张比视频还大的图片下载比视频还快，可能是有限制。所以如果没有必要，尽量不要下载视频。如果要下载且下载失败了，程序会在视频文件夹生成not_downloaded.txt，内容包含视频url和所属的weibo_id，可以再手动下载如果量不是很大的话。但是有一个缺点，url是有有效期的，过了有效期就无法下载了。

感谢反馈，如果还有问题欢迎继续讨论
