### ISSUE TITLE
简介爬取信息丢失

### ISSUE THREAD

**Issue by songzy12** [dataabc/weiboSpider#154]
当前的 extract_user_info 在解析简介时如果遇到简介里本身具有 ":" 的时候会丢失信息：
```
                    self.user[en_list[zh_list.index(
                        i.split(':')[0])]] = i.split(':')[1].replace(
                            '\u3000', '')
```

例如：https://weibo.cn/2110128782/info
```
>>> i
'简介:fit coffee :D life&lt;日常碎碎念 追星&gt;'
>>> i.split(":")[1]
'fit coffee '
```

修正方式为限制 split 的次数 [1]：
```
>>> i.split(":",1)[1]
'fit coffee :D life&lt;日常碎碎念 追星&gt;'
```

[1] https://stackoverflow.com/questions/6903557/splitting-on-first-occurrence

**Comment by dataabc** [comment]
感谢反馈。

不但发现了问题，还给出了解决方案，非常感谢。我有个提议：**你能否将修改后的代码Pull Request**。这样你还能出现在contributors列表里，这是我想到的最好的感谢方法。如果今天24点前没有Pull Request，我会按照上面的方式自己修复代码。因为你上次帮忙编写了multi-file分支，代码非常好，我也非常感激。但是只有master分支的贡献人才会出现在contributors里，现在希望通过上面的方式表达感激之情，也能弥补这个遗憾。

再次感谢，如果还有其他问题或建议欢迎继续讨论

**Comment by songzy12** [comment]
作者客气了。

稍后我会提交这个 Pull Request. 

关于分支的事情我有一点想法，不过还需要稍微调研一下。
可能稍后会再开一个 issue 来讨论这件事。

**Comment by dataabc** [comment]
好的，期待你的新想法
