### ISSUE TITLE
各位能否爬取全站某用户发表的评论

### ISSUE THREAD

**Issue by pursuelu** [dataabc/weiboSpider#158]

**Comment by dataabc** [comment]
感谢反馈。

如果要获取某用户全站发表的评论，需要知道这些评论的页面，比如，假如有一个用户所有评论页或类似的页面，然后才能获取。如果不知道页面或接口是无法获取某用户在全站发表的评论的。

如果还有其它问题，欢迎继续讨论。

**Comment by pursuelu** [comment]
> 感谢反馈。
> 
> 如果要获取某用户全站发表的评论，需要知道这些评论的页面，比如，假如有一个用户所有评论页或类似的页面，然后才能获取。如果不知道页面或接口是无法获取某用户在全站发表的评论的。
> 
> 如果还有其它问题，欢迎继续讨论。

我已经有想法并且有在做了，我现在已完成爬取关注人，再把user_id重置成这位关注人，再去爬取它的微博，点开评论，翻页查找发言人是不是他，是的话，填充到新增的相关评论字段里，不过遇到那种好几十页的评论列表好慢。

**Comment by dataabc** [comment]
感谢回复。

非常好的想法。虽然可能无法获取那些没有关注且没有点赞没有转发但评论过的微博，但确实能得到很多想要的评论。目前这可能是最好的方法了，感谢分享，对以后有相同需求的网友是非常好的借鉴。
