### ISSUE TITLE
请问能否爬取某用户的开博时间，或者开博后发的第一条微博呢？

### ISSUE THREAD

**Issue by xinyuanli59** [dataabc/weiboSpider#159]
大大您好，我想爬取某用户，例如迪丽热巴的开博时间2010-07-02，或者她开博后发的第一条微博（我能看见最早的，是2011-06-07的一条）。请问程序能比较简单、快速地实现吗？我想过把她全部的微博都爬下来，再找最早的一条，可是这样有点慢。您有什么建议吗？或者，能从用户信息里面，爬出来开博时间吗？

谢谢您~啾咪~

**Comment by dataabc** [comment]
如果是开博时间，免cookie版(<https://github.com/dataabc/weibo-crawler>)可以做到。也可以修改本程序，修改get_weibo_info方法：
```
for page in tqdm(range(1, page_num + 1), desc='Progress'):
```
代表从第一页爬到最后一页（page_num），改成：
```
for page in tqdm(range(page_num, page_num + 1), desc='Progress'):
```
这样只会爬取最后一页，速度比爬全部快一些
