### ISSUE TITLE
模块拆分和代码重构

### ISSUE THREAD

**Issue by songzy12** [dataabc/weiboSpider#160]
先占个位置。

重构后的样子会大体类似 #91 的设计，应该还会加一些细化的地方。

可能这周末之前会提一个 pull request.

打包后当前 master 分支的实现里跟文件路径相关的地方似乎还有 bug（涉及到调用 `os.path.realpath` 的地方），到时会一并试着修一下。

**Comment by dataabc** [comment]
感谢，现在你是Collaborator，直接向本项目推送就可以，不一定要pull request。

文件路径相关确实存在bug：

- user_id_list文件路径目前只能写绝对路径；
- 结果文件也是在程序安装路径生成。

以上两个需要修改，只需要把部分**程序目录**
```
os.path.split(os.path.realpath(__file__))[0]
```
改成**命令行当前路径**
```
os.getcwd()
```
就可以。

还有一个我在考虑是否要添加user_id_list.txt文件，因为它对于部分用户可能用不到。如果添加，用户运行
```
python3 -m weibo_spider
```
是不是要帮用户生成，目前我更倾向于添加且生成。

实现上面所有特性后，pypi版应该是这个样子：

用户安装完pypi版本，第一次在任意拥有写权限的目录运行
```
python3 -m weibo_spider
```
如果当前目录不存在config.json和user_id_list.txt，程序会把cong.json和user_id_list.txt从**程序目录**复制到**命令行当前目录**，提示用户修改配置，程序停止；然后用户修改config.json配置；再次执行，因为当前目录已经有config.json了，所以程序可以正式获取微博了，结果文件也会在**命令行当前目录**下生成。
这样的好处是用户不用手动创建config.json和user_id_list.txt，用户也脱离了只能在**程序目录**写结果的限制，可以将结果写入任意有写权限的目录。

这只是我的想法，如果有其它建议，欢迎讨论:smile:路径相关的问题这两天我会修复，user_id_list相关我还在犹豫，毕竟有一部分用户是使用user_id列表（而非user_id_list.txt）输入user_id的，他们用不到user_id_list.txt

**Comment by songzy12** [comment]
感谢。

那我到时候直接 push 到 multi-file 分支，然后再在这个 issue 下讨论。

关于 user_id_list.txt，我也赞同“添加且生成”的方案。
因为如果用户想要通过关注列表自动进行多轮爬取的话，有一个这样文件作为输入还是比较方便的。

**Comment by dataabc** [comment]
好的，在push到multi-file分支，在这个issue下讨论。

文件路径相关的bug已经修复了，后续会添加user_id_list.txt相关的操作

**Comment by songzy12** [comment]
我刚刚更新了一下 multi-file 分支，当前对应 master 分支的这个 commit 的状态: https://github.com/dataabc/weiboSpider/commit/5734620137e23bb2b0acccf09dcae9ad177bfc7d

跟具体代码相关的讨论可以直接在相关的 commit 页面进行：https://github.com/dataabc/weiboSpider/commit/26683b5db48b28297883ae232fb21d8dde2de972

我简单地测了一下各种输出格式和图片视频的下载，应该都是能运行成功的。

如果要跟 master merge 的话也很简单，应该就是把 weibo_spider 这个文件夹下的 weiboSpider.py 这个文件删掉，替换成 multi-file 里面的那一组文件，然后把 multi-file 下的 weibo.py 重命名回 weiboSpider.py 就可以。

**Comment by songzy12** [comment]
我待会儿把 merge 给做了然后也 push 到 multi-file 分支。

**Comment by dataabc** [comment]
好的，辛苦了

**Comment by songzy12** [comment]
现在 multi-file 和 master 这两个分支应该是等价的了。

不过不太知道为什么它还是显示不能 auto merge.

**Comment by songzy12** [comment]
啊，现在看起来好了。

**Comment by dataabc** [comment]
已经把multi-file分支合并到主分支，可以直接向master分支提交代码了，不用同时维护master和multi-file分支了

**Comment by songzy12** [comment]
哇，感谢！我把 multi-file 删掉啦。

**Comment by songzy12** [comment]
对了其实我还想问一下这个项目之后对于 python2 的支持打算是什么样的呢？

因为当前各继承类 (writer, parser, etc) 的实现其实还不太好，
比如其实有一些函数是想要在基类里声明为纯虚函数的，
但是 python2 和 python3 的语法还是有一些区别：
- python2: https://docs.python.org/2/library/abc.html
- python3: https://docs.python.org/3/library/abc.html

另一个参考是最新的 ubuntu 发行版已经默认不再安装 python2 了:
- https://askubuntu.com/a/1224710

如果只考虑 python3 的话可能还会再整理一下各个类，
如果要兼顾 python2 的话可能暂时就让它们保持现状了。

**Comment by dataabc** [comment]
这是一个非常有意义的问题。想了一会，结论是：
默认只提供python3支持，以后也只维护python3版本；另开一个python2相关的分支，现在的兼容版本push到python2分支上，不再维护python2分支。

因为python2已经停止维护了，所以python3是大势所趋。把兼容版本保留在python2分支是为了那些还在使用python的用户，除非有bug，这个版本我们一般不在维护。

以上是我的想法，不一定想到周到，如果你对这个问题有其它想法，我们可以讨论一下

**Comment by songzy12** [comment]
我觉得这个考虑已经非常周到了，赞！

**Comment by dataabc** [comment]
好的，我这两天会加上python2分支，并修改README

**Comment by dataabc** [comment]
已经添加python2分支和修改README。

发现一个“问题”。执行现在的程序会出现“No module named”的错误，应该是模块路径问题。不知道是不是我运行方式不对，还是系统原因。已经修复了，因为更改了一些文件名，在这里说明一下：
为了方便使用，把config_sample.json修改成了config.json；
把parser文件夹名字修改成了weibo_parser，原因是parser与python3中已存在的模块名冲突。

**Comment by songzy12** [comment]
辛苦啦！

关于 config_sample.json 和 ModuleNotFoundError 的问题我在 https://github.com/dataabc/weiboSpider/commit/fa5e242541e0f751945530d58a118db74c1d83ec 里写了两个评论，
作者有空时可以看一下~

**Comment by songzy12** [comment]
这个 issue 在 close 之前还会做的事：
1. 用 abstract class 规范一下 downloader, writer, parser 各模块 [1]。
2. 整理一下各 writer 类的 __init__, write_user, write_weibo 方法。当前的实现虽然能运行，但有些职能体现的不是特别清楚，比如：当前 weibo_spider/writer/mysql_writer.py 的 write_user 里负责了创建数据库的内容，这部分应该要挪到 __init__ 里。
3. weibo_spider/parser/page_parser.py 的 extract_picture_urls 部分出现了新的 selector，这部分会单拎一个 mblog_pic_parser 出来；parser 的设计应该是只负责一个 url，并在对这个 url 调用一次 handle_html 后的 selector 上做 parse.
4. 给重构后出现的这些类加一些注释。

[1] https://www.geeksforgeeks.org/abstract-classes-in-python/

**Comment by dataabc** [comment]
辛苦啦

**Comment by songzy12** [comment]
在自动化测试的部分开始之前，这部分还有一点事情想做：
- 把 weibo 和 user 相关信息具体化成两个类，以方便重用和测试（当前它们是两个 dict）
- 去掉 printer.py，而给这两个类分别加一个 __str__ 的实现。
- 相应的 parser 和 writer 的部分也需要跟着修改一下。

估计要几天的时间。
