### ISSUE TITLE
使用 logging 模块来处理日志

### ISSUE THREAD

**Issue by songzy12** [dataabc/weiboSpider#161]
模块拆分的版本 <https://github.com/dataabc/weiboSpider/commit/036a2ee573ec366758e7f1922d012808f1981593> 功能方面应该是好的；
不过其实有一个问题没仔细处理，就是关于程序的日志部分。

master 版本里
- 使用了 print 语句来打印正常的信息，
- 使用了一个 write_to_log 函数来将出错信息写入了文件。

一个比较好的解决方式是使用 python 的 logging 模块，
- 它可以指定输出的 level 是 DEBUG, INFO, ERROR；
- 并且可以指定输出的位置是控制台屏幕还是写入文件。

这个 issue 用来 track 这个问题。

**Comment by dataabc** [comment]
不错的提议。

目前使用print主要是为了告诉使用者，程序正在运行，并且获取了百分之几的信息，这些信息具体是什么。
write_to_log主要是在cookie失效时使用，告诉使用者某年某月某日cookie已经失效了。**这其实是帮助使用user_id列表的用户的**，告诉他们更新cookie，重新获取这段日期的微博。使用user_id_list.txt用户不受影响，因为只有某目标用户爬取完成才更新since_date日期，如果cookie失效，微博不会获取，since_date也不会更新。更新cookie后，会从当前日期爬到since_date，这是没有问题的。

我们以后可以使用logging处理日志，这样确实比较规范

**Comment by dataabc** [comment]
已经添加写日志功能，可以通过logging.conf修改默认的日志配置，现在有三种形式的日志：
- 命令行输出：默认输出DEBUG级别及以上的信息，这是最全的；
- 写入all.log文件：默认写入INFO级别及以上的信息，按天保存日志，每天生成一个日志，最多保留5个all.log开头的日志；
- 写入error.log文件：默认只写入WARNING级别及以上的信息。

目前生成的日志文文件保存在weiboSpider目录，如果想要修改日志保存路径，可以修改weibo_spider中的logging.conf文件。考虑过让用户像config.json那样在当前文件夹生成配置文件，但是这样会增加用户使用成本，而且用户可能不关心日志相关设置，因此将配置文件放在了weibo_spider文件夹而不是当前目录。因为程序运行中生成的WARNING级别以上的信息较少，因此只单独写在error.log一个文件里，而不是像all.log按日期写入。

**Comment by songzy12** [comment]
作者辛苦了！
