### ISSUE TITLE
希望增加两个功能

### ISSUE THREAD

**Issue by kele2016** [dataabc/weiboSpider#162]
1，设置保存目录。比如/data/wwwroot/XXXX
2，照片视频按/year+month/ 这样可以自动分类。不然一个目录太多了。

我自己本地已经改好了。。

**Comment by songzy12** [comment]
@dataabc Just for your information the point 1 mentioned above is also implemented here:
https://github.com/dataabc/weiboSpider/blob/multi-file/weibo_spider/weiboSpider.py#L25

**Comment by dataabc** [comment]
感谢建议。
第一个问题已经回答了，关于第二个问题：考虑过图片等按日期文件夹分类，但是因为有很多用户微博比较少，如果按日期分，可能很多文件夹只有几张图片，反而更费时。我们如果想浏览图片，必需先打开日期文件夹才可以。要想浏览所有多媒体文件，必需要分别打开它们的文件夹。所以，现在把所有图片和视频分别放到img和video文件夹里。文件名为如下格式：
```
yyyymmdd+微博id+序号
```
如果某微博只有一张图片，序号会省略，否则序号为该图片在这条微博中所有图片的位置。文件名中已经包含日期了，按文件名排序，日期相近的图片位置也相近，与日期文件夹类似，而且更一目了然。因此，暂时没有按日期文件夹分类的打算。

感谢建议，如果还有其它建议欢迎继续讨论
