### ISSUE TITLE
MySQL warning message for VALUES

### ISSUE THREAD

**Issue by songzy12** [dataabc/weiboSpider#163]
当前 MySQL 的 insert 语句会报一个这样的 warning:

```
Warning: (1287, "'VALUES function' is deprecated and will be removed in a future release. Please use an alias (INSERT INTO ... VALUES (...) AS alias) and replace VALUES(col) in the ON DUPLICATE KEY UPDATE clause with alias.col instead")
```

具体应该是由下面这段引发的：
```
            sql = """INSERT INTO {table}({keys}) VALUES ({values}) ON
                        DUPLICATE KEY UPDATE""".format(table=table,
                                                       keys=keys,
                                                       values=values)
            update = ",".join([
                " {key} = values({key})".format(key=key)
                for key in data_list[0]
            ])
            sql += update
```

更具体一点是由
```
            update = ",".join([
                " {key} = values({key})".format(key=key)
                for key in data_list[0]
            ])
```

里面的 `values({key})` 引发的。

不过这个目前只是个 warning，应该不着急修复。

参考：
https://dev.mysql.com/worklog/task/?id=13325
https://dev.mysql.com/worklog/task/?id=6312

**Comment by songzy12** [comment]
我们可以使用右侧的 Assignee 这个功能来避免做同样的事。

比如现在 Assignee 是 No one 就表示还没有人打算做这个，
如果想要做的话就可以把这个 issue assign 给自己。

另一方面我想问一下我要不要过一下当前的 issues 列表，
把那些已经过时的内容标成 close 呢？（有需要的时候可以再 reopen）

这样可以方便大家把关注点放在仍然需要帮助的 issue 上。

**Comment by dataabc** [comment]
关于issues的问题我也考虑过。

事实上，大部分甚至全部没有关闭的issue都可能已经解决了。因为几乎每一个下面我都会给出解决方案，有一部分收到用户反馈，说问题解决了，一部分没有回复。

因为我总希望更min主一点，用户自己不close，就默认认为用户还有其它问题。然而，我自己也清楚，很多时候，用户只是在有问题的时候才回复，问题解决了可能就不管了。所以现在如果要关闭issue，可以先关那些明确回复解决了的issue和时间久远的issue(比如创建时间在一年以上)。其它没有回复，同时创建时间较新的issue可以保留。这是我的想法，其实有点矫情了。

这只是我的想法，欢迎讨论

**Comment by songzy12** [comment]
哈哈同意作者的想法。

那我有时间的时候就按照上面这个标准来过 issue 了哈：
1. 超过一年没有更新
2. 用户明确回复问题已解决

**Comment by dataabc** [comment]
感谢，辛苦了，我自己也会关闭一些issue

**Comment by songzy12** [comment]
我可能也会顺便修改一些 title 使得它能更准确地反映问题，
另一方面我在 close 之前会给一些评论来说明一下 close 的理由。

**Comment by songzy12** [comment]
Reference about Github issues: 
https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612

**Comment by dataabc** [comment]
已经开了一个issue，专门讨论issue问题
