### ISSUE TITLE
关于issue问题的讨论

### ISSUE THREAD

**Issue by dataabc** [dataabc/weiboSpider#164]
@songzy12 

在考虑要不要通过加模板的形式规范issue。

现在的issue没有规范大家如何提issue，所以issue不是特别规范。如果加上模板，大家在提issue时可以根据自己的需求选择模板，然后按照对应的模板提issue，会规范很多，实现的效果可以参考<https://github.com/tensorflow/tensorflow/issues>

**Comment by songzy12** [comment]
赞，加模板的想法很好。

另一方面我在想还可以在 docs 里创建一个 FAQ.md，
用来记录 issue 里超过两三个人问或者说比较典型的报错或者需求，
能想到的包括：
- 关于爬取某一时间段微博的需求
- 关于爬取评论的需求
- 因为爬取频繁导致的 cookie 失效
- user_id 的问题（当然这个已经解决了）

对于一个已知的 FAQ 可以给出相关的 issue 链接，当前的状态（已解决、计划中、不打算做）等。
这样用户可以去 vote up 已有的 issue 而不是开一个重复的。

这样用户或者开发者提 issue 的一个典型的流程可以是：
1. 先检查一下 FAQ 里是不是已经有了，然后得到解答或者去vote up
2. 再搜一下当前 open 和 close 的 issue 是不是有人提过（假设 issue 的 title 能比较明确反映主题）
3. 选取上面提到的适当的模板来写新 issue

不过这些应该也都不急。

**Comment by dataabc** [comment]
FAQ的想法太好了，大赞。

这些我有时间实现下

**Comment by songzy12** [comment]
我刚刚看到了这个：
https://github.com/tesseract-ocr/tesstrain/blob/master/.github/stale.yml

然后我查了一下相关的资料：
https://www.jeffgeerling.com/blog/2020/enabling-stale-issue-bot-on-my-github-repositories
https://github.com/probot/stale

作用是通过配置文件来自动将很久没有更新的issue标成stale或者close，感觉可能会有用。

**Comment by dataabc** [comment]
这个建议很好，已经添加stale了，大部分是默认配置，稍微做了修改：
>60天没活动会设成stale；如果stale状态7天没活动会关闭。有三个标签会跳过检查：pinned、security和to do，前两个标签还没添加，所以如果不想某issue因不活动而关闭，可以加上to do标签，我们也可以商量将其它标签也排除在外。

**Comment by songzy12** [comment]
辛苦啦！

**Comment by dataabc** [comment]
@songzy12 

这两天在思考自动化测试的事情。就是当我们push上代码后，自动检测我们的代码是否正确，这样会更规范，使用者也会更放心。目前想到的是用github actions做，可以参考
<https://medium.com/swlh/automate-python-testing-with-github-actions-7926b5d8a865>

**Comment by songzy12** [comment]
这个自动测试的事情特别好，之前我也想过这个。

把最开始的那个大单一文件拆成各个模块的其中一个好处是方面对各个模块做测试。
我对这部分比较也感兴趣，可以开一个实现自动化测试的issue，我可以take这部分。

有一个地方我还没有特别搞明白，就是怎么对有网络请求的部分做测试。（比如当前parser的部分）

我猜常规的做法应该是 mock 一个返回：给定一个 url 后并不实际发出网络请求，而是返回一个预定义好的 html，然后只测试 parse 的部分是不是正确。
不过我现在还不太知道这个 mock 网络请求的部分具体要怎么做。
我猜应该有现成的测试框架。

**Comment by dataabc** [comment]
issue相关功能已经添加，包含issue模板、stale和常见问题，本issue关闭。
