### ISSUE TITLE
问几个特别基础的问题

### ISSUE THREAD

**Issue by gudaost** [dataabc/weiboSpider#165]
没学过python，所以安装时有些头大
1、完整下载后，只需要保留weibo_spider文件夹内容吗？还是需要把weiboSpider压缩包中所有内容均保留？（这里包含了setup、requirements等）
2、cmd进入weibo_spider文件夹后，
`D:\weibo_spider>python3 -m weibo_spider`
`'python3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。`

`D:\weibo_spider>python -m weibo_spider`
`Traceback (most recent call last):
  File "C:\Users\gu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\weibo_spider\weibo_spider.py", line 16, in <module>
    from . import config_util, datetime_util, printer
ImportError: attempted relative import with no known parent package`

使用的Win 10系统，python安装的3.8.3版本,requirements已经安装完毕。

在这种专业的地方问这么基础的问题实在是抱歉！多谢多谢！

**Comment by dataabc** [comment]
感谢反馈。

1.看你的描述，应该是下载的源码，下载源码后，应先安装依赖，在weiboSpider目录下运行：
```sh
$ python3 -m pip install -r requirements.txt
```
如果你已经完成这步且没有错误，只保留weibo_spider也可以，其它文件是说明文档和pypi打包用到的，源码运行用不到；

2.应该在weiboSpider目录下执行
```sh
$ python3 -m weibo_spider
```
看上面，你应该是只保留了weibo_spider文件夹，如果这样，在D盘下运行上面的命令就可以。

如果还有问题或建议，欢迎继续讨论。

**Comment by songzy12** [comment]
> D:\weibo_spider>python3 -m weibo_spider
'python3' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

補充一點，根據這一條輸出，現在 Windows 下的 python 已經默認是 python3 了。
所以只需要像 @dataabc 說的在 D盤下（和 weibo_spider 平級的文件夾下）運行
```
python -m weibo_spider
```

**Comment by songzy12** [comment]
另一方面如果只是使用的話其實還是推薦直接通過 pip 安裝：
https://github.com/dataabc/weiboSpider#pip%E5%AE%89%E8%A3%85

這樣就不需要擔心路徑出錯的問題了。

**Comment by gudaost** [comment]
明白了，应该在weibo_spider 平級的文件夾下，而不是weibo_spider文件夹里面运行。这样说来，还是把所有内容都保留比较合适。
多谢！！
