### ISSUE TITLE
咨询一个关于版本的问题

### ISSUE THREAD

**Issue by gudaost** [dataabc/weiboSpider#166]
咨询一下，是否是这个情况：
cookie版：可以下载超过9张图片的全部图片，但不能下载转发的图片
免cookie版：不能下载超过9张以外的图片，但可以下载转发图片？
这俩没办法同时满足？
多谢！

**Comment by dataabc** [comment]
没办法，除非改代码。

这两个版本其实都可以改成超过9张的，本程序之所以没加这个功能是因为当初在免cookie版已经实现了，不想造轮子，没想到的是cookie版有限制。这个功能我再考虑下，看看是否在cookie版或免cookie版实现。

**Comment by songzy12** [comment]
其实我有点好奇有cookie和没有cookie的区别。

我刚刚看了一下文档的这一节（不过我还没有看那个项目的代码）：
https://github.com/dataabc/weibo-crawler#%E6%B7%BB%E5%8A%A0cookie%E4%B8%8E%E4%B8%8D%E6%B7%BB%E5%8A%A0cookie%E7%9A%84%E5%8C%BA%E5%88%AB%E5%8F%AF%E9%80%89

从上面的描述里看起来似乎只是在没有 cookie 的时候会漏掉一些内容，
那么有和没有 cookie 的这两个程序的最主要差别在什么地方呢？

**Comment by songzy12** [comment]
我发现了，那个是访问的 Json API，这个是解析了网页内容。
这是它俩的主要区别。

**Comment by dataabc** [comment]
@songzy12 

两种获取的内容差不多。区别是：
免cookie的优点
- 免cookie版不写cookie也可以使用，只是不如写cookie获取的信息多
- 免cookie版可以获取转发微博，cookie版只能获取部分
- 免cookie版可以获取微博中的话题以及艾特的用户，本程序暂时不能

免cookie的缺点
- 免cookie版遇到图片大于9张的情况只能爬9张，cookie版可以获取全部
- 免cookie版微博发布时间只能精确到天，cookie版可以精确到分钟

大致想到这些

**Comment by songzy12** [comment]
嗯嗯，谢谢解答！

**Comment by gudaost** [comment]
> 没办法，除非改代码。
> 
> 这两个版本其实都可以改成超过9张的，本程序之所以没加这个功能是因为当初在免cookie版已经实现了，不想造轮子，没想到的是cookie版有限制。这个功能我再考虑下，看看是否在cookie版或免cookie版实现。

感谢！希望早日实现！
