### ISSUE TITLE
关于自动化测试的讨论

### ISSUE THREAD

**Issue by dataabc** [dataabc/weiboSpider#168]
- 问：请说明需要什么新功能。<br>
答：自动化测试代码。

- 问：请说明添加该功能的意义。（非必填）<br>
答：可以让程序更规范；降低时间成本；增加测试的准确性和可靠性；增加对程序可靠性的信心。

**Comment by dataabc** [comment]
目前的想法是使用github actions实现，测试工具是pytest。
github actions的实现流程可以参考[Automate Python Testing With GitHub Actions](https://medium.com/swlh/automate-python-testing-with-github-actions-7926b5d8a865)。测试可能会用到python的Mock模块，可以参考[Understanding the Python Mock Object Library](https://realpython.com/python-mock-library)。其中文章的**Managing a Mock’s Side Effects**部分讲了一个网络相关的实例（get_holidays），可能对模拟网页解析有帮助。

**Comment by songzy12** [comment]
多谢参考文章！

get_holidays 例子里面提到的 response_mock 就是之前提到想找的东西~

**Comment by songzy12** [comment]
我们已经做了什么：
1. 给涉及到的 parser 都写了 test
2. 给这个 repo 加了一个跑 test 的 workflow
3. 在 README 里添加了显示这个 workflow 状态的 badge

**Comment by songzy12** [comment]
parser 相关的 test 全部在 tests/test_parser 下，相关细节如下：
## testdata 的生成
1. 在 weibo_spider/parser/util.py 中修改
```
GENERATE_TEST_DATA = True
```
这个的作用是 handle_html 函数被调用时会把 requests 的结果保存一份。

2. 设计 config.json 里的内容，使得我们能够访问到各种需要测试的 url pattern. 主要是：
a. filter = 0 ，使得能够包含转发微博链接
b. since_date 设到有图片相关的微博之前，使得能够包含图片链接
```
{
    "user_id_list": [
        "1669879400"
    ],
    "filter": 0,
    "since_date": "2020-06-01",
    "write_mode": [
        "json"
    ],
    "pic_download": 0,
    "video_download": 0,
    "cookie": "xxx",
    "mysql_config": {
        "host": "localhost",
        "port": 3306,
        "user": "xxx",
        "password": "xxx",
        "charset": "utf8mb4"
    }
}
```
3. 然后跑一遍程序
```
python -m weibo_spider
```

这个操作的效果是会在 tests/testdata/ 下
a. 生成 url_map.json，其中对应每一个在上面访问过的 url 生成对应的 hash 过的文件名。
使用 hash 是因为直接使用 url 做文件名的话会保存失败，因为 url 里有 `/` 这样的字符。
b. 对于上面 url_map 里 url 对应的的文件，保存了此时 requests.get(url, cookie) 的结果。
注意不要格式化这个文件，否则会在字符串里面引入一些换行，使得我们parser的结果与实际不符。

这些文件的作用是在 pytest 的时候并不实际发送 requests 请求，
而是读取文件里的内容作为 requests 的结果，从而使测试结果保持稳定。

4. testdata 生成结束后记得把这一行改回去：
```
GENERATE_TEST_DATA = False
```

## 运行 pytest
测试只需要在根目录下运行 
```
pytest
```
具体使用了 pytest 里面对 requests 的 mock，然后测试了各个 parser 对外暴露的函数。

PS: 然后真的测出了重构时的一个 bug 还顺手 fix 了一发（扶额

**Comment by songzy12** [comment]
我感觉这个项目主要需要测试的地方就是这些 parser，
至于其他的 test （比如各种 writer）就由其他人有兴趣时做吧~

**Comment by dataabc** [comment]
辛苦了，棒棒哒
