### ISSUE TITLE
请问这种爬虫触犯相关法律吗

### ISSUE THREAD

**Issue by Hybueno09** [dataabc/weiboSpider#169]
## 如题，谢谢

**Comment by dataabc** [comment]
爬虫是否违法应该和它的应用、数据是否公开等。

如果用于盈利目的应该是违法的。本项目的目的是帮助个人备份微博或者学习，很多使用者都是学生，比如他们毕业设计用到微博信息，但是手动一条条的复制太慢，本程序就是为了帮助他们，这些都是非盈利的。
如果获取的数据是非公开的应该是违法的。本项目获取的所有信息都是用户公开的信息。
如果爬虫影响到网站的正常运营是违法的。本程序是单线程的，并对速度做了限制。不会影响网站的正常运营。
另外，本项目没有添加任何开源协议，意味着是不允许商业项目使用的。即便他们要使用也不可能，因为现在是单线程，速度太慢。说白了，本项目就是一个无偿帮助个人使用者的脚本，为他们毕业设计等提供帮助，帮他们备份女神的微博等。

综上，本项目并不违法。

**Comment by Hybueno09** [comment]
@dataabc  明白了，感谢耐心解答
