### ISSUE TITLE
使用指令时运行不了脚本

### ISSUE THREAD

**Issue by SeepenL** [dataabc/weiboSpider#170]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是。。没运行得了

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：源码安装，在weiboSpider目录下terminal输入python3 -m weibo_spider回车，脚本没有运行直接到了下一空行。可能是因为weibo_spider有报错，于是单独运行该文件，发现可能是我目录设置问题吗，from . import config_util, datetime_util这句会报ImportError: cannot import name 'config_util'这个错。。
查了很久 没查到适合的解决方案。请问该如何解决呢？谢谢！

**Comment by songzy12** [comment]
首先单独运行文件是不行的，需要在 weiboSpider 下运行相应的命令。

另一方面第一遍运行时退出应该是因为当前目录下没有 config.json. 
第一遍运行会生成这个文件，然后根据自己的需要修改后再运行试试

**Comment by songzy12** [comment]
@dataabc 感觉这个地方可以再改一下。把两个配置相关文件（config，和 user list）移到 weiboSpider 下，可能会减少一点误解。

**Comment by SeepenL** [comment]
对 我查了一下，有from .xx import xx好像就不能直接运行该文件。但是对那个importerror我还是不知道是不是可以解决的。
而关于config.json，我也完全按我的需要设置完毕了，terminal的运行目录也没问题，运行了好几遍那个指令，都是没啥反应，直接刷到新的一行了。
很奇怪，你这么一说我反而不知道问题出在哪里了。


Zhengyang Song <notifications@github.com> 于2020年6月19日周五 下午4:39写道：

**Comment by dataabc** [comment]
@songzy12 

这个问题我想了下，我的想法是不移动。因为如果weiboSpider没有config.json，运行后会将weibo_spider中的config.json复制到weiboSpider内，而且会有配置config.json之类的提示。如果把config.json移动到weiboSpider，pypi版（weibo_spider文件夹）就没有config.json，这样pypi用户只能手动创建config.json了。解决手动创建的问题有两个解决方法，一是weiboSpider和weibo_spider文件加都保留config.json，这样的缺点是有两个config.json，使用者可能会迷惑，不知道用哪个。另一种解决方案是config.json和user_id_list.txt只放在weiboSpider内，并且保存到网上。如果pypi使用者使用时如果当前文件夹不存在config.json和user_id_list.txt，就从网上下载，只是这样更啰嗦了。所以，我更倾向于使用现在的方法。
这只是我的想法，可能有考虑不足的地方，我们也可以继续讨论。

**Comment by songzy12** [comment]
@dataabc  哦对我觉得维持当前状态是合理的。
我当时以为该用户的问题是由于 config 导致的，但看后面的描述似乎不是。应该是我想错了。

@SeepenL 或许你可以把你的 config 贴上来看看可能是哪里出了问题（除了 cookie 和 password 敏感信息外）

**Comment by SeepenL** [comment]
嗯。。config里信息就这么多
{
    "user_id_list": "honor.txt",
    "filter": 0,
    "since_date": "2019-01-01",
    "write_mode": ["csv", "txt"],
    "pic_download": 0,
    "video_download": 0,
    "cookie": "",
    "mysql_config": {
        "host": "localhost",
        "port": 3306,
        "user": "root",
        "password": "123456",
        "charset": "utf8mb4"
    }
}
只需要csv，所以数据库部分没有去改。

**Comment by dataabc** [comment]
@SeepenL 
现在可以运行吗？如果还是空行并且没有报错，可能是honor.txt文件有问题。也可以使用<https://github.com/dataabc/weiboSpider/tree/fa5e242541e0f751945530d58a118db74c1d83ec>，这是以前的版本，可以直接运行weiboSpider.py文件

**Comment by SeepenL** [comment]
@dataabc 
还是空行。。所以昨天我用了您的另一个爬虫，免cookie版的weibo_crawler，使用同样的config可以正常运行，但是又隔三差五出现新的报错，还麻烦您到那个项目下我的issue里看看。感谢您的帮助。

**Comment by SeepenL** [comment]
honor.txt中的数据格式就是每行一个uid：
1649597805
6192890377
6026732234
1494908203
1457450377
2352958493
1729790647
6628725744
3201529063
1170264651
...
这种

**Comment by codermino** [comment]
我也是在使用最新的代码的时候，按照指示一步一步的配置了，在weiboSpider目录下terminal输入python3 -m weibo_spider回车，脚本没有运行直接到了下一空行。也没有报错。不知道是什么原因。

**Comment by dataabc** [comment]
@codermino 

感谢反馈，我怀疑该命令没有让程序运行，spider.py是主文件，你可以在main函数里随便打印点什么，还是运行python3 -m weibo_spider，看看能不能大印出东西，如果没有说明程序就没有执行

**Comment by codermino** [comment]
已经解决了，改一下引用的方式就可以了。

**Comment by codermino** [comment]
> 已经解决了，改一下引用的方式就可以了。

不使用 . 的方式进行引入，就可以正常使用了。谢谢回复。

**Comment by dataabc** [comment]
@codermino 

能说明具体的修改方式吗，方面后来人修改，感谢

**Comment by codermino** [comment]
> @codermino
> 
> 能说明具体的修改方式吗，方面后来人修改，感谢

您的程序代码中使用的引入方式都是  from . import config_util, datetime_util 这种方式在我运行的时候报错，
改为from weibo_spider import config_util, datetime_util  这种引入方式，然后运行 __main__.py 即可正常运行。就是换了一种引入文件的方式。
具体原因不清楚。

**Comment by dataabc** [comment]
@codermino 

明白了，感谢

**Comment by codermino** [comment]
> @codermino
> 
> 明白了，感谢

具体的原因我也不清楚，如果您能知道具体的原因，方便在这里在回复下嘛，谢谢。

**Comment by dataabc** [comment]
@codermino 

我的理解是python3 -m weibo_spider和直接运行.py不同，一个是运行模块，一个是运行普通程序，它们的路径不同。所以修改import的路径，就可以直接运行.py了。

我把.改成了 weibo_spider ，还是出错，不知道是不是姿势不对。你现在在weiboSpider目录下使用python3 -m weibo_spider可以正确运行吗？我希望能有一种修改方式可以让两种运行方式都正确执行。

**Comment by codermino** [comment]
> @codermino
> 
> 我的理解是python3 -m weibo_spider和直接运行.py不同，一个是运行模块，一个是运行普通程序，它们的路径不同。所以修改import的路径，就可以直接运行.py了。
> 
> 我把.改成了 weibo_spider ，还是出错，不知道是不是姿势不对。你现在在weiboSpider目录下使用python3 -m weibo_spider可以正确运行吗？我希望能有一种修改方式可以让两种运行方式都正确执行。

是的，今天早上重新clone一下代码，然后通过python -m weibo_spider的方式运行成功了。

**Comment by codermino** [comment]
> @codermino
> 
> 我的理解是python3 -m weibo_spider和直接运行.py不同，一个是运行模块，一个是运行普通程序，它们的路径不同。所以修改import的路径，就可以直接运行.py了。
> 
> 我把.改成了 weibo_spider ，还是出错，不知道是不是姿势不对。你现在在weiboSpider目录下使用python3 -m weibo_spider可以正确运行吗？我希望能有一种修改方式可以让两种运行方式都正确执行。

如果按照我改的方式，你还是不能成功，可以加一下我的Q，我们讨论一下，3400116078.

**Comment by dataabc** [comment]
@codermino 
已添加

**Comment by codermino** [comment]
> @codermino
> 已添加

未收到，QQ：3400116078.

**Comment by dataabc** [comment]
@codermino 
我又添加了一次

**Comment by codermino** [comment]
> @codermino
> 我又添加了一次

还是没收到，我这边都是正常的。这样吧，你给我留一个联系方式，我联系你。

**Comment by codermino** [comment]
> > @codermino
> > 我又添加了一次
> 
> 还是没收到，我这边都是正常的。这样吧，你给我留一个联系方式，我联系你。

我这边使用命令运行的时候，python3 -m weibo_spider是不行的，使用python -m weibo_spider即可。

**Comment by dataabc** [comment]
@codermino 

好久不用qq了，翻出来了多年不用的qq:joy:，为了避免被骚扰，请用base64解码，qq号
```
NDA5NDg3NjQ1
```
感激不尽

**Comment by dataabc** [comment]
@codermino 

麻烦再加我一下，刚才聊着聊着就强制退出了，还要身份验证

**Comment by Chendh1999** [comment]
> > > @codermino
> > > 我又添加了一次
> > 
> > 
> > 还是没收到，我这边都是正常的。这样吧，你给我留一个联系方式，我联系你。
> 
> 我这边使用命令运行的时候，python3 -m weibo_spider是不行的，使用python -m weibo_spider即可。

加一，我现在使用python3 -m weibo_spider也是不行，使用python -m weibo_spider就可以运行程序了
