### ISSUE TITLE
爬取到的内容是“网络出错”

### ISSUE THREAD

**Issue by Reg1ss** [dataabc/weiboSpider#171]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：否

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：1743873607

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：你好，我在爬取上述指定id的微博时，发现只要是长微博（需要点击“全文”），这条微博爬取下来的内容就是“网络出错”，请问有办法解决吗？非常感谢🙏

**Comment by ymm-gh** [comment]
遇到了同样的问题，检查了原微博发现只要是需要点击“全文”的都显示了“网络出错”，设置了休息时间也并没有用。谢谢！

**Comment by dataabc** [comment]
@Reg1ss @ymm-gh
 
我测试了获取长微博的情况没有出错，可以正常获取，不知道微博详情页和列表页是不是限制不一样。
可以降低速度，如果没有效，再降低。也可以访问那条“网络出错”的微博，看看是否有提示，如要求输入验证码等，按提示操作。一般限制一段时间会自动解除，如果还有上述问题，可以等一天再操作

**Comment by Reg1ss** [comment]
@dataabc 
谢谢你的解答！尝试降低速度到每一到两页等待30到40s，仍然出现“网络出错”微博，我访问了这几条微博都可以正常打开没有限制。继续测试的时候发现似乎还只能爬取到昨天的微博不能爬取到最新的微博（大约是获取到cookie的时间）。使用无cookie版本解决了问题，怀疑是cookie的问题，没有做更详细的测试了。再次感谢🙏

**Comment by molixiaoge** [comment]
同样网络错误，不知如何解决

**Comment by dataabc** [comment]
@molixiaoge 

就是速度太快了被限制了，限制一段时间会自动解除。降低速度或者更换账号再或者使用[免cookie版](https://github.com/dataabc/weibo-crawler)可以解决该问题。

降低速度可以查看[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的第一个问题，这个方法只是降低了被限制的概率，如果限制还没有自动解除，还是会出现错误；如果你有多个账号，使用另一个账号的cookie也是不错的选择；如果只有一个账号，免cookie版是不错的选择，可以解决这个问题。
