### ISSUE TITLE
爬取特定时间段内的微博内容——设置end_date

### ISSUE THREAD

**Issue by Mak-LokGay** [dataabc/weiboSpider#172]
- 问：请说明需要什么新功能。<br>
答：设置多一个end_date，即可以获取特定时间段内的微博内容，而非一直获取到程序执行的日期为止。

- 问：请说明添加该功能的意义。（非必填）<br>
答：可能只是我个人的需求，不过还是想向您提一下。在不需要爬取至程序执行日期当天的微博内容的情况下，可能设置一个爬取特定时间段内的微博内容可能会节省不少时间和提高效率，不知道您有没有意向考虑一下呢？十分感谢！

**Comment by dataabc** [comment]
感谢建议。

非常好的建议，以前以前有个这个想法，也有网友提过。只是当时因为实现起来运行效率很低就没实现，不知道是当时想复杂了还是其它因为。现在看起来应该可以在很高的运行效率下实现这个功能，后续会添加这个功能。

再次感谢，如果还有其它问题或建议欢迎讨论

**Comment by dataabc** [comment]
已经可以按时间段获取微博了，在config.json添加了end_date字段。默认值为“now”，表示不限制，获取从since_date到现在的微博。如果要按时间段获取，比如想获取2020年三月某用户的微博，可以在config.json中设置since_date="2020-03-01"，end_date="2020-03-31"，这样程序就会获取发布时间从since_date到end_date的微博，包含边界。

注意，end_date的值只能是"now"或者“yyyy-mm-dd”形式，所以如果要把2020年3月5日设为end_date，请使用"2020-03-05"，不要使用"2020-3-5"。另外，程序目前只支持通过config.json输入end_date，不支持以user_id_list.txt的方式输入。如果你想通过文件为每个用户单独设置不同的时间段暂时还不行，不过你可以通过文件单独为每个用户设置不同的since_date，然后通过config.json的end_date参数为所以用户设置一个总的end_date。综上，since_date既可以通过config.json设置，也可以通过user_id_list.txt设置，end_date暂时只支持config.json设置。

**Comment by Mak-LokGay** [comment]
> 已经可以按时间段获取微博了，在config.json添加了end_date字段。默认值为“now”，表示不限制，获取从since_date到现在的微博。如果要按时间段获取，比如想获取2020年三月某用户的微博，可以在config.json中设置since_date="2020-03-01"，end_date="2020-03-31"，这样程序就会获取发布时间从since_date到end_date的微博，包含边界。
> 
> 注意，end_date的值只能是"now"或者“yyyy-mm-dd”形式，所以如果要把2020年3月5日设为end_date，请使用"2020-03-05"，不要使用"2020-3-5"。另外，程序目前只支持通过config.json输入end_date，不支持以user_id_list.txt的方式输入。如果你想通过文件为每个用户单独设置不同的时间段暂时还不行，不过你可以通过文件单独为每个用户设置不同的since_date，然后通过config.json的end_date参数为所以用户设置一个总的end_date。综上，since_date既可以通过config.json设置，也可以通过user_id_list.txt设置，end_date暂时只支持config.json设置。

收到，十分感谢！现在我个人在运行本项目最新的代码还面临着一个新的问题，麻烦您移步到我们最新的问题解答一下！十分感谢！
