### ISSUE TITLE
发布时间精确到 Hour : Minute 

### ISSUE THREAD

**Issue by Mak-LokGay** [dataabc/weiboSpider#173]
- 问：请说明需要什么新功能。<br>
答：微博发布时间精确到几时几分 -- 不知道是否可行？

- 问：请说明添加该功能的意义。（非必填）<br>
答：也是我个人的一些微小建议，可以增加微博信息的颗粒度。

**Comment by dataabc** [comment]
感谢建议。

现在发布时间就是精确到分，你可能和免cookie版搞混了，免cookie版是精确到天。

如果还有其它问题或建议欢迎继续讨论。

**Comment by Mak-LokGay** [comment]
> 感谢建议。
> 
> 现在发布时间就是精确到分，你可能和免cookie版搞混了，免cookie版是精确到天。
> 
> 如果还有其它问题或建议欢迎继续讨论。

你好，确实是的，我不久前clone了您旧的script，当时还没有精确到分，现在才发现有了更新，十分感谢！

但是，刚才运行weibo_spider.py的时候又出现了一个新的错误：

ImportError: cannot import name 'config_util' from '__main__' (/Users/maizixin/Desktop/毕业论文/python类/test/weiboSpider-master/weibo_spider/weibo_spider.py)

请问这次是什么原因呢？我也已经在config_sample.json中修改好cookies了，但是就是运行不了，请问要如何解决呢？谢谢！

**Comment by Mak-LokGay** [comment]
> 感谢建议。
> 
> 现在发布时间就是精确到分，你可能和免cookie版搞混了，免cookie版是精确到天。
> 
> 如果还有其它问题或建议欢迎继续讨论。

你好，确实是的，我不久前clone了您旧的script，当时还没有精确到分，现在才发现有了更新，十分感谢！

但是，刚才运行weibo_spider.py的时候又出现了一个新的错误：

ImportError: cannot import name 'config_util' from '__main__' (/Users/maizixin/Desktop/毕业论文/python类/test/weiboSpider-master/weibo_spider/weibo_spider.py)

请问这次是什么原因呢？我也已经在config_sample.json中修改好cookies了，但是就是运行不了，请问要如何解决呢？谢谢！

**Comment by dataabc** [comment]
在weiboSpider目录下运行
```sh
$ python3 -m weibo_spider
```
就可以了

**Comment by Mak-LokGay** [comment]
> ```shell
> python3 -m weibo_spider
> ```

<img width="570" alt="issue" src="https://user-images.githubusercontent.com/61657760/85764740-208f1e00-b748-11ea-8930-134b672768d0.png">
我在terminal上cd到了weibo_spider.py所在的文件夹中了，然后再运行了$ python3 -m weibo_spider，但结果还是一样的import error，请问是我哪里操作失误了吗？

**Comment by songzy12** [comment]
@Mak-LokGay 要在 weiboSpider-master 下运行这个命令，`python3 -m weibo_spider` 中的 weibo_spider 是指 `weibo_spider` 这个文件夹而不是 `weibo_spider.py` 这个文件。

**Comment by Mak-LokGay** [comment]
> @Mak-LokGay 要在 weiboSpider-master 下运行这个命令，`python3 -m weibo_spider` 中的 weibo_spider 是指 `weibo_spider` 这个文件夹而不是 `weibo_spider.py` 这个文件。

原来如此，果然成功在weiboSpider-master这一目录中出现了config.json的文件了！接下来的问题也都解决了！实在感谢两位大佬，大半夜的，辛苦了！感激不尽！！

**Comment by songzy12** [comment]
@dataabc 要不要把 weibo_spider.py 重命名成 spider.py，或许可以在以后减少一些误解。
现在它里面只有一个 Spider 的类了，我们已经把 Weibo 类和 User 类都单拆了出来。

**Comment by dataabc** [comment]
@songzy12 

好主意，很多使用者确实会把命令中的weibo_spider误解为weibo_spider.py，可以把weibo_spider.py重命名为spider.py。

**Comment by songzy12** [comment]
重命名好了哈

**Comment by dataabc** [comment]
@songzy12 
棒棒哒，我今天再把这个问题加到常见问题里，这样就没问题了。
