### ISSUE TITLE
未爬完就停止而无报错？

### ISSUE THREAD

**Issue by NJUleo** [dataabc/weiboSpider#176]
您好，比如我设置了config中为
`    "since_date": "2018-01-01",
	"end_date": "2020-03-17",`
正常爬取一段时间后程序停止，显示“信息抓取完毕”，但实际上只爬取了大概一个月的。其他的设置，我只按说明增加了几秒的sleep时间。请问可能的原因是什么？

**Comment by dataabc** [comment]
感谢反馈。

使用的哪种方式输入user_id？是通过config.json的user_list参数呢，还是user_id_list.txt文件

**Comment by NJUleo** [comment]
直接修改config.json的参数
`"user_id_list": ["2803301701"],`

**Comment by dataabc** [comment]
现在还有错吗？

不知道是不是因为账号的限制不同，因为这种zz相关的账号确实限制非常严格，可以再降低速度试试

**Comment by NJUleo** [comment]
好的，谢谢，我再加几秒试试。
另外使用user_id_list.txt文件来输入也是这样。

**Comment by dataabc** [comment]
我试了下，和你差不多，是有错误的
```
TypeError: cannot unpack non-iterable NoneType object
```
应该是和账号有关，如果是娱乐账号问题不大

**Comment by xinyuanli59** [comment]
我也遇到类似的问题。我想爬一些新闻报纸广播类的账号，例如人民日报，南方日报，国家应急广播，显示‘已获取XXXX的第XXX页微博’（页数非零），‘共爬取0条微博’，‘信息抓取完毕’。我用的是带cookie的版本，也用了uidList.txt，现在sleep设在20-25秒，还是抓不出，请问有什么解决方法吗？谢谢您

**Comment by dataabc** [comment]
@xinyuanli59 

以前可以爬微博吗，是之前可以，爬了一会就不行了吗？

**Comment by xinyuanli59** [comment]
@dataabc 

之前爬迪丽热巴，北京平安，试着把他们发的所有微博都扒下来，都是可以的。

现在我uidList.txt里8000+微博账号，我只爬他们的最早一条微博（之前问过您，按照您说的，成功了，其实就是爬最后一页），但是爬了一遍发现输出的csv只有7000+个，发现没爬出来的就是上面那种情况。整个过程没有停止。报错也只有一两个是list out of range，但不停止，只是继续下一个账号了。

于是我把这1000+个没爬出来的存成新的uidList.txt再爬一遍，也把sleep由2-6s改成20-25s，奇怪，有的能扒出来，有的还是扒不出来（占90%）。

**Comment by dataabc** [comment]
@xinyuanli59 

可能是爬的太频繁了。而且每个微博的限制级别不同，像娱乐类的就比较容易，新闻、医疗及zz等相关的就比较严，可以更换账号或者过一段时间再爬。因为能爬下7000多，说明程序是没问题的，只是出错的限制太严格了，尽可能的放慢速度，每爬一页就暂停几秒，而不是每爬几页暂停。

**Comment by xinyuanli59** [comment]
@dataabc 

好，谢谢您。我再试试，我换个账号（就是换个cookie对吧）试试。

**Comment by dataabc** [comment]
@xinyuanli59 

另一个账号的cookie

**Comment by arrogant-create** [comment]
请教一下大大，有些爬不出来，有些爬了没有保存下来是怎么回事，还有的只能下一办是怎么回事？
E:\python\weibo\weiboSpider-master - V1.0\weibo\胡歌\img
即将进行视频下载
Download progress: 100%|██████████████████████████████████████████████ 2/2 [00:00<?, ?it/s] 
视频下载完毕,保存路径:%|                                                                                                                       | 0/2 [00:00<?, ?it/s] 
E:\python\weibo\weiboSpider-master - V1.0\weibo\胡歌\video
Progress:   0%|▎                                                                                                                     | 1/390 [00:02<17:27,  2.69s/it]------------------------------已获取胡歌(1223178222)的第2页微博------------------------------
Progress:   0%|▎

**Comment by dataabc** [comment]
@arrogant-create 

如果没有报错就不是错误。应该是进度条没有100%就停止或者下载的数目不如进度条中的大，你才这么想。
总的进度条是按页数计算的，比如上面的1/390，说明微博共有390页，如果没有到390/390就停止，说明满足了停止的条件，比如你设置的since_date，假如是2020-01-01，程序遇到发布时间在这之前的就停止，因为它们不满足since_date。文件下载也类似，比如现在有10条微博，要下载它们的图片，进度条就是xxx/10，但是这些微博不一定每一条都包含图片，因此数量会比显示的少。不知道你的疑惑是不是指这些。

**Comment by arrogant-create** [comment]
就是下载完毕，但是未保存下来，在微博文件夹下没有，还有就是有有些下载了一半会停止不下载了

**Comment by arrogant-create** [comment]
还有的就是微博全文是这样结尾的：代表 珠...全文 
后面还有话但是他省略了

**Comment by dataabc** [comment]
@arrogant-create 

如果下载失败，应该会生成not_downloaded.txt文件，内容包括没有下载图片/视频的微博的id及对应的url。

微博获取不全可以参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)问题4，程序尝试获取完整的内容，但是没有获取成功，所以保存了不完整的版本。

**Comment by arrogant-create** [comment]
就是说没有我设置的开始时间太短，而爬取的数量没有满足而导致的保存进度一直是空的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午5:51
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 未爬完就停止而无报错？ (#176)





 
@arrogant-create
 
如果没有报错就不是错误。应该是进度条没有100%就停止或者下载的数目不如进度条中的大，你才这么想。
 总的进度条是按页数计算的，比如上面的1/390，说明微博共有390页，如果没有到390/390就停止，说明满足了停止的条件，比如你设置的since_date，假如是2020-01-01，程序遇到发布时间在这之前的就停止，因为它们不满足since_date。文件下载也类似，比如现在有10条微博，要下载它们的图片，进度条就是xxx/10，但是这些微博不一定每一条都包含图片，因此数量会比显示的少。不知道你的疑惑是不是指这些。

**Comment by dataabc** [comment]
@arrogant-create 
你说的是进度条的问题吗？
比如，某微博有100页微博，所以进度条会有xxx/100这样的字样，你设置since_date="2020-06-01"，即只爬取2020-06-01之后的，所以遇到发布时间比since_date早的就暂停了，因为后面会越来越早，都不满足发布时间在since_date之后的要求，故暂停，进度条就不会达到100/100。

**Comment by xinyuanli59** [comment]
@dataabc 

我换了cookie也增长了sleep时间，发现仍然扒不出来的一种情况是例如南方日报，weibo.cn显示共有155页微博，但点开第155页是空的，weibo.com上连时间轴也只显示到2020年，还有一种是例如河北综合广播，weibo.cn显示共有4931页微博，但点开第4931页是空的，但起码weibo.com上时间轴是全的（尽管点第一条微博还是不可见）。

我猜这种账户是设置了微博不可见，所以也就没办法扒出开博之后第一条了？（残念detsu）

**Comment by dataabc** [comment]
@xinyuanli59 

感谢反馈，非常好的思路，程序只能获取网页上显示的微博，对于不显示的无法获取，因此获取不到第一条，这也是虽然程序运行但获取内容为空的原因之一。

印象里你想要知道开博时间，这点[免cookie版](https://github.com/dataabc/weibo-crawler)是可以做到的，同样无法获取第一条微博

**Comment by xinyuanli59** [comment]
@dataabc 

再反映一个问题，因为我关心发第一条微博的时间，但吕梁交通广播的weibo.cn（2019-04-26）和weibo.com（2013-8-6）第一条是不一样的。您有没有方法扒出weibo.com上面的第一条微博的时间呢？

我还没试过免cookie版获取开博时间，但迪丽热巴weibo.com基本资料有写开博时间，有些账户weibo.com基本资料没写开博时间，请问后一种情况还能扒出来吗？还是你扒的是时间轴的最低部（2010年07月02日 @Dear-迪丽热巴 Join WeiboO(∩_∩)O）？

**Comment by dataabc** [comment]
@xinyuanli59 

没有尝试过weibo.com，这个不清楚。

获取开博时间用的接口，不是算的第一条微博时间。很多微博都可以获取注册时间，但是吕梁交通广播也不行，不知道什么原因

**Comment by xinyuanli59** [comment]
@dataabc 

我试了一下免cookie版，而且我加了cookie（我发现，如果不加cookie的话，迪丽热巴的注册时间也是不能抓取的），发现我关心的账户（主要是报纸新闻公安类，人民日报，光明日报）*全部*都抓不出注册时间。我猜这和账户类型有关。我查了一下免cookie版用的移动版网址m.weibo.cn上偶像明星都有注册时间，包活我看我自己也有，所以我估计是报纸新闻类的基本资料比较特殊，根本没有这些信息。

我在想，开博时间是不是只能试着从weibo.com爬取了？而且可能唯一可行的是时间轴，因为基本资料里也没有。。。

**Comment by dataabc** [comment]
@xinyuanli59 

可能这类微博比较特殊，免cookie版在加上cookie后，可以得到个人用户的注册时间，而上面你说的这种获取不到。
