### ISSUE TITLE
运行spider.py的时候报错

### ISSUE THREAD

**Issue by sunxiao06** [dataabc/weiboSpider#177]
就是我运行spider.py代码后，报ImportError: attempted relative import with no known parent package，我网上查找了，但是却没有解惑，，所以想来问问

**Comment by dataabc** [comment]
感谢反馈。


不要直接运行spider.py，可以在weiboSpider目录下运行python3 -m weibo_spider，或者运行__main__.py

**Comment by sunxiao06** [comment]
为啥它老是报cookie错误或者过期呢？

**Comment by sunxiao06** [comment]
大大，我解决了，之前获取的cookie不对，现在可以了，麻烦了

**Comment by arrogant-create** [comment]
直接运行main还是报错

**Comment by arrogant-create** [comment]
还是什么都没有，具体操作是打开vscode，pip安装，再次执行python3 -m weibo_spider --config_path="config.json"没有任何反应了，无论执行什么也没生成weibo文件夹

**Comment by dataabc** [comment]
@arrogant-create 

报什么错了吗？有使用者使用命令没有报错也没有执行，他本地是python3，使用
```
python -m weibo_spider
```
就能成功

**Comment by arrogant-create** [comment]
python3.8版本，用python -m weibo_spider命令出现以下错误：
E:\pa\weiboSpider-master>python -m weibo_spider
Error:  [Errno 2] No such file or directory: 'E:\\pa\\weiboSpider-master\\weibo_spider\\config_sample.json'
Traceback (most recent call last):
  File "E:\pa\weiboSpider-master\weibo_spider\spider.py", line 254, in main
    config = _get_config()
  File "E:\pa\weiboSpider-master\weibo_spider\spider.py", line 239, in _get_config
    shutil.copy(src, config_path)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\pa\\weiboSpider-master\\weibo_spider\\config_sample.json'

**Comment by dataabc** [comment]
@arrogant-create 

这个错误是因为你的'E:\pa\weiboSpider-master\weibo_spider\'下没有config_sample.json文件，是不是你把它重命名了，再改回来或者单独下载，再运行就可以了

**Comment by arrogant-create** [comment]
可以了，非常感谢，用python就可以运行，谢谢大大
