### ISSUE TITLE
数据库的创造

### ISSUE THREAD

**Issue by sunxiao06** [dataabc/weiboSpider#178]
就是我想将数据库里创建的weibo表里的子表weibo，我想将他改成news，我应该在mysql_writer.py的哪里修改我，问一下，我没有找到准确的位置

**Comment by dataabc** [comment]
write_weibo方法，“CREATE TABLE IF NOT EXISTS weibo”创建了weibo表；“self._mysql_insert("weibo", weibo_list)”向weibo表写入微博，修改这两次就行

**Comment by sunxiao06** [comment]
好的，谢谢大大解惑，深夜打扰。
