### ISSUE TITLE
用户的增加

### ISSUE THREAD

**Issue by sunxiao06** [dataabc/weiboSpider#179]
就是如果我想爬取多个用户，我是直接在json配置文件中，id添加多个用户id吗？那这些数据可以写在不同子列表吗？

**Comment by dataabc** [comment]
可以在config.json中设置，但是不推荐这样做，因为所有的since_date都是统一的，如果新增加用户，想爬他的全部微博，就得设置since_date，这样其他爬过的用户也会受影响。

推荐使用user_id_list.txt。可以为每个user_id单独设置since_date，每个人的进度不相互影响，还可以自动更新since_date。方法可以参考[设置user_id_list](https://github.com/dataabc/weiboSpider/blob/master/docs/settings.md#%E8%AE%BE%E7%BD%AEuser_id_list)部分

**Comment by arrogant-create** [comment]
txt文件和json文件在同一目录下会报错

**Comment by dataabc** [comment]
@arrogant-create 
感谢反馈。

能否说明报错信息，看能否复现错误，我的txt和json都在weiboSpider目录下可以正确运行。能否说下报错的细节，方便调试，感谢

**Comment by arrogant-create** [comment]
我的json文件会跳出weibospider目录，直接和weibospider同级目录中生成

**Comment by arrogant-create** [comment]
将json文件和txt文件放到weibospider文件夹中出现的错误：
Error:  [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "E:\python\weibo\weiboSpider-master - V1.1\weibo_spider\spider.py", line 255, in main
    config = _get_config()
  File "E:\python\weibo\weiboSpider-master - V1.1\weibo_spider\spider.py", line 245, in _get_config
    with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by dataabc** [comment]
@arrogant-create 

错误显示不存在config.json，是否在执行命令行时使用了--config_path参数，且后面的名字与json不一致？
如果没有--config_path参数，且当前目录没有json文件，程序会自动生成，不会出现上面的错误；如果有config_path参数，程序会使用参数后的路径，如果参数后是config.json且当前目录没有该文件就会出现上面的错误提示。

**Comment by arrogant-create** [comment]
有了，是user那行的方括号的问题，谢谢大大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 晚上9:21
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 
错误显示不存在config.json，是否在执行命令行时使用了--config_path参数，且后面的名字与json不一致？
 如果没有--config_path参数，且当前目录没有json文件，程序会自动生成，不会出现上面的错误；如果有config_path参数，程序会使用参数后的路径，如果参数后是config.json且当前目录没有该文件就会出现上面的错误提示。

**Comment by arrogant-create** [comment]
大大，再问一个问题，如果把id、名称、开始时间都写入txt文件，那后面的since_date需要修改吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午5:29
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 感谢反馈。
 
能否说明报错信息，看能否复现错误，我的txt和json都在weiboSpider目录下可以正确运行。能否说下报错的细节，方便调试，感谢

**Comment by dataabc** [comment]
@arrogant-create 
不用修改，程序会自动修改since_date

**Comment by arrogant-create** [comment]
就是json文件自带的sinc_date后面直接改成固定值就行了？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 晚上9:46
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 不用修改，程序会自动修改since_date

**Comment by arrogant-create** [comment]
如果我在短时间里重复爬取会出错，比如部分错误如下：
Error:&nbsp; 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\weibo_spider\weiboSpider.py", line 196, in start
&nbsp; &nbsp; self.get_user_info(user_config["user_uri"])
&nbsp; File "C:\Users\dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\weibo_spider\weiboSpider.py", line 84, in get_user_info
&nbsp; &nbsp; for k, v in user.items():
AttributeError: 'NoneType' object has no attribute 'items'





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 晚上9:46
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 不用修改，程序会自动修改since_date

**Comment by dataabc** [comment]
@arrogant-create 

上面说明速度太快了，应该降低速度，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2。

config.json改成固定值就行。如果你是通过user_id_list.txt输入user_id，程序会读里面的since_date，如果没有才使用config.json固定的since_date，而且每次爬完一个用户，程序会修改user_id_list.txt，自动修改对应用户的since_date值。

**Comment by arrogant-create** [comment]
好的，谢谢大大






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 晚上10:06
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 
上面说明速度太快了，应该降低速度，参考常见问题的问题2。
 
config.json改成固定值就行。如果你是通过user_id_list.txt输入user_id，程序会读里面的since_date，如果没有才使用config.json固定的since_date，而且每次爬完一个用户，程序会修改user_id_list.txt，自动修改对应用户的since_date值。

**Comment by arrogant-create** [comment]
大大，请教一个问题，怎样爬取微博用户的博主类型呢？

**Comment by arrogant-create** [comment]
还有就是能实现同一条微博昨天和今天的点赞数，观看数等的区别吗

**Comment by dataabc** [comment]
@arrogant-create 

博主类型是什么字段？程序只能获取页面中存在的信息，如果没有该字段就不能获取。

如果使用列表输入user_id_list，且使用json、mysql或mongodb保存，点赞数等信息是会更新的。使用txt输入user_id_list，大部分微博是不会更新的，因为对于已经获取的微博，它们的since_date已经自动更新，程序会尽量获取新的微博而不是爬过的微博，所以就不会爬旧微博，因此不会更新。

**Comment by arrogant-create** [comment]
好的，谢谢大大

**Comment by arrogant-create** [comment]
博主类型就类似于小字部分内容


‍



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 下午5:12
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 
博主类型是什么字段？程序只能获取页面中存在的信息，如果没有该字段就不能获取。
 
如果使用列表输入user_id_list，且使用json、mysql或mongodb保存，点赞数等信息是会更新的。使用txt输入user_id_list，大部分微博是不会更新的，因为对于已经获取的微博，它们的since_date已经自动更新，程序会尽量获取新的微博而不是爬过的微博，所以就不会爬旧微博，因此不会更新。

**Comment by dataabc** [comment]
@arrogant-create 

是不是图片保存成附件了，这里看不了

**Comment by arrogant-create** [comment]
我重新发了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 晚上8:02
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 
是不是图片保存成附件了，这里看不了

**Comment by arrogant-create** [comment]
文字版是这样的，微博名称下面的小字：
知名星座命理博主 神出兔没工作室创始人 喜马拉雅签约主播 微博vlog博主 微博签约自媒体


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 晚上8:02
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 
是不是图片保存成附件了，这里看不了

**Comment by dataabc** [comment]
@arrogant-create 

你说的是不是用户简介，这个如果有是可以得到的

**Comment by arrogant-create** [comment]
那简介需要怎么弄呢，直接在spider.py文件里添加吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 晚上8:39
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"握不住的沙♬就扬了它"<1246051548@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)





 
@arrogant-create
 
你说的是不是用户简介，这个如果有是可以得到的

**Comment by dataabc** [comment]
@arrogant-create 

简介获取已经自带了，只是只保存到mysql和mongo里，如果想要写入csv，可以使用[免cookie版](https://github.com/dataabc/weibo-crawler)

**Comment by arrogant-create** [comment]
嗯，谢谢大大------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Chen&amp;nbsp;Lei&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月4日(星期六) 晚上10:05
收件人:&nbsp;&quot;dataabc/weiboSpider&quot;<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;&quot;arrogant-create&quot;<1246051548@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 用户的增加 (#179)
