### ISSUE TITLE
强烈建议允许自定义下载位置，及可否提供带参数的命令运行方式

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#180]
- 问：请说明需要什么新功能。<br>
答：
1、强烈建议允许在配置文件中允许自行设置下载位置
2、是否可以提供带参数的命令运行方式，该参数即为id（或多个），例如python3 -m weibo_spider id1,id2,id3

- 问：请说明添加该功能的意义。（非必填）<br>
答：
第一个：当下载图片和视频时，实在是太大了
第二个：
用于解决新增爬取某个微博用户的情况
目前遇到的情况是：已经关注并爬取了n多个微博用户信息，但忽然发现需要新关注某个用户，这时的操作是在user_id_list里面添加一个新的id，然后运行程序。但这时候，如果已经关注的那些很久没有爬取，就得把所有的全部爬完，否则的操作就是把user_id_list文件备份一份，只加上这个新的id，爬取完了，再把原来的user_id_list内容弄回来，比较麻烦，而且毕竟爬取有个时间段，容易忘记。
增加命令行的方式，类似于https://github.com/arc298/instagram-scraper（话说，这个也很赞！），当然未必需要那么多，但可以增加比如某个id（最好允许多个）作为参数，则只爬取该id的相关信息，等爬取完毕后，会在user_id_list中添加对应的记录。这样相当于把原有的爬取记录无需任何处理的情况下，新增了爬取用户，并且立刻爬取。

同时，个人有个小思路，因为有时候会出现某人同时开设了微博和Ins的账号，那么，用这种带参数的命令如果支持的话，就可以写个简单批处理文件，两个顺次运行就是了，^_^

**Comment by dataabc** [comment]
感谢建议。

## 关于自定义下载位置

本程序是支持自定义下载位置的，比如你想把文件下载到位置/home/result，可以使用命令
```
$ python3 -m weibo_spider -output_dir /home/result
```

## 关于新增用户

**现有的功能**
本程序有两种方式输入user_id，第一种是通过config.json的user_id_list参数直接输入；第二种是把要获取的用户id写入txt文件，然后将文件路径赋值给config.json的user_id_list参数。第二种方式是可以为每个id设置单独的since_date，且每次获取完某个用户会自动更新对应的since_date。比如你的txt可以为如下内容：
```
1669879400 Dear-迪丽热巴 2020-07-01 19:18
1223178222 胡歌 2020-07-01 19:28
1729370543 郭碧婷 2020-07-01 19:33
```
你已经爬过上面三个用户了，它们的since_date会更新成爬取时的时间，如果不存在会使用config.json中的since_date，否则使用txt内的。现在你想增加爬取杨紫2018年之后的微博，可以在txt中添加一行，修改后的内容如下：
```
1669879400 Dear-迪丽热巴 2020-07-01 19:18
1223178222 胡歌 2020-07-01 19:28
1729370543 郭碧婷 2020-07-01 19:33
1227368500 杨紫 2018-01-01
```
这样程序会分别爬取它们，只有杨紫的是较早的，其它的都可以很快爬完。

如果其他用户太长时间没爬，可以单独使用第一种方式，单独获取他们。

**你的想法**
不知道是不是上面的方式不满足要求，才提了通过命令行输入user_id的方式。建议也很好，多了一种运行方式，且自动更新user_id。这种方式我考虑下，如果可以，后续会添加。

感谢建议，如果还有其它问题，欢迎继续讨论

**Comment by dataabc** [comment]
已经添加通过命令行参数的形式输入user_id，可以输入一个或多个，若输入多个，每个user_id用英文逗号连接，如果这些user_id中有重复的user_id，程序会自动去重。

使用方式：
```
$ python3 -m weibo_spider -u 1669879400,1223178222
```
注意user_id和逗号之间不要有空格。

该方式的所有user_id使用config.json中的since_date和end_date设置，通过修改它们的值可以控制爬取的时间范围。若config.json中的user_id_list是文件路径，每个命令行中的user_id都会自动保存到该文件内，且自动更新since_date；若不是路径，user_id会保存在当前目录的user_id_list.txt内，且自动更新since_date，若当前目录下不存在user_id_list.txt，程序会自动创建它。

感谢建议，如果还有其它建议欢迎讨论

**Comment by gudaost** [comment]
“config.json中的user_id_list是文件路径”，可以直接在config.json中设置路径吗？
在里面这样设置：
    "user_id_list": "D:\Desktop\idlist测试\user_id_list.txt",
提示说“config.json 格式不正确”
怎么在这里设置user_id_list的路径？
多谢！

**Comment by gudaost** [comment]
知道了，这里的配置：
1、不能使用中文路径，会出现乱码，进而导致错误
2、如果是Windows的绝对路径，“\”应该用"\\"
感谢，非常方便！
