### ISSUE TITLE
请问如何自定义保存位置

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#181]
由于程序放在同步盘里面，爬取图片、视频后实在太大（网盘免费流量不够，也没必要），所以希望修改默认保存位置
认真学习了半天代码，发现有个：
 if FLAGS.output_dir is not None:
                file_dir = FLAGS.output_dir
这是直接把FLAGS.output_dir改了就可以调整图片、视频的默认保存位置么？（还是这个其实是数据库……）
或者，用什么方式可以自定义保存位置么？
多谢！

**Comment by dataabc** [comment]
通过命令行自定义，比如你想保存到/home/pan文件夹下，就运行命令：
```
python3 -m weibo_spider -output_dir /home/pan
```
这样文件、图片、视频等就保存在/home/pan下了，你可以把/home/pan修改成自己的位置

**Comment by gudaost** [comment]
多谢！这个真是相当方便！！非常感谢！
