### ISSUE TITLE
--config_path无法识别含空格的路径

### ISSUE THREAD

**Issue by gudaost** [dataabc/weiboSpider#185]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：3.8

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
运行时使用--config_path设置文档路径
X:\Program Files\Pic_Follow
由于中间有个空格，软件提示
Error:  [Errno 22] Invalid argument: "r'X:\\Program"
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_Download_WeiBo\weibo_spider\spider.py", line 256, in main
    config = _get_config()
  File "X:\Program Files\Pic_Follow_Download_WeiBo\weibo_spider\spider.py", line 246, in _get_config
    with open(config_path) as f:
OSError: [Errno 22] Invalid argument: "r'X:\\Program"

**Comment by dataabc** [comment]
感谢反馈。

如果以--config_path设置路径且路径中包含空格，在路径外添加双引号就可以了

**Comment by gudaost** [comment]
成功了！多谢！
但是--user_id_list能配置到非软件目录下吗？看spider文件好像也可以自定义的啊
命令：
--user_id_list="X:\Program Files\Pic_Follow\各软件配置文件\Weibo_user_id_list.txt"
提示：
不存在X:\Program Files\Pic_Follow_Download_WeiBo\user_id_list.txt文件

**Comment by gudaost** [comment]
是不是我在config.json中写的是：
"user_id_list": "user_id_list.txt",
是需要修改这个吗？

**Comment by dataabc** [comment]
可能是config.json中user_id_list的原因，它和命令行参数user_id_list是同一个东西。你更新到最新版看看，现在的程序逻辑是如果有多个路径设置，优先使用命令行中的路径，你看看最新版有这个问题吗

**Comment by gudaost** [comment]
还是不行，提示为：
没有配置有效的user_id，请通过config.json或user_id_list.txt配置user_id

设置为：
config.json：
    "user_id_list": [],
运行命令为：
python -m weibo_spider --config_path="X:\Program Files\Pic_Follow\各软件配置文件\Weibo_config.json" --user_id_list="X:\Program Files\Pic_Follow\各软件配置文件\user_id_list.txt"

路径是没问题的，因为config_path用的是同一个路径，如果把后面user_id有关内容删除，可以正常运行
user_id_list.txt文件也没问题，刚才把这个放在程序目录下也可以正常运行
看了半天代码，业余，没看出有啥问题，这是啥情况呢？？

**Comment by dataabc** [comment]
这不是错误，出现这个提示说明user_id_list.txt内没有符合要求的user_id，可能是txt内格式不正确

**Comment by gudaost** [comment]
config.json肯定是只有一个，而且为了避免错误，我是重新下载了软件，把原来的东西清空了的。
事实上，之所以想把config.json和user_id_list放到另外一个文件夹，就是为了您这边软甲能调整时，升级方便（按照我这样，就可以每次都直接把软件文件夹清空，然后解压缩新的进去就行了。
提示的含义理解，说的是没有可以下载的id，那么意味着软件读取的依旧是config.json里面指定的[]，也就是空。而没有读取我指定的user_id_list.txt文件。

代码是：
user_id_list = config["user_id_list"]
        if not isinstance(user_id_list, list):
            if FLAGS.user_id_list is not None:
                user_id_list = FLAGS.user_id_list
这里的第一条含义是否是从config里面取值，而FLAGS.user_id_list由于缩进，比前面的优先级低？编程很业余，不知道理解的是否正确，仅供参考

**Comment by dataabc** [comment]
代码的意思是先读config.json中的user_id_list，如果命令行中有--user_id_list，就把前面的覆盖了，如果命令行中有--u同样覆盖前面的，因此优先级从高到低是：--u、--user_id_list、config.json中的user_id_list。上面命令行有user_id_list，就覆盖了[]，读的是user_id_list.txt中的user_id，如果里面没有有效id，就会提示：没有配置有效的user_id，请通过config.json或user_id_list.txt配置user_id

**Comment by gudaost** [comment]
我看到软件更新了，重新下载，还是不行，麻烦您方便时，测试一下吧。

**Comment by dataabc** [comment]
我测试过，没有出错。

当config.json中的user_id_list值为[]时，
不使用--user_id_list即运行如下命令：
```
$ python3 -m weibo_spider
```
没有出现“没有配置有效的user_id，请通过config.json或user_id_list.txt配置user_id”提示吗？你上面的意思应该是没有出现，但事实上，这样会出现提示。而加上--user_id_list，你上面的意思是出现“没有配置有效的user_id，请通过config.json或user_id_list.txt配置user_id”，这样很奇怪。只有一种情况可以说得通，就是config.json的user_id_list是包含user_id的列表而不是[]，所以正常运行，而在命令行加上--user_id_list后，"X:\Program Files\Pic_Follow\各软件配置文件\user_id_list.txt"不包含有效的user_id，--user_id_list的优先级比列表高，覆盖了config.json中的use_id列表，所以才出现“没有配置有效的user_id，请通过config.json或user_id_list.txt配置user_id”。

如果还是出现这个问题，如果你方便，可以留下qq或其它联系方式，我加你好友。

**Comment by gudaost** [comment]
不知道为什么，好用了，感觉和之前的设置完全一样的，汗……
感谢耐心讲解！
