### ISSUE TITLE
python3 -m weibo_spider -output_dir /home/pan不会创建人物昵称的文件夹

### ISSUE THREAD

**Issue by gudaost** [dataabc/weiboSpider#186]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。<br>
<br>

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：3.8

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：
希望自定义下载位置，按照您的答复，使用“python3 -m weibo_spider -output_dir /home/pan”
但是这样之后带来的问题是，所有的csv文件都下载到了定义的文件夹中，同时，所有id的图片都放到了img文件夹中，即没有自动创建“人名/昵称”的文件夹

**Comment by dataabc** [comment]
感谢反馈，后面会在指定路径中自动生成用户昵称的文件夹，所有下载文件都会保存在该文件夹下面。

**Comment by gudaost** [comment]
谢谢！

**Comment by dataabc** [comment]
现在会创建用户昵称文件夹了，所有下载文件都会保存在该文件夹下。
