### ISSUE TITLE
建议可以直接下载关注的微博，而不通过Id List文件

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#187]
- 问：请说明需要什么新功能。<br>
答：建议可以直接下载关注的微博，而不通过Id List文件

- 问：请说明添加该功能的意义。（非必填）<br>
答：
1、有时候，某些id并不想一直跟踪，而是偶尔下载一下，用这种方式直接读取“关注”，而非“id list”。同时用这样的方式，加上命令输入时可以添加id的方式，可以减少大家修改id list文档，也能够减少各种错误的出现。
2、点关注，比id list添加更容易，呵呵
3、看之前的软件，是可以获得关注了哪些用户的，所以，或许可以复用一下代码，充分利用^_^

**Comment by dataabc** [comment]
感谢建议。

目前不打算这样做，原因如下：
1.id_list文档是程序自动生成的，即便持续获取某id，也不用修改id_list文档。可以修改id_list文档是为了更好的自定义配置，但修改不是必需的。
2.因为微博是有限制的，有时候某个用户爬到一半可能失败，而之前的用户是成功的。如果直接下载，使用者是无法控制的，中途如果失败只能重新来一次，而现在使用user_list，爬取成功会更新since_date，第二次在爬时，如果以前爬成功的用户没有发新微博，是会忽略它们的，效率更高。

[weibo-follow](https://github.com/dataabc/weibo-follow)是用来获取用户关注的，并自动生成id_list文档，该文档本程序是可以直接用的，也非常方便。如果你想获取某些用户及他们关注者的微博，可以先使用该程序获取id_list，再利用本程序获取微博。

如果还有建议或问题，欢迎继续讨论

**Comment by gudaost** [comment]
有道理！感谢这么详尽的回复！
顺便问一下（免得又开新帖），这个程序怎么修改爬取时的间隔时长？

**Comment by gudaost** [comment]
感谢详尽回复！
