### ISSUE TITLE
希望能够提供MS SQL Server的支持

### ISSUE THREAD

**Issue by pig3three** [dataabc/weiboSpider#189]
- 问：请说明需要什么新功能。<br>
答：增加对微软 sql server的支持

- 问：请说明添加该功能的意义。（非必填）<br>
答：查到需要 pymssql 模块，本来想自己写，奈何python水平有限。。

**Comment by dataabc** [comment]
感谢建议。

这个功能近期应该不会去实现，因为已经有mysql了，它们的操作很相似。你可以参考[mysql_writer](https://github.com/dataabc/weiboSpider/blob/master/weibo_spider/writer/mysql_writer.py)，mysql相关的主要操作包括创建数据库、创建数据表、插入数据都在这个文件里，spider.py通过调用这个文件操作mysql。或者使用mysql存储数据，然后再将数据从mysql迁移至SQL Server，参考[MySQL到MsSQL的迁移工具——SSMA](https://developer.aliyun.com/article/308147)。

再次感谢建议，如果还有其它问题或建议欢迎讨论
