### ISSUE TITLE
需求：自动获取 cookie

### ISSUE THREAD

**Issue by tiantaozhang** [dataabc/weiboSpider#19]
我尝试去做自动登录并拿到cookies，[loginURL](https://login.sina.com.cn/sso/login.php?client=ssologin.js(v1.4.19))，按照参数去post，登录成功，也拿到cookie，但是用于获取用户信息时却让我登录，郁闷，不知楼主有没高招

**Comment by ybbzbb** [comment]
尝试登录的时候，session-id 或者 一些 头部内容有没有变化呀？

**Comment by dataabc** [comment]
@ybbzbb 
当时尝试过自动登录，失败了，所以没有添加自动登录。最近在写m.weibo.cn版的，不需要登录和cookie，或许对你有帮助
