### ISSUE TITLE
增加对于某条微博下面评论和评论图片下载的支持

### ISSUE THREAD

**Issue by pig3three** [dataabc/weiboSpider#190]
- 问：请说明需要什么新功能。<br>
答：增加对于某条微博下面评论和评论图片下载的支持

- 问：请说明添加该功能的意义。（非必填）<br>
答：评论中很多时候会有晒图啊啊什么的 也挺不错的

**Comment by dataabc** [comment]
感谢建议。

这个技术上有限制，微博的评论获取不全，且不稳定。只能得到很少的一部分，所以评论和图片很难获取。
