### ISSUE TITLE
请问能否抓取头条文章

### ISSUE THREAD

**Issue by XiaoXiaoYanHe** [dataabc/weiboSpider#191]
- 问：请说明需要什么新功能。<br>
答：抓取头条文章，单独txt

- 问：请说明添加该功能的意义。（非必填）<br>
答：某网文被封微博周更，想收集起来免得又没了

**Comment by dataabc** [comment]
感谢建议。

这个建议很好，但这个属于附加的功能，优先级比较低，所以如果要实现的话，应该要过一段时间，近期不会添加这个功能。目前的想法和你一样，不去下载多媒体文件，只获取文章，其它字段是否获取还没考虑好。应该会和图片一样，保存在专门的文件夹里，一篇文章一个txt，txt的名字就是文章的名字，暂时就想到这些。

感谢建议，如果还有其它建议欢迎继续讨论。
