### ISSUE TITLE
建议增加爬取多久就暂停的设置（解决爬取因被ban而失败的问题

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#192]
- 问：请说明需要什么新功能。<br>
答：希望可以增加爬取一定时长，或爬取某些数量id的微博后，暂停一定时间，来解决因被ban而带来失败的问题

- 问：请说明添加该功能的意义。（非必填）<br>
答：
我个人的id list中均为娱乐微博，所以理论上应该是被ban的概率相对较小，同时，已经把sleep频率改为1到2页，Sleep时长改为10到15秒，依旧在爬取了大概60、70个id后就会被ban而停止，同时从讨论区来看，这个情况算是普遍存在的。
目前的解决方式是，等一阵再重启，但这时会重新跑一边id list，按顺序跑，上一次运行被ban之前的所有id爬取其实没啥意义，白白浪费了时间，而手动改，就得把它们剪切出去。但我的list里面有200多个id，所以，被ban后运行至少4次才能所有都爬取完，很是麻烦

建议可以考虑的方式：
1、整体运行比如2小时，则sleep 30分钟一类的
2、每爬取10个id或多少个id，则一次长时间sleep
如果可以在config修改则更好了

**Comment by dataabc** [comment]
感谢建议。

非常好的建议，近期会实现这个功能，非常感谢。

建议通过txt文件输入user_id，你现在应该是直接把user_id直接写到config.json，这样不如前者好。因为在user_id_list.txt输入user_id，可以自动更新since_date，就是保存进度。一个微博爬完，会自动在对应user_id后更新since_date，值为上一次爬取该user_id的end_date。下次再爬这个user_Id时，会接着上次的执行，这样就避免了上面说的被ban后重新再爬的问题。而且，txt还可以添加注释，也更清晰。设置方法见<https://github.com/dataabc/weiboSpider/blob/master/docs/settings.md>设置user_id_list部分。

再次感谢，如果还有其它建议，欢迎继续讨论

**Comment by gudaost** [comment]
我现在用的是idlist的txt方式，也是跟踪爬取，只是在使用时，大概两个月才爬取一次，这样导致每次爬取的时间会比较长。由于爬取的时间比较长，并且习惯晚上睡觉前开始爬取，所以当被ban而导致中断时（尤其目前版本是有分钟的），就会出现，等到我第二次重启时，距离上次第一个爬取的时间点过去了8、9个小时，这样，自然前面的又会爬取一遍（当然，不是说这个无意义，毕竟这8、9个小时之间也会有更新），但这个时候个人更加关心其他爬取完，而不是前面的更新这8、9个小时的内容。

另外，不知道有多少人对爬取的时效性有多高，但至少对我来说不高，并且大多都是晚上爬取，所以，比如每爬取40个id，暂停一个小时都是没问题的，反倒是一次能全部爬取完更加重要。

**Comment by dataabc** [comment]
感谢反馈。

这个功能我其实一直想添加，但不清楚具体的限制规则。所以我目前的想法是在config.json控制暂停的频率和每次暂停的时间，可能也会根据爬取的用户数目暂停，这个还没想好，近期应该会添加这个特性。

**Comment by dataabc** [comment]
这个功能已经添加。

分为两个功能：设置小的等待和全局等待。
**小的等待**
通过config.json配置
```
    "random_wait_pages": [1, 5],
    "random_wait_seconds": [6, 10],
```
random_wait_pages控制多久暂停一次，random_wait_seconds控制每次暂停多少时间。上面表示每爬1到5页，等待6到10秒。

**全局等待**
这是在全局方面控制等待。之前的思考是有两种实现方式：1.控制用户数量，即爬取多少用户后暂停较长的一段时间；2.控制爬取页数，即爬取多少页后暂停较长的时间。
然而两种方法都有缺点，前者因为每个用户的微博数不同，有的很多，有的很少。比如，假如每100个用户暂停1小时。假如这100个用户的微博都不多，加起来可能都不到1000条；另一种情况，某些用户微博很多，几个用户可能比几百个用户的都多。这些如果按照用户数量暂停，可能有的只爬了1000多条就要暂停1小时，有的只爬一个用户就导致被限。后者较前者的优点是根据页数来，不会出现因不同用户微博数目不均导致的问题。缺点是可能漏爬，因为在等待时用户可能发了新微博。还有非常有可能出现某用户只爬了一部分然后长时间等待的情况。这时候如果使用者不想等了，就丢失了该用户之前已经获取的部分。
基于以上原因，两种情况都有优点和缺点，所以我结合它们的优点实现了这个功能，以控制页数为主，控制用户数为辅。每次开始爬取某用户的微博时会判断已经获取的页数加上待爬用户微博页数是否满足等待条件，如果满足就停止。所以对于大部分情况，不会出现暂停前爬了一部分，还要暂停后再爬一部分的问题。也因为算法是加上待爬用户微博页数的，目前所获得的微博页面是不满足暂停页数的，因此暂停时间会比配置的短，值是配置时间乘以以获取的页数占配置页数的比例。但是对应微博页数非常多的用户，如配置了爬1000页暂停1小时，某用户有2000页微博。这种情况是会拆分处理的。
全局等待通过config.json文件的global_wait参数控制
```
    "global_wait": [[1000, 3600], [500, 2000]], 
```
上面的意思是获取1000页微博，一次性等待3600秒；之后获取500页微博一次性等待2000秒。默认只有两个global_wait配置，可以添加更多个，也可以自定义。当配置使用完，如默认配置在获取1500（1000+500）页微博后就用完了，之后程序会从第一个配置开始循环使用（获取第1501页到2500页等待3600秒，获取第2501页到第3000页等待2000秒，以此类推）。

**Comment by gudaost** [comment]
赞！暂时还没顾上下载新版，在折腾我那个百度识图那个呢……
或许有个小思路，供参考：
被ban的时候，报错基本上是固定的，比如我那个百度识图会不返回url，或者页面中包含了特定字段，我在里面增加了个最长的sleep时长，这个是在常规sleep失效的情况下，即使被ban了，也可以让脚本不因为报错而停止，而是跳转到这个最长时间的sleep里面，比如sleep 1、2个小时啥的（肯定解除ban的时长）
仅供参考

**Comment by dataabc** [comment]
感谢建议，不错的思路

**Comment by gudaost** [comment]
刚开始尝试，没改数值又被ban了，呵呵。然后想改一下设置，发现有点不知道该改什么，主要不知道爬了多少页被ban的，不晓得哪个条件被触发了……
一点小想法，是否可以考虑，在log文档或其他什么文档里面写入每次运行程序，整体爬了多少页，当然最终是成功了，还是失败了最好也能显示一下。
一个呢，这样每次运行完，可以直接看这个文件，知道是否成功了（要是能做到的话，我会选择用批处理读取一下，然后弹出来个成功或失败的对话框之类的）
另外一个，一旦失败了，也很容易知道爬了多少页被干掉的，修改这里的配置也容易一些。

**Comment by gudaost** [comment]
不过我还是觉得被ban了，来个Sleep4、5个小时，而不是中断简单直接，呵呵

**Comment by dataabc** [comment]
感谢建议。

1.因为不同微博类型限制不一样，加了随机，不一定每次被ban都是相同的页数，有时候会差很大，不会是某一特定的数字。加入等待较长时间是想让程序不要爬的太频繁，降低被限概率。
2.这个我不确定被ban后多长时间解除，每个用户被ban的时间是不是相同，解除后是否重新爬取被ban的内容还没想好。
