### ISSUE TITLE
Provisional headers are shown. Disable cache to see full headers.

### ISSUE THREAD

**Issue by mashagua** [dataabc/weiboSpider#194]
按照你提示的cookies.md发现我的request headers里面出现了Provisional headers are shown. Disable cache to see full headers.，并没用出现cookies,

**Comment by dataabc** [comment]
感谢反馈。

你是不是在<https://m.weibo.cn>出现的这个，应该在<https://weibo.cn/>获取。刚刚我在第一个链接也出现相同错误，在第二个链接可以获取成功。
