### ISSUE TITLE
能否获取粉丝列表

### ISSUE THREAD

**Issue by mashagua** [dataabc/weiboSpider#195]
程序中如何获取粉丝列表

**Comment by dataabc** [comment]
感谢反馈。

本程序无法获取粉丝列表，因为有限制。不过，如果你想获取关注列表倒是可以，<https://github.com/dataabc/weibo-follow>，该项目是获取关注列表的，你可以仿照者获取粉丝。

如果还有其它问题或建议欢迎继续讨论

**Comment by xiaolinfan** [comment]
请问获取粉丝和关注列表时，只显示前20页，请问怎样爬取后面的粉丝和关注呢

**Comment by dataabc** [comment]
@xiaolinfan 
这个没办法

**Comment by xiaolinfan** [comment]
好的，谢谢
