### ISSUE TITLE
相关博文的全部转发/评论信息

### ISSUE THREAD

**Issue by yaginkr** [dataabc/weiboSpider#196]
大神，您好，我也是正在学习python，您分享的代码，对我新人而且要紧急使用于工作上，对我帮助十分大。在此先谢谢您。
因为我们微博做了转发留言活动，所以我们有1万多条转发，需要下载下来。

但是我发现，不仅是您，还有很多写python爬虫的大神们，一般都是部分评论或者是只有评论数，而很少是爬取内容的。
是否因为这个难度比较大呢？还是说不太常用的功能，所以没有写代码呢？ 谢谢您

**Comment by dataabc** [comment]
客气了。

因为只能获取一部分，所以没有写。

微博的转发地址：<https://weibo.cn/repost/weibo_id?page=页码>，比如<https://weibo.cn/repost/JcxtnEzql?page=1>，这条微博有10万页转发，开始几页你能看到转发者，后面的就是空白页了，可能是作了限制。
对应的评论地址<https://weibo.cn/comment/JcxtnEzql?page=1>也类似，获取不全

**Comment by dataabc** [comment]
刚发现一个可能满足你要求的，能获取较多的转发，大约几万吧，不确定。
<https://weibo.com/aj/v6/mblog/info/big?id=微博id&page=页码>，如<https://weibo.com/aj/v6/mblog/info/big?id=4529886099669293&page=1>。这里的微博id是免cookie版中的id，你在<m.weibo.cn>点开微博评论页，链接上就有。好像最多可以获取1000页转发，每页大约有十几条转发，如果这么算，可以获取不到2万的转发,你只需要解析每个转发页面就可以了。
