### ISSUE TITLE
程序不懂求助

### ISSUE THREAD

**Issue by yuhaoWu-1993** [dataabc/weiboSpider#201]
![image](https://user-images.githubusercontent.com/59786812/89711212-62ec8180-d9bb-11ea-8b1f-dd9153e9764b.png)
你好，请教一下，spider.py中，如下三行是什么意思？
                                                   from . import config_util, datetime_util
                                                   from .parser import IndexParser, PageParser
                                                   from .user import User

**Comment by dataabc** [comment]
就是导入本地的包。

第一行导入了config_util.py、datetime_util.py；
第二行导入了parser文件夹下的IndexParser,类（index_parser.py）和PageParser类（page_parser.py）；
第三行导入了user.py内的User类。

**Comment by yuhaoWu-1993** [comment]
谢谢！
