### ISSUE TITLE
是否考虑加入“用户点赞的微博列表”爬取

### ISSUE THREAD

**Issue by Xun66** [dataabc/weiboSpider#202]
- 问：请说明需要什么新功能。<br>
答：Ta最近赞过的微博清单（API：https://weibo.com/{user_id}/like）

从README中没有看到相关描述，如果尚未实现是否考虑加入？谢谢！

**Comment by dataabc** [comment]
感谢建议。

目前还没有这个功能，暂时没有加入的打算。因为本程序主要是用来获得指定用户的微博，而不是点赞过的微博。如果添加，应该会另开一个新项目。

再次感谢建议，其实是非常好的建议，只是现在主要想围绕用户所发布的微博，其它方面还待考虑。如果还有其它建议，欢迎继续讨论
