### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Lachesis1128** [dataabc/weiboSpider#204]
请问安装weibo-crawler依赖项时出现这堆错误是什么问题呀？
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8q/280scm4n74s7xw1cm8g0n4540000gn/T/pip-install-c1l5l3r8/lxml/setup.py'"'"'; __file__='"'"'/private/var/folders/8q/280scm4n74s7xw1cm8g0n4540000gn/T/pip-install-c1l5l3r8/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/8q/280scm4n74s7xw1cm8g0n4540000gn/T/pip-record-1jqe4q8n/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/lxml Check the logs for full command output.

**Comment by dataabc** [comment]
感谢反馈。

你可以参考[在执行 pip install 时遇到错误](https://zhuanlan.zhihu.com/p/89858202)。

如果还有问题，欢迎继续讨论

**Comment by Lachesis1128** [comment]
> 感谢反馈。
> 
> 你可以参考[在执行pip install时遇到错误](https://zhuanlan.zhihu.com/p/89858202)。
> 
> 如果还有问题，欢迎继续讨论

那俩我都安装了还是不行 因为我的是mac也没办法安装最后的exe文件TT

**Comment by dataabc** [comment]
通过
```
$ python3 -m pip install xxx(不要指定版本)
```
手动安装依赖呢?

**Comment by Lachesis1128** [comment]
> 通过
> 
> ```
> $ python3 -m pip install xxx(不要指定版本)
> ```
> 
> 手动安装依赖呢？

谢谢，可以了！虽然不知道怎么做到的但总算成功了 我实在太菜了TTT
