### ISSUE TITLE
本地包import错误

### ISSUE THREAD

**Issue by EchoComma** [dataabc/weiboSpider#205]
spider.py直接运行就会出现本地包import错误，修改id也会出现。以下是报错信息

  File "C:/Users/lyylx/Documents/weiboSpider-master (1)/weiboSpider-master/weibo_spider/spider.py", line 17, in <module>
    from . import config_util, datetime_util

ImportError: cannot import name 'config_util' from '__main__' (C:/Users/lyylx/Documents/weiboSpider-master (1)/weiboSpider-master/weibo_spider/spider.py)

**Comment by dataabc** [comment]
感谢反馈。

cd到weiboSpider目录，运行
```
python3 -m weibo_spider
```
即可，或者直接运行__main__.py文件。
