### ISSUE TITLE
学术文章引用

### ISSUE THREAD

**Issue by EchoComma** [dataabc/weiboSpider#206]
您好，请问用您的代码获得的数据如果要用于个人学术研究需要怎么引用或注明呢，谢谢！

**Comment by dataabc** [comment]
这个我也不太懂，你可以网上搜索，这是我发现的[关于引用网络参考文献的写法](https://zhuanlan.zhihu.com/p/97260850)

**Comment by EchoComma** [comment]
非常感谢！只是确定一下您是否有特殊的鸣谢要求。

**Comment by songzy12** [comment]
@EchoComma 你好，论文如果被接收发表的话可以回来这条 issue 里贴一下链接吗，我个人非常感兴趣。多谢！也祝学术顺利！
@dataabc 我们到时可以在 README 里加一节来标明使用了该工具的学术研究，感觉非常有意义，对这个项目也会很有好处。

**Comment by dataabc** [comment]
@songzy12 
建议很好。

只是我担心很多使用者因为隐私原因不一定会告诉我们在哪些学术研究中使用了本项目，如果对方告诉了，我们应该明确询问是否可以将学术研究展示在README里，对方同意了我们就可以这么做了。我这个想法是不是有点矫情了。。

**Comment by songzy12** [comment]
@dataabc 哈哈并不是矫情，而是考虑问题比较全面。
我们确实不用主动去找，可以在 README 里说明如果使用了该软件并想要被展示的话欢迎来告诉我们。
有的作者应该也会愿意增加自己研究成果的曝光率，大概会有种双赢的感觉。

**Comment by dataabc** [comment]
@songzy12 
对的，有机会在README中宣传下，如果有作者原意的话可以专门加个相关学术页面
