### ISSUE TITLE
运行程序提示没有absl某块，但是我已经安装了。

### ISSUE THREAD

**Issue by herkoy** [dataabc/weiboSpider#208]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：
GitHub版
- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：否

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：在配置好运行环境后，第一次运行提示Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
![image](https://user-images.githubusercontent.com/24191851/90496400-5b299b80-e178-11ea-9c0e-14e988dfc2da.png)

**Comment by dataabc** [comment]
卸载absl重新安装有效果吗
