### ISSUE TITLE
我执行命令的时候  一直报下面的错

### ISSUE THREAD

**Issue by Doralf** [dataabc/weiboSpider#209]
cookie错误或已过期,请按照README中方法重新获取
<img width="754" alt="WX20200820-171629@2x" src="https://user-images.githubusercontent.com/22440323/90751746-1d0fb180-e309-11ea-87b1-1b19fcc50b70.png">

**Comment by dataabc** [comment]
感谢反馈。

说明cookie不正确或者过期了，按照[如何获取cookie](https://github.com/dataabc/weiboSpider/blob/master/docs/cookie.md)获取cookie就可以了，或者使用[免cookie版](https://github.com/dataabc/weibo-crawler)。

如果还有问题，欢迎继续讨论
