### ISSUE TITLE
能否增加地理信息、微博客户端信息（手机品牌，iphone）信息

### ISSUE THREAD

**Issue by leonall** [dataabc/weiboSpider#21]

**Comment by xnzmc** [comment]
地理信息有点难获取，因为定位在网页中显示为链接。
而客户端信息倒是较容易获取，和发布时间是一个字段，把`来自`分隔开就可以获取

**Comment by dataabc** [comment]
只能获取部分微博的这些信息，因为一些微博没有地理位置、手机信息

**Comment by GongShengyue** [comment]
我正在努力尝试获取地理定位中，目前遇到了一点困难，首先不是所有的微博都会带定位，其次定位信息在一个<a>中，比较难获取，如果有兴趣的话，我们可以一起讨论下。
