### ISSUE TITLE
请求源代码作者的署名

### ISSUE THREAD

**Issue by Mak-LokGay** [dataabc/weiboSpider#213]
大大以及其他各位contributors，你们好！

我的论文中用到了您的源代码对微博数据进行了爬取，因此我也希望能够对您以及其他各位contributors进行署名，以便保护各位的创作成果，不知您以及其他各位是否方便提供署名呢？

如果不方便提供真实姓名的话，我也可以直接将源代码的网址：

https://github.com/dataabc/weiboSpider 进行引用，避免窃取各位创作成果的可能！

详细信息我们可以进一步商量，我的邮箱是maizixin1021@gmail.com！等待您的回复！

**Comment by dataabc** [comment]
已经在邮件中回复了

**Comment by songzy12** [comment]
关于这个问题，如果我们参考 tensorflow models 的引用：
https://github.com/tensorflow/models#citing-tensorflow-model-garden

我想 README “学术研究”中可以加一段类似这样：
```
@misc{weibospider2020,
  author = {Chen Lei},
  title = {{Weibo Spider}},
  howpublished = {\url{https://github.com/dataabc/weiboSpider}},
  year = {2020}
}
```

其中 year 可以是项目的创建时间或者做出比较大改动的时间。

不知 @dataabc 意下如何？

**Comment by dataabc** [comment]
@songzy12 好主意。author最好把所有贡献者都写上，毕竟这是大家共同的努力。还有，这一段可以帮忙修改吗？因为最近一段时间，电脑不在身边，担心手机上格式弄不好。如果不方便，过几天我再做也可以。

**Comment by songzy12** [comment]
@dataabc cool，刚发了一个PR：https://github.com/dataabc/weiboSpider/pull/426

我们可以在那条PR下继续讨论相关的修改意见。^_^
