### ISSUE TITLE
可否整合weibospider与weibo-crawler两者的优点？

### ISSUE THREAD

**Issue by bwzhang-7** [dataabc/weiboSpider#214]
- 问：请说明需要什么新功能。<br>
答：1.针对图片数量超过9图的单条微博，weibospider可以爬取该微博的所有图片，但weibo-crawler最多只能爬取9图;
2.对于live photo，weibospider只能保存jpg，但weibo-crawler可以以视频的形式保存；

- 问：请说明添加该功能的意义。（非必填）<br>
答：为了实现上述需求只能同时使用两者，但第9张之后的live photo依旧无法以视频形式保存，希望之后能整合两者的优点，感谢！

**Comment by dataabc** [comment]
感谢建议。

因为weibo-crawler和本项目使用的是不同的接口，前者是<m.weibo.cn>，后者是<weibo.cn>。<m.weibo.cn>一条微博本身最多只能获取9张图片，这是微博限制的，但是它可以获得live photo； <weibo.cn>可以获取全部图片，但是无法下载live photo，这也是受限的。这两个接口是分开的，二者取其一，所以互有优缺点，无法调和。所以，暂时无法整合两者的优点，鱼和熊掌难兼得。

感谢建议，如果还有问题，欢迎继续讨论。

**Comment by dataabc** [comment]
其实有个办法，就是遇到有图片的微博就同时使用两者，但是这样被限制的风险会提高

**Comment by bwzhang-7** [comment]
了解了，感谢！
