### ISSUE TITLE
有可能定期自动更新Cookie吗？

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#217]
- 问：请说明需要什么新功能。<br>
答：有可能定期自动更新Cookie吗？

- 问：请说明添加该功能的意义。（非必填）<br>
答：主要是很多时候并不知道Cookie是否正确设置了，是否正确运行了。周期更新，也有点小麻烦。
其实自己尝试搜索了一下，然后没弄出来，呵呵……

**Comment by dataabc** [comment]
感谢建议。

这个以前我考虑过，不过自动登录接口好像对ip限制比较严，可能要经常更新代码，暂时应该不会添加这个功能。
