### ISSUE TITLE
除了第一条weibo之外别的剩下的微博都显示“网络出错”

### ISSUE THREAD

**Issue by dreamiter** [dataabc/weiboSpider#218]
请问“网络出错”是什么情况？除了每次scrap的第一条微博可以正常显示之外 剩下的都是网络出错？
但奇怪的是点赞数，转发数都可以正常显示。Image和Video也可以正常download。

==========================================================

Progress:   0%|                                         | 0/185 [00:00<?, ?it/s][置顶]#明星权力榜人气榜#  2020年8月份演员类、歌手类、新星类、海外艺人类投票结果公示，欢迎继续为你的偶像投票加油→http://t.cn/R9c8b9D  [组图共8张] 原图 
微博发布位置：无
发布发布时间：2020-09-01 13:09
发布发布工具：微博 weibo.com
点赞数：67791
转发数：1151
评论数：1066
url：https://weibo.cn/comment/JiBjvwNKo
----------------------------------------------------------------------------------------------------
网络出错
微博发布位置：无
发布发布时间：2020-09-11 13:15
发布发布工具：微博 weibo.com
点赞数：5767
转发数：106
评论数：188
url：https://weibo.cn/comment/Jk7CMf0lS
----------------------------------------------------------------------------------------------------
网络出错
微博发布位置：无
发布发布时间：2020-09-10 13:16
发布发布工具：微博 weibo.com
点赞数：2838
转发数：27
评论数：131
url：https://weibo.cn/comment/JjYcWFyj3
----------------------------------------------------------------------------------------------------

**Comment by dataabc** [comment]
感谢反馈，问题已经解决了。

出现错误的都是长微博，一般微博在微博列表页获取，但是长微博在列表页只能获取全部内容的一部分，为了获取全部内容，程序会尝试单独访问长微博的详情页，如果访问成功就返回获取到的内容，如果失败了会在尝试几次，只有所有尝试都访问失败才使用之前不全的内容。因为之前程序在访问失败时也会返回内容（成功返回正文，失败返回网络出错），后续的程序以为返回了内容，所以出现了上面的问题。现在问题已经修复。如果5次访问长微博失败，就把之前不全的内容写入结果，如果成功就写入完整的内容。如果一定要获取长微博的内容，可以修改comment_parser.py的get_long_weibo方法，增加for循环的次数，或者把for循环改成while循环。

感谢反馈，如果还有问题欢迎继续讨论

**Comment by dreamiter** [comment]
Thanks!
