### ISSUE TITLE
config中的end_date设置无效

### ISSUE THREAD

**Issue by rainwormzx** [dataabc/weiboSpider#219]
- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：github版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：是

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：无论在config里设置end_date是什么日期，都会从最新发布的那条开始爬取。

**Comment by dataabc** [comment]
感谢反馈。

是不是在weiboSpider/weibo_spider/config_sample.json中修改的end_date？应该修改weiboSpider/config.json中的end_date参数。

**Comment by rainwormzx** [comment]
感谢回复！
我是pip安装在其他目录下，修改生成的config.jason文件里的end_date。 不知道是不是这个原因
晚上我去试试源码下载安装的方式。再次感谢~

**Comment by dataabc** [comment]
就是这个原因，目前只有github版支持end_date，pip还不支持。

**Comment by rainwormzx** [comment]
感谢回复！
