### ISSUE TITLE
每次爬取到这一天就会报错，只能爬取一年不到的数据

### ISSUE THREAD

**Issue by JunkeyLau** [dataabc/weiboSpider#22]
![image](https://user-images.githubusercontent.com/30010225/40320575-c048cca2-5d5e-11e8-88a1-1550b9d861db.png)
想问问，为什么每次爬取到这一条就会报错啊？

**Comment by dataabc** [comment]
如果方便，能否提供爬取的微博id我调试下

**Comment by JunkeyLau** [comment]
好的麻烦了
ID：5178873319
成都理工大学

2018-05-22 23:18 GMT+08:00 Chen Lei <notifications@github.com>:

**Comment by JunkeyLau** [comment]
哦，谢谢了，那可以通过增加延迟来爬更多的数据吗？

**Comment by dataabc** [comment]
可以，你可以参考#8

**Comment by zyxbcde** [comment]
有很多是博主点了个禁止评论，然后下面按钮少了一个，这样XPATH就乱了，会导致报错。

**Comment by dataabc** [comment]
@zyxbcde 
如果可以，能否提供出现错误的微博id，方便调试。因为我找了几个疑似禁止评论的微博，都可以正确爬取。
