### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by RivenLUO** [dataabc/weiboSpider#221]
按照README中的方法获取cookie修改config后，运行程序显示cookie错误或者过期，希望解答

**Comment by dataabc** [comment]
感谢反馈。

想到几种可能：
1.应该修改config.json，你可能修改的是config_sample.json，这种可能性不大，因为上面说的是config；
2.可能在获取cookie时跳过了一些步骤，必需按照readme操作，不能省略；
3.可能使用的编辑器自动添加了一些字符，因为cookie很长，有的编辑器在换行时会自动加上换行符，导致出错，这种可能性最大。

如果还有问题欢迎继续讨论

**Comment by RivenLUO** [comment]
> 感谢反馈。
> 
> 想到几种可能：
> 1.应该修改config.json，你可能修改的是config_sample.json，这种可能性不大，因为上面说的是config；
> 2.可能在获取cookie时跳过了一些步骤，必需按照readme操作，不能省略；
> 3.可能使用的编辑器自动添加了一些字符，因为cookie很长，有的编辑器在换行时会自动加上换行符，导致出错，这种可能性最大。
> 
> 如果还有问题欢迎继续讨论

**Comment by RivenLUO** [comment]
> > 感谢反馈。
> > 想到几种可能：
> > 1.应该修改config.json，你可能修改的是config_sample.json，这种可能性不大，因为上面说的是config；
> > 2.可能在获取cookie时跳过了一些步骤，必需按照readme操作，不能省略；
> > 3.可能使用的编辑器自动添加了一些字符，因为cookie很长，有的编辑器在换行时会自动加上换行符，导致出错，这种可能性最大。
> > 如果还有问题欢迎继续讨论

**Comment by RivenLUO** [comment]
已解决cookie问题
