### ISSUE TITLE
文章爬取功能

### ISSUE THREAD

**Issue by CottonChou** [dataabc/weiboSpider#222]
- 问：请说明需要什么新功能。<br>
答：希望可以新增文章爬取功能，可以单独存放到独立文件夹或者将文章在对应微博处展开（一般发表文章后会生成一条概览的微博，如果按照对应微博的顺序展开可能更加有时序性）

- 问：请说明添加该功能的意义。（非必填）<br>
答：很多科普或者财经博主分享的内容是以文章的形式分享，希望能够将其保存下来。谢谢。
PS：可以挂个赞赏，请您喝杯咖啡

**Comment by dataabc** [comment]
感谢建议。

这个功能在计划中，后续会添加，但应该过一段时间。目前打算把文章下载到本地对应用户名下的文章文件夹，文件名是文章标题，标题中可能还会有时间等信息。

如果还有问题，欢迎继续讨论
