### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by hou5835629** [dataabc/weiboSpider#225]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/kristen/weiboSpider/weibo_spider/__main__.py", line 4, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

**Comment by dataabc** [comment]
感谢反馈。

说明没有absl模块，安装absl就可以了
```
$ python3 -m pip install absl-py
```
如果还有问题欢迎继续讨论

**Comment by yuqwang913** [comment]
> python3 -m pip install absl-py

您好，安装absl-py后依然显示no module named 'absl'，请问这是怎么回事？
git clone之后进入目录，然后执行
python -m weibo_spider
之后报错
![image](https://user-images.githubusercontent.com/50217068/97790765-b4c43280-1bcb-11eb-9414-47af2f58ea30.png)
另行安装absl-py也没用

**Comment by od61** [comment]
> > python3 -m pip install absl-py
> 
> 您好，安装absl-py后依然显示no module named 'absl'，请问这是怎么回事？
> git clone之后进入目录，然后执行
> python -m weibo_spider
> 之后报错
> ![image](https://user-images.githubusercontent.com/50217068/97790765-b4c43280-1bcb-11eb-9414-47af2f58ea30.png)
> 另行安装absl-py也没用

这还是显示没安装啊，可能没装对

**Comment by dataabc** [comment]
@od61 

是不是同时安装了python2和python3？如果是，可能是安装了python3的absl，用python2运行的程序。如果安装是python3 -m pip install absl-py，运行就用python3 -m weibo_spider
