### ISSUE TITLE
个性化定制程序

### ISSUE THREAD

**Issue by hou5835629** [dataabc/weiboSpider#227]
我想着修改一下爬取微博的时候，不想爬取这么多内容，比如说我只想要微博内容和时间，应该在哪里修改？我在目录下面没有找到weibo_spider.py这个文件，有spider.py和weibo.py，请作者帮帮忙！

**Comment by dataabc** [comment]
感谢反馈。

要修改weibo_spider**文件夹**下的内容。主要逻辑在spider.py，writer文件夹下是保存信息的操作，根据自己保存的类型修改对应文件就行。

如果还有问题欢迎继续讨论
