### ISSUE TITLE
感谢作者，服务器上已经运行成功了，顺便想请教几个小问题。

### ISSUE THREAD

**Issue by Mordiggian** [dataabc/weiboSpider#228]
我是一个对编程不太熟悉的菜鸟，我最初是想要把自己微博时间线整理成rss，用rss阅读器来阅读关注的人的微博。一开始是使用rsshub，非常方便，但它有个缺点，我不知道用专业的计算机语言如何描述，就是，他只能是不用登陆的从“外面”定时获取最新动态，但是一旦这个微博账号设置成只“粉丝可见”，不登陆账号自然就看不见，那么rsshub就完全束手无策了，而我最需要关注一个账号最近不巧就改成了这个样子，我于是就想找个别的办法，就想到了在服务器上装个爬虫。

但我发现，爬虫设置里面基本是以“天”为最小单位来自动运行的，而我关注的用户更新微博时效性非常强，短到我觉得要做到5min/次。

同时，因为我的目的是浏览更新，所以单纯用爬虫远没有rss方便。

因此，我想试着自己去改进一下rsshub获取微博的功能，请教下作者，有没有方法让它能“预载”一个微博账号（是不是就是cookie？），然后获得“粉丝可见”的信息？

ps：定期爬虫设置的user_id_list.txt的地址该怎么在config.json里写呢？我在/root/weiboSpider下新建了个txt，里面写上要关注的id，然后config.json里写上“  "user_id_list": ["/root/weiboSpider/user_id_list.txt"]  ”结果程序运行config时报错？

**Comment by dataabc** [comment]
感谢反馈。

1.rsshub不熟悉，它相关的帮不了忙；
2.程序是以天为单位爬取的，但是可以改成以分为单位，比如每次只爬指定用户最近5分钟发的微博，然后使用crontab每5分钟执行一次本程序。具体修改spider.py的__init__方法：
原来
```
    def __init__(self, config):
        ......
        if isinstance(since_date, int):
            since_date = date.today() - timedelta(since_date)
        ......
```
修改后
```
    def __init__(self, config):
        ......
        if isinstance(since_date, int):
            minute = timedelta(minutes=int(since_date))
            since_date = (datetime.now() - minute).strftime('%Y-%m-%d %H:%M')
        ......
```
修改config.json中的since_date
```
   "since_date": 5,
```
表示获取指定用户最近5分钟发表的微博，值是整数，如果认为5分钟太长，可以改成1（最近1分钟）；

3.config.json里user_id_list应为
```
  "user_id_list": "/root/weiboSpider/user_id_list.txt",
```

如果还有问题欢迎继续讨论

**Comment by Mordiggian** [comment]
非常感谢，我已经用crontab设置成功了，但又衍生出了一个新的小问题，请教下作者。

我现在是按你上面所提的，在config上时间设置为“1”，然后我看crontab的log里面（我crontab设定每分钟自动运行），每分钟可能是第14s完成、27s完成等等等，也就是在这一分钟不定秒后完成，那么是不是就存在着漏掉微博信息的可能呢？（我不太确定其中的机制，只是一种猜测？）

所以我想还是在config里设置成绝对时间，但是，我发现配合crontab自动运行的话，好像只有自己设定的user_id_list里的时间会自动更新成新的。不知道是list.txt里的时间会自动覆盖config里的时间，然后能配合crontab每分钟自动从txt里设置的时间点开始爬取？

**Comment by Mordiggian** [comment]
ps:指南里查看微博用户id的方法有点繁琐，可以直接电脑上在weibo.com上点到用户资料页，f12后再console里输入 $config 就能看到id了

**Comment by dataabc** [comment]
如果设置获取最近1分钟的微博，程序会计算1分钟之前的时间，只要微博发布时间在这一分钟内就获取。要获取这1分钟的微博，可能不到1分钟就获取了。比如你想获取某用户一天的微博，可能几分钟就获取了，用不到一天，因为获取的是之前的微博，耗时和最近多少天没关系。还是以1分钟来说，程序获取的是程序执行时到之前1分钟内这一分钟内发布的微博，不是获取的从执行时到未来1分钟内发布的微博，所以提前完成很正常，不会漏掉微博，不知道上面说的漏掉微博的可能是不是指的这个？

上面我说错了一个地方。因为有两个地方可以设置since_date，一个是在config.json内设置，一个是在user_id_list.txt设置，如果user_id_list参数是文件路径，会优先使用txt中的since_date，因为这样更灵活。所以，上面如果想获取最近1分钟发的微博（"since_date": 1）,user_id_list应该是user_id列表，不应该是文件路径。

因为你使用的是user_id_list.txt，所以更推荐把user_id_list设置为它的路径，这样只有在第一次执行的时候，如果user_id_list.txt没有手动设置since_date，程序会使用since_date内的设置，此后程序会自动生成或更新user_id_list.txt内的since_date。更新的原理是如果某个用户爬取成功，程序会把该用户的since_date设置成开始获取该用户微博的时间。这样下次再爬该用户时，就爬到该时间止，因为这个时间之前的已经爬过了，并更新新的since_date，以此类推。

总之，你不需要任何改动，使用现在的代码就可以了，连上面的spider.py都不用修改，只要保证user_id_list是文件路径就可以。

另外，请教下，上面说“微博用户id的方法有点繁琐”是因为该方法需要访问手机版的原因吗？因为现在的方法也是点击资料，就可以得到id的，感觉和上面的方法类似，不知道我理解的对不对，不管是否采用上面的方法，都感谢热心建议。

**Comment by Mordiggian** [comment]
我想了下，之前我说直接控制台输$config的方法其实和你写在readme里的差不多，只不过之前第一次设置，把获取cookie+获取用户id的步骤想到一块去了。。。
非常感谢作者耐心详细的解答，祝中秋&国庆快乐！
