### ISSUE TITLE
获取限定时间段内的最新x条微博

### ISSUE THREAD

**Issue by ChenYuyu1912** [dataabc/weiboSpider#229]
您好，不好意思又打扰了。

我之前再weibo-crawler的项目里咨询过关于获取从某个日期至今的最新x条微博，也得到了答复，谢谢！
但是还想请问一下，在使用weiboSpider的程序时，如果同样有一个很长的user_id_list，现在需要获取列表里每一个用户在2016-01-01至2017-01-01间最新的100条微博，（也就是说，如果存在A用户在这个日期区间不满100条微博，就获取A用户在这个区间的所有微博；如果存在B用户在2016-10-01至2017-01-01就发了100条微博，那只需要获取B用户2016-10-01至2017-01-01期间的这100条微博），不知道我是否描述清楚了……请问可以怎样通过修改程序实现呢？我尝试模仿之前您在weibo-crawler的方法改了一下，但是我太蠢了程序总是出错……

谢谢！

**Comment by dataabc** [comment]
感谢反馈。

修改page_parser.py的get_one_page方法：
用来
```
    def get_one_page(self, weibo_id_list):
                        ......
                        publish_time = datetime_util.str_to_time(
                            weibo.publish_time)
                        ......
```
修改后
```
    def get_one_page(self, weibo_id_list):
                        ......
                        publish_time = datetime_util.str_to_time(
                            weibo.publish_time)
                        if len(weibo_id_list) == 100:
                            return weibos, weibo_id_list
                        ......
```

如果还有问题欢迎继续讨论
