### ISSUE TITLE
用的一个人的userid，爬取了两个人的微博记录【笑哭】

### ISSUE THREAD

**Issue by charlootte** [dataabc/weiboSpider#23]
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "weibospider.py", line 40, in get_username
    username = selector.xpath("//title/text()")[0]
AttributeError: 'NoneType' object has no attribute 'xpath'
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "weibospider.py", line 57, in get_user_info
    str_wb = selector.xpath(
AttributeError: 'NoneType' object has no attribute 'xpath'
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "weibospider.py", line 105, in get_weibo_info
    if selector.xpath("//input[@name='mp']") == []:
AttributeError: 'NoneType' object has no attribute 'xpath'
第二个人的微博只爬取了一小部分就报错了，第一个人全都整理了，想爬取的是第二个人，纳闷为什么会出现两个人？

**Comment by dataabc** [comment]
能否提供userid，方便调试

**Comment by charlootte** [comment]
2189910831，谢谢~

**Comment by charlootte** [comment]
问题解决啦，是我的问题，写重了【捂脸】 谢谢~
