### ISSUE TITLE
爬取中途停止爬取是因为太频繁被限制了吗

### ISSUE THREAD

**Issue by SekiBetu** [dataabc/weiboSpider#231]
- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：PyPi

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：是

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：
![image](https://user-images.githubusercontent.com/38283893/94890010-956fa380-046d-11eb-9375-ba0393c66c92.png)
程序在爬取中途提示爬取完成，并且再次修改爬取时间后接着爬也是提示0条微博
![image](https://user-images.githubusercontent.com/38283893/94890061-bcc67080-046d-11eb-9502-d823bc2adc10.png)

**Comment by SekiBetu** [comment]
没事了，过了一段时间再运行发现又可以了

**Comment by dataabc** [comment]
感谢反馈。

猜测你是通过user_id_list.txt输入user_id的，这种情况，第一次爬到since_date因为之后的不满足since_date，处就停了，并在user_id_list.txt自动添加了该用户的新的since_date。再次爬同一用户时，因为在config.json和user_id_list.txt都有since_date，优先使用txt中的。程序发现上一次的since_date进度，知道之前的已经爬取，就停止了，这样就实现了自动更新since_date，断点续爬。所以你再次爬取该用户时，没有获取微博就停了。
