### ISSUE TITLE
cookie错误或已过期,请按照README中方法重新获取

### ISSUE THREAD

**Issue by lbhfox** [dataabc/weiboSpider#234]
已经按方法获获取到新的COOKIe 了在哪个文件里更新啊，谢谢

**Comment by Fierygit** [comment]
我也遇到了这个问题， 在config 下更改了， 而且用了好多的cookie

**Comment by dataabc** [comment]
@lbhfox 

在命令行的当前目录应该会有config.json文件（一般在哪个目录运行程序就会在哪个目录生成config.json），把your cookie换成新的cookie就行了。

**Comment by dataabc** [comment]
@Fierygit 

猜测有几种可能：
1.可能获取到的cookie确实是不正确的；
2.可能改错文件了，应该在config.json修改，不是config_sample.json；
3.有些编辑器在换行时会自动加上换行符导致cookie出错。

如果还有问题欢迎继续讨论

**Comment by yqf** [comment]
使用Chrome浏览器，另开访客模式，登录后拿到的cookie就是当前登录的有效cookie。亲测有效

**Comment by 2929886881** [comment]
> 使用Chrome浏览器，另开访客模式，登录后拿到的cookie就是当前登录的有效cookie。亲测有效

你是我的大哥！
