### ISSUE TITLE
dalao我想请问一下能不能获取是谁点赞、评论、转发以及评论、转发的内容信息。

### ISSUE THREAD

**Issue by ShoZhou** [dataabc/weiboSpider#237]
- 问：请说明需要什么新功能。<br>
答：获取点赞、评论、转发信息。

- 问：请说明添加该功能的意义。（非必填）<br>
答：用于分析用户之间的情感、关系。

**Comment by dataabc** [comment]
感谢反馈。

这个因为限制，只能获取一部分点赞、评论和转发，获取不全。对于那些评论十几万的，只能获取很少的一部分，所以没有添加获取这些的功能。

如果还有问题欢迎继续讨论

**Comment by PanZ820** [comment]
麻烦请问一下 如何获取到部分点赞、评论和转发的用户信息及内容

**Comment by dataabc** [comment]
@PanZ820 

以id为JogrxB09L的微博为例，它的点赞页：
<https://weibo.cn/attitude/JogrxB09L?&page=1>
评论页：
<https://weibo.cn/comment/JogrxB09L?&page=1>
转发页：
<https://weibo.cn/repost/JogrxB09L?page=1>

编写程序从网页提取信息就可以了
