### ISSUE TITLE
似乎爬不了了

### ISSUE THREAD

**Issue by ntyxj** [dataabc/weiboSpider#24]
本人小白，使用anaconda运行该脚本，添加了迪丽热巴的用户id和用户名后，运行，得到的结果如下：
runfile('C:/Users/Administrator/Desktop/1/weiboSpider-master/weiboSpider.py', wdir='C:/Users/Administrator/Desktop/1/weiboSpider-master')
用户名: 登录 - 新
微博数: 864
关注数: 215
粉丝数: 41405239
===========================================================================
共0条微博
微博写入文件完毕，保存路径:
C:\Users\Administrator\Desktop\1\weiboSpider-master\weibo\1669879400.txt
信息抓取完毕

1669879400.txt的文件内容是：
用户信息
用户昵称：登录 - 新
用户id: 1669879400
微博数: 864
关注数: 215
粉丝数: 41405239

微博内容: 

没有实现UP主的结果，望能抽空解答，谢谢！

**Comment by dataabc** [comment]
这说明你的cookie没有配置好，按照README的方法获取重新获取cookie就可以

**Comment by ntyxj** [comment]
谢谢！今早重新查找了cookie并粘贴，已经完整实现了迪丽热巴的微博的备份。但是在爬另一个人的微博的时候，已经爬到了2017年3月，突然出现Error:  'NoneType' object has no attribute 'xpath'，就中断了。烦请UP主抽空解答，谢谢！

**Comment by dataabc** [comment]
说明你爬的太快了，可以控制下爬取的频率，如每爬n页sleep几秒，可以是等待固定n秒，也可以随机指定，等等

**Comment by ntyxj** [comment]
非常感谢UP主的回复！已经折腾了2天了也没有实现随机指定sleep的功能，在https://github.com/dataabc/weiboSpider/issues/8 里面提问也没有回应，无奈再次求助UP主。怎样实现每取随机1-10个微博的时候随机停顿30-60秒？或者每提取10条微博就随机停顿30-60秒？烦请UP主解答，感激不尽！

**Comment by dataabc** [comment]
如你所说，如果是sleep没定义的问题，你需要加上"from time import sleep"，就没有错误了
