### ISSUE TITLE
可以添加微博的url爬取功能嘛

### ISSUE THREAD

**Issue by Lxhnnn** [dataabc/weiboSpider#245]
- 问：请说明需要什么新功能。<br>
答：

- 问：请说明添加该功能的意义。（非必填）<br>
答：

**Comment by dataabc** [comment]
感谢反馈。

现在的程序已经包含了，只是打印输出没有保存，原因是它是冗余字段，可以由其它字段推出来。
可以把微博的评论页看作它的url，它是由<https://weibo.cn/comment/>+<weibo_id>组成的，知道了weibo_id就知道了url，因此没有保存。

如果还有问题欢迎继续讨论。
