### ISSUE TITLE
爬取内容不全

### ISSUE THREAD

**Issue by hughzeng-x** [dataabc/weiboSpider#248]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。<br>
<br>

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：PyPi

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？<br>
答：id正确

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：
爬取某一用户的微博时，对于时间比较早的微博爬取不全；比如今年的可以爬取500条，但在2016、2017之类的可能只能爬到几十条

**Comment by dataabc** [comment]
感谢反馈。

config.json的end_date值是不是是日期（默认是“now”）。这种方式有限制，当微博数量很多时，较早的微博可能获取不全，将end_date改成"now"就可以了。

如果还有问题欢迎继续讨论。

**Comment by hughzeng-x** [comment]
谢谢您的回复；当我使用now的时候，爬取一定数量以后会报错（因为报错后，我按照一年一年的爬取）；当爬取时间过长的时候，对random_wait_second是否要合理设置一下；

**Comment by dataabc** [comment]
random_wait_second值越大越好，对应速度会变慢。可以参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2。

还有一种方法，end_date值设为now，修改起始页，修改spider.py的get_weibo_info方法：
```
                for page in tqdm(range(1, page_num + 1), desc='Progress'):
```
程序默认从第一页开始爬，你可以把起始页设成真实的end_date开始的页面，比如你想获取从2019-01-01到2019-12-31的微博，可以把上面代码内range的第一个1换成发布日期在2019-12-31的微博所在的页，这样程序就会跳过前面的微博。因为你是一年年的爬，在爬2020年时，程序结束时的页码就是2019-12-31附近的页面，可以用它替换。

**Comment by hughzeng-x** [comment]
当我设置为now，把random_wait_second设为[100,200]时，然后爬取2015-2020的时候，到2018附近就自动停止了

我试试使用代码的方式来爬取，再与您交流
Duplicate of #

**Comment by pythonpythonxyj** [comment]
> 感谢反馈。
> 
> config.json的end_date值是不是是日期（默认是“now”）。这种方式有限制，当微博数量很多时，较早的微博可能获取不全，将end_date改成"now"就可以了。
> 
> 如果还有问题欢迎继续讨论。

你好！我设置的是默认的（也就是“now”），但程序报错（'NoneType' object）自动终止的时候，其实单个用户微博信息是没有爬取完毕的（比如这个用户的微博是从2013年-2020年，程序爬到2017年的就停止了，那2017年以前的微博就没有拿到），但下一次运行的时候也没有接着爬这个用户上次没爬完的继续爬。
