### ISSUE TITLE
cookie问题

### ISSUE THREAD

**Issue by cdp2287841965** [dataabc/weiboSpider#249]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github
- 问：您使用的是否是最新的程序（是/否）？<br>
答：是
- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：报cookie的问题，可是我已经换成自己的了

**Comment by dataabc** [comment]
感谢反馈。

如果提示是cookie相关问题，应该就是cookie是无效的，有的编辑器可能在换行的时候会自动加换行符，使cookie无效，不知道是不是这个原因。你可以：
1.按照README重新获取cookie，再查看编辑器是否会添加换行符；
2.使用[免cookie版](https://github.com/dataabc/weibo-crawler)。

上面二个方法选择一种就可以，如果还有问题，欢迎继续讨论
