### ISSUE TITLE
咨询一下现在Sleep的规则是什么？

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#250]
配置文件中，我设置成：
    "random_wait_pages": [5, 10],
    "random_wait_seconds": [10, 15],
    "global_wait": [[300, 3000], [300, 1800]],
运行时，爬取了2页后，开始了一个80秒的全局等待时间（我好像没有80秒这个范围啊）
然后是一个18秒的全局等待，之后分别是30秒、18秒、54秒等
没搞懂为什么会出现这些数字，都不在我定义的10~15之间呢，而且页数也不全是在5~10页之间

**Comment by dataabc** [comment]
配置是理论的时间，实际上可能还有网络原因等，比如有时可能因为网络或者限制，会等待很久，这个时间不是程序决定的，是网络原因。所以实际上会与配置有差别，配置是在排除所有外部因素影响下的等待配置。

**Comment by gudaocode** [comment]
我说的等待时间，是“即将进入全局等待时间，80秒后程序继续执行”这种，不是我自己掐表计时的，这个也是正常的么？

**Comment by dataabc** [comment]
是正常的。

程序的逻辑是尽可能的在进入等待前已经爬完上一个用户（即不会出现某用户爬了一半，然后进入全局等待，再爬另一半）因为有的使用者可能认为等待太长，没有耐心就关闭程序了，这样如果像括号中那样，就会出现某用户只爬了一半的情况。

本程序就是尽可能在全局等待前，让旧的用户已经完成，新的用户还没开始，这样使用者就可以这全局等待时尽可能的方向关闭程序了。为了达到这个效果，再开始新用户时，会判断当前获得的页数加上新用户微博的页数，和是否大于配置值，如果大于，就进入全局等待。因为毕竟程序没有真的达到配置规定的页数，所以等待时间等于活得的页数与规定页数的比值再乘以规定的等待时间。这样就避免了刚爬了没几页，却因新用户微博过多导致等待时间过长的问题。

上面的现象应该是程序发现虽然当前得到的页数不够配置要求，但是加上新用户的微博页数就超了，为了避免出现括号中的情况，提取进入了全局等待，等待时间是根据配置时间和时间获得的页数调整过的，即80秒。

**Comment by gudaocode** [comment]
感谢您的详细答复！
