### ISSUE TITLE
结果集乱码

### ISSUE THREAD

**Issue by wdq233** [dataabc/weiboSpider#252]
采集的结果集中文乱码，是需要在哪里配置字符编码吗

寰崥id | 寰崥姝ｆ枃 | 澶存潯鏂囩珷url | 鍘熷鍥剧墖url | 寰崥瑙嗛url | 鍙戝竷浣嶇疆 | 鍙戝竷鏃堕棿
-- | -- | -- | -- | -- | -- | --

**Comment by dataabc** [comment]
感谢反馈。

出来结果乱码，命令行打印的信息也是乱码吗？怀疑是系统编码原因，可以按照自己的系统，搜索“xx系统 中文 乱码”解决。

如果还有问题，欢迎继续讨论

**Comment by wdq233** [comment]
命令行都正常，导出了两种格式的文件，txt格式文字正常，csv格式用excle打开是上面的乱码。

**Comment by dataabc** [comment]
csv用其它编辑器打开也是乱码吗？

**Comment by wdq233** [comment]
刚试了下，用其他编辑器打开正常。那这个问题就关了吧。
