### ISSUE TITLE
Cookie 获取方式失效

### ISSUE THREAD

**Issue by x13-caesar** [dataabc/weiboSpider#253]
原本通过 https://passport.weibo.cn/signin/login 登陆的方法已经失效，不管登陆什么账户都会报错「url格式错误」：
![image](https://user-images.githubusercontent.com/26029733/98505374-03567a00-2227-11eb-8208-db2664c4aba1.png)

直接通过 https://m.weibo.cn 登陆所获取的 cookie 事实上是无效的，用户自己的 cookie 并不能用来爬取仅自己可见的内容。

**Comment by dataabc** [comment]
感谢反馈。

我用上面的链接登录，会让验证手机，没出现url格式错误，不知道是不是账号不同显示也不同。可以先使用[免cookie版](https://github.com/dataabc/weibo-crawler)，这个版本我找个时间修复下。

再次感谢反馈，如果还有问题欢迎继续讨论

**Comment by modun** [comment]
同样遇到过「url格式错误」，通过手机验证码后抓到的cookie，程序提示cookie过期，转而用的免cookie版。

**Comment by dataabc** [comment]
@x13-caesar @modun 

现在应该可以了。只要在登录微博的情况下，在<weibo.cn>页可以通过：鼠标右键检查->Network，在Name列中找到<weibo.cn>，点击，就能在Request Headers找到Cookie。

**Comment by x13-caesar** [comment]
> @x13-caesar @modun
> 
> 现在应该可以了。只要在登录微博的情况下，在<weibo.cn>页可以通过：鼠标右键检查->Network，在Name列中找到<weibo.cn>，点击，就能在Request Headers找到Cookie。

感谢及时优化。提交 issue 之后我也在别人的设备上试了一次，并未复现同样的报错，一切顺利。看来也可能是本地设备设置的问题。

**Comment by walter211** [comment]
只能用weibo.cn不能用pc版的weibo.com吗？

**Comment by dataabc** [comment]
@walter211 

你指的是cookie吗？最好用weibo.cn版的cookie，因为本就是根据weibo.cn开发的。也可以尝试weibo.com的，如果报cookie无效，就用weibo.cn的。
