### ISSUE TITLE
爬取100多页以后自动停止爬取显示progress

### ISSUE THREAD

**Issue by ShadowKingLKJ** [dataabc/weiboSpider#254]
想问一下为什么爬取100多页以后就不会继续爬了 ，后面页面只显示progress进度。

**Comment by dataabc** [comment]
感谢反馈。

是100多页后程序停止了，还是虽没有停止，progress一直更新动，但没有像之前100页一样显示微博？

**Comment by ShadowKingLKJ** [comment]
是一直更新 但是没有显示微博，爬取不到内容了

**Comment by dataabc** [comment]
感谢反馈。

可能是这个账号本来就100多页后就没有微博，只是空页。程序模仿的是微博的移动版，如果网页是空，程序也无法获取内容。log文件中有每条微博的地址，在微博页点击用户昵称，会跳转到用户微博列表。按照上面的描述，100多页之后应该是空的。这可能是微博限制或用户设置的，如果是这样，程序也无法获得更多微博。

如果还有问题，欢迎继续讨论

**Comment by Sniper970119** [comment]
并不是只有100多页，重新运行（更新end_time）之后就可以继续运行，举个例子，某人在2019-01-01~2019-12-31中间有10w个微博，从12-31日开始爬，爬到150页左右，假如到了12-01号，他就会不爬取微博，只是继续显示progress进度，当你停止程序，把时间范围更新到2019-01-01~2019-12-01，就可以继续爬取150页左右的微博了

> 
> 
> 感谢反馈。
> 
> 可能是这个账号本来就100多页后就没有微博，只是空页。程序模仿的是微博的移动版，如果网页是空，程序也无法获取内容。log文件中有每条微博的地址，在微博页点击用户昵称，会跳转到用户微博列表。按照上面的描述，100多页之后应该是空的。这可能是微博限制或用户设置的，如果是这样，程序也无法获得更多微博。
> 
> 如果还有问题，欢迎继续讨论

**Comment by Sniper970119** [comment]
> 
> 
> 感谢反馈。
> 
> 可能是这个账号本来就100多页后就没有微博，只是空页。程序模仿的是微博的移动版，如果网页是空，程序也无法获取内容。log文件中有每条微博的地址，在微博页点击用户昵称，会跳转到用户微博列表。按照上面的描述，100多页之后应该是空的。这可能是微博限制或用户设置的，如果是这样，程序也无法获得更多微博。
> 
> 如果还有问题，欢迎继续讨论

并不是只有100多页，重新运行（更新end_time）之后就可以继续运行，举个例子，某人在2019-01-01到2019-12-31中间有10w个微博，从12-31日开始爬，爬到150页左右，假如到了12-01号，他就会不爬取微博，只是继续显示progress进度，当你停止程序，把时间范围更新到2019-01-01到2019-12-01，就可以继续爬取150页左右的微博了

**Comment by Sniper970119** [comment]
![图片](https://user-images.githubusercontent.com/30463691/104114299-d9f8be00-533d-11eb-8274-ff7f44fabcc0.png)

**Comment by Sniper970119** [comment]
![图片](https://user-images.githubusercontent.com/30463691/104114302-e250f900-533d-11eb-983d-8831752f3dd7.png)

**Comment by Sniper970119** [comment]
刚开始我以为是被ban了，发现不是，每次都会在150页±10页的范围出错，拉高sleep值也不行，感觉是程序逻辑bug或者新浪那边的限制，我之前自己写的m.weibo.com的接口（就是你们无接口版用的那个），即使是正版的网页，也会有下拉到头的情况，但是微博并没有到头，只是不再进行更新，如果把最后一个接口的since_id重新拼接还是好用，只不过前端不再更新了，不知道是什么骚操作

**Comment by dataabc** [comment]
@Sniper970119 

感谢反馈。当end_date为日期时，程序使用的是一个不稳定的接口，如果微博量很多就可能出错，会有很多空页，这是难以避免的。end_date为now是稳定的，你可以使用它，手动指定要爬的日期所在页数为起始页，具体修改spider.py的get_weibo_info方法，
```
    def get_weibo_info(self):
                ...
                for page in tqdm(range(1, page_num + 1), desc='Progress'):
               ...
```
range的第一个数就是起始页。

**Comment by Sniper970119** [comment]
> 
> 
> @Sniper970119
> 
> 感谢反馈。当end_date为日期时，程序使用的是一个不稳定的接口，如果微博量很多就可能出错，会有很多空页，这是难以避免的。end_date为“now”是稳定的，你可以使用它，手动指定要爬的日期所在页数为起始页，具体修改spider.py的get_weibo_info方法，
> 
> ```
>     def get_weibo_info(self):
>                 ...
>                 for page in tqdm(range(1, page_num + 1), desc='Progress'):
>                ...
> ```
> 
> range的第一个数就是起始页。

好的，感谢分享~
