### ISSUE TITLE
单个用户微博信息没有爬取完毕

### ISSUE THREAD

**Issue by DylanDenali** [dataabc/weiboSpider#255]
程序报错（'NoneType' object）自动终止的时候，其实单个用户微博信息是没有爬取完毕的（比如这个用户的微博是从2013年-2020年，程序爬到2017年的就停止了，那2017年以前的微博就没有拿到），但下一次运行的时候也没有接着爬这个用户上次没爬完的继续爬。

**Comment by dataabc** [comment]
感谢反馈。

这是因为爬虫账号被限制了，限制一般过一段时间后自动解除。可以按照[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)2中的做法降低速度。

如果还有问题欢迎继续讨论
