### ISSUE TITLE
运行python3 -m weibo_spider不会生成config.json

### ISSUE THREAD

**Issue by Raider-Ti** [dataabc/weiboSpider#259]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github版本

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：否

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：我的系统window10

**Comment by dataabc** [comment]
程序是在第一次运行时在命令行目录生成config.json，如果目录下有config.json是不会生成的。如果在weiboSpider文件夹下运行，就在该目录下生成，是不是命令行目录不是当前目录？

**Comment by Raider-Ti** [comment]
![image](https://user-images.githubusercontent.com/70249174/100535258-3c946f80-3252-11eb-9b4d-5d8a0c19c633.png)

**Comment by Raider-Ti** [comment]
这是我运行完 python3 -m weibo_spider后的截图，目录也在weiboSpider下 我python版本是
![image](https://user-images.githubusercontent.com/70249174/100535293-8f6e2700-3252-11eb-8a1c-f11b8a2dcb42.png)
暂时不知道哪里出了问题，

**Comment by dataabc** [comment]
如果你本机只有python3，可以运行python -m weibo_spider

**Comment by Raider-Ti** [comment]
Windows系统需要修改一些配置文件吗？
还是没有出现json文件
![image](https://user-images.githubusercontent.com/70249174/100535757-b0d11200-3256-11eb-8067-2ee8d56f985f.png)

**Comment by Raider-Ti** [comment]
![image](https://user-images.githubusercontent.com/70249174/100535780-e5dd6480-3256-11eb-8396-18ffcc23575e.png)

**Comment by dataabc** [comment]
直接运行weibo_spider下的__main__.py有反应吗？

**Comment by Raider-Ti** [comment]
是我Python其他环境没有配置好，我下了anaconda，然后可以了

**Comment by Raider-Ti** [comment]
感谢回答~
