### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Evphoria** [dataabc/weiboSpider#26]
运行weiboSpider.py的时候出现了：

> File "<ipython-input-25-3b0f195b07e6>", line 42
>     print u"用户名: " + self.username
>                  ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print u"用户名: " + self.username)?

这样的bug，请问要怎么解决？

**Comment by dataabc** [comment]
这不是bug, 因为print "xxx"是需要在python 2下运行的，如果想要在python 3下运行，改成print("xxx")的形式即可
