### ISSUE TITLE
建议在配置文件中允许用户设定以ID或以昵称为文件名

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#260]
- 问：请说明需要什么新功能。<br>
答：建议在配置文件中允许用户设定以ID或以昵称为文件名

- 问：请说明添加该功能的意义。（非必填）<br>
答：因昵称在微博是允许修改的，结果导致后续整理起来有点麻烦，尤其当爬的id多了以后

**Comment by dataabc** [comment]
感谢建议。

很有道理，最近会实现这个功能，因为文件名已经是id形式了，所以这个设置只会影响文件夹。

再次感谢，如果还有建议欢迎继续讨论。

**Comment by gudaocode** [comment]
多谢！！

**Comment by dataabc** [comment]
已经添加了。

在config.json配置result_dir_name，值为0表示以昵称为目录名，值为1表示以id为目录名。
