### ISSUE TITLE
是否考虑只爬图片的爬虫版本（其他思路）

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#261]
- 问：请说明需要什么新功能。<br>
答：
最近试用了一个Chrome插件，Octo微博相册批量下载（https://chrome.google.com/webstore/detail/octo%E5%BE%AE%E5%8D%9A%E7%9B%B8%E5%86%8C%E6%89%B9%E9%87%8F%E4%B8%8B%E8%BD%BD/cdimdlckbkfelaogjhfbkjcfncbpngkn）
不知道使用的是什么原理，但是对于单纯爬取微博图片来说，好像是直接获取了图片地址，然后就下载了

- 问：请说明添加该功能的意义。（非必填）<br>
答：
1、相信某些人和我一样，只爬取图片，而不关注其他内容
2、感觉这个方式，如果只爬取图片的话，好像效率高一些
3、至少在用Chrome使用这个插件时，我同时开了5个并发，没有出现被ban的情况，或许也可以解决经常被ban的问题。

**Comment by dataabc** [comment]
感谢建议。

这个目前不打算做，因为我想到的方法是直接获取相册，这样好像只能获取图片，而获取不到它们与微博的关系，可能这对很多使用者不重要，但是也不能直接确定它们之间的关系，到底哪种和那张是一组，这些不是重点，应该可以解决。重点是已经有上面的插件做了，没有必要再做，还有现在没有太多心力做，也许有空了会做，一切都不好说，所以我也不敢打保票，希望理解。

这其实是很好的建议，只是现在还有很多事情要做，开发这个要比一般的添加功能的建议要费时，先把手头的弄完吧。再次感谢，如果还有建议或问题欢迎继续讨论

**Comment by gudaocode** [comment]
完全理解，多谢回复！
