### ISSUE TITLE
请问下如何发送消息给用户呢？

### ISSUE THREAD

**Issue by charujing** [dataabc/weiboSpider#263]
想发消息给特定的用户ID，这个怎么写呢？谢谢

**Comment by dataabc** [comment]
这个我也没写过，帮不上忙，抱歉。

**Comment by charujing** [comment]
> 这个我也没写过，帮不上忙，抱歉。

谢谢您的回复。您写的这个项目爬取特别快，我们如果要大量爬取上万用户的时候，是不是得注意限速吧？

**Comment by dataabc** [comment]
是的。

按照[程序设置](https://github.com/dataabc/weiboSpider/blob/master/docs/settings.md)，设置random_wait_pages、random_wait_seconds和global_wait，就能限速了。

**Comment by charujing** [comment]
谢谢
