### ISSUE TITLE
咨询一个网络连接或爬虫关闭的问题

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#264]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：最新版本

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
由于爬取过程中会出现被Ban的情况，且尝试n多次调整Sleep时长后，都没法保证每次都能爬取完全，所以尝试了另外一种思路。
用py简单写了点东西，运行时把list文件按照50个为单位拆分，然后每次爬完这50个，就开始执行其他任务，这段时间是不需要本爬虫工作的，理论上，这样应该就相当于爬取50个id后就Sleep了一段时间。
但是在实际使用过程中发现（大概3次都出现类似情况），比如有5组50个，一般第一、二组会全部爬取成功，但是到了第三、四组就可能出现第4、5个（50个中的前面数第4、5个）出现被ban的情况，然后当然本组就都over了。然后运行其他东西，再次继续下一组时，大多就没问题了。
由于我说的这些包括运行本爬虫，也包括其他任务，都在通过一个py文件中，用一个控制台连续运行（本爬虫使用的os.system('python -m weibo_spider --config_path=****命令运行的），这种现象是否说明：每次我在运行其他任务时，本爬虫并没有真正关闭？或者是本爬虫的网络连接并没有真正关闭？
如果是的话，该如何关闭？谢谢！

**Comment by gudaocode** [comment]
或者python有没有什么方法可以直接把所以py已经建立的网络连接都杀掉？（上网查了好半天，也没找到解决办法）

**Comment by dataabc** [comment]
可以参考[Python-Requests close http connection](https://stackoverflow.com/questions/10115126/python-requests-close-http-connection)
