### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by DylanDenali** [dataabc/weiboSpider#272]
想问下comment_parser.py 中
def get_long_weibo(self):
        """获取长原创微博"""
        try:
            for i in range(5):
                self.selector = handle_html(self.cookie, self.url)
                if self.selector is not None:
                    info = self.selector.xpath("//div[@class='c']")[1]
这部分代码try后面为什么要for i in range(5)循环5遍呢？

**Comment by dataabc** [comment]
因为有时候会获取失败，所以如果失败会等待几秒后重新获取，以提高获取成功率。

如果还有问题，欢迎继续讨论。

**Comment by pythonpythonxyj** [comment]
那已经请求成功的岂不是还会经历多次循环？

**Comment by songzy12** [comment]
请求成功的情况会在这里直接返回：

https://github.com/dataabc/weiboSpider/blob/c2e4bf18816e8d37d64ffcc98f798b999e84200e/weibo_spider/parser/comment_parser.py#L28-L29

**Comment by pythonpythonxyj** [comment]
OK，明白了，非常感谢😊
