### ISSUE TITLE
页面获取bug

### ISSUE THREAD

**Issue by DylanDenali** [dataabc/weiboSpider#273]
运行过程中发现一个问题：有的用户只爬了ta一部分页面，还有一些页面没有爬完。但是程序直接跳到下一个用户了。比如一个用户一共有30页微博，但是程序只爬了10页，而且没有任何报错。

**Comment by dataabc** [comment]
感谢反馈。

可能是since_date造成的。如果使用满足since_date，即新微博的发布时间早于since_date且非置顶微博，程序会结束当前用户，因为后面的微博发布时间也早于since_dae。另外，如果使用user_id_list.txt输入id，会自动更新since_date达到增量爬取的目的，程序会优先使用use_id_list.txt的since_date。出现上面的情况是因为：
1.config的since_date满足停止条件；
2.然后不满足1，但使用了user_id_list.txt，且user_id_list.txt中的since_date满足条件。

如果还有问题，欢迎继续讨论。

**Comment by pythonpythonxyj** [comment]
我这边的原因好像是爬取过程中遇到某一页没有一条微博，但是后面的页面是有的。spider.py中的
                    if weibos:
                        yield weibos
                    else:
                        return weibos
所以当遇到空白的页面程序就结束了，继续爬其他用户去了。

**Comment by dataabc** [comment]
这个问题之前已经解决了，你现在使用的应该不是新版本，更新到最新版本就可以了。
