### ISSUE TITLE
只爬取用户信息?无法配置

### ISSUE THREAD

**Issue by bbkali** [dataabc/weiboSpider#274]
在配置文件中无法配置

**Comment by dataabc** [comment]
将config.json的since_date设置成未来的时间或负数就行，如：
```
since_date: -1,
```
程序会跳过微博爬取。

如果还有问题，欢迎继续讨论。

**Comment by bbkali** [comment]
建议用户信息支持批量爬取，同时增加用户简介、教育、日期等字段且用户信息可单独解析为用户json格式

**Comment by dataabc** [comment]
现在txt、csv等是按用户分别保存的，数据库是保存在一起的。你说的批量是不是让用户信息统一保存在一个文件里？目前[免cookie版](https://github.com/dataabc/weibo-crawler)是可以这样做的，支持csv形式。本程序保存数据库类型也是这么做的，是否支持csv、json还没想好。
