### ISSUE TITLE
PyCharm中如何运行该项目？

### ISSUE THREAD

**Issue by swordcarefree** [dataabc/weiboSpider#275]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：按照说明中的运行方式，运行无反应。想问下，如果在PyCharm 中执行的话，该怎么执行呢？

**Comment by dataabc** [comment]
感谢反馈。

直接运行__main__.py就行，或者在Terminal运行python3 -m weibo_spider。

如果还有问题欢迎继续讨论。

**Comment by swordcarefree** [comment]
好的，谢谢~

**Comment by Alfrednio** [comment]
我也是同样的问题，在朋友charm的terminal上运行 python3 -m weibo_spider 。 显示'python3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by Alfrednio** [comment]
不是在pycharm 的terminal上运行 python3 -m weibo_spider ,而是找到__main__.py，运行__main__.py，可以执行，怎么执行的问题解决了，但是在pycharm 的terminal上运行 python3 -m weibo_spider ,不能运行还是不知道是什么原因。

**Comment by dataabc** [comment]
@Alfrednio 
感谢反馈，可以参考下[完美解决pycharm工具的terminal 不识别python命令问题解决](https://blog.csdn.net/weixin_46417755/article/details/104753217)。

**Comment by specman333** [comment]
我在Pycharm里直接运行__main__.py，程序可以跑起来，不过我想通过debug模式观察一些内部结果，我在spider.py, page_parser.py里设置了断点，然后Pycharm里 Debug '__main__'，然而程序并不会在断点停下来，请问这是为什么？ 怎样在Pycharm debug运行这个程序？谢谢

**Comment by dataabc** [comment]
@specman333 
你可以参考[How to debug a Python package in PyCharm](https://stackoverflow.com/questions/37944296/how-to-debug-a-python-package-in-pycharm)。

**Comment by specman333** [comment]
抱歉，我比较菜，看了半天也没弄明白。 我的pycharm直接运行是可以进入debug模式的，但是您的这个程序直接运行会报ImportError: attempted relative import with no known parent package。只能通过运行__main__.py的方式跑，我看了__main__.py里的代码是：
from absl import app
app.run(main)

我不知道pycharm现在不进入断点是不是absl模块的关系，我也没弄清楚pycharm如何配置 run and debug configuration，既让您的爬虫程序跑起来，又能进入spider.py, page_parser.py的断点

**Comment by dataabc** [comment]
@specman333 
我自己用的不是pycharm，上面的链接是根据你的问题搜到的。上面的报错“ImportError: attempted relative import with no known parent package”是Import导入的问题，本程序是模块，它的路径和普通py文件的路径不同。如果是这个错误，你可以修改import本地文件的路径，如换成相对路径或绝对路径。

**Comment by specman333** [comment]
抱歉，是我搞错了，pycharm设置断点是没问题的，谢谢指教
