### ISSUE TITLE
end_date设置

### ISSUE THREAD

**Issue by DylanDenali** [dataabc/weiboSpider#276]
设置了end_date为2014-09-12，但是还是从最近的一条微博往前爬呢？

**Comment by dataabc** [comment]
感谢反馈。

id是否是通过user_id_list.txt输入的呢？如果是，程序使用的是user_id_list.txt的since_date。每次爬完，since_date都会更新成爬取的时间。这样，since_date会比end_date还晚，筛选条件就不合逻辑了。可能会让程序忽略end_date，爬取全部微博，故而出现上面的问题。

如果还有问题欢迎继续讨论。

**Comment by Lemanxiaoyu** [comment]
您好，我设置了since_date是2020-01-01，end_date为2020-01-05，爬取的微博id是    "user_id_list": ["2656274875","2024623547","2210168325"]添加，发现程序一开始确实从2020-01-05开始爬，但是爬到2020-01-01的时候会继续从最近的一天开始爬，并不会执行下一个userid的爬取

**Comment by dataabc** [comment]
@Lemanxiaoyu 

出现空页是因为当end_date非now时，有时候结果会不稳定；end_date为now时是稳定的，但是不能获取时间段。如果想稳定且获取时间段，可以手动指定微博的其实页。当end_date为now时，程序默认从第一页开始爬，可以把起始页手动设为2020-01-05微博的页面，具体修改spider.py的get_weibo_info方法
```
                ...
                for page in tqdm(range(1, page_num + 1), desc='Progress'):
                ...
```
把第一个1改成发布日期在2020-01-05的微博所在的页面。

程序是按user_id_list顺序爬的，没有重新开始，上面第一个爬的是央视文艺(2210168325)，第二个是央视一套(2024623547)。

如果还有问题，欢迎继续讨论。

**Comment by Qiegao1994** [comment]
> @Lemanxiaoyu
> 
> 出现空页是因为当end_date非now时，有时候结果会不稳定；end_date为now时是稳定的，但是不能获取时间段。如果想稳定且获取时间段，可以手动指定微博的其实页。当end_date为now时，程序默认从第一页开始爬，可以把起始页手动设为2020-01-05微博的页面，具体修改spider.py的get_weibo_info方法
> 
> ```
>                 ...
>                 for page in tqdm(range(1, page_num + 1), desc='Progress'):
>                 ...
> ```
> 
> 把第一个1改成发布日期在2020-01-05的微博所在的页面。
> 
> 程序是按user_id_list顺序爬的，没有重新开始，上面第一个爬的是央视文艺(2210168325)，第二个是央视一套(2024623547)。
> 
> 如果还有问题，欢迎继续讨论。

您好~感谢代码分享。
我也遇到了同样的问题：end_data为非now时，程序在抓取指定时间段后会继续运行，不停止。测试时间：2020年12月21日。
举例：如果设置"since_date": "2020-12-20", "end_date": "now", 其实就是爬了20号和21号两天的微博，爬完后顺利结束程序。
但是如果设置"since_date": "2020-12-20", "end_date": "2020-12-21", 同样也是20号，21号两天，爬完后无法停止，程序会继续爬取用户微博，但是并不会写入csv。

您在这里提供的解决方法：“手动指定微博的起始页”挺好，但是在实际操作中有点麻烦，比如说，需要爬取100个微博账号，那就得自己找到100个账号的起始页，并且手动设置起始页码。。。感觉比较低效。

请问：这个end_date还有别的解决方法吗？ 

期待您的解答~

**Comment by dataabc** [comment]
@Qiegao1994 
对于微博较少的账号，非now的end_date还是可行，多了就可能出问题。有个想法，不知道是否可行：只获取100个账号的信息，不爬微博（since_date设置为-1就行）；根据微博数排序100个账号；对微博数大于某个值的账号手动设置起始页，其它的微博较少的使用end_date设置。其实就是根据微博数分成两部分，多的手动，少的end_date。不过如果大部分微博数都很多，这样做效率就不行了。

**Comment by Qiegao1994** [comment]
> @Qiegao1994
> 对于微博较少的账号，非now的end_date还是可行，多了就可能出问题。有个想法，不知道是否可行：只获取100个账号的信息，不爬微博（since_date设置为-1就行）；根据微博数排序100个账号；对微博数大于某个值的账号手动设置起始页，其它的微博较少的使用end_date设置。其实就是根据微博数分成两部分，多的手动，少的end_date。不过如果大部分微博数都很多，这样做效率就不行了。

感谢快速回复！懂了~希望之后这个项目可以改进end_date这个点，因为指定时间段爬虫确实蛮重要的O(∩_∩)O比如只需要爬取某个账号2019年的微博，使用“now”就会多爬2020年一整年的微博，效率会低很多~Anyway,再次感谢！

**Comment by Qiegao1994** [comment]
> @Qiegao1994
> 对于微博较少的账号，非now的end_date还是可行，多了就可能出问题。有个想法，不知道是否可行：只获取100个账号的信息，不爬微博（since_date设置为-1就行）；根据微博数排序100个账号；对微博数大于某个值的账号手动设置起始页，其它的微博较少的使用end_date设置。其实就是根据微博数分成两部分，多的手动，少的end_date。不过如果大部分微博数都很多，这样做效率就不行了。

**感谢快速回复！懂了希望之后这个项目可以改进end_date这个点，因为指定时间段爬虫确实蛮重要的O(∩_∩)O比如只需要爬取某个账号2019年的微博，使用“now”就会多爬2020年一整年的微博，效率会低很多Anyway,再次感谢！**

**Comment by dataabc** [comment]
@Qiegao1994 

感谢建议。如果有可能，会继续改进end_date的。

**Comment by dataabc** [comment]
@lrq315 
就是这样修改，不知道是不是其它地方有问题，比如修改了别的代码。

**Comment by lrq315** [comment]
> @lrq315
> 就是这样修改，不知道是不是其它地方有问题，比如修改了别的代码。

感谢大佬，已经运行成功。
然而过程也比较奇葩，与代码本身无关，估计大家都不会碰到我这种情况，但是想着万一有人碰到还是说一下吧：就是我重新下载了源代码，然后还是老样子，更奇怪的是我后来干脆把spider.py整个文件都删除了，仍然照爬不误，所以推测我运行的就不是这个spider.py（cmd进入桌面的这个文件夹）
然后就搜索电脑上的其他spider.py一个个测试，最后发现“C:\ProgramData\Anaconda3\Lib\site-packages\weibo_spider”文件中的spider.py才是我每次运行的，然而之前在桌面测试的时候用的config是桌面。
总结一下就是运行的config和spider.py不处于同一个文件，具体哪一个config看从哪里进入，而spider.py则一直是anaconda文件夹中的。
废话好多哈哈哈，希望说清楚点，也希望没人遇到这种奇葩事。如果有大佬能解释一下就更好了哈哈哈

**Comment by dataabc** [comment]
@lrq315 
感谢反馈。应该之前你安装过pypi版，程序默认使用的这个，所以源码改动才不起作用的。

**Comment by smurfs9** [comment]
我这里出现的问题比较奇怪，since_date为2017-11-20，然后end_date为2018-03-19，最后爬取到的不是2018-03-19当天的所有页面，只有部分页面，只爬取到从2018-03-19 11：59到2017-11-20间的微博，前面的2018-03-19 23:30的其他微博没有爬取到！

**Comment by dataabc** [comment]
@smurfs9
 
可能是因为接口不稳定的缘故，当end_date不是now时，有时候会漏爬一些内容。

**Comment by smurfs9** [comment]
> @smurfs9
> 
> 可能是因为接口不稳定的缘故，当end_date不是now时，有时候会漏爬一些内容。

确实是，一页中时不时都会漏几条微博的，不知道是什么问题，直接访问那个链接，看到是完整很多条微博的，但是程序爬取下来就会漏😂😂😂而已又没有报错🤣🤣

**Comment by schaepher** [comment]
可以用代码通过用二分法快速找到 end_date 所在页码，然后将其设置为起始页码。
