### ISSUE TITLE
从mongodb到csv表情包乱码

### ISSUE THREAD

**Issue by AprilWang711** [dataabc/weiboSpider#277]
我把数据先放进了Mongodb数据库中，然后导出到csv文件中，可是表情包出现乱码，该怎么处理？

# 连接mongodb数据库
client = pymongo.MongoClient("localhost")
# 连接数据库
db = client["weiboSampleThousand"]
# 数据表
table = db["test"]
# 将mongodb中的数据读出
print(type(table.find().limit(1)))
data = pd.DataFrame(list(table.find().limit(20000000)))
print(data)
# 保存为txt格式
# data["_id"].to_csv('output_mongo_list.txt', encoding='utf-8', header=True, index=False)
data.to_csv('test1.csv', encoding='utf-8', index=False)
# 读取txt数据
df = pd.read_csv('test1', low_memory=False, index_col=0)
# 查看数据大小(行列)
print(data.shape)
# 找出所有满足字段的行
for line in fileinput.input("test1", inplace=1):
    if not fileinput.isfirstline():
        print(line.replace('\n', ''))

**Comment by dataabc** [comment]
这个我也不清楚，可能表情包比较特殊吧。直接保存成csv格式不满足吗？如果现有csv不满足，可以修改spider.py和csv_writer.py，改成满意的形式。
