### ISSUE TITLE
可以添加对微博评论的爬取吗，谢谢！

### ISSUE THREAD

**Issue by beichen1994** [dataabc/weiboSpider#278]
- 问：请说明需要什么新功能。<br>
答：对微博评论的爬取

- 问：请说明添加该功能的意义。（非必填）<br>
答：用户对微博的评论分析也很有意义

**Comment by dataabc** [comment]
感谢建议。

暂时不会添加，因为：
1.评论获取不全，对于有上百万评论的微博，只能获取一部分；
2.速度会降低到原来的1/11左右。

如果还有建议，欢迎继续讨论。
