### ISSUE TITLE
页面数据缺失

### ISSUE THREAD

**Issue by DylanDenali** [dataabc/weiboSpider#279]
我在weibo.cn中查看一个人的全部微博，显示ta一共有1000页微博，微博总数是10000条，但有的页面却一条微博都没有，就是又的微博数据缺失了，但是，我去weibo.com这个站点查看的时候又显示全部页面都是有微博的，也就是没有微博数据缺失。这是什么原因呢？

**Comment by dataabc** [comment]
这个我也不清楚，可能是限制不同吧。
