### ISSUE TITLE
m.weibo.cn chrome无法获取cookies

### ISSUE THREAD

**Issue by luox2** [dataabc/weiboSpider#28]
访问m.weibo.cn，查看chrome保存数据，显示provisional headers are shown。
通过访问weibo.cn，可以获得cookies。

**Comment by xnzmc** [comment]
一个取巧的办法是使用这个库 [fuck-login](https://github.com/xchaoinfo/fuck-login)。  
可以直接在脚本中写入账号密码，然后会自动获取cookie。  

但是劣处是现在weibo.cn对于登陆管理很严，如果异地登陆或者是很久没用的账号都会提示输入验证码。详见该库的具体说明~

**Comment by dataabc** [comment]
我按照README可以正确获取cookies，你的chrome显示provisional headers are shown，可能是插件所致。
