### ISSUE TITLE
报错[Errno 1]

### ISSUE THREAD

**Issue by Lemanxiaoyu** [dataabc/weiboSpider#281]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：

- 问：您使用的是否是最新的程序（是/否）？<br>
答：

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：

**Comment by dataabc** [comment]
感谢反馈。

能否说明报错详情？问的太简单，我不知道是什么错。添加描述，可以帮助定位错误。
