### ISSUE TITLE
建议可以添加微博评论数据的爬取

### ISSUE THREAD

**Issue by zjyzh** [dataabc/weiboSpider#282]
- 问：请说明需要什么新功能。<br>
答：增加微博评论数据爬取

- 问：请说明添加该功能的意义。（非必填）<br>
答：如果能实现，万分感谢！

**Comment by dataabc** [comment]
感谢建议。

因为只能获取一部分评论，无法获取全部评论，所以暂时不添加这个功能，希望理解。

如果还有建议，欢迎继续讨论。

**Comment by walter211** [comment]
> 感谢建议。
> 
> 因为只能获取一部分评论，无法获取全部评论，所以暂时不添加这个功能，希望理解。
> 
> 如果还有建议，欢迎继续讨论。

如何获取有的那一部分呢

**Comment by dataabc** [comment]
@walter211 

以id为JogrxB09L的微博为例，它的评论页：
https://weibo.cn/comment/JogrxB09L?&page=1
，这是第一页，第二页page=2，以此类推。
编写程序获取页面信息即可。

**Comment by zjyzh** [comment]
@dataabc 为何只能获取一部分的评论，是因为cookie的问题还是什么问题，有什么具体的解决方向可以指导下吗

**Comment by dataabc** [comment]
应该是微博限制了，只显示一部分评论。这个我也没研究过，你可以网上搜搜。

**Comment by schaepher** [comment]
我测试了一下，只能获取前 50 页的评论。  

微博的评论数量太多，会分库存储。如果使用严格的分页，会消耗大量资源，而且很慢。前 50 页的评论可能是随机取的，热评的 50 页是排序后取前 50，取到数据后做了缓存。
