### ISSUE TITLE
微博没有写进csv?

### ISSUE THREAD

**Issue by AprilWang711** [dataabc/weiboSpider#283]
在使用csv的保存形式时，没有生成关于用户信息的文件，并且微博内容的csv是空的，只有列名，内容没有写进去。请问这个怎么办啊？

**Comment by dataabc** [comment]
感谢反馈。

用户信息是写入json和数据库的，不写入csv。如果想写入csv，可以使用[免cookie版](https://github.com/dataabc/weibo-crawler)，这个会把用户信息写在单独的users.csv里。
没写进去内容是不是运行是只显示进度，没有打印微博，如果是，两种可能：1.config.json的end_date是非now值，这个不太稳定，建议end_date赋值为“now”，这是稳定的；2.速度太快，被暂时限制，一般来说过一段时间限制会自动解除，降速可参考README常见问题的问题2。

如果还有问题，欢迎继续讨论。

**Comment by AprilWang711** [comment]
打印出来了，但是没有写进csv欸，太感谢您了，每次都那么及时回答

**Comment by dataabc** [comment]
奇怪了，如果打印出来就应该写进去了。不知道是不是在写入时csv被其它程序打开了，导致被占用，无法写入。有报错吗？如果方便，能否把log贴出来。

**Comment by AprilWang711** [comment]
没有任何报错，请问log是在哪个文件夹下？

**Comment by dataabc** [comment]
在weiboSpider下，形式是all.log.yyyy-mm-dd，贴出今天的就行。如果有个人信息，比如保存文件路径，可用xxx替代真实路径再贴。

**Comment by AprilWang711** [comment]
好像没有欸，这个工程是学姐发给我的，有可能被改了，图片一直上传不了，真是不好意思，麻烦您了

**Comment by dataabc** [comment]
可能是旧版本，使用最新版本应该可以写csv。
