### ISSUE TITLE
增加微博内容中视频播放数

### ISSUE THREAD

**Issue by swordcarefree** [dataabc/weiboSpider#284]
- 问：请说明需要什么新功能。<br>
答：增加微博内容中的视频被点击播放的次数

- 问：请说明添加该功能的意义。（非必填）<br>
答：知道视频播放数，能更清晰的了解此条微博对视频宣传的效果

**Comment by dataabc** [comment]
感谢建议。

页面中貌似没有播放数，暂时无法获取。如果还有建议，欢迎继续讨论。
