### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#286]
- 问：请说明需要什么新功能。<br>
答：目前，如果爬取过程中，出现了错误，比如被ban获取其他什么错误（比如我的前一条问题的情况），当然会停止爬取，但id list文件中依旧会把当前的日期放进去，这样如果没有及时查看log文件，那么，下次再爬取时就会从上次爬取的时间点开始（而不是爬取错误的微博发布时间点），进而导致中间一堆微博没有爬取到。
既然爬取过程能够读取到每个微博的内容、发布时间等内容，那么是否当前述出错情况出现时，id list文件中被写入的时间为最后一个被爬取到的微博的发布日期、时间呢？这样下次再爬取时，也不会有遗漏了。
不知道是否可行，谢谢

- 问：请说明添加该功能的意义。（非必填）<br>
答：

**Comment by dataabc** [comment]
感谢建议。

写入最后一个微博的发布时间是不行的，应该是写第一个。比如爬从现在到2019年1月1日的微博，如果都爬取成功，新since_date应该是2019的（如果2019发微博的话），下次又会重新爬一遍现在到2019的微博。但是第一个也是不行的，因为加入就前几条都是成功后几条都是失败的，用第一条更新since_date，会让程序忽略失败的那些。

所以目前我的想法是只有顺利结束时才更新since_date，值是爬第一条的时间，如果因错误中断，就不更新，下次还是会爬失败的那些，有个缺点是也会爬成功的那些，但json或数据库可以过滤重复。

**Comment by gudaocode** [comment]
我看log文件，爬取的顺序是从最早日期（第一条微博）（假设起点是比如2009年，肯定就是爬取全了），到现在（假设是到现在的话）
按照这个顺序爬，断掉的位置，意味着它前面日期的所有都爬取完毕了啊，这时候不就应该是下次从这里继续往现在爬（或者说时间顺序的往后）不就行了么？

**Comment by gudaocode** [comment]
对了，顺便确认一件事，这个爬虫是不能爬取转发图片的原图的，是这样吧？因为查看log时，发现好像能够爬取到转发的信息……

**Comment by dataabc** [comment]
已经优化user_id_list.txt更新了，只有用户没有爬取失败才更新。

你说反了，是从最新的日期往最早爬。这样不好定位，因为用户可能发新微博，页数在变，程序不知道上次出错的微博现在在第几页。

这个程序不能下载转发图片，[免cookie版](https://github.com/dataabc/weibo-crawler)可以，但是免cookie貌似一个用户最多获取200页。

**Comment by gudaocode** [comment]
1、免Cookie版好像可以获取超过200页啊，
2020-12-29 03:30:25,765 - INFO - ------------------------------已获取唐嫣粉丝团地盘(1649240191)的第2323页微博------------------------------
2020-12-29 03:30:35,914 - INFO - ------------------------------已获取唐嫣粉丝团地盘(1649240191)的第2324页微博------------------------------
我把内容显示关了，要不看有没有出错很麻烦

**Comment by gudaocode** [comment]
1、如果修改不复杂，是不是可以考虑爬取顺序从最早的时间往现在的时间爬
2、是否可以参考since day的情况，以及id list更新的日期的情况，这两个其实都是知道开始时间，然后继续往后爬取的
仅供参考啊，要是您觉得烦了，就不回答好了，^_^

**Comment by dataabc** [comment]
免cookie版过了200有显示，但是是空的。

因为很多时候新微博比旧微博有价值，所以爬取最近多少天的微博是比较好的，这样也可以实现增量爬取。
从最早的爬实现不难，就是从最后一页开始，现在没有实现这个的打算，因为会丢掉现在一些比较好的特性，使用成本会提高。

**Comment by gudaocode** [comment]
明白，多谢回复！
