### ISSUE TITLE
爬取用户信息时如何对其“标签”进行爬取

### ISSUE THREAD

**Issue by ChenYuyu1912** [dataabc/weiboSpider#287]
您好，谢谢您的分享！
但是目前对用户信息的爬取里没有关于“兴趣标签”这一栏的爬取，请问有可能通过修改代码的方式实现对这个信息的补充吗？
谢谢！

**Comment by dataabc** [comment]
你说的兴趣标签是达人吗？达人已经获取了，就是用户的标注，不知道是不是同一个东西。

**Comment by ChenYuyu1912** [comment]
好像不太一样，就是用户自己选择的一个标签，可以在主页里查看到的。类似截图这种，但是不一定是达人用户或者加V用户才有的。
![捕获](https://user-images.githubusercontent.com/23412831/103480938-97515600-4e12-11eb-969d-17642fc91d3c.JPG)

**Comment by dataabc** [comment]
修改info_parser.py，用户相关的解析在这里，还有这里没有写入，如果要写入文件，修改writer文件夹的文件就行。
