### ISSUE TITLE
为什么不支持微博视频的抓取

### ISSUE THREAD

**Issue by hebehan** [dataabc/weiboSpider#289]
- 问：请说明需要什么新功能。<br>
答：想要新增微博视频的抓取

- 问：请说明添加该功能的意义。（非必填）<br>
答：我看可以拿到微博视频的链接,理论上是可以下载的,为什么跳过了所有的微博视频?

**Comment by dataabc** [comment]
支持视频下载啊，配置video_download为1就是下载视频啊。还是说你说的微博视频和程序中的不一样或者下载失败了?
