### ISSUE TITLE
日志设置

### ISSUE THREAD

**Issue by DylanDenali** [dataabc/weiboSpider#290]
日志只是把print的内容保存了，但是像进度条这种就没有被保存到日志中呢？
可不可以把输出栏的所有结果包括进度条保存到日志中呢？

**Comment by dataabc** [comment]
这个没有研究过。程序主要在总进度(spider.py)和文件下载(downloader.py)使用了tqdm进度，你可以参考[Pass progress bar to logger
](https://github.com/tqdm/tqdm/issues/313#issuecomment-267959111)。如果还有问题，欢迎继续讨论。
