### ISSUE TITLE
info_parser.py代码获取信息的方式报错

### ISSUE THREAD

**Issue by lyjamare** [dataabc/weiboSpider#291]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。<br>
<br>

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：info_parser.py中，获取用户信息是使用xpath的方式即self.selector.xpath( "//div[@class='tip'][2]/text()")[0] == u'学习经历'

  我在本地运行时，会报错，这个xpath的配置会获取的结果是空值

  我改用`self.selector.xpath('/html/body/div[9]/a/text()')`就对了。

  我用的是python3

  想问下，是什么原因导致的，代码中的xpath结果为空。

**Comment by dataabc** [comment]
感谢反馈。

我想到的原因是可能被限制了，但是你修改代码后就没错了，怀疑是不是出bug了，但是测了几个都没问题。如果方便，能否提供出错的user_id。

**Comment by lyjamare** [comment]
> 感谢反馈。
> 
> 我想到的原因是可能被限制了，但是你修改代码后就没错了，怀疑是不是出bug了，但是测了几个都没问题。如果方便，能否提供出错的user_id。

我理解的是，info_parser.py爬取cookie对应的用户的信息吧，我是这里xpath解析出来是None。

**Comment by lyjamare** [comment]
> 感谢反馈。
> 
> 我想到的原因是可能被限制了，但是你修改代码后就没错了，怀疑是不是出bug了，但是测了几个都没问题。如果方便，能否提供出错的user_id。

原因我找到了，我是爬取自己的id的信息时，这块出错了，换成别人的id就可以了，哈哈
