### ISSUE TITLE
pycharm运行main.py时出错

### ISSUE THREAD

**Issue by jasmine-1026** [dataabc/weiboSpider#294]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：直接运行main.py报错：
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by dataabc** [comment]
感谢反馈。

你可以在console上直接运行
```
$ python3 -m weibo_spider
```

**Comment by jasmine-1026** [comment]
直接运行没有json文件出现。请问一下还有其他方法吗？



---原始郵件---
寄件人： "Chen Lei"<notifications@github.com&gt;
傳送時間： 2021年1月28日(週四) 晚上10:09
收件人： "dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送： "jasmine-1026"<351390139@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主旨： Re: [dataabc/weiboSpider] pycharm运行main.py时出错 (#294)




 
感谢反馈。
 
你可以在console上直接运行
 $ python3 -m weibo_spider

**Comment by dataabc** [comment]
可能有json，只是你没发现，一遍第一次运行会生成json，并且提示配置json。

直接用命令行工具运行python3 -m weibo_spider就可以

**Comment by jasmine-1026** [comment]
请问生成一般是在哪个文件夹下呢？我还是没有找到。
然后想顺便请教一下如果爬取用户首页的话是不是要模拟登录呀？我直接爬的时候解码会有错误而且内容和网页直接查看的不太一样。请问你们遇到过这种情况吗？



---原始郵件---
寄件人： "Chen Lei"<notifications@github.com&gt;
傳送時間： 2021年1月28日(週四) 晚上11:52
收件人： "dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送： "jasmine-1026"<351390139@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主旨： Re: [dataabc/weiboSpider] pycharm运行main.py时出错 (#294)




 
可能有json，只是你没发现，第一次运行会生成json，并且提示配置json。
 
直接用命令行工具运行python3 -m weibo_spider就可以

**Comment by dataabc** [comment]
在命令行目录下生成，如果你是在weiboSpider目录下运行的就在weiboSpider目录下生成。一般第一次运行，会显示生成位置。

是需要cookie的。和浏览器操作一样，因为浏览器浏览是需要登录的，如果你不想使用cookie，可以使用[免cookie版](https://github.com/dataabc/weibo-crawler)。

**Comment by jasmine-1026** [comment]
那如果刚运行得到的cookie放进去之后显示cookie错误或已过期，请问应该怎么解决呢？

------------------ 原始邮件 ------------------
寄件人： Chen Lei <notifications@github.com&gt;
发送时间: 2021年1月29日 13:43
收件人： dataabc/weiboSpider <weiboSpider@noreply.github.com&gt;
抄送: jasmine-1026 <351390139@qq.com&gt;, Author <author@noreply.github.com&gt;
主旨： 回覆：[dataabc/weiboSpider] pycharm运行main.py时出错 (#294)





 
在命令行目录下生成，如果你是在weiboSpider目录下运行的就在weiboSpider目录下生成。一般第一次运行，会显示生成位置。
 
是需要cookie的。和浏览器操作一样，因为浏览器浏览是需要登录的，如果你不想使用cookie，可以使用免cookie版。

**Comment by dataabc** [comment]
说明cookie是无效的，也可能修改错了json文件，应该修改config.sjon，不知道修改的是不是这个。

**Comment by jasmine-1026** [comment]
请问什么情况会导致cookie无效呢



---原始郵件---
寄件人： "Chen Lei"<notifications@github.com&gt;
傳送時間： 2021年1月29日(週五) 下午3:02
收件人： "dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送： "jasmine-1026"<351390139@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主旨： Re: [dataabc/weiboSpider] pycharm运行main.py时出错 (#294)




 
说明cookie是无效的，也可能修改错了json文件，应该修改config.sjon，不知道修改的是不是这个。

**Comment by dataabc** [comment]
就是cookie无效啊
