### ISSUE TITLE
爬取微博数较多的用户时容易出现丢失

### ISSUE THREAD

**Issue by JlSakuya** [dataabc/weiboSpider#295]
- 问：请说明需要什么新功能。<br>
答：爬取时有可能因为网络波动造成爬取错误，建议判断PageParser函数返回的weibos为空时退避一段时间后重新请求该页

**Comment by dataabc** [comment]
感谢建议。

目前有多种情况可能返回为空，比如要爬原创，某页全为转发，所以返回为空；网络原因；或者因为限制，这一页本身就返回为空。第一种好处理，后两种不好区分是网络原因还是限制，如果区分错误，可能导致程序无限循环，因此这个功能我再考虑下。

再次感谢，如果还有问题或建议欢迎继续讨论。

**Comment by JlSakuya** [comment]
在爬取过程中打印了http请求的状态码存在403，服务器端限制问题或许可以通过util.py中request返回的状态码为403来进行判断，

**Comment by dataabc** [comment]
感谢反馈。某页面出现403后，后面的页面在这次运行时可以正确获取吗，还是也出现403?

**Comment by JlSakuya** [comment]
可能会出现连续的403。目前主要出现的爬取错误为 返回403；返回200但显示“系统繁忙”或“system error!”；显示正常微博页面但提示"没有找到符合条件的微博"或没有微博内容

**Comment by dataabc** [comment]
如果少数的403可以重新获取，连续出现可能比较麻烦，我再考虑考虑，还没想好403、“系统繁忙”怎么处理。单纯的暂停似乎不能解决，因为不知道暂停多久才好。无论如何，再次感谢热心回复。

**Comment by JlSakuya** [comment]
也许可以考虑使用免费的IP代理池进行轮换请求，但可能存在Cookie泄露风险，非专业方向，建议仅供参考。

**Comment by dataabc** [comment]
不打算用代理池，因为这样速度会加快，但是容易被商用，而本程序是为个人用户写的，用来学习研究的。

增加等待时间可能会减少爬取错误。
