### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by dyj9588** [dataabc/weiboSpider#296]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：2212518065  2020-01-01

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：您好，我想要爬取2020年全年的微博，但是爬取到8月份就不行了，试了很多次，也换了几个账号，都不行，如图所示，即使显示100%，实际上是没有数据的，可以麻烦帮忙解答一下吗
![image](https://user-images.githubusercontent.com/52643868/106719197-fa662080-663c-11eb-902e-ec803538fc7c.png)

**Comment by dataabc** [comment]
感谢反馈。

是不是end_date是具体日期而不是now，当end_date为日期时，接口是不稳定的，可以改成now，不知道是不是这个问题。

**Comment by dyj9588** [comment]
您好，我修改为now后仍然只能爬取到8月3号的，不知道是什么原因呢，麻烦了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 晚上7:21
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"邓亚君"<742914780@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 运行出错 (#296)





 
感谢反馈。
 
是不是end_date是具体日期而不是now，当end_date为日期时，接口是不稳定的，可以改成now，不知道是不是这个问题。

**Comment by dataabc** [comment]
这个在网页上也只显示到8月3日，不知道是不是设置成了显示半年内的微博。
