### ISSUE TITLE
请求增加爬取微博具体时间的功能 万分感谢！！！

### ISSUE THREAD

**Issue by plxpx** [dataabc/weiboSpider#297]
- 问：请说明需要什么新功能。<br>
答：增加爬取微博具体时间的功能 精确到分钟

- 问：请说明添加该功能的意义。（非必填）<br>
答：鄙人心理学辅修 想利用微博数据研究对自我性格的认可程度 所以微博发布的具体时间有很大意义（eg 早上/晚上几点发 不同的时间反映不同的心理状态）

**Comment by dataabc** [comment]
感谢反馈。

现在程序就是微博发布时间精确到分钟的，不知道您用的时候是否出来什么问题？

**Comment by plxpx** [comment]
> 感谢反馈。
> 
> 现在程序就是微博发布时间精确到分钟的，不知道您用的时候是否出来什么问题？
十分抱歉 我看成是您最初的weibo crawler版本了！
