### ISSUE TITLE
cookie无效

### ISSUE THREAD

**Issue by ermaozi** [dataabc/weiboSpider#298]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：否

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：1576966507;2008-01-01

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：使用文档中的方法获取cookie后, 填入配置文件. 运行脚本提示:"cookie错误或已过期,请按照README中方法重新获取"

**Comment by dataabc** [comment]
感谢反馈。

应该是cookie就是无效的，或者cookie写错地方了，cookie应该写在当前命令行目录下的config.json，可能写到其它json中了。把cookie写到config.json中就可以了。

如果还有问题，欢迎继续讨论。
