### ISSUE TITLE
请问可以爬具体的粉丝followed/关注的人 following 的id列表吗？

### ISSUE THREAD

**Issue by jinzhezhang** [dataabc/weiboSpider#299]
简单看了一下关键字列表似乎不可以，有希望增加吗？

期待的功能如下：
用户A , ID 1234567890
粉丝 id_list: [2234567890]
关注 id_list: [3234567890, 4234567890]

这样子的功能

**Comment by dataabc** [comment]
感谢建议。

本程序不能实现这个，[weibo-follow](https://github.com/dataabc/weibo-follow)已经可以获取关注人的id，并写入文件，可以和本程序配合使用。

如果还有问题或建议，欢迎继续讨论。

**Comment by jinzhezhang** [comment]
谢谢你的回答！我先关掉issue，如果有后续问题再来讨论！
