### ISSUE TITLE
在问下怎么获取每一个微博评论里面的内容呢？

### ISSUE THREAD

**Issue by matakk** [dataabc/weiboSpider#30]
其实评论里面的内容也是特别重要。
有办法吗？

**Comment by dataabc** [comment]
可以获取。因为每条微博都有一个id,可以在微博列表页(如<https://weibo.cn/u/1729370543?page=2>)获取每条微博的id，还是以上述括号中的微博为例，你可以获取它的微博id，如有一个id为GwisCbyYb，这条微博的详细地址是<https://weibo.cn/comment/GwisCbyYb?uid=1729370543&page=1>，格式为<https://weibo.cn/comment/微博id?uid=用户id&page=页码>。知道了这条微博的详细的信息，就可以用xpath提取它的详细内容了

**Comment by matakk** [comment]
多谢讲解，实验一下

**Comment by Weiyangxu** [comment]
请问具体的代码和位置可以给一下吗？
