### ISSUE TITLE
爬取的用户被封禁，会报错并终止运行

### ISSUE THREAD

**Issue by iamumr** [dataabc/weiboSpider#301]
- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：GitHub

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：否（爬去所有被封禁用户会出现）

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：
1. 有些用户违规导致被微博封禁，直接访问界面会出现那个微博提示的被封禁界面直接跳转首页，很难避免爬取列表的人不被封禁，是不是可以加一个判断，直接跳过。谢谢。
2. 写入mysql数据库，如果是远程库存在访问失败，也会自动终止运行，如果能进行自动充实，三次不成果直接跳过并写入log最好了。
```
list index out of range
Traceback (most recent call last):
  File "E:\weiboSpider\weibo_spider\parser\info_parser.py", line 39, in extract_user_info
    if self.selector.xpath(
IndexError: list index out of range
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "E:\weiboSpider\weibo_spider\parser\index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
```

**Comment by dataabc** [comment]
感谢反馈。

非常有意义的建议。如果方便，能否提供封禁用户的id，方便调试，感谢。

**Comment by iamumr** [comment]
> 感谢反馈。
> 
> 非常有意义的建议。如果方便，能否提供封禁用户的id，方便调试，感谢。

谢谢，辛苦了，被封禁用户id: 7516346659

**Comment by dataabc** [comment]
感谢回复，问题已经解决了，目前数据库失败就跳过，没有添加统计失败次数超三跳过，如果想实现，修改mysql_writer.py就行。如果还有问题，欢迎继续讨论。

**Comment by iamumr** [comment]
非常感谢，谢谢辛苦劳动。
