### ISSUE TITLE
个性化定制程序方面

### ISSUE THREAD

**Issue by Summer0059** [dataabc/weiboSpider#302]
老师您们好，在可选的部分提供了一份默认的调用代码，我试了很久还是没明白该在哪里怎么输入和运行，请问各位老师有没有什么提示吗？

**Comment by dataabc** [comment]
定制现在在spider.py里
```
        config = _get_config()
        config_util.validate_config(config)
        wb = Spider(config)
        wb.start()
```
还是在config.json输入，现在因为改了逻辑，最好不用这个代码，直接在start方法里修改就行:
```
                ...
                for weibos in self.get_weibo_info():
                ...
```
在这行代码后，weibos存储的就是某页的微博，是list，你可以直接对它操作。

如果还有问题，欢迎继续讨论。

**Comment by Summer0059** [comment]
老师 那份list我已经获取了，我更想请教的是获取这些关注者们的诸如工作学习经历、性别、所在地等的信息。我可能还是没成功调用spider类，不知道该怎么做了

**Comment by dataabc** [comment]
在上面for循环之前就已经得到这些了，zaiself.user里，是当前关注者的信息。

**Comment by Summer0059** [comment]
不好意思老师，我又来打扰您了，真麻烦您。
我的问题是这样的：您第一次的回答中说，因为改了逻辑，所以，最好不用上面那几行代码了。老师我要是仍然想知道，如果使用那几行代码，该怎么做？需要在后面wb.user吗？

**Comment by dataabc** [comment]
因为现在是每开始一个用户前就会初始化，所以wb.user只是最后应该用户的不是全部。如果你想要全部，需要在init方法中定义一个list，每次获取一个就加到list里。
