### ISSUE TITLE
正文数量多，爬取丢失问题

### ISSUE THREAD

**Issue by jawi225** [dataabc/weiboSpider#303]
您好，想询问有无办法解决正文丢失问题?
-
自身观察发现在https://weibo.cn跳页时，
有时会空白页，需重新整理正文才会出现；
或在爬取时，只有爬取到9笔正文(正常一页为10笔正文)。

**Comment by jawi225** [comment]
补充:使用cookie爬取且为单一微博帐户直接修改range起始爬取页数。

**Comment by dataabc** [comment]
感谢反馈。

“整理正文”指的是重新获取吗？我不确定如果某空网页多次获取是否可以得到有效微博，如果是，可以修改page_parser.py的init方法，
修改前
```
    def __init__(self, cookie, user_config, page, filter):
        ...
        self.selector = handle_html(self.cookie, self.url)
        ...
```
修改后
```
    def __init__(self, cookie, user_config, page, filter):
        ...
        self.selector = ''
        for i in range(3):
            self.selector = handle_html(self.cookie, self.url)
            info = self.selector.xpath("//div[@class='c']")
            is_exist = info[0].xpath("div/span[@class='ctt']")
            if is_exist:
                break
        ...
```
程序会获取某网页3次，如果你想获得更高的成功率，可以把3改成其它，或者把for改成while。

再次感谢反馈，如果还有问题，欢迎继续讨论。

**Comment by jawi225** [comment]
感谢您回覆。
实测发现每一页笔数可能都不一定，
通常状况为10笔正文，但也有看到9笔，7笔（目前也只发现某几页有而已，如央视网1792、1793页），所以也无法计算总比数，查看是否有丢失状况。
不过加上您修改后的规则，应该能减少空白页丢失正文的可能，谢谢您！
