### ISSUE TITLE
图片下载速度

### ISSUE THREAD

**Issue by smurfs9** [dataabc/weiboSpider#306]
运行时，其他文字信息采集很快，但是下载图片时很慢，不知道哪里可以调一下？

**Comment by dataabc** [comment]
下载相关的位于downloader文件夹下，图片下载慢可能是因为下载的是原始图片，体积相对较大。

**Comment by smurfs9** [comment]
> 下载相关的位于downloader文件夹下，图片下载慢可能是因为下载的是原始图片，体积相对较大。

对的，程序非常好，爬取很详细，感谢开发。我主要想实现的是按照日期时间区间爬取微博正文和微博配图原图😂，并且保存路径可以截取微博正文中的某些关键字作为保存路径文件夹名称，不知道在img_downloader.py里面怎么引用微博正文内容weibo_content或者content

**Comment by dataabc** [comment]
修改img_downloader.py的handle_download方法，urls参数是图片地址，w是微博的所有信息，w.content就是微博正文,方法中的file_path就是文件的保存路径，你要做的是在w.content提取关键字，然后根据关键字修改file_path就可以。

**Comment by smurfs9** [comment]
> 修改img_downloader.py的handle_download方法，urls参数是图片地址，w是微博的所有信息，w.content就是微博正文，方法中的file_path就是文件的保存路径，你要做的是在w.content提取关键字，然后根据关键字修改file_path就可以。

感谢答疑，我去尝试一下！
