### ISSUE TITLE
不好意思打扰了，请问出现这个问题应该怎么解决呢在weiboSpider目录下运行bash $ python3 -m weibo_spider 会提示 Permission denied

### ISSUE THREAD

**Issue by RXBJT** [dataabc/weiboSpider#307]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：在weiboSpider目录下运行bash $ python3 -m weibo_spider 会提示 Permission denied

**Comment by dataabc** [comment]
感谢反馈。

是不是在运行时打开了csv文件，关闭就没错误了。

**Comment by schaepher** [comment]
如果是在 Windows 10 应用商店安装的 Python3，在 bash 里执行会出现 Permission denied 。解决办法是到 Python 官网下载安装包来安装。
