### ISSUE TITLE
爬取100页以后的内容没有下载图片

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#313]
爬取过程正常，出现的情况是，前面100页时，显示出了微博内容，此时可以正常下载图片
但是接下来显示：
2021-03-10 09:07:35,192 - spider.py - INFO - ------------------------------已获取******的第101页微博------------------------------
2021-03-10 09:07:35,731 - spider.py - INFO - ------------------------------已获取******的第102页微博------------------------------
2021-03-10 09:07:36,038 - spider.py - INFO - ------------------------------已获取******的第103页微博------------------------------
2021-03-10 09:07:46,972 - spider.py - INFO - ------------------------------已获取******的第104页微博------------------------------
2021-03-10 09:07:47,979 - spider.py - INFO - ------------------------------已获取******的第105页微博------------------------------
2021-03-10 09:07:57,613 - spider.py - INFO - ------------------------------已获取******的第106页微博------------------------------
时，相关的图片没有下载
请问，这是正常的吗？爬虫就是这样设置的？如何修改配置才能爬取全部图片？

**Comment by gudaocode** [comment]
对了，config里面设置的    "end_date": "2016-05-31"、"since_date": "2009-01-01",

**Comment by gudaocode** [comment]
另外，感觉后面出现前述样式时，也有点奇怪。
就拿我当前尝试的这个微博来说把，它的总页面数量大概时2700多，如果我把结束日期设置为now，那么获取每一页的微博是正常的。但是当我把end date设置为2016年时，按照其他讨论，爬虫应该是从这个时间起，往更早的时间爬取，而该微博的第一条大概时在2010年，即从2010年到2016年之间，微博页数不可能还是2700多页啊。而当我再次把end date修改为2012年的某个日期时，它还在获取2000多页（最后出错断掉了）的提示……

**Comment by dataabc** [comment]
当end_date为日期时，接口不稳定，经常出现空页，所以上面没有获取内容，也就没有下载图片，当值为now时是稳定的。当微博很多时可以把end_date设成now，然后修改下爬取的起始页（spider.py文件的get_weibo_info方法range的第一个数字），变相达到时间段的效果。

**Comment by gudaocode** [comment]
当一个用户的内容比较多时，我又遇到了之前遇到的那个问题，ssl的错误，而且是在爬取空页的时候出现的。
建议能否在连续出现空页的时候，直接停止继续爬取？这样一个不必因此浪费很多时间，另一方面也避免因为连续爬取而出现我之前那个和账户关联的ssl错误。

**Comment by gudaocode** [comment]
另外，看到另外一个问答里面有人提到“config.json里尝试了一下"start_page"=201，结果也爬不到内容”
这个是啥意思？在config.json里面没有找到start_page这个参数啊？填到哪里？

**Comment by dataabc** [comment]
感谢建议。

我考虑下。因为出现连续空页很容易发现，如果跳过这样使用者反而不知道漏了微博。start_page是免cookie版的，因为不填cookie最多200页，所以start_page=201没效果，加上cookie就能获取了。cookie版spider.py文件的get_weibo_info方法range的第一个数字和start_page是一样的。

**Comment by gudaocode** [comment]
> 感谢建议。
> 
> 我考虑下。因为出现连续空页很容易发现，如果跳过这样使用者反而不知道漏了微博。start_page是免cookie版的，因为不填cookie最多200页，所以start_page=201没效果，加上cookie就能获取了。cookie版spider.py文件的get_weibo_info方法range的第一个数字和start_page是一样的。

单纯站在使用者的角度上描述一下自己的感觉。
我自己是直到这次提问才知道连续出现这样的提示时，是丢失页面的含义，所以感觉大多数用户也未必知道这意味着没能正常爬取。
但由于贵爬虫可以连续爬取，这样的提示连续出现的确会比较吸引注意力。
综合到一起，比如说这样呢：
1、当出现爬取空页时，连续出现十次/页
2、当连续出现十次/页以后，有个比较明显的文字提示，出现连续空页，停止继续爬取，id list不会更新，建议把end_date设置为now一类的提示啥的，或者给个该情况说明的链接……
仅从使用者角度描述，仅供参考

**Comment by dataabc** [comment]
感谢建议。

目前的打算是当出现多次空页时，就跳过该用户，同时给出提示，继续爬其他的，这样就不会影响其他的。id list应该还是会更新，因为已经写入一部分了，而且因为接口原因，即便是非空页也可能会漏微博。同样漏微博，有的更新有的不更新也不好。

**Comment by gudaocode** [comment]
> 感谢建议。
> 
> 目前的打算是当出现多次空页时，就跳过该用户，同时给出提示，继续爬其他的，这样就不会影响其他的。id list应该还是会更新，因为已经写入一部分了，而且因为接口原因，即便是非空页也可能会漏微博。同样漏微博，有的更新有的不更新也不好。

那就等更新了 ^_^

**Comment by dataabc** [comment]
已修复空页问题。默认某页3次无法获取就跳过，不过没有给出提示，因为当end_date是日期时不稳定，很多地方都不正确，难以准确判断是否漏爬。
