### ISSUE TITLE
数据采集完成后，article_url字段没有内容

### ISSUE THREAD

**Issue by tianshanzhilong** [dataabc/weiboSpider#314]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。<br>
<br>

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：直接通过 github 命令生成的

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：目前只爬取 人民日报 这个微博用户 ，微博id：2803301701

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：

**Comment by dataabc** [comment]
感谢反馈。

article_url是头条文章的url，如果微博本身不是头条文章是没有内容的。上面说的没有内容是普通微博还是头条文章，如果是普通微博（大部分微博都是普通微博），article_url为空是正常的，如果是包含头条文章的微博（内容类似与...发布了头条文章xx）为空，能否指出具体的微博方便调试，感谢。

**Comment by tianshanzhilong** [comment]
我这边提到的是普通微博url的情况，感谢答复
后续需要普通微博url地址，自己手动处理下，谢谢了


提个建议：如果可以把普通微博url让程序完成，就更好了
让程序进行普通微博地址拼接




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 数据采集完成后，article_url字段没有内容 (#314)





 
感谢反馈。
 
article_url是头条文章的url，如果微博本身不是头条文章是没有内容的。上面说的没有内容是普通微博还是头条文章，如果是普通微博（大部分微博都是普通微博），article_url为空是正常的，如果是包含头条文章的微博（内容类似与...发布了头条文章xx）为空，能否指出具体的微博方便调试，感谢。

**Comment by dataabc** [comment]
感谢建议。

因为微博的地址就是https://weibo.cn/comment/+id，这个是微博的评论地址，点赞和转发地址也差不多。因为id就能推出url，加上url就冗余了，所以没添加。

**Comment by tianshanzhilong** [comment]
你好，可否增加微博评论数据的采集？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 数据采集完成后，article_url字段没有内容 (#314)





 
感谢建议。
 
因为微博的地址就是https://weibo.cn/comment/+id，这个是微博的评论地址，点赞和转发地址也差不多。因为id就能推出url，加上url就冗余了，所以没添加。

**Comment by dataabc** [comment]
没有爬取评论的打算，评论只能获取一部分，不全。
