### ISSUE TITLE
weiboSpider通过源码安装后，按第3步运行程序操作，程序无法启动

### ISSUE THREAD

**Issue by tianshanzhilong** [dataabc/weiboSpider#318]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。<br>
<br>

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：https://github.com/dataabc/weiboSpider
直接通过源码进行安装
$ git clone https://github.com/dataabc/weiboSpider.git
$ cd weiboSpider
$ pip install -r requirements.txt

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：
![安装结果](https://user-images.githubusercontent.com/80507525/111906001-80bdb100-8a89-11eb-9870-e688474d5d27.png)

**Comment by dataabc** [comment]
感谢反馈。

不知道是不是环境变量的问题，这个我也不确定。python运行其它程序有问题吗？如果无法解决可以使用[免cookie版](https://github.com/dataabc/weibo-crawler)。

**Comment by tianshanzhilong** [comment]
收到，我试用下免cookie版的，谢谢
python运行其它程序没有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] weiboSpider通过源码安装后，按第3步运行程序操作，程序无法启动 (#318)





 
感谢反馈。
 
不知道是不是环境变量的问题，这个我也不确定。python运行其它程序有问题吗？如果无法解决可以使用免cookie版。

**Comment by yingYYDoL** [comment]
我也遇到了一样的问题。我的方法是1.进入weibo.py所在目录 ；2.python __main__.py

**Comment by tianshanzhilong** [comment]
就是要这样进行启动python程序
