### ISSUE TITLE
对内容的判别有问题

### ISSUE THREAD

**Issue by MengyingQian** [dataabc/weiboSpider#32]
这个爬虫在爬取用户转发某条微博的微博时，会把被转发的微博判定为微博内容，而不是用户转发时写的文字内容，比如A转发一条抽奖微博并说“求中”，这里会误把抽奖微博判定为内容而丢弃了”求中“两个字

**Comment by dataabc** [comment]
感谢反馈。现在添加了获取"转发微博"转发理由、原始用户的功能。
例如，用户**A**发表了内容为"**xxxxx**"的微博，用户B在转发时添加了"**yyy**"为转发理由，则程序获取到的信息如下：
转发理由: **yyy**
原始用户: **A**
转发内容: **xxxxx**
微博位置: xxx
发布时间: yyyy-mm-dd hh:mm
点赞数: x	 转发数: x	 评论数: x
发布工具: xxx
