### ISSUE TITLE
关于爬取的微波数与实际显示的微博数差距

### ISSUE THREAD

**Issue by PANPANPAN-S** [dataabc/weiboSpider#326]
请教一个问题，在爬虫的时候已经添加了cookie，但是有个别ID的微博爬取数量跟个人主页显示的微博数量不一致，目前碰到的有这几个账号ID，
1000174321，
1653154915，
1353538765，
2000408367，
1653714227，
1829744931，
1972840517，
主要是两种情况，一种是爬取的微博数量完全为0，另一种是是爬虫一半左右的就显示爬取成功，实际上还是有很多微博的，求解决这个问题

**Comment by dataabc** [comment]
感谢反馈。

是不是since_date设置的原因，程序只会爬取发布日期在since_date之后的微博。还有，如果微博很多，且end_date为日期，也可能会出现这种情形，把end_date换成now就好了。

**Comment by PANPANPAN-S** [comment]
感谢回复~
但是我回头查了一下，之前的设置方式设置的sincedate，为2010-01-01，end_date为now，遇到的结果跟之前的描述还是一样的，大部分的ID是可以比较准确的爬取微博，少部分的这种爬取微博数与实际数量差还是蛮大的。。。
![image](https://user-images.githubusercontent.com/65796381/112829058-26dd6c80-90c3-11eb-8b8a-8cc337f544b7.png)
![image](https://user-images.githubusercontent.com/65796381/112829328-89cf0380-90c3-11eb-9c7d-7198e19aabc6.png)

**Comment by dataabc** [comment]
我在移动版访问时发现上面的微博没有展示，应该是对方设置了权限，所以获取不到。

**Comment by ylj1314** [comment]
> 我在移动版访问时发现上面的微博没有展示，应该是对方设置了权限，所以获取不到。

我也遇到了程序爬到一半左右就结束的情况，根据上面回复，去看了微博原文，确实爬虫停止页面没有数据，但是点击下页后，后面的数据是可以看到的，不知道爬虫能不能设置爬完progress的百分百进度再停止工作，

**Comment by dataabc** [comment]
@ylj1314 
把spider.py文件get_weibo_info方法的
```
                    if not to_continue:
                        break
```
注释掉就能到百分百进度了。

**Comment by ylj1314** [comment]
> @ylj1314
> 把spider.py文件get_weibo_info方法的
> 
> ```
>                     if not to_continue:
>                         break
> ```
> 
> 注释掉就能到百分百进度了。

感谢，成功了
