### ISSUE TITLE
请问能否增加把所有微博合并成带图片的电子书(单个html或多个分页html、PDF等)的功能

### ISSUE THREAD

**Issue by droppiggy** [dataabc/weiboSpider#328]
- 问：请说明需要什么新功能。<br>
答：把所有微博合并成带图片的电子书(单个html或多个分页html、PDF等)

- 问：请说明添加该功能的意义。（非必填）<br>
答：新功能，如能实现，非常感谢！

**Comment by dataabc** [comment]
感谢建议。

这个暂时不打算实现，还有一堆feature待弄，以后看情况，希望理解。

**Comment by schaepher** [comment]
https://github.com/YaoZeyuan/stablog
试试这个？
