### ISSUE TITLE
建议增加用户选择是否下载转发图片/视频的功能选项

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#329]
- 问：请说明需要什么新功能。<br>
答：
目前的爬虫支持下载转发图片啦！大赞！
希望可以像免cookie版一样，增加自行选择是否下载转发的配置选项。
另外，如果可以，是否考虑在id list中，对单个id设置是否下载转发

- 问：请说明添加该功能的意义。（非必填）<br>
答：
因为部分id希望下载转发，部分id不希望下载转发

**Comment by dataabc** [comment]
感谢建议。

是否支持转发必要性不是很大，因为爬取原创就是不下载，爬取全部就是下载。比免cookie更简单，而且如果添加是否下载转发，在获取原创时，是否转发参数 就无效了，反而可能会给部分使用者疑问，明明设置了下载转发为什么没有下载。所以免cookie版的下载控制更详细也更复杂，cookie版的更简单，这也是二者的区别。单独设置似乎也没有必要，因为只有两种情况，下载和不下载（而since_date可以有无数值），使用者可以配置两份程序，一份所有微博都下载，一份都不下载，这样应该不单独为某一微博配置要方便。这只是我个人的想法，不一定正确。

**Comment by gudaocode** [comment]
咦，之前居然没有注意到filter这个参数，汗……
谢谢！

**Comment by gudaocode** [comment]
还有个问题，是否考虑下载时，把转发和原创的图片保存在两个独立的文件夹中？两者还是有点区别的

**Comment by dataabc** [comment]
现在转发和原创的图片会存储在两个文件夹了。

**Comment by gudaocode** [comment]
> 现在转发和原创的图片会存储在两个文件夹了。

赞！感谢！
