### ISSUE TITLE
爬取到中间，代码报错，172行

### ISSUE THREAD

**Issue by Issac110** [dataabc/weiboSpider#33]
爬区用户ID：1476938315  的 第277条微博时报如下错误

===================================================================
早起来到这里观看著名景点——手机森林，看着手机杆杆上的硕果累累，感慨于国家日益强盛，伴随着国歌的响起，心中汹涌澎湃，颇感欣慰。
('Error: ', IndexError('list index out of range',))
Traceback (most recent call last):
  File ".\weiboSpider.py", line 172, in get_weibo_info
    "span[@class='ctt']/a")[-1]
IndexError: list index out of range
微博写入文件完毕，保存路径:
E:\tmp\weibospider\weibo\1476938315.txt
信息抓取完毕
===================================================================

**Comment by dataabc** [comment]
感谢反馈，已修复

**Comment by slimwang** [comment]
> 感谢反馈，已修复

修复了就把 issue 关了呀!
