### ISSUE TITLE
weibocrawler 出现的问题

### ISSUE THREAD

**Issue by ROJ1999** [dataabc/weiboSpider#330]
- 问：请说明需要什么新功能。<br>
答：这个爬虫如果不加cookie 的话有些字段无法爬取 比如用户的注册时间，生日 ，信用等等，加了cookie的话，经常403禁止访问

- 问：请说明添加该功能的意义。（非必填）<br>
答：

**Comment by dataabc** [comment]
感谢反馈。

这和速度和账号可能有关，尽量放慢速度，或者更换其它账号。
