### ISSUE TITLE
爬取用户信息不完整

### ISSUE THREAD

**Issue by hongxiujie** [dataabc/weiboSpider#331]
![image](https://user-images.githubusercontent.com/48142196/113553366-41b36200-962a-11eb-853e-ae5d16f84c0f.png)
爬取微博用户信息只有图中的几种，请问是需要改一些参数值吗

**Comment by dataabc** [comment]
感谢反馈。

使用txt保存确实是这些，数据库是全的。如果想写全，参照user.py文件在txt_writer.py的user_desc添加属性就可以了，如果还有问题，欢迎继续讨论。

**Comment by hongxiujie** [comment]
好的，感谢答疑。

**Comment by hongxiujie** [comment]
好的，感谢答疑。

**Comment by hongxiujie** [comment]
参照user.py文件在txt_writer.py的user_desc添加属性之后还需要更改mysql_config的值吗？
![image](https://user-images.githubusercontent.com/48142196/113582465-fc5b5880-965a-11eb-90bc-573cab7730f7.png)

如果需要的话请问在哪里查看自己mysql的配置

**Comment by dataabc** [comment]
mysql配置在自己服务器上看

**Comment by hongxiujie** [comment]
方便告知具体操作方法吗 或者说一下这个参数值格式是怎样的

**Comment by dataabc** [comment]
config.json的mysql_config的这些参数很多都是默认的，如果你在本地运行host就是localhost，默认使用root用户访问数据库，如果你不是，改成自己数据库的用户名密码。

**Comment by hongxiujie** [comment]
写入格式使用数据库之前需要在数据库里面去建表吗





------------------ 原始邮件 ------------------
发件人: Chen Lei ***@***.***&gt;
发送时间: 2021年4月12日 18:57
收件人: dataabc/weiboSpider ***@***.***&gt;
抄送: hongxiujie ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[dataabc/weiboSpider] 爬取用户信息不完整 (#331)





 
config.json的mysql_config的这些参数很多都是默认的，如果你在本地运行host就是localhost，默认使用root用户访问数据库，如果你不是，改成自己数据库的用户名密码。

**Comment by dataabc** [comment]
不需要

**Comment by dataabc** [comment]
不需要

**Comment by hongxiujie** [comment]
建表的语句都在sqlite_writer.py文件里面是吗





------------------ 原始邮件 ------------------
发件人: Chen Lei ***@***.***&gt;
发送时间: 2021年5月17日 21:14
收件人: dataabc/weiboSpider ***@***.***&gt;
抄送: hongxiujie ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[dataabc/weiboSpider] 爬取用户信息不完整 (#331)





 
不需要

**Comment by hongxiujie** [comment]
我用的是mysql，配置charset是utf8，设置数据库为写入文件之后，结果如图所示，但是打开数据库中的表的时候只能看到user表里面有内容，而查看weibo表的时候显示Empty set （0.00 sec），请问一下知道是咋回事吗？

------------------ 原始邮件 ------------------
发件人: Chen Lei ***@***.***&gt;
发送时间: 2021年5月17日 21:14
收件人: dataabc/weiboSpider ***@***.***&gt;
抄送: hongxiujie ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[dataabc/weiboSpider] 爬取用户信息不完整 (#331)





 
不需要

**Comment by dataabc** [comment]
都在mysql_writer.py文件里。我这里看不到图片。配置charset用默认的，Empty set可能是配置不正确，比如since_date时间过新或者晚于end_date，或者使用txt输入的id
