### ISSUE TITLE
提示Cookie过期，但是实际上并没有过期（浏览器可正常访问）

### ISSUE THREAD

**Issue by leven-space** [dataabc/weiboSpider#333]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：无

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：3911558393

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：cookie错误或已过期,请按照README中方法重新获取

**Comment by dataabc** [comment]
感谢反馈。

出现这个提示说明就是cookie过期了，可能和网页版的cookie不一致，重新获取就可以了。如果还有问题，欢迎继续讨论。

**Comment by Sword-zgz** [comment]
我也有同样的问题，获取到最新的cookie填入后提示“cookie错误或已过期,请按照README中方法重新获取”，请问怎么解决？

**Comment by dataabc** [comment]
@Sword-zgz 

应该就是cookie无效，也可以使用[免cookie版](https://github.com/dataabc/weibo-crawler)

**Comment by lin12138** [comment]
我也有同样的问题

**Comment by lin12138** [comment]
即使重复登出多次问题也还是照旧

**Comment by dataabc** [comment]
@lin12138 
如果方便，可以换个账号，或者使用[免cookie版](https://github.com/dataabc/weibo-crawler)

**Comment by chopper-go** [comment]
我刚也遇到这问题，后来检查了下，是因为我把config.json保存错了路径，一开始错放到config_sample.json同级目录，就报错。后来挪到上一级目录就正常运行了。

**Comment by dataabc** [comment]
> 我刚也遇到这问题，后来检查了下，是因为我把config.json保存错了路径，一开始错放到config_sample.json同级目录，就报错。后来挪到上一级目录就正常运行了。

感谢反馈，非常有用，感谢

**Comment by taizihuang** [comment]
用网页版weibo.com的cookie报错，但是用移动版m.weibo.cn的cookie就可以，不知道微博为什么要设计两套cookie

**Comment by Mizar6** [comment]
> 我刚也遇到这问题，后来检查了下，是因为我把config.json保存错了路径，一开始错放到config_sample.json同级目录，就报错。后来挪到上一级目录就正常运行了。

感谢。实际上好像是程序在两个地方都生成了config.json，不是我们保存错了。
