### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by hongxiujie** [dataabc/weiboSpider#334]
请问程序用了什么框架 还有功能是怎么实现的

**Comment by dataabc** [comment]
本程序用python3实现的，没有用框架。字段是解析的网页，然后根据使用者配置写入/下载文件。

**Comment by hongxiujie** [comment]
可以具体说一下程序是怎样设计的吗





------------------ 原始邮件 ------------------
发件人: Chen Lei ***@***.***&gt;
发送时间: 2021年5月14日 18:25
收件人: dataabc/weiboSpider ***@***.***&gt;
抄送: hongxiujie ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[dataabc/weiboSpider] 请教几个问题 (#334)





 
本程序用python3实现的，没有用框架。字段是解析的网页，然后根据使用者配置写入/下载文件。

**Comment by dataabc** [comment]
大部分程序在weibo_spider文件夹内，spider.py控制主要部分，downloader负责文件下载，parser负责网页解析，writer负责文件和数据库写入。你可以从spider.py阅读。

**Comment by hongxiujie** [comment]
spider里面的主要都是定义是吗



------------------ 原始邮件 ------------------
发件人: Chen Lei ***@***.***&gt;
发送时间: 2021年5月15日 18:18
收件人: dataabc/weiboSpider ***@***.***&gt;
抄送: hongxiujie ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[dataabc/weiboSpider] 请教几个问题 (#334)





 
大部分程序在weibo_spider文件夹内，spider.py控制主要部分，downloader负责文件下载，parser负责网页解析，writer负责文件和数据库写入。你可以从spider.py阅读。

**Comment by dataabc** [comment]
spider.py是主程序，它调用其它程序

**Comment by hongxiujie** [comment]
所有功能不是通过main函数中调用spider类实现的吗？然后spider又调用downloader、parser、writer这三个部分？





------------------ 原始邮件 ------------------
发件人: Chen Lei ***@***.***&gt;
发送时间: 2021年5月19日 18:31
收件人: dataabc/weiboSpider ***@***.***&gt;
抄送: hongxiujie ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[dataabc/weiboSpider] 请教几个问题 (#334)





 
spider.py是主程序，它调用其它程序

**Comment by dataabc** [comment]
是的

**Comment by hongxiujie** [comment]
数据库里面可以显示图片视频链接吗





------------------ 原始邮件 ------------------
发件人: Chen Lei ***@***.***&gt;
发送时间: 2021年5月20日 17:51
收件人: dataabc/weiboSpider ***@***.***&gt;
抄送: hongxiujie ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[dataabc/weiboSpider] 请教几个问题 (#334)





 
是的

**Comment by dataabc** [comment]
显示
