### ISSUE TITLE
是否可以考虑一下添加此功能。消息发送到钉钉或者企业微信群机器人

### ISSUE THREAD

**Issue by luolovehk** [dataabc/weiboSpider#335]
爬取的内容发送到钉钉或者企业微信机器人实现起来难度大吗？
是否可以考虑一下添加此功能。

**Comment by dataabc** [comment]
感谢建议。

这个暂时没考虑过，不清楚是否有难度，最近不会添加，感谢理解。不过如果有网友实现这个功能并提交到本程序，是非常乐意merge的。

**Comment by luolovehk** [comment]
你好，我发现下载下来的视频有点模糊，视频的爬取规则是什么判断的？
爬取的视频可以趴到1080的吗？或者是最高像素的那个视频。

**Comment by dataabc** [comment]
视频是通过网页提取的，目前最高支持到720p。

**Comment by luolovehk** [comment]
请问一下这是什么问题。

[Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/root/weiboSpider/weibo_spider/writer/csv_writer.py", line 43, in write_weibo
    writer.writerows(result_data)
OSError: [Errno 29] Illegal seek

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weiboSpider/weibo_spider/writer/csv_writer.py", line 43, in write_weibo
    writer.writerows(result_data)
PermissionError: [Errno 1] Operation not permitted
[Errno 1] Operation not permitted
OSError: [Errno 29] Illegal seek

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weiboSpider/weibo_spider/writer/txt_writer.py", line 54, in write_weibo
    f.write((weibo_header + result).encode(sys.stdout.encoding))
PermissionError: [Errno 1] Operation not permitted

**Comment by dataabc** [comment]
貌似程序没有权限写文件，是不是权限被系统限制了

**Comment by luolovehk** [comment]
[Errno 1] Operation not permitted
OSError: [Errno 29] Illegal seek

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weiboSpider/weibo_spider/writer/csv_writer.py", line 28, in __init__
    writer.writerows([[kv[0] for kv in self.result_headers]])
PermissionError: [Errno 1] Operation not permitted
[Errno 1] Operation not permitted
OSError: [Errno 29] Illegal seek     

又遇到问题了~~~~请问这是什么错误。

**Comment by luolovehk** [comment]
> 视频是通过网页提取的，目前最高支持到720p。

我发现我下载下来的视频都是852X480。没有达到720p是怎么回事呢。？

**Comment by dataabc** [comment]
可以换成<https://github.com/dataabc/weibo-crawler>，这个清晰度应该能满足

**Comment by luolovehk** [comment]
> 可以换成https://github.com/dataabc/weibo-crawler，这个清晰度应该能满足

感谢，请问爬取下来的内容储存路径可不可以自定义，需要在哪里修改？

**Comment by dataabc** [comment]
本程序支持路径自定义，通过output_dir指定，weibo-crawler暂时不支持，可以通过修改代码实现，修改get_filepath方法，file_dir就是路径，改成你想要的。

**Comment by luolovehk** [comment]
'encoding' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "weibo.py", line 1197, in main
    config = get_config()
  File "weibo.py", line 1186, in get_config
    with open(config_path, encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function


weibo-crawler 程序的保持，这是什么问题。

**Comment by dataabc** [comment]
猜测你用的是python2, python3没有问题

**Comment by luolovehk** [comment]
> 猜测你用的是python2, python3没有问题

使用 PY3报错这个，这个扩展安装过的了。

Traceback (most recent call last):
  File "weibo.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

我之前用PY2可以使用的。

**Comment by luolovehk** [comment]
是的，用了PY3成功运行了，

weibo-crawler好像只爬了146页就停下，下面还有很多内容没有继续进行下去。
