### ISSUE TITLE
能否利用Github action定时爬取，也不需要在本地安装依赖了

### ISSUE THREAD

**Issue by xlzy520** [dataabc/weiboSpider#338]
- 问：请说明需要什么新功能。<br>
答：能否利用Github action定时爬取

- 问：请说明添加该功能的意义。（非必填）<br>
答：在本地跑，既要安装依赖，还要手动执行，性能也不一定高，定时爬取也没那么方便，如果用GitHub action定时爬取的话，可以忽略平台的差异，只需要配置一些数据即可，还可以定时爬取

**Comment by xlzy520** [comment]
跑完之后，可以设置一些接口接收结果文件，或者远程数据库配置

**Comment by dataabc** [comment]
感谢建议。

这个我考虑下，不确定是否添加，再次感谢。
