### ISSUE TITLE
照片时间+内容命名，爬取的时候如何显示微博内容

### ISSUE THREAD

**Issue by lyscop** [dataabc/weiboSpider#340]
请教下， 参照前天在weibo-crawler设置的，用时间+内容命名，能正常命名和保存2021年5月21日的图片（图2）
weiboSpide出现了保存不了图片，看了下可能是换行符的原因，在img_downloader.py里面改成下面这样（图3）
如何输出爬取到20210521这条微博内容呀（图1）
https://weibo.com/u/3827955141
```
def handle_download(self, urls, w):
        """处理下载相关操作"""
        file_prefix = w.publish_time[:10].replace('-', '') + '_' + w.content.replace(':','').replace('/','').replace('|','').replace('?','').replace('<','').replace('>','').replace('"','').replace('/','').replace('*','').replace('<br>','').replace('</br>','')
        
```
![](https://i.imgur.com/TQXEcbJ.png)
![](https://i.imgur.com/PRvOVJI.png)
![](https://i.imgur.com/HBwVk9h.png)

**Comment by dataabc** [comment]
应该是还有很多特殊字符，这部分难以语料，不建议这样做。

**Comment by lyscop** [comment]
好的好的，我改回id了
