### ISSUE TITLE
爬虫爬取速度出奇地慢，不确定问题出在哪里请求帮助，谢谢！

### ISSUE THREAD

**Issue by ShulamitWu** [dataabc/weiboSpider#341]
您好，感谢你们开发了这个微博爬虫项目，帮助巨大🙏

本人为Python初学者，很多Python和编程相关知识都不甚了解，所以我想请教几个关于这个微博爬虫的小问题。

1. 我分别用weibo-crawler和weiboSpider尝试爬取新华社（user ID: 1699432410) 从2019-11-01到2020-12-30的微博内容, 但是二者爬取速度都奇慢无比：weibo-crawler爬取15天的微博（85页）花费9小时，weiboSpider甚至在仅仅爬取2020-12-30和12-29两天的内容后便停止了。我等待了几个小时爬虫都没有任何动静，目前我的csv文件中仍然只有30号和29号两天的80多条微博。截图如下：
![weiboSpider stopped](https://user-images.githubusercontent.com/73413661/119756639-6b8a4780-be69-11eb-921e-fbdc4297e10f.png)

2. 我用我的微信登录微博网页端（weibo.com）后找到的cookie对于weibo-crawler有效，但是weiboSpider却报错说该cookie错误或已过期。反而，当我用手机号注册并登陆微博网页端（weibo.cn）后找到的cookie对于weiboSpider有用。这两个通过不同账号不同网址得到的cookie效果也不同，这令我很费解，您可以帮忙解释下吗？

3. 我第一次用weibo-crawler爬取时设置的since_date为2019-11-01，但是爬虫只爬取了1958条微博，也就是新华社大约一个月的微博。随后，爬虫自动停止了。我好奇weibo-crawler是否能设置end_date？我之前设置了end_date，但是运行时报错。因此，我猜测只有weiboSpider才可以设置since_date & end_date，weibo-crawler只能设置since_date，是这样吗？如果是这样，我只想爬取2019-2020的数据，额外爬的数据有效影响效率。请问有什么办法规避这一点吗？

4. 最后一个问题：我在使用weibo-crawler爬取新华社内容时，进度条显示85/14039。根据程序的提示，85意为“已获取新华社的第85页微博”。可是，我在网页版微博找到新华社并划到底部发现新华社一共只有3118页（140336条微博总数）。既然如此，为什么程序会显示已爬取14039页的85页呢？还是我的理解有误？截图如下：
![progress](https://user-images.githubusercontent.com/73413661/119757997-662dfc80-be6b-11eb-9499-73fa03cd443a.png)

非常感谢您宝贵的时间和帮助，期待您的回复～

**Comment by dataabc** [comment]
感谢反馈。

1.可能和网络有关，部分与zf相关的限制比较大，当某用户联系几页都无法得到有效内容时，说明被限制了，为了避免不必要的爬取，就自动跳过当前微博了；
2.weibo-crawler没有cookie也能运行，可能第一个cookie也是无效的。本程序使用的是移动版，和网页版的cookie有时不能共用；
3.weibo-crawler没有end_date，本程序虽然能使用end_date，但接口不稳定，会出现漏爬问题，如果只爬单个用户一段时间的微博，可以手动查询该日期微博所在的页码，然后赋值给start_page；
4.网页版和移动版每页的微博数可能不同，移动版大约10条每页，前者更多。
