### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by Harukuku** [dataabc/weiboSpider#342]
出现'NoneType' 错误后，针对某一个用户的爬虫失败，在等待一段时间后恢复正常，是不是会从user_id_list的下一位开始进行爬虫？
比如说user_id_list：["胡歌" "迪丽热巴"]，胡歌的微博爬取失败，再次正常爬虫的时候会爬取迪丽热巴的微博，而不是从爬取失败的胡歌的微博开始爬取？

**Comment by Harukuku** [comment]
谢谢作者解答😊
我在爬取数据的时候，有很多的用户在爬取过程中出现了'NoneType' 错误后，获取到的微博文件生成的scv文件是空的，或者是只有极少的数据，这是正常现象吗？这种情况是因为爬虫进程重新开始，从而跳过了之前爬取失败的用户造成的吗？

**Comment by dataabc** [comment]
这是被限了，过一段时间再试

**Comment by gudaocode** [comment]
个人经验：当出现NoneType错误后，尤其当第一个id由于这个错误而出现爬取停止的情况时，基本上就是微博账号被微博那边封禁了，的确，爬取第二个id时，不会立刻封禁，但除非下一个id你只爬取很少的页面数量，否则大概率第二个id也会在爬取20多页（我最少遇到过10几页）就被干掉了的情况。
所以，是否跳过第一个，爬取第二个没什么用，因为还是会失败；这时候，基本上最佳方式就是换个微博账号来爬，原来那个账号等3、4天后再用来爬取
