### ISSUE TITLE
爬虫只爬取了极少量数据后便自动停止

### ISSUE THREAD

**Issue by ShulamitWu** [dataabc/weiboSpider#343]
您好，感谢你们开发这款程序🙏

我有三个小问题，非常感谢您帮忙解答：

1. 我用weiboSpider时sice_date设置的2019-11-1，end_date设置为“now”，但是spider并没有按照运行程序的当天（5/28/2021）往2019-11-1爬，而是选择了一个随机日期开始往2019-11-1爬。我换了一个since_date后，保持end_date为now，爬虫仍然是从随机的一天往过去爬，和当天没有任何关系。

2. 当使用weibo-crawler爬取共青团中央和紫光阁（都是zf媒体账号）时，我设置的since_date为2019-11-1，但是crawler爬取这两个账号时都在一半时停住。它从当天（5/28/2021）往回爬，却在2021年2月左右停住。以下为截图：
<img width="1614" alt="crawler auto stop@2x" src="https://user-images.githubusercontent.com/73413661/120079580-1cffc780-c07a-11eb-931d-102408b6061b.png">

3. weiboSpider还遇到了爬取时时间顺序颠倒的诡异问题。我设置的since_date为2019-11-1，end_date为2020-12-30. 但是，爬取的时候先爬取了2019-11-15到2019-11-1，随后又爬取了2019的12月份，然后再次回到2019-11-30 到 2019-11-15，最后进入了2020年。以下为截图：
![CleanShot 2021-05-29 at 11 56 11](https://user-images.githubusercontent.com/73413661/120079539-f477cd80-c079-11eb-8146-e94e125889f7.png)
![spider time consistency](https://user-images.githubusercontent.com/73413661/120079553-ff326280-c079-11eb-9975-fa15f76c11e7.png)

再次感谢您宝贵的时间和帮助，期待您的回复🙏

**Comment by dataabc** [comment]
感谢反馈。

1.我也没想明白，可能和账号有关系吧；
2.zf相关的账号限制比较严格，速度过快就无法得到有效数据，为避免不必要的网页访问，程序会跳过；
3.当end_date为日期时，接口不稳定，建议换成now。

如果还有问题，欢迎继续讨论。
