### ISSUE TITLE
抓取到的微博中的换行符没了。 

### ISSUE THREAD

**Issue by enel1jk** [dataabc/weiboSpider#344]
- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：全部

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：4634950810468673

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：抓取到的微博中的换行符没了。

**Comment by dataabc** [comment]
感谢建议，weibo-crawler已merge，本程序得到的页面稍复杂，有一些不可见的字符，暂时没有添加，感觉修改handle_garbled应该可以实现。

**Comment by enel1jk** [comment]
我有时间了会试着改一下。
