### ISSUE TITLE
怎么不能下载带LIVE视频？

### ISSUE THREAD

**Issue by yeoxeo** [dataabc/weiboSpider#345]
- 问：请说明需要什么新功能。<br>
答：下载视频

- 问：请说明添加该功能的意义。（非必填）<br>
答：

**Comment by dataabc** [comment]
感谢反馈，无法得到live视频有效地址，目前不支持下载。

**Comment by yeoxeo** [comment]
> 感谢反馈，无法得到live视频有效地址，目前不支持下载。

action-data pic_video 
STK.register("lib.feed.plugins.media"
里面有阿

**Comment by songzy12** [comment]
> > 感谢反馈，无法得到live视频有效地址，目前不支持下载。
> 
> action-data pic_video
> STK.register("lib.feed.plugins.media"
> 里面有阿

你好，这段文字仿佛乱码了。

我刚才确认了一下，对于 live，weibo.cn （本程序的爬取站点）只能获取到封面图片。
烦请您请给出具体的用户id，状态id，以及相应的视频链接。

**Comment by yeoxeo** [comment]
用户 [https://weibo.com/tiexuelong?profile_ftype=1&is_all=1#_0](url)
比如这个视频 https://video.weibo.com/media/play?livephoto=//us.sinaimg.cn/001Kmr5Egx07Ndx0EUoT0f0f0100azlV0k01.mov&KID=unistore,videomovSrc

可以在html中找到视频id: 001Kmr5Egx07Ndx0EUoT0f0f0100azlV0k01
是在.media_box ul的action-data属性的pic_video参数中

页面会通过FM.view（域名$CONFIG['mJsPath']）加载 page/js/pl/content/homeFeed/index.js
通过STK.register调用lib.feed.plugins.media模块 把pic_video中的视频id转成"//us.sinaimg.cn/" + a[1] + ".mov"
通过STK.register调用lib.image.livephoto模块 再把上面的转换成f.src = "//video.weibo.com/media/play?livephoto=" +  c + "&KID=unistore,videomovSrc";
要获取js的内容确实不好处理
