### ISSUE TITLE
视频下载链接解析有误

### ISSUE THREAD

**Issue by songzy12** [dataabc/weiboSpider#346]
这个是在调查 issue#343 的过程中发现的：

当前获取视频下载链接的逻辑是拿到类似 m.weibo.cn/s/video/show 的 url 后将 show 替换为 object:
https://github.com/dataabc/weiboSpider/blob/ce0aa6e2a12002293fe165b27a8b4308a59c9269/weibo_spider/parser/util.py#L90-L91

这个假设似乎对某些微博不成立：
- https://weibo.cn/u/3937348351
- https://weibo.cn/comment/KitY97deO
- https://m.weibo.cn/s/video/show?object_id=1034%3A4643974800146544&fromWap=1

上面这条视频的当前下载链接我开 debugger 看了一下是（看起来是用了 cdn 之类的）：
<http://f.video.weibocdn.com/gX5MRq13lx07NaasMvmU010412019YgT0E010.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&Expires=1622731687&ssig=yZbfZln1FR&KID=unistore,video>

而直接替换拿到的链接会报错：
https://m.weibo.cn/s/video/object?object_id=1034%3A4643974800146544&fromWap=1

暂时还不知道这是个例还是系统性的问题。

一个可能的 fix 是接着 parse 视频页面来获取实际 video 的 url：
https://m.weibo.cn/s/video/show?object_id=1034%3A4643974800146544&fromWap=1

应该不着急 fix，只是把遇到的问题先记下来。

**Comment by dataabc** [comment]
这个应该是没问题的，视频的链接逻辑是先拿到上面的video_object_url，然后
https://github.com/dataabc/weiboSpider/blob/ce0aa6e2a12002293fe165b27a8b4308a59c9269/weibo_spider/parser/util.py#L98-L106
video_url是最终的视频链接，这个是没问题的

**Comment by songzy12** [comment]
咦好像确实是这样，刚试了一下是好的。

昨天的时候似乎中间步骤的这条链接打不开：
https://m.weibo.cn/s/video/object?object_id=1034%3A4643974800146544&fromWap=1

多谢答疑！

**Comment by dataabc** [comment]
客气了，哈哈
