### ISSUE TITLE
被反爬严重吗？不改源码使用，会被反爬吗？

### ISSUE THREAD

**Issue by LYi9369** [dataabc/weiboSpider#348]

**Comment by dataabc** [comment]
和爬取的微博及数量有关，有的微博限制比较严，明星微博限制较松。量少不易被限制，爬的多了会被限制爬取

**Comment by LYi9369** [comment]
如果要爬单个人的一万条微博，需要改哪些参数防止反爬呢？ 感谢回答：）

**Comment by LYi9369** [comment]
> 和爬取的微博及数量有关，有的微博限制比较严，明星微博限制较松。量少不易被限制，爬的多了会被限制爬取

而且这个人不是明星，只有小几万的粉丝

**Comment by LYi9369** [comment]
感谢回答，已经在“常见问题”里看到了怎么处理，非常感谢回答！
