### ISSUE TITLE
会自动生成txt文件吗？为什么之前的版本好像可以自动生成，这次最新的版本似乎没有？

### ISSUE THREAD

**Issue by Evphoria** [dataabc/weiboSpider#35]
如题

**Comment by dataabc** [comment]
会自动生成txt文件，如果没有生成是不是运行时出错了，有什么提示信息吗?

**Comment by dataabc** [comment]
是否是在命令行中写的代码?这样会出现**name '\__file\__' is not defined**的问题，必须把代码写在.py文件里，然后运行.py文件就没有问题了

**Comment by Evphoria** [comment]
解决了，谢谢！
