### ISSUE TITLE
新功能：请问能否获取用户的关注列表？

### ISSUE THREAD

**Issue by LeeRinji** [dataabc/weiboSpider#351]
有时用户关注的账号也包含了丰富的内容，是否有可能获得用户的关注列表呢？

**Comment by dataabc** [comment]
感谢建议。

[weibo-follow](https://github.com/dataabc/weibo-follow)已经实现了，暂时不打算额外添加到本项目。如果还有问题或建议，欢迎继续讨论。

**Comment by LeeRinji** [comment]
感谢您的回复，您的回复对我帮助很大。


在2021年6月22日 16:33，Chen ***@***.***> 写道：

感谢建议。

weibo-follow已经实现了，暂时不打算额外添加到本项目。如果还有问题或建议，欢迎继续讨论。
