### ISSUE TITLE
转发的原微博全文没有爬取

### ISSUE THREAD

**Issue by shortcut-queen** [dataabc/weiboSpider#354]
- 问：请说明需要什么新功能。

答：转发的原微博全文进行爬取

- 问：请说明添加该功能的意义。（非必填）

答：

**Comment by dataabc** [comment]
感谢反馈。

这应该和网络或账号有关。修改comment_parser.py的get_long_weibo方法，默认是尝试5次，如果5次都无法获取全文就用之前获取的部分替代，你可以把5改成较大的数字，这样程序就会更多次的获取全文直到获取成功或者达到该次数为止。

如果还有问题，欢迎继续讨论。
