### ISSUE TITLE
詢問免cookie版weibo-crawler加入cookie後會跳出格式不正確，是一定要用cookie版weiboSpider嗎?

### ISSUE THREAD

**Issue by vickyj304** [dataabc/weiboSpider#355]
詢問免cookie版weibo-crawler加入cookie後會跳出格式不正確，是一定要用cookie版weiboSpider嗎?

为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：cookie版weiboSpider

- 问：您使用的是否是最新的程序（是/否）？

答：是 PyPi用的是最新版本

- 问：爬取任意用户都会运行出错吗（是/否）？

答：否暫時還是使用迪麗熱巴作為下載，因為想要加入cookie，所以只有加入迪麗熱巴的cookie

在weiboSpider的操作上想確定一下安裝程序是在weiboSpider-master還是weiboSpider-master向下的weibo_spider呢?

**Comment by dataabc** [comment]
感谢反馈。

如果提示config.json格式不正确，应该和cookie没关系。可能是在修改config.json时删除了必要的标点符号（如删除了双引号或者逗号等）或其它有其它使json格式不正确的操作。

weiboSpider的pypi版一般安装在特定的pypi目录，安装成功后在任意目录执行python3 -m weibo_spider，执行的都是这个pypi目录的程序，即便又下载了github版，执行的还是pypi版。不知道我说的是否清楚，如果还有问题，欢迎继续讨论。

**Comment by vickyj304** [comment]
你好 我後來知道為什麼了，我忘記用無痕模式找cookie了
另外想問一下我可以在weibo-crawler的write_mode加入代表將結果信息寫入txt文件嗎?

另外關於weiboSpider我的操作方式是解壓縮之後
1.pip install -r requirements.txt
2. python3 -m weibo_spider
第一次執行說會出現config.json但就沒有出現，cmd也只是一閃而過也沒有特殊提示

**Comment by dataabc** [comment]
weibo-crawler目前不支持写入txt。

如果当前目录没有config.json，运行python3 -m weibo_spider会出现在当前目录下，如果没出现是不是没安装成功，运行
```
$ python3 -m pip install weibo-spider
```
或者源码安装

**Comment by vickyj304** [comment]
謝謝回復，不過weiboSpider還是失敗了我在摸索看看好了

另外想問一下用weibo-crawler微博數量介於兩千到超過一萬以上的是不是沒辦法全部爬下來，有加cookie

**Comment by dataabc** [comment]
weibo-crawler不加cookie最多2000条，加了可以超过2000，是否能超10000没测试过

**Comment by vickyj304** [comment]
你好不好意思想問一下使用weibo-crawler-master突然不能用了，然後有出現錯誤訊息如下，我後來用下載的範本在跑一次也是出現這個

Traceback (most recent call last):
  File "D:\Downloads\weibo-crawler-master\weibo.py", line 28, in <module>
    logging.config.fileConfig(logging_path)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\logging\config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\logging\config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

**Comment by dataabc** [comment]
应该是不小心把logging.conf删了，重新下载即可
