### ISSUE TITLE
您好，在腾讯云函数中运行失败

### ISSUE THREAD

**Issue by Firestl** [dataabc/weiboSpider#358]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：使用pip3 install weibo-spider -t .安装在项目目录中

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：您好，我想每隔一段时间就爬取一次微博，于是想到使用云函数，关于config.json和cookie都已配置好，在本机中可以使用，没有问题。但是在云函数中执行python3 -m weibo_spider后，会报错：
 ERROR - page_parser.py[:247] - list index out of range
ERROR - page_parser.py[:340] - 'NoneType' object is not subscriptable
[error.log](https://github.com/dataabc/weiboSpider/files/6871767/error.log)

**Comment by dataabc** [comment]
可能是被暂时限制了，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)问题2。如果还有问题欢迎继续讨论。

**Comment by Firestl** [comment]
> 可能是被暂时限制了，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)问题2。如果还有问题欢迎继续讨论。

这次增加了时间间隔，依然报错，主要是：IndexError: list index out of range
[error (2).log](https://github.com/dataabc/weiboSpider/files/6872086/error.2.log)

**Comment by dataabc** [comment]
增加时间间隔只能减少被限，不能解除限制，需要一段时间自动解除限制。如果方便，更换其它账号。
