### ISSUE TITLE
    用Jupyter运行时出现Error:  object() takes no parameters

### ISSUE THREAD

**Issue by ray994** [dataabc/weiboSpider#36]
想爬取多美滋的微博。请问，按照Demo替换了
"Cookie": "_T_WM=c4986869a399d0fcf75eb95f33ea19a9; SCF=Au5B9n0rm4weXXNkdngmiujmOOgqNAvkpVg926WBbEt6cvYLaalQ6ZrK0Zh7Dw1aRwRpLoEIdGbbmkKvzU68Obg.; MLOGIN=1; SUB=_2A25xFWwEDeRhGeRO6lsW9C_Eyj-IHXVS9nRMrDV6PUJbkdBeLXb1kW1NUJF8cSwTrlrgL4W3NPxime-EAGEh_SLV; SUHB=0bt93TCcOA8189; SSOLoginState=1544625236; M_WEIBOCN_PARAMS=luicode%3D10000011%26lfid%3D102803; WEIBOCN_FROM=1110106030"}
 
user_id = 1928244585 
但是还是出现 Error:  object() takes no parameters，怎么办？

![image](https://user-images.githubusercontent.com/45824331/49877692-15341480-fe7a-11e8-8089-6dfb7e2a5ce8.png)

**Comment by dataabc** [comment]
是不是__init__的问题?网上很多都是这个问题，init两边是双下划线
