### ISSUE TITLE
这种微博爬不了的。

### ISSUE THREAD

**Issue by luolovehk** [dataabc/weiboSpider#374]
https://weibo.com/u/7484498105?profile_ftype=1&is_all=1#1630415140033  

这种微博爬不了的。她的内容好像是发了一天就隐藏的了，

**Comment by dataabc** [comment]
感谢反馈。这种应该需要一天运行一次程序。

**Comment by luolovehk** [comment]
> 感谢反馈。这种应该需要一天运行一次程序。

我的程序是半小时运行一次的，都没爬到。

**Comment by luolovehk** [comment]
> 我的意思是只能一天运行一次获取她新发的，之前的不能获取。没爬到是不是没配置好config?

程序是挂载服务器的，每30分钟运行一次，其他人的更新了，可以爬到，唯独是这个更新了爬不到。

**Comment by dataabc** [comment]
是我搞错了，缺失不能获取，已经修复了，再次感谢，如果还有问题欢迎继续讨论。

**Comment by gudaocode** [comment]
类似问题，一起反馈吧，这些也都会出错
核实了一下，好像，所有id的共性都是，它们曾经改过名字，即现在上微博看，他们的中文名字和我们id list里面记录（即下面这些）不一样

1393829297 汤唯的秘密基地 2021-10-10 23:34

1500894097 朱珠ZhuZhu 2021-10-10 23:37

1582134940 林心如工作室 2021-10-10 23:37

1657910611 阿兰家族粉丝团 2021-10-10 23:40

1772143893 侯佩岑百度贴吧 2021-10-10 23:52

1787715710 白歆惠BaiBai 2021-10-10 23:53

1796248865 郭碧婷图库 2021-10-10 23:55

1838921261 邢菲_ 2021-10-10 23:57

2131819280 i周迅 2021-10-11 00:07

2249410485 金泰希吧官博 2021-10-11 00:08

2289651603 朴敏英银星后援会 2021-10-11 00:10

2386048403 高圆圆工作室 2021-10-11 00:15

2460011560 赵薇吧官博 2021-10-11 00:18

2703780464 吃冰冰的喵酱 2021-10-05 01:21

2725463701 北川景子一生推的景幻官博 2021-10-11 00:26

3513085300 南笙官方后援会 2021-10-11 00:37

6403553546 巩俐粉丝会 2021-10-11 01:12

6575314806 徐睿知吧 2021-10-11 01:19

3056366991 舒淇國際粉絲 2021-10-11 01:47

**Comment by dataabc** [comment]
@gudaocode 
感谢，很有帮助。

**Comment by dataabc** [comment]
@luolovehk @gudaocode 感谢反馈，已经修复了，如果还有疑问欢迎继续讨论。
