### ISSUE TITLE
通过修改 config.json 实现下载自己微博

### ISSUE THREAD

**Issue by gregist** [dataabc/weiboSpider#375]
- 问：请说明需要什么新功能。

答：通过修改 config.json 实现下载自己微博

- 问：请说明添加该功能的意义。（非必填）

答：现在的处理方法是

```
修改page_parser.py中__init__方法，将self.url修改为：

        self.url = "https://weibo.cn/%s/profile?page=%d" % (user_uri, page)
```
该做法较为繁琐，且无法兼容实现下载所有人微博。建议沿用 user-id-list.txt 规范，例如该文档中含有
```
self self since_date
```
字段，则自动适配 self.url 地址实现下载自己微博功能。

**Comment by dataabc** [comment]
感谢建议。

很多使用者可能是用来获取别人的微博，如获取idol的图片等，获取自己微博的情况可能较少。为了获取自身微博增加参数会增加使用难度。所以还是想尽量不增加参数，最好的方式可能是自己微博和别人微博相同，都是只输入id即可，只是这种方式还暂时没实现。本建议也非常好，因为我想的这种可能比您建议的要多访问几次网络，这是目前的缺点。所以，还未打算使用哪种方式。

尽管如此，您还是给了我们一个不错的实现方案，再次感谢，如果还有建议，欢迎继续讨论。

**Comment by gregist** [comment]
您太客气了。

获取自己微博的情况还是挺多的，譬如用于数据备份检索。我使用此工具的初衷就是如此，毕竟夹总没有提供这个功能...

![image](https://user-images.githubusercontent.com/6292095/132211338-f0d1a51a-c87f-4d81-b4a1-1e49004925f5.png)

一个通用的解决思路是直接调用 API，可以不区分自己或他人的微博，你在姊妹项目中似乎就使用了这个做法。为什么不直接移植过来呢？

**Comment by dataabc** [comment]
这个问题的关键是如何判断某id是自己的还是别人的，如果是自己的可以用上面的方法，别人的使用现在的程序，当然别人的也可以使用上面的方法，但这样和weibo-crawler就没有区别了，所以想通过本程序的方法实现，先获取自己的id，再和待获取id对比，相同就使用最上面的方法。但是判断可能需要多余的网络访问，会让程序更耗时，所以暂时没实现。

**Comment by gregist** [comment]
> 当然别人的也可以使用上面的方法，但这样和weibo-crawler就没有区别了，

明白了，您是想尽量避免在本项目中出现调用 API ，大概是出于鲁棒性的考虑？

> 但是判断可能需要多余的网络访问，会让程序更耗时，

想要避免多余的网络访问，要么直接从 cookie 中读出 `user-id` 的信息作为比对，要么手动提供相关信息。前者没有找到成功案例，后者的一个具体思路是在 `user-id-list.txt` 中，以 `#` 或其他特殊字符前缀指代自己微博，比如

```
#88888888 me 2021-09-01
77777777 other 2021-09-01
```

这样既不破坏整体的格式，保证兼容性的同时，也最大化方便程序的修改。至于您之前提到增加使用难度问题，没有此类需求的没有增加，有需求的不需要手动修改源代码，反而是降低了使用难度。

**Comment by dataabc** [comment]
感谢建议。这是一个非常好的备选方案，我再考虑下自己的方案，如果无法实现，以后有机会会参考上面的方案。
再次感谢热心回复和建议。
