### ISSUE TITLE
修改文件保存路径，提示：config.json 格式不正确，请访问 https://github.com/dataabc/weiboSpider#2程序设置

### ISSUE THREAD

**Issue by PiscesYXT** [dataabc/weiboSpider#376]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：否

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：
运行命令：
Python -m weibo_spider --output_dir="F:\桌面\各类软件运行数据存档-专用文件夹\新浪微博用户图片下载\微博用户图片下载存档"

错误提示：config.json 格式不正确，请访问 https://github.com/dataabc/weiboSpider#2程序设置

**Comment by PiscesYXT** [comment]
![Uploading 1.jpg…]()

**Comment by dataabc** [comment]
感谢反馈。

可能就是config.json格式不正确，比如漏写了标点等。

**Comment by PiscesYXT** [comment]
排查了确实是漏写了标点，不好意思了。谢谢您了！
