### ISSUE TITLE
关于下载路径默认设置的、和是否有检测重复下载的问题？

### ISSUE THREAD

**Issue by PiscesYXT** [dataabc/weiboSpider#377]
您好，打扰到您了！
1、我想问一下我想设置下载默认路径，但在JSON包括程序设置文档中也没有提到相关的命令，只有这一条命令：python3 -m weibo_spider --output_dir="/home/weibo/"。
关于这一条命令我想问一下是运行过一次后，在以后的运行都默认是这个下载路径；还是说每一次运行都要执行这一条命令才能下载到自己想设置的路径？如果是说每一次运行都要执行这一条命，那我想问您一下我想设置默认的下载路径应该需要如何设置？
2、我想通过PyCharm运行，但是报错：运行 'crawl_weibo' 时出错: 无法启动进程,工作目录'D:\Python运行程序包\img-crawler（新浪微博图片批量下载）'不存在。但在用CMD运行是没有问题是，不清楚是不是没有执行对的py。
3、还有一个问题想问您一下，代码中是否有针对已下载文件的重复检测；我怕到时候重新执行命令会再一次把已下载的文件重新下载导致文件的重复。

最后，打扰到您了，也谢谢您的解答！

**Comment by dataabc** [comment]
客气了。

1.每次都得设置，要实现每次都默认使用新路径，修改spider.py的_get_filepath方法
```
    def _get_filepath(self, type):
                ...
                file_dir = (os.getcwd() + os.sep + 'weibo' + os.sep + dir_name)
                ...
```
dir_name可能是用户昵称或id，file_dir就是默认路径，如果你想把微博下载到用户昵称的文件夹，需要保留dir_nir_name，其它换成你想改的目录即可；
2.你可以运行__main__.py这个文件看看；
3.如果使用txt文件输入id是可以去重的，在config.json直接输入id是会重复的。

如果还有疑问，欢迎继续讨论。

**Comment by dataabc** [comment]
@goooooodperson 

对于已经下载的文件是不会重新下载的。txt可以控制控制输入的id。当txt中如多个相同id时，如果相同id行内容完全相同时会忽略重复，否则会重复获取。除了以上，程序本身是没有对id重复作太多处理。
关于重复request。程序可能会重复获取某个微博，比如你第一次想获取1号到3号的微博，第二次获取3号到5号的，第一次的3号可能是当前运行程序的日期，作为下一次的since_date，第二次也会获取这一天的。为什么这样？因为当时的日期很可能不是那一天的最后一刻，也就是说，第一次运行之后用户在当天可能发新微博，为了不遗漏，since_date是那一天而不是它的下一天。因此这种边缘日期是可能重复的，自然会造成重复request图片的现象。目前无法做到根据id进行去重。就像薛定谔的猫，如果不获取就不知道id，就无法与已有的比较；如果指定某微博已经获取了，说明又重复request了。

再次感谢热心反馈，如果还有疑问或建议，欢迎继续讨论。
