### ISSUE TITLE
关于能否增加多个cookie账号及批量获取大量user_id时再自动添加对应的用户昵称？

### ISSUE THREAD

**Issue by PiscesYXT** [dataabc/weiboSpider#378]
- 问：请说明需要什么新功能。

答：
1、能否通过修改命令cookie": "your cookie" ；为cookie": ["cookie1"，"cookie2"，"cookie3"], 增加多个cookie账号随机获取下载视频。可以有多个cookie，"cookie1"处应该填真实的cookie，"cookie2"为另一个账号的cookie，也可以有cookie3、cookie4等，因为不知道这样是否能够减少被限制的概率，所以没有更新代码
2、在程序设置中有关于获取大量user_id的功能，但能否在获取大量user_id的用户id后面再增加采集对应用户的昵称。

- 问：请说明添加该功能的意义。（非必填）

答：
1、如果用多个cookie随机，在限制之前会不会比使用一个cookie获取的结果多（不清楚微博是否是通过IP地址来限制还是账号限制）。
2、在获取大量user_id的用户id后面，再增加采集对应用户的昵称是为了方便后面的管理（如下图所示范）
![1](https://user-images.githubusercontent.com/66818699/132295885-ab21b129-2804-4fd8-a8cf-db91878cc7a4.jpg)

**Comment by dataabc** [comment]
感谢建议，没有添加多个cookie的打算。本程序只是为了学术研究获取少量微博的，添加多个cookie担心用于商业，这与本程序的初衷不符，因此没有这个打算，望理解。

**Comment by PiscesYXT** [comment]
非常抱歉，可能是我没有说明清楚原因，导致您误会了。我这边也是做一个课题研究，由于一开始需要获取数据的账号有五十个左右导致容易限制，但是这边课题研究时间上也比较紧张才说出相关疑问的，包括用户昵称的自动添加也是为了后面课题研究数据的展现。不管如何，也感谢您的解答了，谢谢！

**Comment by dataabc** [comment]
客气了。程序是可以自动添加昵称的，当txt中只有id时，程序会自动添加昵称的。如果还有疑问，欢迎继续讨论。
