### ISSUE TITLE
运行提示：AttributeError: 'NoneType' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by PiscesYXT** [dataabc/weiboSpider#379]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：否

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答 以为课题研究时间上比较紧张，昨天晚上挂机下载起来后发现报错：AttributeError: 'NoneType' object has no attribute '__dict__'，附件如下：
[error.log](https://github.com/dataabc/weiboSpider/files/7126371/error.log)

**Comment by dataabc** [comment]
这应该是被暂时限制了，限制一段时间会自动解除，可以参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2，降低速度，如果还有疑问，欢迎继续讨论。

**Comment by PiscesYXT** [comment]
好的，谢谢了
