### ISSUE TITLE
爬取微博数据时候，突然断电断网了，重新启动程序能够自动断点续爬吗

### ISSUE THREAD

**Issue by ahulxj** [dataabc/weiboSpider#381]
您好，用您的爬虫爬取某一个账号的微博数据，很顺利。但是突然断网了，程序终止（假设数据采集到2021年5月1日12时断网的）。我现在重新启动程序，是会从今天（2021年9月12日）全部重新爬，还是从我上次采集到的断点时间（2021年5月1日12时）开始继续往前爬。谢谢

**Comment by dataabc** [comment]
会从今天开始。如果想从上次的开始，可以在日志中获取上次的中断时最后获取到哪页，然后让程序从那页开始获取，修改spider.py的get_webo_info方法
```
    def get_weibo_info(self):
          ...
                for page in tqdm(range(1, page_num + 1), desc='Progress'):
         ...
```
把第一个1换成上面那一页的数字。

**Comment by ahulxj** [comment]
谢谢
