### ISSUE TITLE
可以获取原画质或者1080p视频吗？

### ISSUE THREAD

**Issue by C7ios-4Nino** [dataabc/weiboSpider#382]
想问一下大佬通过修改哪里可以获得原画质或者1080p的视频，我直接改动mp4_720p_mp4并没有作用，反而只能获取到最低分辨率的视频了.

**Comment by dataabc** [comment]
page_parser.py的get_video_url方法就是获取视频的方法，本程序使用的是微博移动版获取的视频，最高是720p，无法获取更高的画质。如果还有疑问，欢迎继续讨论。

**Comment by C7ios-4Nino** [comment]
了解了！谢谢您的回复！
