### ISSUE TITLE
关于nickname的错误

### ISSUE THREAD

**Issue by ligujie123** [dataabc/weiboSpider#385]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：pip

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：否

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：你好，首先谢谢提供这个工具。我在爬了一段时间数据后，经常出现以下错误。

![image](https://user-images.githubusercontent.com/29496632/136716305-96d385f3-5a0e-4fb0-8cf5-b0bacbd3f07b.png)

**Comment by dataabc** [comment]
感谢反馈。这是速度过快导致的，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2，如果还有问题，欢迎继续讨论。
