### ISSUE TITLE
关于end_date的疑问

### ISSUE THREAD

**Issue by ligujie123** [dataabc/weiboSpider#386]
你好，因为我在文档中注意到

”推荐使用"now"作为end_date值，当值为"now"时，获取结果是正确和稳定的；当end_date值不是"now"时，在爬微博数非常多的账号时，程序可能不稳定，得到很多空微博页，并且此时无法获取微博中的视频，如果想要获取视频，请为end_date赋值为"now"。“

想请问一下，这只是针对需要获取视频的情况吗，如果我并不需要获取视频和图片，加上end_data是不是也会导致爬虫结果不稳定？谢谢。

**Comment by dataabc** [comment]
end_date和视频没关系，只要不是now，就不稳定。
