### ISSUE TITLE
爬取自己的微博出错，爬别人的没问题

### ISSUE THREAD

**Issue by 1101Yang1101** [dataabc/weiboSpider#390]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：pypi

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：否

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：list index out of range
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\weibo_spider\spider.py", line 318, in get_one_user
    self.download_user_avatar(user_config['user_uri'])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\weibo_spider\spider.py", line 147, in download_user_avatar
    user_uri).extract_avatar_album_url()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\weibo_spider\parser\photo_parser.py", line 15, in extract_avatar_album_url
    return "https://weibo.cn" + result[0]
IndexError: list index out of range

**Comment by dataabc** [comment]
感谢反馈。

若要获取自己的微博，需要修改代码，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题7。

**Comment by 1101Yang1101** [comment]
> 感谢反馈。
> 
> 若要获取自己的微博，需要修改代码，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题7。

我修改了，也没有用

**Comment by dataabc** [comment]
你使用的应该不是最新版，我刚更新了最新版，你可以试下。

**Comment by 1101Yang1101** [comment]
> 你使用的应该不是最新版，我刚更新了最新版，你可以试下。

谢谢您，我刚试了还是不行。请问常见问题的问题7，指的就是将page_parser.py中的38、39行改成        self.url = "https://weibo.cn/%s/profile?page=%d" % (user_uri, page)
吗

**Comment by 1101Yang1101** [comment]
> 把init方法的
> 
> ```
>         self.url = 'https://weibo.cn/%s?page=%d' % (self.user_uri, page)
> ```
> 
> 改成
> 
> ```
>         self.url = "https://weibo.cn/%s/profile?page=%d" % (self.user_uri, page)
> ```我的init方法的self.url = 'https://weibo.cn/%s/profile?starttime=%s&endtime=%s&advancedfilter=1&page=%d' % (
                self.user_uri, starttime, endtime, page)是这样的，但我刚才的确重新下载了zip

**Comment by 1101Yang1101** [comment]
> 把init方法的
> 
> ```
>         self.url = 'https://weibo.cn/%s?page=%d' % (self.user_uri, page)
> ```
> 
> 改成
> 
> ```
>         self.url = "https://weibo.cn/%s/profile?page=%d" % (self.user_uri, page)
> ```

欸！我知道了我看错了，我再试试

**Comment by 1101Yang1101** [comment]
> > 把init方法的
> > ```
> >         self.url = 'https://weibo.cn/%s?page=%d' % (self.user_uri, page)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成
> > ```
> >         self.url = "https://weibo.cn/%s/profile?page=%d" % (self.user_uri, page)
> > ```
> 
> 欸！我知道了我看错了，我再试试

确定修改了，但还是一样的错误

**Comment by dataabc** [comment]
上面的错误是之前的，已经修复了，如果还是相同的错误，可以下载github版，再修改。

**Comment by 1101Yang1101** [comment]
> 上面的错误是之前的，已经修复了，如果还是相同的错误，可以下载github版，再修改。

谢谢，我再试试看

**Comment by 1101Yang1101** [comment]
解决了，谢谢
