### ISSUE TITLE
完全按照readme操作，但是依然显示“cookie错误或已过期,请按照README中方法重新获取”

### ISSUE THREAD

**Issue by Chloe-gra** [dataabc/weiboSpider#391]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：githubb版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by dataabc** [comment]
感谢反馈。如果是这个错误，很可能是cookie原因，还有可能你安装了pypi版，当你执行本程序的时候实际上执行的是pypi，所以使本程序的cookie不起作用，如果是这样，卸载pypi就可以。

**Comment by winterswang** [comment]
pip install的版本不可以吗？必须要源码安装的版本？

**Comment by dataabc** [comment]
@winterswang 都可以，如果同时存在两版，可能运行的是pypi版，导致另一版可能无效。
