### ISSUE TITLE
config.json 格式不正确，请访问 https://github.com/dataabc/weiboSpider#2程序设置

### ISSUE THREAD

**Issue by Yangyehong** [dataabc/weiboSpider#392]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：pypi（weibo-spider使用cookie）

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：当我修改cookie之后就会显示，查找cookie的方式就是查看源代码，复制cookie的值。使用示例中的迪丽热巴的例子，替换成自己的cookie之后，也会提示这个错误，应该是cookie的问题？
config.json 格式不正确，请访问 https://github.com/dataabc/weiboSpider#2程序设置。

**Comment by dataabc** [comment]
可能是格式错误，比如标点符号。

**Comment by Yangyehong** [comment]
> 可能是格式错误，比如标点符号。

cookie复制的时候，需要自己再修改吗

**Comment by dataabc** [comment]
不用，是不是忘了引号？

**Comment by Yangyehong** [comment]
> 不用，是不是忘了引号？

有引号，我就把引号里的换了

**Comment by dataabc** [comment]
不换之前有错吗？就是只换引号之内的。

**Comment by Yangyehong** [comment]
不换就没有自己的cookie，其他的东西都是用的示例里的

{
    "user_id_list": ["1669879400"],
    "filter": 1,
    "since_date": "1900-01-01",
    "end_date": "now",
    "write_mode": ["csv", "txt", "json"],
    "pic_download": 1,
    "video_download": 1,
    "result_dir_name": 0,
    "cookie": "your cookie"
}

**Comment by dataabc** [comment]
你把删了一部分参数，所以报错，删除config.json，重新运行。

**Comment by Yangyehong** [comment]
感谢大佬帮忙解答，我搞清楚了，是我的问题，我用的是之前我一直用的网页版的cookie，必须用教程里那个cookie
