### ISSUE TITLE
可以考虑 话题关键字搜索

### ISSUE THREAD

**Issue by taoyeh** [dataabc/weiboSpider#394]
- 问：请说明需要什么新功能。

答：老哥的项目好像只能用户的所有的话题的微博，有没有考虑出一下话题搜索的功能比如#全球变暖

- 问：请说明添加该功能的意义。（非必填）

答：很多学生的作业要求是这样的

**Comment by dataabc** [comment]
[weibo-search](https://github.com/dataabc/weibo-search)已经可以搜索话题了，[免cookie版](https://github.com/dataabc/weibo-crawler)可以搜索指定用户包含特定关键词的微博，不知道是否是你需要的。
