### ISSUE TITLE
建议增加关联评论采集

### ISSUE THREAD

**Issue by abnerCrack** [dataabc/weiboSpider#395]
- 问：请说明需要什么新功能。

答：增加微博关联评论

- 问：请说明添加该功能的意义。（非必填）

答：有几个科研类的的博主评论内容比较有价值，微博主题可能只是抛砖引玉

**Comment by dataabc** [comment]
感谢建议。[免ookie版](https://github.com/dataabc/weibo-crawler)已经支持获取评论了。
