### ISSUE TITLE
长微博爬取

### ISSUE THREAD

**Issue by plutonji** [dataabc/weiboSpider#397]
- 问：请说明需要什么新功能。

答：某些较长的微博在 weibo.cn 的时间线下会折叠，只能爬取到前面一小段。希望能解决这部分微博的爬取问题。

- 问：请说明添加该功能的意义。（非必填）

答：相比而言这些文字较多的微博反而有着更大的价值，例如：https://weibo.cn/comment/L2COaufuI?ckAll=1

**Comment by melisa81** [comment]
我也碰到这个问题，无法抓取非展开微博内容。

**Comment by mtuwei** [comment]
支持，有同样的需求，希望能够增加这一功能，谢谢！

**Comment by plutonji** [comment]
更正一下描述：
对于同一个用户的两条长微博，有的微博可以抓取全文，有的却抓不到。简单看了下html代码两种微博代码没多大区别：
例如用户：https://weibo.cn/u/2014433131
这一条微博可以抓到全文：https://weibo.cn/comment/L4U9gh25T?ckAll=1
这一条微博抓不到：https://weibo.cn/comment/L4U06n4qZ?ckAll=1

**Comment by dataabc** [comment]
@plutonji @melisa81 @mtuwei 我测试了下，发现同一条长微博，有时候可以完整获取，有时候不能。程序每次获取长微博不一定成功，会尝试5次，有一次成功就保存了，如果5次都失败，就使用那条不完整的数据，聊胜于无。因为强制等待获取成功可能会销号很多时间，使用默认是测试5次。如果想要增加长微博成功概率，可以修改weibo_spider/parser/comment_parser.py的get_long_weibo方法，将数字5改成其它更大的整数。如果还有问题，欢迎继续讨论。

**Comment by junbaor** [comment]
https://m.weibo.cn/statuses/show?id=L7EVX4vuU
https://m.weibo.cn/statuses/show?id=L4U06n4qZ

有没有可能利用这个接口拿到长微博详情？

**Comment by dataabc** [comment]
@junbaor 感谢，带视频的有什么建议吗？

**Comment by junbaor** [comment]
不太清楚这个工具之前怎么提供的视频内容，我用不到视频就先过滤了。
如果有人想完善的话可以在 pr 的基础上把那段 html 解析下。

**Comment by iython** [comment]
获取长微博失败的原因是xpath没有解析到内容。将 info = self.selector.xpath("//div[@class='c']")[1]  替换成 info = self.selector.xpath("//div[@class='c' and @id='M_']")[0] 可以解决问题

**Comment by iython** [comment]
self.selector.xpath("//div[@class='c' and @id='M_']")[0]

> 获取长微博失败的原因是xpath没有解析到内容。将 info = self.selector.xpath("//div[@Class='c']")[1] 替换成 info = self.selector.xpath("//div[@Class='c' and @id='M_']")[0] 可以解决问题

更简洁的：info = self.selector.xpath("//div[@id='M_']")[0]
