### ISSUE TITLE
文件找不到config.json weibospider.py，下载暂停中断后 保存任务，浏览该视频的权限

### ISSUE THREAD

**Issue by DeanShiDirect** [dataabc/weiboSpider#398]
替换大约在weibospider.py文件的22行左右的cookie   但是 weibospider.py 这个文件找不到。

设置要爬取的user_id 打开 config.json 文件，但是 config.json  在哪儿呢

**Comment by DeanShiDirect** [comment]
https://github.com/dataabc/weibo-search  这个是微博搜索，我跟着一遍成功学习了，   但是微博视频这个教程 还是不太明白，步骤没有问题，就是缺文件，无论是下载源代码 还是 pip命令安装，最后都找不到文件 weibospider.py config.json

**Comment by melisa81** [comment]
config.json 在文件目录里啊？

**Comment by DeanShiDirect** [comment]
> config.json 在文件目录里啊？

你是指 config_sample.json 这个文件吗？

 weibospider.py 这个文件也找不到呢？

**Comment by plutonji** [comment]
源码安装的用户可以在weiboSpider目录运行如下命令，pip安装的用户可以在任意有写权限的目录运行如下命令

```
$ python3 -m weibo_spider
```
第一次执行，会自动在当前目录创建config.json配置文件，配置好后执行同样的命令就可以获取微博了。

**Comment by DeanShiDirect** [comment]
谢谢回复哦！
pip安装
$ python3 -m pip install weibo-spider
第一次我用的是 pip install weibo-spider
刚才修正后用 python -m pip install weibo-spider
如果用您那个完整的 python3... cmd报错说 python3不是内部外部命令之类。
谢谢

**Comment by dataabc** [comment]
感谢反馈。

一般源码下载后，在weibo_spider会有config_sample.json，它和config.json是一样的内容。应该先下载源码，然后在下载的文件夹内运行命令行
```
python3 -m weibo_spider
```
第一次运行会生成config.json，按README修改后，再次运行就可以，如果还有问题欢迎继续讨论。

**Comment by DeanShiDirect** [comment]
谢谢回复，感谢您分享好用的工具！

**Comment by DeanShiDirect** [comment]
你好，我是通过下载源码包，这个包包含 weibo_spider文件夹，但是没有weibo_spider.py文件
weiboSpider-maste如下：
[https://i.iluoli.moe/2021/12/10/e90181210103439.png](url)
weibo_spider文件夹如下：
[https://i.iluoli.moe/2021/12/10/782b81210103439.png](url)


然后在窗口D:\Python\Python39\weiboSpider-master直接输入cmd

运行：
`python3 -m weibo_spider`
效果：D:\Python\Python39\weiboSpider-master>python3 -m weibo_spider
报错：'python3' 不是内部或外部命令，也不是可运行的程序或批处理文件。

运行：
`python -m weibo_spider`
报错：ModuleNotFoundError: No module named 'weibo_spider.spider'

我的下载是通过运行【python weibo_spider】  实现的
想问一下为什么，要去掉【python3 -m】的【3 -m】
谢谢

**Comment by dataabc** [comment]
使用user_id_list.txt输入uid时是会保存进度的，会记录上次结束时的时间，下次运行时它会变成since_date值。
目前因为有的文件是有有效期的，现在能下载，之后就失效了，所以没有实现。
因为程序已经给出“没有浏览该视频的权限”的微博url了，认为没必要再说明uid，这个暂时不会添加。
程序命令行中的weibo_spider指的是模块，所以要加-m，你之所以没出错是因为你之前可能通过pip安装过这个.
如果还有问题，欢迎继续讨论。

**Comment by DeanShiDirect** [comment]
谢谢回复，祝您编程愉快！
