### ISSUE TITLE
cookie版抓取微博仅能抓取10%后自动跳到下一个id抓取

### ISSUE THREAD

**Issue by dandaopitiao** [dataabc/weiboSpider#399]
大佬您好，我有一个user_id_list需要依次抓取，但是在实操中第一个id微博抓取到1400多条的时候就结束了，开始抓第2个id的微博，但是实际上第一个id（BEIJING北汽新能源）有八千条微博，我在无cookie版本中也只能到2000条就会自动切换id，请问大佬我应该如何解决呢？谢谢！

**Comment by dandaopitiao** [comment]
****************************************************************************************************
被ban了
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
用户信息
'id'
Traceback (most recent call last):
  File "D:/onedrive/OneDrive - ruc.edu.cn/EV_proj/2021.4_Marketing_EV/City_sales/Sales_20211125/weibo-crawler-master/weibo.py", line 1526, in get_pages
    self.print_user_info()
  File "D:/onedrive/OneDrive - ruc.edu.cn/EV_proj/2021.4_Marketing_EV/City_sales/Sales_20211125/weibo-crawler-master/weibo.py", line 666, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
信息抓取完毕

**Comment by dandaopitiao** [comment]
大佬好，我已经把休眠间隔全部调整成25秒以上了，但是还是会被ban orz 请问我应该怎么办呢

**Comment by dataabc** [comment]
感谢反馈。
抓取10%可能是since_date没设置好；免cookie版加上cookie可以获取全部微博；没有特别好的避免被ban的方法，尽量放慢速度。
如果还有问题，欢迎继续讨论。

**Comment by vicshi94** [comment]
我用了cookie版遇到了同样的问题，我尽量放慢了速度，没有被ban，但是仅抓取一点点，就显示抓取完成了。
以下是我的设置：
`"since_date": "2020-01-01", 
"end_date": "2021-12-20",`
但是实际反馈的结果是：
2328516855这个id爬到了2021-10-28至2021-12-20，
3937348351这个id爬到了2021-06-21至2021-12-20，
其他的id都有类似的情况。

为了不让爬虫爬到一半就跳转下一个id，后来我又单独爬了一次2328516855这个id，但结果还是向前爬到2021-10-29就显示爬取完成了

**Comment by dataabc** [comment]
@vicshi94 当end_date不是now时，程序不会漏爬，可能是这个原因，换成now会好一点。

**Comment by vicshi94** [comment]
@dataabc 测试了一下，好像不是end_date的原因，end_date为now或指定日期，表现一样，且还是会出现爬不完的情况。但是将速度放慢，一次可以爬取更多的微博数量。我怀疑有个可能是因为爬取速度过快，导致没有抓取到数据，但是程序没有报错，而是认为爬取完成了。

**Comment by dataabc** [comment]
@vicshi94 感谢反馈，这对遇到类似问题的网友是不错的建议。
