### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Michaeljmyabg** [dataabc/weiboSpider#40]
请教您以下问题如何解决？感谢。
File "weibospider.py", line 58, in get_user_info
    "//div[@class='tip2']/span[@class='tc']/text()")[0]
IndexError: list index out of range
共0条微博，其中0条为原创微博

**Comment by dataabc** [comment]
感谢反馈，能否提供微博id，方便调试

**Comment by dataabc** [comment]
可能是你的微博id没有写对，导致无法获取用户信息。
大部分用户的微博id可以在目标用户首页url里找到,是一串数字。然而有一部分用户的微博id不是这一串数字。需要点击用户首页的"资料"，此时url里的数字才是用户的微博id。
出现上述情况的原因是，微博曾经推出过"微号"功能，用户申请微号，就可以得到"https://weibo.cn/u/微号"形式的个性化地址。然而用户的信息页用的是"https://weibo.cn/微博id/info"这样的地址，所以用微号替代微博id无法获取用户信息，故而出错。

**Comment by Michaeljmyabg** [comment]
谢谢您的回复，一时不查，搞错id，已经解决。
不过仍有一个问题，最近在爬虫时，大概爬一两个月就会自动停止，无法继续爬完。
情况如下，以人民日報（id: 2803301701）為例:
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "weibospider.py", line 89, in get_long_weibo
    info = selector.xpath("//div[@class='c']")[1]
AttributeError: 'NoneType' object has no attribute 'xpath'
【河南安阳警方通报辅警收钱37段视频：基本属实，大队长和3民警停职，10名辅警被开除】近日，安阳一超限站交通协助交警向司机收受钱物的视频曝光。@安阳交警 通报：情况 基本属实。已对收受钱物的10名交通协助交警联合治超人员予以开除，对负管理责任的大 队长及3名民警停止执行职务并接受调查。  全
微博位置: 无
微博发布时间: 2018-12-03 21:11
微博发布工具: 微博 weibo.com
点赞数: 11025
转发数: 5471
评论数: 6337

**Comment by dataabc** [comment]
这个可能是网络问题。因为这条微博内容较长，在微博列表页无法全部显示，所以先获取这一条微博的地址(<https://weibo.cn/comment/H5yJ7CMa4>)，然后再获取此页的微博内容。因为网络原因，网页内容获取失败，所以才出现'NoneType' 。另外，出现错误提示后，程序还是会继续爬下一条微博，不会停止。
测试了上述微博，可以爬取到这条微博并获取全部的文字内容。

**Comment by Michaeljmyabg** [comment]
谢谢您的答复，其实之前爬是可以的，但后来不管是爬哪个微博都会出现相同情形。
瞭解您的逻辑，但由于自己是程式码的新手，想请问程式码内容要如何做更改？
麻烦您了。

**Comment by Michaeljmyabg** [comment]
您好，我后来重複测试用不同帐号的cookie爬虫，发现该问题解决，不过始终只能爬取约前三个月的贴文就自动停止并完成存档。之前可以全部爬完，现在只能爬一下下就停止爬取了@@

**Comment by dataabc** [comment]
可能是爬的速度太快了，减慢爬取速度应该会解决。例如，每爬几页sleep几秒，可以参考#8

**Comment by Michaeljmyabg** [comment]
您好，我按照解决步骤：

包的依赖：
numpy
#pip install numpy

#代码正文：
import numpy as np
#第一部分的插入代码：
page1=0
random_pages=2
#第二部分的插入代码：
random_sleep= np.random.randint (6,10)
if page-page1==random_pages:
sleep(random_sleep)
page1=page
random_pages = np.random.randint (1, 5)

爬虫速度看起来没有变慢，且爬到相同处便停止。以人民日报为例(ID: 2803301701)
我是用Python 3.7版本

**Comment by dataabc** [comment]
用下面代码替换get_long_weibo，试试。
```python
    def get_long_weibo(self, weibo_link):
        try:
            while True:
                html = requests.get(weibo_link, cookies=self.cookie).content
                selector = etree.HTML(html)
                if selector is not None:
                    info = selector.xpath("//div[@class='c']")[1]
                    wb_content = info.xpath("div/span[@class='ctt']")
                    if len(wb_content) >= 1:
                        wb_content = wb_content[0].xpath("string(.)").replace(u"\u200b", "").encode(sys.stdout.encoding, "ignore").decode(
                            sys.stdout.encoding)
                        return wb_content
                else:
                    print("123")
        except Exception as e:
            print("Error: ", e)
            traceback.print_exc()
```
爬虫速度没变慢可能是你的get_weibo_info没有改好。

**Comment by pengxianyang** [comment]
您好！
我下载了您的代码运行之后发现遇到了以下的情况：
E:\Englishwaypoint\GitDP\weiboSpider>python weiboSpider.py
用户名: 新浪
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 59, in get_user_info
    "//div[@class='tip2']/span[@class='tc']/text()")[0]
IndexError: list index out of range
进度:   0%|                                                                                        | 0/1 [00:00<?, ?it/s]
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 240, in get_weibo_info
    is_empty = info[0].xpath("div/span[@class='ctt']")
IndexError: list index out of range
微博写入文件完毕，保存路径:
E:\Englishwaypoint\GitDP\weiboSpider\weibo\2175582565.txt
信息抓取完毕
===========================================================================

且怎么更换目标id用户名都是“新浪” ，不知是什么问题所致的呢？

**Comment by pengxianyang** [comment]
您好，我在运行了您的代码之后一直出现：

E:\Englishwaypoint\GitDP\weiboSpider>python weiboSpider.py
用户名: 新浪
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 59, in get_user_info
    "//div[@class='tip2']/span[@class='tc']/text()")[0]
IndexError: list index out of range
进度:   0%|                                                                                        | 0/1 [00:00<?, ?it/s]
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 240, in get_weibo_info
    is_empty = info[0].xpath("div/span[@class='ctt']")
IndexError: list index out of range
微博写入文件完毕，保存路径:
E:\Englishwaypoint\GitDP\weiboSpider\weibo\2175582565.txt
信息抓取完毕

且无论怎么更换目标ip依然存在这个错误，请问这个是什么情况呢？

**Comment by dataabc** [comment]
@pengxianyang 说明cookie没有设置正确，按照README获取cookie并替换your cookie即可

**Comment by pengxianyang** [comment]
> @pengxianyang 说明cookie没有设置正确，按照README获取cookie并替换your cookie即可
感谢！已成功解决！之前登陆之后没有跳转到weibo.cn那里去找cookie 找了mweibo的

**Comment by ymm-gh** [comment]
> 用下面代码替换get_long_weibo，试试。
> 
> ```python
>     def get_long_weibo(self, weibo_link):
>         try:
>             while True:
>                 html = requests.get(weibo_link, cookies=self.cookie).content
>                 selector = etree.HTML(html)
>                 if selector is not None:
>                     info = selector.xpath("//div[@class='c']")[1]
>                     wb_content = info.xpath("div/span[@class='ctt']")
>                     if len(wb_content) >= 1:
>                         wb_content = wb_content[0].xpath("string(.)").replace(u"\u200b", "").encode(sys.stdout.encoding, "ignore").decode(
>                             sys.stdout.encoding)
>                         return wb_content
>         except Exception as e:
>             print("Error: ", e)
>             traceback.print_exc()
> ```
> 
> 爬虫速度没变慢可能是你的get_weibo_info没有改好。

您好，我在weibospider.py中没有看到长微博相关的代码，请问哪里可以找到替换get_long_weibo的地方呢，感谢。

**Comment by songzy12** [comment]
@ymm-gh 现在的 get_long_weibo 在 weiboSpider/weibo_spider/parser/comment_parser.py. 
不过我怀疑这个 issue 中的问题已经被 fix 过了。

**Comment by dataabc** [comment]
@songzy12 

这个issue确实被修过了。长微博尝试获取5次，如果有一次成功就返回，如果都失败就使用对应微博列表中内容不全的正文。
