### ISSUE TITLE
如何只抓取用户信息，而不抓取微博内容（json格式）

### ISSUE THREAD

**Issue by fengyuan106** [dataabc/weiboSpider#403]
- 问：请说明需要什么新功能。

答：因为json格式的用户信息比较全面，csv格式用户信息比较少，如果把since data设成将来的时间的话，会生成csv文件（只包含永和信息，不包含微博），但是json格式如果设成将来的时间的话，就不会生成json文件。

- 问：请说明添加该功能的意义。（非必填）

答：

**Comment by dataabc** [comment]
感谢反馈。

可以修改json_writer.py的write_user方法，内容可以仿造write_weibo，如果还有问题，欢迎继续讨论。

**Comment by fengyuan106** [comment]
感谢感谢，已解决！



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2021年12月18日(周六) 晚上9:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dataabc/weiboSpider] 如何只抓取用户信息，而不抓取微博内容（json格式） (Issue #403)




 
感谢反馈。
 
可以修改json_writer.py的write_user方法，内容可以仿造write_weibo，如果还有问题，欢迎继续讨论。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
