### ISSUE TITLE
这个版本不能获取一级评论了吗？

### ISSUE THREAD

**Issue by OptimusMsc** [dataabc/weiboSpider#404]
- 问：请说明需要什么新功能。

答：老版本是可以爬取评论的，新版本不支持了吗？

- 问：请说明添加该功能的意义。（非必填）

答：

**Comment by dataabc** [comment]
感谢反馈。

没有修改评论的代码，如果不能获取是不是配置问题，需要在sqlite模式下。

**Comment by OptimusMsc** [comment]
哦哦哦这样，是示例的config还有readme都没有提到爬取评论，老版本都是有写的，我先入为主了还没看代码，感谢热心回复~

**Comment by OptimusMsc** [comment]
您好，我又去check一遍新代码，发现确实是没有爬取一级评论的code呀，是删除了吧？

**Comment by dataabc** [comment]
我看错了，你说的是weibo-crawler，它是有评论的。
