### ISSUE TITLE
为什么爬取有些日期会出写空白页，直接停止？

### ISSUE THREAD

**Issue by a1012819022** [dataabc/weiboSpider#405]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：py

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by dataabc** [comment]
能否详细说明出现的情况，谢谢。

**Comment by a1012819022** [comment]
我爬取id为[2508021512]的用户，日期设定为2018-1-1到2018-12-31，运行的时候显示获取三个空白微博就停止了。

**Comment by dataabc** [comment]
我测试了上面的微博，没有出现上面的问题，可能是之前速度太快被暂时限制了，限制过一段时间会自动解除，当end_date为日期时，可能会漏掉部分微博，建议改成now。

**Comment by aiden-leong** [comment]
> 我爬取id为[2508021512]的用户，日期设定为2018-1-1到2018-12-31，运行的时候显示获取三个空白微博就停止了。

@dataabc 这个情况是真实存在的。

https://github.com/dataabc/weiboSpider/blob/4c9c8bdc5232132ced5d54f04d946aac3c6b9f57/weibo_spider/parser/page_parser.py#L57

可以修改`page_parser.py`，调大重试次数，或者干脆注释掉。
```
if PageParser.empty_count > 2:
      self.to_continue = False
      PageParser.empty_count = 0
```
