### ISSUE TITLE
修改cookie并运行python3 -m weibo_spider命令后，并未自动生成一个weibo文件夹。

### ISSUE THREAD

**Issue by banlangen1111** [dataabc/weiboSpider#407]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：cookie修改完成后在weiboSpider目录下运行如下命令：
$ python3 -m weibo_spider
运行后，并未自动生成一个weibo文件夹

**Comment by dataabc** [comment]
运行后有其它信息吗，出错了吗？

**Comment by banlangen1111** [comment]
> 
没有出现报错。是命令出错。我的情况不是python3 -m weibo_spider，而是python -m weibo_spider

**Comment by banlangen1111** [comment]
> 谢谢您。
没有出现报错。是命令出错。我的情况不是python3 -m weibo_spider，而是python -m weibo_spider。
