### ISSUE TITLE
关于新浪微博搜索爬虫的小问题，求帮助

### ISSUE THREAD

**Issue by Shy0418** [dataabc/weiboSpider#409]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？

答：是

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。

答：通过user_id爬取的微博用户信息没有生日、所在地、学习经历、公司、注册时间、阳光信用
![7f9cc6aa496976eec596687bb9654a7](https://user-images.githubusercontent.com/86863443/150481293-7c41aad2-b2a2-4bfc-a90c-17f33f42f483.png)
。

**Comment by dataabc** [comment]
你使用的应该是免cookie版，添上cookie就可以了。

**Comment by Shy0418** [comment]
你好，我已经加上了cookie的结果。
按照您的教程，我改动的地方如下图所示，但貌似还是不行。我使用的是weibo-crawler这个项目。

**Comment by dataabc** [comment]
说明cookie无效，cookie能在本程序使用才是有效的。

**Comment by Shy0418** [comment]
啊，我按照您的readme里的方法，验证了我的cookie，确实是无效。那么请问这种情况该如何解决？我尝试过退出新浪微博账号重新登录，但没用。我是需要重新申请个小号，使用小号的cookie或者换其他账号的cookie吗？

**Comment by dataabc** [comment]
我是用readme方法获取cookie的，你再看看，换其他账号也可。

**Comment by Shy0418** [comment]
ok,非常感谢你的指导。提前祝您新年愉快！！

**Comment by Shy0418** [comment]
大哥，你好，我按照readme的方法获取cookie已经成功把代码运行起来了，原来，一定要按照readme里的方法即使用这个网址（

）获取的cookie才能运行。输出得加上“json”，才会显示性别，生日，教育信息等用户信息（

）。然后按照这readme方法获取cookie的时候，网页会经常提示url格式不对，我试了好几次才登录成功的。最后，真的非常非常感谢您能在百忙之中给予我帮助。
