### ISSUE TITLE
运行设置初始时间显示keyerror

### ISSUE THREAD

**Issue by dontclosemountain999** [dataabc/weiboSpider#410]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：
github
- 问：您使用的是否是最新的程序（是/否）？

答：
是
- 问：爬取任意用户都会运行出错吗（是/否）？是
<img width="548" alt="屏幕截图 2022-01-21 193748" src="https://user-images.githubusercontent.com/82384248/150520873-738d9c89-1e14-4afd-bfb2-557521f9b316.png">

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：
<img width="548" alt="image" src="https://user-images.githubusercontent.com/82384248/150520966-6e4822b9-641d-4b3f-b2b7-0676dfe63ed8.png">

**Comment by dataabc** [comment]
设置时间要修改config.json，参考下readme。

**Comment by dontclosemountain999** [comment]
> 设置时间要修改config.json，参考下readme。

欧拉
