### ISSUE TITLE
安装时提示错误

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#412]
使用的清华源，py默认的源怎么都连不上

ba2a/absl-py-0.9.0.tar.gz (104 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\jinqi\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jinqi\\AppData\\Local\\Temp\\pip-install-nzzbi61w\\absl-py_5270108e362b43d4b10270703ac2ed06\\setup.py'"'"'; __file__='"'"'C:\\Users\\jinqi\\AppData\\Local\\Temp\\pip-install-nzzbi61w\\absl-py_5270108e362b43d4b10270703ac2ed06\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jinqi\AppData\Local\Temp\pip-pip-egg-info-a2j1zl2v'
       cwd: C:\Users\jinqi\AppData\Local\Temp\pip-install-nzzbi61w\absl-py_5270108e362b43d4b10270703ac2ed06\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jinqi\AppData\Local\Temp\pip-install-nzzbi61w\absl-py_5270108e362b43d4b10270703ac2ed06\setup.py", line 34, in <module>
      raise RuntimeError('Python version 2.7 or 3.4+ is required.')
  RuntimeError: Python version 2.7 or 3.4+ is required.
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/1a/53/9243c600e047bd4c3df9e69cfabc1e8004a82cac2e0c484580a78a94ba2a/absl-py-0.9.0.tar.gz#sha256=75e737d6ce7723d9ff9b7aa1ba3233c34be62ef18d5859e706b8fdc828989830 (from https://pypi.tuna.tsinghua.edu.cn/simple/absl-py/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement absl-py==0.9.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.15.0, 1.0.0)
ERROR: No matching distribution found for absl-py==0.9.0

**Comment by dataabc** [comment]
感谢反馈。

我这几天没法调试，猜测可能是网络原因，不知道是否正确。

**Comment by gudaocode** [comment]
这个是作用在哪个部分的？好像运行起来没啥错误

**Comment by gudaocode** [comment]
目前尝试：
pip install absl-py
提示：
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: absl-py in c:\users\jinqi\appdata\local\programs\python\python310\lib\site-packages (1.0.0)
Requirement already satisfied: six in c:\users\jinqi\appdata\local\programs\python\python310\lib\site-packages (from absl-py) (1.16.0)
意思应该是安装好了吧？

但是执行我们的安装包时，提示是：

Collecting absl-py==0.9.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1a/53/9243c600e047bd4c3df9e69cfabc1e8004a82cac2e0c484580a78a94ba2a/absl-py-0.9.0.tar.gz (104 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jinqi\AppData\Local\Programs\Python\Python310\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jinqi\\AppData\\Local\\Temp\\pip-install-hq9mz_r5\\absl-py\\setup.py'"'"'; __file__='"'"'C:\\Users\\jinqi\\AppData\\Local\\Temp\\pip-install-hq9mz_r5\\absl-py\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jinqi\AppData\Local\Temp\pip-pip-egg-info-p63xeeu1'
         cwd: C:\Users\jinqi\AppData\Local\Temp\pip-install-hq9mz_r5\absl-py\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jinqi\AppData\Local\Temp\pip-install-hq9mz_r5\absl-py\setup.py", line 34, in <module>
        raise RuntimeError('Python version 2.7 or 3.4+ is required.')
    RuntimeError: Python version 2.7 or 3.4+ is required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\jinqi\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

 没搞懂什么意思，是没问题了么？

**Comment by dataabc** [comment]
应该和你的Python版本有关，换成最新的版本还有错吗

**Comment by gudaocode** [comment]
新装的机器，用的Python 3.10最新版
或许是3.10兼容性带来的问题吧，我用这个3.10，还碰到了同时涉及proxy和https时出现的问题。
