### ISSUE TITLE
当出现cookie过期时，能否给其他py提供信息，以供判断？

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#413]
我目前弄了个py，用os.system的方式运行您的爬虫，丢在NAS上周期运行
但是不会经常上去看，如果出现了Cookie过期的问题时，会不知道。
所以在想，能否当出现这个错误时，我在我那个py里面如何设置，可以知道返回的是这个错误，然后给我的bark推送个信息（话说，bark还是很好用的说，推荐）
感谢！

**Comment by dataabc** [comment]
这个暂时没法设置，你可以修改info_parser.py文件，上面的信息就出自这里，你可以在适当的位置将提示信息发送给bark等。

**Comment by gudaocode** [comment]
找到方法了，其他py里面运行时，给个参数就行了，参数是-1，就是出错了，只是没法分辨是其他原因出错还是cookie出错，但对我来说也算够用了
谢谢！
