### ISSUE TITLE
使用txt录取需要爬取的id时出错

### ISSUE THREAD

**Issue by curee-ee** [dataabc/weiboSpider#415]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答："1669879400","1223178222","1729370543"

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答："since_date": "2021-12-01",
    "end_date": "2022-01-01",

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：
![image](https://user-images.githubusercontent.com/74724256/153004902-765c2d70-7392-4a5a-a7aa-ae146c061332.png)

**Comment by dataabc** [comment]
感谢反馈。当使用txt时，since_date默认使用txt的配置，会不会是这个原因。如果还有问题，欢迎继续讨论。

**Comment by curee-ee** [comment]
谢谢回复！
“当使用txt时，since_date默认使用txt的配置”这句话不太能理解是什么意思，后来我设置了2021-2022一整年的时间，用txt爬取正常了！很感谢您的代码！
另外不知道能不能将年月日的时间和每日发布的时刻时间分开成两个参数结果呢？
如能回复十分感激！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上6:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 使用txt录取需要爬取的id时出错 (Issue #415)





 
感谢反馈。当使用txt时，since_date默认使用txt的配置，会不会是这个原因。如果还有问题，欢迎继续讨论。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by curee-ee** [comment]
感谢回复，刚刚重新查看数据发现许多用户的数据随机遗失了一些微博内容没有爬取，cookie是有效的，请问改如何解决呢？我为了不被禁，设置了"global_wait": [[300, 1800], [500, 2000]],
希望可以得到帮助，十分感激！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上6:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 使用txt录取需要爬取的id时出错 (Issue #415)





 
感谢反馈。当使用txt时，since_date默认使用txt的配置，会不会是这个原因。如果还有问题，欢迎继续讨论。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dataabc** [comment]
txt可以设置since_date，如果使用txt输入，就用这个。如果end_date不是now，会漏掉部分微博，这不是程序控制的。
