### ISSUE TITLE
csv爬取结果中微博ID显示不太正常，怎么样可以调节成数字，求教

### ISSUE THREAD

**Issue by lqz19980404** [dataabc/weiboSpider#419]
![ZV2$@JJZQ5ZF73__YG0}HKF](https://user-images.githubusercontent.com/75606302/155867825-5200532b-a77f-4c78-9b38-adedb297961d.png)

**Comment by dataabc** [comment]
可以使用程序weibo-crawler，这个id是显示数字的。
