### ISSUE TITLE
微博评论

### ISSUE THREAD

**Issue by DylanDenali** [dataabc/weiboSpider#420]
请问项目中有抓取部分/全部微博评论的功能吗？

**Comment by dataabc** [comment]
这个没有，weibo-crawler可以获取部分评论。

**Comment by dataabc** [comment]
可以选择，默认是按时间，也可以是热门，要修改settings.py。

**Comment by binchen19** [comment]
> weibo-crawler

请问有推荐的scripts可以给定微博id抓取所有评论吗？
