### ISSUE TITLE
请问有办法爬取某个地区的全部微博吗

### ISSUE THREAD

**Issue by CoinCheung** [dataabc/weiboSpider#421]
- 问：请说明需要什么新功能。

答：爬取某个地区的全部微博

- 问：请说明添加该功能的意义。（非必填）

答：比如爬出最近一个月在上海市浦东新区发布的微博这样的功能

**Comment by dataabc** [comment]
感谢反馈。只能获取指定用户的，地区的不行。

**Comment by CoinCheung** [comment]
请问这个是因为技术上不容易实现吗，比如微博不提供按地区搜索的功能，所以我们只能爬全部的微博然后按地区筛选?

**Comment by dataabc** [comment]
是技术上不能实现。
