### ISSUE TITLE
系统中可能没有安装或正确配置MySQL数据库，请先根据系统环境安装或配置MySQL，再运行程序

### ISSUE THREAD

**Issue by xmingpyccnu** [dataabc/weiboSpider#425]
程序正常运行一段时间后出现以下提示，然后程序运行结束。

提示：系统中可能没有安装或正确配置MySQL数据库，请先根据系统环境安装或配置MySQL，再运行程序

求解答。

**Comment by dataabc** [comment]
可能是配置写入mtsql，但是你没有安装mysql或者配置不正确。
