### ISSUE TITLE
爬虫过程中断网了一阵结果程序不结束也不继续跑了该怎么解决哇？难道要重头再来吗呜呜

### ISSUE THREAD

**Issue by BXpoomo** [dataabc/weiboSpider#428]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：

- 问：您使用的是否是最新的程序（是/否）？

答：

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by dataabc** [comment]
这只影响一个用户，如果微博不多，可以重来，如果多，可以根据日志，确定最后的微博日期，推测它的页码，然后修改spider.py的page相关的代码，将该页码设置成初始页。
