### ISSUE TITLE
用户所在地没有内容

### ISSUE THREAD

**Issue by JackLin24** [dataabc/weiboSpider#431]
不知可否把 有IP归属地的也一并爬下来 求问

**Comment by dataabc** [comment]
感谢反馈，目前还不知道如何加归属地，以后考虑。

**Comment by JackLin24** [comment]
望您能指教一下

**Comment by dataabc** [comment]
代码有说明，大致是在获取用户信息的方法下添加ip_location的获取，然后在写csv、json、mysql等文件的方法下，加上新属性。

**Comment by JackLin24** [comment]
> 代码有说明，大致是在获取用户信息的方法下添加ip_location的获取，然后在写csv、json、mysql等文件的方法下，加上新属性。

好的 谢谢您

**Comment by JackLin24** [comment]
您好 按照您的说法 添加了ip_location 但是好像IP属地的内容都是空的 附上图片和文件 若您有空可否帮忙查看下
![图片](https://user-images.githubusercontent.com/99023214/166138960-bcd1db13-53dd-4745-a954-1b027e308a00.png)
[weibo.zip](https://github.com/dataabc/weiboSpider/files/8598562/weibo.zip)

**Comment by dataabc** [comment]
猜测是不是只是添加了字段，但是没有加上数据？我这几天只有手机，不方便调试。你可以调试下，看看是不是字段为空。

**Comment by JackLin24** [comment]
好的谢谢 我再试试 您哪天有条件了 也可帮我看一下 很感谢您的回复

**Comment by mengshixing** [comment]
> 您好 按照您的说法 添加了ip_location 但是好像IP属地的内容都是空的 附上图片和文件 若您有空可否帮忙查看下 ![图片](https://user-images.githubusercontent.com/99023214/166138960-bcd1db13-53dd-4745-a954-1b027e308a00.png) [weibo.zip](https://github.com/dataabc/weiboSpider/files/8598562/weibo.zip)

hi 你有新的进展了么，我也遇到了同样的问题

**Comment by songzy12** [comment]
我刚看了一下，ip属地在 m.weibo.cn 的个人信息页目前是没有的；对比：

- https://weibo.cn/1775794015/info
- https://weibo.com/u/1775794015

所以目前还无法实现。
