### ISSUE TITLE
粉丝、关注数据获取

### ISSUE THREAD

**Issue by bei2love** [dataabc/weiboSpider#434]
- 问：请说明需要什么新功能。

答：后续会考虑增加爬取用户的粉丝和关注的数据功能么

- 问：请说明添加该功能的意义。（非必填）

答：

**Comment by bei2love** [comment]
> 感谢建议，目前没有添加这个的打算，你可以查看weibo-fellow，可以获取关注。

感谢回复，最近在关注这个。但是因为微博的安全设置，总是不能获取更多的粉丝信息，安装您另一个项目的思路。需要梳理出某个明星的粉丝，还是需要一些功夫的。如果有相关经验，请指点一二

**Comment by dataabc** [comment]
我也没获取过粉丝信息，你网上搜索看看。
