### ISSUE TITLE
下载转发微博的图片和视频的控制

### ISSUE THREAD

**Issue by sa1yi2** [dataabc/weiboSpider#436]
您好，请问我想有些微博下载转发微博的图片和视频，有些微博不想下载，我应该怎么调？以前crawl可以直接在config.json里调节1和0，这个spider我应该在哪里控制，谢谢！

**Comment by dataabc** [comment]
这个暂时无法控制。

**Comment by sa1yi2** [comment]
那那个转发怎么下载呢？我现在全部的转发都是显示正在过滤

**Comment by dataabc** [comment]
只能使用crawler下载目前。

**Comment by sa1yi2** [comment]
我现在的问题又是我的crawl不能用cookie下载，换了两个号都一样，难道是因为我在海外的关系吗？被限制了吗？

**Comment by dataabc** [comment]
这个我也不确定，可能是crawl还有bug，需要完善。

**Comment by sa1yi2** [comment]
那spider会考虑加入这个功能吗？

**Comment by dataabc** [comment]
目前没有加入的计划。
