### ISSUE TITLE
爬取微博时每一页都会少爬1-2条微博

### ISSUE THREAD

**Issue by weiyedeng** [dataabc/weiboSpider#437]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？

答：不确定，但我爬取的3个用户都出现了同样的情况

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。

答：不太清楚是否是爬取了太久导致的问题。有些时候一页只能爬取9条，有时候是8条，但一开始使用的时候似乎基本都是每页都能爬满。

**Comment by dataabc** [comment]
感谢反馈。最近不方便调试，过几天看看，不确定是不是网页格式变了，再次感谢。

**Comment by weiyedeng** [comment]
oh我设置的是具体时间。可以知道一下为什么会少爬取吗？我可能需要稍微解释一下~

**Comment by DragonL915** [comment]
据说是引用了其他的url，你看下作者的回复
https://github.com/dataabc/weiboSpider/issues/440#issuecomment-1125065226
