### ISSUE TITLE
长微博不能获取全文

### ISSUE THREAD

**Issue by liu-song** [dataabc/weiboSpider#44]
Traceback (most recent call last):
Error:  'NoneType' object has no attribute 'xpath'
  File "/Users/song/Downloads/weiboSpider-master/weiboSpider.py", line 89, in get_long_weibo

长文博不能获取全文   已经显示的文字的结尾 所爬的结果    ...全文   

是需要设置延时吗

**Comment by liu-song** [comment]
用户ID：5019711860

谢谢

**Comment by ljy123liu** [comment]
#40 有新代码 get_long_weibo ，替换掉就可以了

**Comment by liu-song** [comment]
貌似不行啊   这样的错误

Traceback (most recent call last):
  File "/Users/song/Downloads/weiboSpider/weiboSpider.py", line 57, in get_user_info
    str_wb = selector.xpath(
AttributeError: 'NoneType' object has no attribute 'xpath'

**Comment by ljy123liu** [comment]
@liu-song 你这个也不是替换报错的吧，你这个不是报错在获取用户信息那里了，你自己看看代码吧。我昨天替换的，我这边可以获取到全文

**Comment by dataabc** [comment]
@liu-song 报错说明selector为空，是否修改过get_user_info代码?

**Comment by liu-song** [comment]
@ljy123liu 能获取部分长文，之后就不行了，可能是长文的属性也不太一样，不同的用户爬取的结果不太一样。 @dataabc   get_user_info没有修改过，我下载再试了一遍，仅替换get_long-weibo还是如此。能爬取一部分信息已经很好了，感谢开源

**Comment by dataabc** [comment]
@liu-song get_long_weibo的错误通过上面替换代码的方法可以解决；用微博id 5019711860试了几遍，没有复现get_user_info的错误。以前曾经因为微博id写错了，在get_user_info出过"list index out of range"错误，但你的微博id是对的，不知道是不是微博爬虫账号问题

**Comment by redMUSCLE** [comment]
我也出现了这个问题。今天检查备份的时候一惊：但凡是字数多点的微博，后边都有【...全文】。
我并未修改过get_long_weibo的参数。同时程序运行正常，没有报错。
我再次修改了几次cookie（分别用几个小号），爬取同一个人的微博，还是会有【...全文】这样的情况呢。请问该怎么解决？

**Comment by dataabc** [comment]
@redMUSCLE 
可能是爬的速度太快了，可以减慢速度试试，具体是修改方法get_weibo_info的代码，具体代码如下：
```
if (page-page1) % random_pages == 0 and page < page_num:
    sleep(random.randint(6,10))
    page1 = page
    random_pages = random.randint(1,5)
```
这是默认的随机等待策略：每1到5页随机等待6到10秒，你可以修改上面的数字，加快等待频率和加长等待时间等等，来避免被限制。
程序爬长微博的思路是首先获取文本列表页中长微博的微博内容，这时内容是不完整的，然后尝试打开并获取对应长微博的详情页。如果获取成功就将原来不完整的内容更新为获取到的完整信息。因为被限制或者网络原因，长微博的详情页获取失败，导致结果中出现很多不完整的微博。如果是被限制，一段时间限制会自动解除。
另外，更换cookie不一定能解除限制，因为ip也会被限制。如果可以，你也可以用小号在其它电脑上测试下。

**Comment by redMUSCLE** [comment]
您好，之前我用的一直是一月份的weibo-crawler-master，代码里不含get_weibo_info
于是刚刚下载并运行了最新版本（昨日更新的）weibospider。发现报错如下：
Error:  'pic_download'
Traceback (most recent call last):
  File "C:\Users\Assunta\Downloads\weiboSpider-master (1)\weiboSpider-master\weiboSpider.py", line 1093, in main
    wb = Weibo(config)
  File "C:\Users\Assunta\Downloads\weiboSpider-master (1)\weiboSpider-master\weiboSpider.py", line 26, in __init__
    self.validate_config(config)
  File "C:\Users\Assunta\Downloads\weiboSpider-master (1)\weiboSpider-master\weiboSpider.py", line 68, in validate_config
    if config[argument] != 0 and config[argument] != 1:
KeyError: 'pic_download'

我的json设置中可调自选参数都写的是零，在crawler上可以顺滑运行
而我怎么反复更改也都无法让spider合理运行。
请问我应该怎么办？谢谢

**Comment by dataabc** [comment]
@redMUSCLE 
感谢反馈，能否提供user_id，方便调试，谢谢

**Comment by dataabc** [comment]
@redMUSCLE 
优化了长微博的获取，主要是修改了get_long_weibo方法。以前思路是如果是长微博，就去它的详情页获取，获取成功就更新，否则使用在微博列表页获取的不完整的内容。现在的思路是尝试获取5次，如果5次都获取失败，才使用在列表页获取的不完整的内容。之所以只尝试5次是因为这样不影响后续爬取，如果你坚持想获取每条长微博的完整内容，可以提高尝试次数或者把for循环改成while true

**Comment by Symbolk** [comment]
@dataabc 你好，经尝试从Issue中提到的方法后，发现这个问题还是存在，我的config.json如下：

```
{
    "user_id_list": ["1650111241"],
    "filter": 0,
    "since_date": "2023-02-05",
    "end_date": "now",
    "random_wait_pages": [1, 5],
    "random_wait_seconds": [16, 30],
    "global_wait": [[1000, 3600], [500, 2000]],
    "write_mode": ["csv", "txt", "json"],
    "pic_download": 0,
    "video_download": 0,
	"file_download_timeout": [5, 5, 10],
	"result_dir_name": 0,
    "cookie": "...
}

```

**Comment by dataabc** [comment]
@Symbolk 您可以尝试weibo-crawler版本。

**Comment by Symbolk** [comment]
好的👌
