### ISSUE TITLE
程序没爬到since_date设置的日期就自动结束了，请问是哪里需要设置总爬取数吗？

### ISSUE THREAD

**Issue by fxx-real** [dataabc/weiboSpider#447]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：Pypi版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：目前只试过一个用户

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：user_id：2803301701  since_date：2019-12-31  end_date：2020-5-17

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：爬取着2803301701这个用户，设置的日期是2019-12-31到2020-5-17每次爬取不到一个月程序就会自动结束，期间尝试过一个月为间隔爬取，但也会遇到爬取几天就结束的问题。2020-5-17开始总会在2020-04-14停下来

**Comment by dataabc** [comment]
感谢反馈。当end_date为非now时，程序不稳定，建议改成now。

**Comment by fxx-real** [comment]
好的 感谢
