### ISSUE TITLE
cookie复制问题

### ISSUE THREAD

**Issue by qqqqmmmm** [dataabc/weiboSpider#449]
请问cookie应该复制哪些进config.json中，我复制cookie：后的全部，程序提示 cookie错误或已过期,请按照README中方法重新获取。这个问题可能非常愚蠢，但是希望得到您的回复。

**Comment by dataabc** [comment]
就是cookie：后的，按照read me一步步的来。

**Comment by Breeze1114** [comment]
按照readme来获取的cookie，但是还是显示错误或已过期
