### ISSUE TITLE
文件保存问题

### ISSUE THREAD

**Issue by FXM12581** [dataabc/weiboSpider#451]
您好，我想请教一下我一次爬取多个用户信息时，怎么把这些信息写入到一个文件（如txt,csv)中而不是像之前那样每个用户一个文件

**Comment by dataabc** [comment]
如果仅用户信息，weibo-crawler可以找到，如果包含微博，需要修改代码。

**Comment by dataabc** [comment]
weibo-crawler的write_csv方法有file_fath变量，你可以把它改成固定值，这样csv就会写作一个文件里。
