### ISSUE TITLE
按照readme来获取的cookie，但是还是显示错误或已过期

### ISSUE THREAD

**Issue by Breeze1114** [dataabc/weiboSpider#454]
按照readme来获取的cookie，但是还是显示错误或已过期
![image](https://user-images.githubusercontent.com/46240676/173970955-03beec1a-5e13-4f86-944d-66174712d265.png)

**Comment by dataabc** [comment]
一般来说，就是cookie的问题，您可以再次尝试或换个账号，如果方便的话。

**Comment by maying0120** [comment]
也遇到这个问题 换了另一个账号的cookie也不行

**Comment by dataabc** [comment]
@maying0120 应该就是cookie问题，或者使用免cookie版

**Comment by mujiangxielu** [comment]
![image](https://user-images.githubusercontent.com/44597051/185777259-d15c9b05-2119-4b2c-a4e3-c71493aa0f97.png)
同问，换了好几个账号刷新好几次还是这个问题，选择手机模式也没用
