### ISSUE TITLE
微博id写入csv文件后自动改变，个位数变为0

### ISSUE THREAD

**Issue by Liuhaidong09** [dataabc/weiboSpider#456]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：

- 问：您使用的是否是最新的程序（是/否）？

答：

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by dataabc** [comment]
没有改变，只是显示不全，如果方便，换个软件打开看看。

**Comment by Liuhaidong09** [comment]
好的好的谢谢您啦！昨晚解决了



---- 回复的原邮件 ----
| 发件人 | Chen ***@***.***> |
| 日期 | 2022年06月23日 22:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [dataabc/weiboSpider] 微博id写入csv文件后自动改变，个位数变为0 (Issue #456) |

没有改变，只是显示不全，如果方便，换个软件打开看看。
