### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by 2426852837** [dataabc/weiboSpider#465]
你好，运行spider.py时17行出现问题
from . import config_util, datetime_util
ImportError: attempted relative import with no known parent package
包括之后的几行也出现目录错误的问题，我python版本是3.7，求解答

**Comment by 2426852837** [comment]
我解决了，到现在为止是可以跑的

**Comment by 276676521** [comment]
> 我解决了，到现在为止是可以跑的，而且数据爬下来了

可以请教一下怎么解决的吗 我也遇到了这个问题

**Comment by 84yy** [comment]
@2426852837 怎么解决的老铁

**Comment by 84yy** [comment]
from weibo_spider import config_util, datetime_util
from weibo_spider.downloader import AvatarPictureDownloader
from weibo_spider.parser import AlbumParser, IndexParser, PageParser, PhotoParser
from weibo_spider.user import User

把导入的相对路径改为绝对路径解决了
