### ISSUE TITLE
能开发出获取评论的功能么？

### ISSUE THREAD

**Issue by sg-zhu** [dataabc/weiboSpider#466]
- 问：请说明需要什么新功能。

答：
能开发出获取评论的功能么？万分感谢！
- 问：请说明添加该功能的意义。（非必填）

答：因为这样可能可以拯救好多人的生命，很多心理有问题的人，好多都是在评论里才找得到

**Comment by dataabc** [comment]
感谢建议。暂时没有这个打算，你可以使用weibo-crawler，这个是可以获取评论的。

**Comment by sg-zhu** [comment]
好的好的 谢谢

**Comment by diguage** [comment]
这个功能确实很需要，建议开发啊
