### ISSUE TITLE
请问能开发出抓取粉丝属性的功能吗？

### ISSUE THREAD

**Issue by KristHu** [dataabc/weiboSpider#469]
- 问：请说明需要什么新功能。

答：微博粉丝属性，比如迪丽热巴的粉丝有8千万，能否开发出爬取这8千万粉丝性别、年龄、职业等信息

- 问：请说明添加该功能的意义。（非必填）

答：分析某些艺人的粉丝属性，对产要发布的产品进行定位

**Comment by dataabc** [comment]
感谢建议，这个感觉没法实现，因为无法获取全部粉丝，只能得到极少部分，这样分析不准确。

**Comment by libraprince** [comment]
涉及个人隐私问题，不建议这样做吧！

**Comment by KristHu** [comment]
> 感谢建议，这个感觉没法实现，因为无法获取全部粉丝，只能得到极少部分，这样分析不准确。

好的，了解了，谢谢
