### ISSUE TITLE
cookie问题

### ISSUE THREAD

**Issue by zcs0001** [dataabc/weiboSpider#471]
cookie错误或已过期,请按照README中方法重新获取
换cookie之后是没问题的，我想知道这句话的代码在哪，或者是怎么判断cookie过没过期的

**Comment by dataabc** [comment]
好像在spider.py，根据昵称判断，如果cookie无效，昵称好像是“登录”之类的。应该就是cookie过期了，如果不行可以使用weibo-crawler。

**Comment by BigCatDi** [comment]
> 好像在spider.py，根据昵称判断，如果cookie无效，昵称好像是“登录”之类的。应该就是cookie过期了，如果不行可以使用weibo-crawler。

我的也是同样的问题，cookie确定没错。但就是显示这个问题
