### ISSUE TITLE
微博关注这具体信息

### ISSUE THREAD

**Issue by BigCatDi** [dataabc/weiboSpider#473]
- 问：请说明需要什么新功能。

答：想获取微博关注数的具体信息和粉丝的具体信息。谢谢

- 问：请说明添加该功能的意义。（非必填）

答：想对微博关注者和粉丝进行社区检测，探索图分布。谢谢

**Comment by BigCatDi** [comment]
> 因为部分微博粉丝较多，这是没有办法获取全的。

谢谢您，麻烦了，那仅仅获取关注者粉丝的id昵称，注册和关注时间可以吗？

**Comment by dataabc** [comment]
如何粉丝过多，就没法获取了。
