### ISSUE TITLE
定时功能

### ISSUE THREAD

**Issue by KT197** [dataabc/weiboSpider#474]
请问怎样添加下方代码，实现定时功能。

def auto_spider(stop_time):
    schedule.every(1).minutes.do(main)
    while True:
        if datetime.datetime.now().strftime('%H:%M') <= stop_time:
            schedule.run_pending()
            time.sleep(60)
        else:
            break

if __name__ == '__main__':
    auto_spider('22:00')

**Comment by KT197** [comment]
import time
import datetime
import schedule

import os
import sys

from absl import app
sys.path.append(os.path.abspath(os.path.dirname(os.getcwd())))
from weibo_spider.spider import main as mn


def func():
    app.run(mn)


def auto_spider(stop_time):
    schedule.every(1).minutes.do(func)
    while True:
        if datetime.datetime.now().strftime('%H:%M') <= stop_time:
            schedule.run_pending()
            time.sleep(600)
        else:
            break

if __name__ == '__main__':
    auto_spider('20:00')

对原文件进行了修改，但是无法实现定时刷新，不知道是方法不对，还是代码错误了

**Comment by dataabc** [comment]
你可以使用第三方工具定时执行程序。
