### ISSUE TITLE
config.json格式不正确

### ISSUE THREAD

**Issue by huohaozi** [dataabc/weiboSpider#476]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：GitHub

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：config.json格式不正确
![$ATZY~572I76O5 ORZAFBQP](https://user-images.githubusercontent.com/113079122/189856915-36b1ab3e-5e95-48ae-bcab-c4019d0abded.png)
![36N(PU`~%N}G3AABX 0Y4(E](https://user-images.githubusercontent.com/113079122/189856935-6f9bf996-29dc-4dde-9c41-825d68c7fc2e.png)

**Comment by dataabc** [comment]
应该就是格式问题，肉眼看不到，你可以先使用最初的config.json，然后一点点修改，看在哪里出错，再修改。

**Comment by huohaozi** [comment]
您方便提供一个成功的cookie可以给我试下嘛？我换了好多个都不可以&nbsp; 就没法再试其他的参数&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] config.json格式不正确 (Issue #476)





 
应该就是格式问题，肉眼看不到，你可以先使用最初的config.json，然后一点点修改，看在哪里出错，再修改。

**Comment by songzy12** [comment]
在翻历史 issue，恰好看到了这条。

根据截图里的情况看起来是 cookie 的值在复制填充后其最后的双引号被自动换到了下一行。
