### ISSUE TITLE
程序出错

### ISSUE THREAD

**Issue by zcs0001** [dataabc/weiboSpider#479]
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\PythonProjects\django4.4\crawler\spider.py", line 178, in get_weibo_info
    weibos, self.weibo_id_list, to_continue = PageParser(
  File "D:\PythonProjects\django4.4\crawler\parser\page_parser.py", line 45, in __init__
    info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
共爬取0条原创微博
信息抓取完毕

我把这个程序放到django中，为了爬完一次之后，可以在网页端输入网址接着爬，之前还是可以的，但现在爬完之后，不管再爬哪个用户，都会出现这个问题

**Comment by zcs0001** [comment]
好像是因为我最后一部分不是id，是英文

**Comment by minshengxinwen** [comment]
> 好像是因为我最后一部分不是id，是英文

请问解决了吗？我也遇到了同样的问题。只能爬取几十条数据，然后就停止了。

**Comment by zcs0001** [comment]
主页url里是英文的话，你在用户的微博里再点那个用户，网址里最后一个就是id了
至于爬几十条数据，我也不太懂，有时候确实很快就报错结束了，有时候就能完整爬下来
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataabc/weiboSpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 程序出错 (Issue #479)





  
好像是因为我最后一部分不是id，是英文
  
请问解决了吗？我也遇到了同样的问题。只能爬取几十条数据，然后就停止了。
