### ISSUE TITLE
多账号的情况下无法使用

### ISSUE THREAD

**Issue by MTmin** [dataabc/weiboSpider#480]
- 问：请说明需要什么新功能。

答：添加多账号的设置,目前多账号的时候只会读取一个号的群,且如果是在其他bot账号添加的订阅,也会提示群聊不存在

- 问：请说明添加该功能的意义。（非必填）

答：

**Comment by dataabc** [comment]
感谢反馈。我没明白您的意思，您是不是说添加多个cookie账户？

**Comment by MTmin** [comment]
> 感谢反馈。我没明白您的意思，您是不是说添加多个cookie账户？

是如果nb2链接了多个机器人的QQ号,本插件只显示其中一个的,如果机器人A在这个群里添加了订阅,机器人B不在这个群里就无法推送,会提示群聊不存在,可能是因为本插件读取到的只有机器人B

**Comment by dataabc** [comment]
是不是回复错了？本程序只是获取微博的，和QQ没关系啊。

**Comment by MTmin** [comment]
> 是不是回复错了？本程序只是获取微博的，和QQ没关系啊。

没有没有,是nb2对接了go-cq以后出现的!

**Comment by dataabc** [comment]
本程序只和微博有关，用来获取微博，不知道是不是您的程序使用了本程序的代码，我现在一头雾水。
