### ISSUE TITLE
weibo user profile url wrong

### ISSUE THREAD

**Issue by huaiwens** [dataabc/weiboSpider#482]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？

答：latest

- 问：您使用的是否是最新的程序（是/否）？

答：yes

- 问：爬取任意用户都会复现此bug吗（是/否）？

答：yes

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。

答：
Original codes return all weibos that this user can see but not the ones that this user created(or forward).
Please check below codes section for the changes.

b/weibo_spider/parser/index_parser.py

-        self.url = 'https://weibo.cn/%s' % (user_uri)
+        self.url = 'https://weibo.cn/%s/profile' % (user_uri)

b/weibo_spider/parser/page_parser.py

-        self.url = 'https://weibo.cn/%s?page=%d' % (self.user_uri, page)
+        self.url = 'https://weibo.cn/%s/profile?page=%d' % (self.user_uri, page)

**Comment by dataabc** [comment]
感谢反馈。

您的意思是现在的代码无法获得全部微博，而修改后的可以吗？我现在不方便调试，如果您方便，可以通过pull request的方式修改代码，这样您还可以成为本项目的contributor。如果您不方便，不提交也没关系，这不是强制的。无论如何，都感谢您的热心反馈，再次感谢。

**Comment by huaiwens** [comment]
您好，
我的意思是目前代码运行后抓取的是某微博用户全部的微博，包括他关注的人发的微博也在内，我作为使用者本意仅仅想抓取该用户原创或者转发的那些微博。
因此需要改一下url，一个很小的改动。我试过改过以后就仅仅抓取该用户为作者的那部分微博了。pull request 等我有时间再说哈。:)



发自我的iPhone


------------------ Original ------------------
From: Chen Lei ***@***.***&gt;
Date: Sun,Oct 16,2022 9:09 PM
To: dataabc/weiboSpider ***@***.***&gt;
Cc: huaiwens ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dataabc/weiboSpider] weibo user profile url wrong (Issue #482)





 
感谢反馈。
 
您的意思是现在的代码无法获得全部微博，而修改后的可以吗？我现在不方便调试，如果您方便，可以通过pull request的方式修改代码，这样您还可以成为本项目的contributor。如果您不方便，不提交也没关系，这不是强制的。无论如何，都感谢您的热心反馈，再次感谢。

**Comment by dataabc** [comment]
明白了，感谢热心回复。
