### ISSUE TITLE
保存的实现类里，能不能请求一个接口，把json传过去

### ISSUE THREAD

**Issue by 1311433098** [dataabc/weiboSpider#485]
- 问：请说明需要什么新功能。

答：在保存数据时，实现把要保存的json请求一个接口，我自己实现保存逻辑

- 问：请说明添加该功能的意义。（非必填）

答：我可以把数据保存到一些非通用的数据库

**Comment by dataabc** [comment]
感谢建议。目前没计划实现这个接口，未来可能会。您可以修改json_writer.py，它包含了写入json的操作，如果想自定义，应该符合您的需求。
