### ISSUE TITLE
如何修改csv中图片链接的写法

### ISSUE THREAD

**Issue by SingleRottenChips** [dataabc/weiboSpider#486]
csv中的多个图片urls是以逗号来间隔的，请问有什么方法可以将其改成空格吗？多谢！

**Comment by dataabc** [comment]
修改page_parser.py的extract_picture_urls方法，把picture_urls = ','.join(picture_list)改成picture_urls = ' 
 '.join(picture_list) 。

**Comment by SingleRottenChips** [comment]
> 修改page_parser.py的extract_picture_urls方法，把picture_urls = ','.join(picture_list)改成picture_urls = ' '.join(picture_list) 。

感谢回复。请问是这样改吗？
![image](https://user-images.githubusercontent.com/63144489/198280609-65beaa91-bac8-4588-b26e-2db2ba4ffd49.png)
可是我改了之后，csv里依旧是逗号。
另外，在我视频链接那段里看到"m.weibo.cn/s/video/show?object_id="，我想保存视频的页面“https://video.weibo.com/show?fid=” 请问也可以简单地通过修改哪一行做到吗？谢谢。

**Comment by dataabc** [comment]
我现在没法调试，应该就是这样，可能你之前安装了pip的版本，默认运行的它，所以修改无效吧，要先卸载pip版。video_page_url就是视频网址。

**Comment by SingleRottenChips** [comment]
> 我现在没法调试，应该就是这样，可能你之前安装了pip的版本，默认运行的它，所以修改无效吧，要先卸载pip版。video_page_url就是视频网址。

感谢回复。那我不卸载了，就偶尔需要的时候在excel里替换好了。有看到video_page_url，但无奈才疏学浅，完全不知道怎么改写 lol. 如果大佬没空的话，我把这帖子开着看看会不会有其他能者也有这需要吧。微博可以在正文里输入视频网址以转载——包括半年前不可见的——视频哟，很好用的。
