### ISSUE TITLE
运行出现缺少库，出现ModuleNotFoundError: No module named 'absl'

### ISSUE THREAD

**Issue by BigCatDi** [dataabc/weiboSpider#487]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版本

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：ModuleNotFoundError: No module named 'absl'

在运行程序时出现了，ModuleNotFoundError: No module named 'absl'，但是库都安装成功？麻烦您，谢谢！

**Comment by dataabc** [comment]
感谢反馈。应该是没安装模块或者错安装成了Python2版了。
