### ISSUE TITLE
pip install -r requirements.txt时出错

### ISSUE THREAD

**Issue by Alpenl** [dataabc/weiboSpider#488]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：安装包时报错
![image](https://user-images.githubusercontent.com/112090565/198981347-199f8793-ec3c-4390-a870-6677ada243f5.png)

**Comment by dataabc** [comment]
感谢反馈。是不是Python版本不对，需要Python3.4以上的版本。

**Comment by Alpenl** [comment]
不是，我用的版本是3.10
![image](https://user-images.githubusercontent.com/112090565/199021446-7de16925-7ea7-45f9-980d-a728c4bacb8b.png)

**Comment by dataabc** [comment]
好像是absl安装失败了，单独用pip安装看看。

**Comment by linbuxiao** [comment]
> 好像是absl安装失败了，单独用pip安装看看。

https://github.com/abseil/abseil-py/issues/161 需要升级 absl 到 0.12.0 版本

**Comment by linbuxiao** [comment]
@dataabc 已经修复，可以关闭 issue。

**Comment by dataabc** [comment]
@linbuxiao 每个人的情况不同，一般等提问者自己关或者程序自动关。
