### ISSUE TITLE
作者可否加一个倒序爬取微博的判断，从lastpage开始爬取，我发现会有爬取总数不完整的情况？

### ISSUE THREAD

**Issue by sunbat** [dataabc/weiboSpider#49]
给你提供个id： 有个梨UGlee 1655747731
 
共31859条微博，其中874条为原创微博
我爬取的最后一条微博为 2018-12-29 17:45当天的。

之前日期的原创微博就没有爬取到了实际上他的原创微博并不止这些，所以问一下这个是什么问题？

**Comment by dataabc** [comment]
关于倒叙爬取微博可以参考#43
爬取不完整有出错提示吗？能否提供出错提示，谢谢

**Comment by sunbat** [comment]
> 关于倒叙爬取微博可以参考#43
> 爬取不完整有出错提示吗？能否提供出错提示，谢谢

1.倒序的我已经参考那个issue。
2.爬取不完整的问题，我这边控制台没有发现出错提示异常。
我这边是想爬取原创微博跨度（2011-2019），但是我发现未爬取的原创微博并未收录在url上的?filter=1的结果集里（我很确信2016年里面还有原创微博，只是没有筛选出来）。
这个应该是微博本身的问题，你觉得呢？

**Comment by sunbat** [comment]
你可有微信，方便加个好友吗 @dataabc

**Comment by dataabc** [comment]
其实我更怀疑"有个梨UGlee"确实没有2016的原创微博，也可能博主把以前的微博删除了。该账号一共显示有"31863"条微博，事实上，它可能没有这么多微博。以前我发现爬取的微博数和显示的微博数不同，以为漏爬了，就手动浏览了某些微博数较少的微博，一条条的数，发现显示的微博比存在的微博数量多，不知道是不是某条微博删除了，总数却没有减1，这只是我的怀疑。
在它的[列表页](https://weibo.cn/u/1655747731)有3185页，每页有10条微博，最后一页可能不到10条，也就是说它的微博数量在31841-31850之间，这也是本程序可爬取的微博数量，与它显示的31863相差不多，所以我认为微博没有问题，没有2016的原创微博可能是因为那些微博被删除了。
另外，github上也可以讨论问题，不一定用微信，这样也挺好。

**Comment by dataabc** [comment]
刚刚发现，今天上午还在的原创微博竟然没有了，可能确实是微博给隐藏了，现在原创微博只显示到了2018-12-29 22:40:29，这么看，微博可能把它们混在了全部微博里，原创微博列表里没有显示出来，你的猜测是对的。

**Comment by dataabc** [comment]
现在可以爬取全部原创微博了，因为现在是先爬全部微博，然后再从中根据不同格式判断原创微博，提取之。有个梨UGlee有3万多条微博，为了防止你的账号被限制，最好每爬几页sleep一段时间

**Comment by sunbat** [comment]
好的  多谢

**Comment by sunbat** [comment]
好的 多谢
