### ISSUE TITLE
什么新功

### ISSUE THREAD

**Issue by codehelloworld22** [dataabc/weiboSpider#490]
- 问：请说明需要什么新功能。

答：
你能做一个微博图片链接搜索器吗

- 问：请说明添加该功能的意义。（非必填）

答：

**Comment by dataabc** [comment]
感谢反馈。目前没有该计划。

**Comment by linbuxiao** [comment]
微博图片链接搜索器 具体是指？

**Comment by codehelloworld22** [comment]
即使是微博被删除的账号，图片链接和文件依然保留。

**Comment by linbuxiao** [comment]
> 微博被删除的

保留后呢

**Comment by codehelloworld22** [comment]
微博上有一个图片托管服务器，名字叫ww1.sinaimg.cn，即使删除了微博账号，图片托管服务器上存储的照片也会保留在图片托管服务器上。
因此，你能做一个微博图片托管服务器链接查找器吗？

**Comment by codehelloworld22** [comment]
打扰一下？

**Comment by jerrylaikr** [comment]
你这个功能描述也太宽泛了一些，最好可以详细描述一下需求的使用场景，输入和输出分别是什么这样。
使用这个项目的爬虫是可以做到爬取现存用户的所有图片链接并保存到本地文件或数据库中，即使该用户之后被删除应该也可以访问图片。但是如果微博账号已删除的用户，主页都访问不了，还能怎么爬取该用户的任何内容？

**Comment by codehelloworld22** [comment]
我不能只搜索 ww1.sinaimg.cn 上托管的所有图片的链接吗？

**Comment by codehelloworld22** [comment]
不能访问被删除用户的主页，但是照片的链接是存在的，而且微博好像在每个用户的图片链接前都放了用户自己的图片名。也许你可以使用它？
例）https://wx1.sinaimg.cn/mw690/65d6c939ly1ha6xlayb2wj20u03wo7sk.jpg

https://wx3.sinaimg.cn/mw690/65d6c939ly1ha6oecjj8yj20n00odq8d.jpg

**Comment by jerrylaikr** [comment]
> 不能访问被删除用户的主页，但是照片的链接是存在的，而且微博好像在每个用户的图片链接前都放了用户自己的图片名。也许你可以使用它？ 例）https://wx1.sinaimg.cn/mw690/65d6c939ly1ha6xlayb2wj20u03wo7sk.jpg
> 
> https://wx3.sinaimg.cn/mw690/65d6c939ly1ha6oecjj8yj20n00odq8d.jpg

我还是不太能理解你所描述的思路。现在更麻烦的情况是无法通过爬取的url访问图片，就算爬下来也没有用，详见我发的另一个issue：https://github.com/dataabc/weiboSpider/issues/503
