### ISSUE TITLE
pip install -r requirements.txt报错，

### ISSUE THREAD

**Issue by siperuisf** [dataabc/weiboSpider#493]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：   *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml, idna, absl-py, requests
  Attempting uninstall: lxml
    Found existing installation: lxml 4.9.0
    Uninstalling lxml-4.9.0:
      Successfully uninstalled lxml-4.9.0
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      Building lxml version 4.9.1.
      Building without Cython.
      Building against pre-built libxml2 andl libxslt libraries
      running install

**Comment by siperuisf** [comment]
C:\Users\Ye\AppData\Local\Temp\xmlXPathInithx_5sb3e.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of lxml
  Moving to c:\users\ye\appdata\local\programs\python\python311\lib\site-packages\lxml-4.9.0.dist-info\
   from C:\Users\Ye\AppData\Local\Programs\Python\Python311\Lib\site-packages\~xml-4.9.0.dist-info
  Moving to c:\users\ye\appdata\local\programs\python\python311\lib\site-packages\lxml\
   from C:\Users\Ye\AppData\Local\Programs\Python\Python311\Lib\site-packages\~xml
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

F:\software\weiboSpider-master\weiboSpider>

**Comment by siperuisf** [comment]
系统是win的，求助，按网上的办法都试了，装了wheel和lmxl，还是不行....

**Comment by dataabc** [comment]
可能安装成了Python2？不确定。

**Comment by zxc110** [comment]
换个Python的版本,你的版本太新了。Python 3.11.x不兼容win的lxml 4.9.1，目前官网lxml winamd64的版本最高支持到3.10.x换成这个版本就行了。重新运行下pip install -r 文本名包括后缀，然后就可以用了，不知道是不是我的电脑问题，我得等半分钟命令窗口才有信息刷新。
