### ISSUE TITLE
新手小白 想问大佬如何将weibo-follow的功能在这个项目上实现

### ISSUE THREAD

**Issue by Gywikun** [dataabc/weiboSpider#495]

**Comment by dataabc** [comment]
感谢反馈。不建议新手这么做，如果非要做，可以修改spider.py的get_one_user方法，这是获取单个微博的方法，你可以把获取关注的代码放在这个文件里面，然后在方法里调用它，当然要修改关注的代码。

**Comment by Gywikun** [comment]
好的   谢谢大佬   大佬我还有一个问题  如果想要把这个做成网页形式   是要怎么办呢？

**Comment by dataabc** [comment]
我没这么做过，猜测可以用重新直接下载网页或者用获取的信息组成html代码。

**Comment by Gywikun** [comment]
好的 谢谢大佬
