### ISSUE TITLE
如何只爬取微博用户信息

### ISSUE THREAD

**Issue by wl-wus** [dataabc/weiboSpider#498]
能否批量爬取user id，写入所有用户信息到同一个csv呢？

**Comment by wl-wus** [comment]
因为json的信息更加全面，但是不获取微博信息，就无法生成json信息，有看到在json_writer里面修改，请问具体该怎么修改呢？

**Comment by dataabc** [comment]
感谢反馈。这个weibo-crawler可以做到。
