### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by zhangjibao** [dataabc/weiboSpider#5]
Error:  list index out of range
Traceback (most recent call last):
  File "E:\python\weiboSpider-master\weiboSpider.py", line 144, in writeTxt
    text=str(i) + ':' + self.weibos[i-1] + '\n'+'点赞数：' + str(self.num_zan[i-1]) + '        转发数：' + str(self.num_forwarding[i-1]) + '       评论数：' + str(self.num_comment[i-1]) + '\n\n'
IndexError: list index out of range

请问，这个要怎么解决呢？

**Comment by bctclc** [comment]
同问！

**Comment by XiangyuShi** [comment]
同问，第一次还没问题，晚点再用就出问题了

**Comment by donghao1995** [comment]
同问....

**Comment by chelly911** [comment]
你这个问题没有解决啊，关掉了后面也都是别人提出这个问题
