### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by sunbat** [dataabc/weiboSpider#50]
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "weibospider.py", line 246, in get_weibo_info
    info = selector2.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'

这个提示是什么问题，解析字符获取dom的类名的时候获取dom失败吗？是因为我爬取次数太多的原因吗

**Comment by dataabc** [comment]
可能是爬取次数太多，也可能是网络原因
