### ISSUE TITLE
不知能否爬取新鲜事下的微博？

### ISSUE THREAD

**Issue by SaraKale** [dataabc/weiboSpider#502]
- 问：请说明需要什么新功能。

答：新鲜事功能下的微博

- 问：请说明添加该功能的意义。（非必填）

答：我自己创建了自用收藏微博，就是用“新鲜事”功能创建的，然后收集了一些有用的微博，但它地址是这样的：https://m.weibo.cn/c/novelty/detail?card_id=7632222645426178
不知这样单独的新鲜事能否爬取？自己只需要这样的功能，不会自定义定制，我Python了解不多😭
作者开发的项目很好用！对了，新鲜事的原文也有需要展开全文的按钮，点击它会跳转新的页面…

**Comment by dataabc** [comment]
感谢建议。我没尝试过新鲜事，理论上只要用网页能访问的都可以，程序只能模拟访问页面，提取数据而已。目前没有这个打算，您可以仿造本程序，获取下页面，看看是否能获取信息。

**Comment by SaraKale** [comment]
好滴~回头有空我试试！非常感谢回复！
