### ISSUE TITLE
请问 在weiboSpider目录运行 python3 -m weibo_spider 的时候没反应，没有在当前目录创建config.json配置文件 是什么问题？

### ISSUE THREAD

**Issue by kimoji12138** [dataabc/weiboSpider#505]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：

- 问：您使用的是否是最新的程序（是/否）？

答：

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by dataabc** [comment]
可能您之前安装过pip版本，需要先卸载它再运行。

**Comment by kimoji12138** [comment]
> 可能您之前安装过pip版本，需要先卸载它再运行。

感谢您的回复，但不是这出了问题

**Comment by kimoji12138** [comment]
![8W_FNP1QRICE5~26BLA8T3L](https://user-images.githubusercontent.com/123629872/215921479-68099846-69d3-4bb3-84af-62a9cd39a54d.png)

**Comment by kimoji12138** [comment]
![FYIG2@BE9$N`ZVS3(FF75BC](https://user-images.githubusercontent.com/123629872/215921577-df8afed0-4d26-47d9-8539-ac466998ef59.png)

**Comment by dataabc** [comment]
直接运行__main__.py有反应吗

**Comment by kimoji12138** [comment]
> 直接运行__main__.py有反应吗

感谢回复，我之前在cmd里面就没反应，直接运行__main__.py就有反应了

**Comment by ManutdGTA** [comment]
我也是同样的问题，但是第一次会生成config.json

**Comment by dataabc** [comment]
@ManutdGTA 运行_main_.py了吗

**Comment by ManutdGTA** [comment]
> @ManutdGTA 运行_main_.py了吗

运行了，没反应，问了ai，ai也搞不定

**Comment by dataabc** [comment]
@ManutdGTA 是不是之前安装过pip版？

**Comment by ManutdGTA** [comment]
> @ManutdGTA 是不是之前安装过pip版？

可能是吧，我最后换了个环境，去mac上就好了
