### ISSUE TITLE
pip install -r requirements.txt报错 与安装 lxml相关

### ISSUE THREAD

**Issue by ManutdGTA** [dataabc/weiboSpider#509]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：Installing collected packages: lxml, idna, absl-py, requests
  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      Building lxml version 4.9.1.
      Building without Cython.
      Building against pre-built libxml2 andl libxslt libraries
      running install
      C:\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\builder.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\cssselect.py -> build\lib.win-amd64-cpython-311\lxml
    ...
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

新手刚搭的开发环境，所以用的版本应该都是最新的，问题定位在pip版本上，可能pip 23.1的新版本强制了某种方式导致了安装失败。

现在降级到  pip 20.2.4 python 3.10.10 ，安装了wheel 报错依旧

 Building wheel for lxml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python310\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\3080PC\\AppData\\Local\\Temp\\pip-install-z4hl9agr\\lxml\\setup.py'"'"'; __file__='"'"'C:\\Users\\3080PC\\AppData\\Local\\Temp\\pip-install-z4hl9agr\\lxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\3080PC\AppData\Local\Temp\pip-wheel-x59p1o0p'
       cwd: C:\Users\3080PC\AppData\Local\Temp\pip-install-z4hl9agr\lxml\
 ...
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /TcC:\Users\3080PC\AppData\Local\Temp\xmlXPathInitn8ubiyug.c /FoUsers\3080PC\AppData\Local\Temp\xmlXPathInitn8ubiyug.obj
  xmlXPathInitn8ubiyug.c
  C:\Users\3080PC\AppData\Local\Temp\xmlXPathInitn8ubiyug.c(1): fatal error C1083: 无法打开包括文件: “libxml/xpath.h”: No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml, chardet, certifi, idna, urllib3, requests, tqdm, six, absl-py
    Running setup.py install for lxml ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python310\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\3080PC\\AppData\\Local\\Temp\\pip-install-z4hl9agr\\lxml\\setup.py'"'"'; __file__='"'"'C:\\Users\\3080PC\\AppData\\Local\\Temp\\pip-install-z4hl9agr\\lxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\3080PC\AppData\Local\Temp\pip-record-wjyy5ob5\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\3080PC\AppData\Roaming\Python\Python310\Include\lxml'
         cwd: C:\Users\3080PC\AppData\Local\Temp\pip-install-z4hl9agr\lxml\
    Complete output (91 lines):
    Building lxml version 4.9.1.
    Building without Cython.
    Building against pre-built libxml2 andl libxslt libraries
    running install
    C:\Program Files\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    ...
    C:\Users\3080PC\AppData\Local\Temp\xmlXPathInitwsfygl3x.c(1): fatal error C1083: 无法打开包括文件: “libxml/xpath.h”: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python310\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\3080PC\\AppData\\Local\\Temp\\pip-install-z4hl9agr\\lxml\\setup.py'"'"'; __file__='"'"'C:\\Users\\3080PC\\AppData\\Local\\Temp\\pip-install-z4hl9agr\\lxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\3080PC\AppData\Local\Temp\pip-record-wjyy5ob5\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\3080PC\AppData\Roaming\Python\Python310\Include\lxml' Check the logs for full command output

**Comment by ManutdGTA** [comment]
问题定位在lxml版本上，目前应该只能安装lxml旧版本，不知道。新手刚搭的开发环境，所以用的版本应该都是最新的，不知道怎么设置setuptools里的安装版本。设置成这样也无效

install_requires=[
        'absl-py',
        'lxml<3.4.2',
        'requests',
        'tqdm',
    ],

**Comment by ManutdGTA** [comment]
我问了ai，ai叫我
python -m pip install --upgrade pip.

Try installing lxml using a pre-compiled binary wheel. You can download the binary wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml and install it using the following command: pip install path/to/lxml-<version>-cp<python_version>-cp<python_version>m-<platform>.whl, where <version>, <python_version>, and <platform> are the appropriate values for your system.

最后再 pip install -r requirements.txt --use-pep517

**Comment by dataabc** [comment]
我也没遇到过这个问题，您可以查看一下https://stackoverflow.com/questions/74332756/installing-lxml-facing-a-legacy-install-failure-error 。
