### ISSUE TITLE
userid

### ISSUE THREAD

**Issue by jyjune24** [dataabc/weiboSpider#51]
请问作者能否获取到很多账号的userid以做到大规模爬取呢，比如通过爬取关注列表的userid再循环爬取？

**Comment by dataabc** [comment]
你的意思是不但爬取某个用户的微博，而且爬此用户关注的微博用户的微博，甚至再爬这些关注用户关注用户的微博吗，等等？
可以爬取userid。在用户的关注列表页(<https://weibo.cn/xxx/follow>)可以获取关注人的主页链接，很多链接就是<https://weibo.cn/u/userid>的形式，这些userid很容易提取；另外一些链接是<https://weibo.cn/个性域名>的形式，可能还有其它形式，这些微博的userid需要到链接页面即用户主页获取，userid就包含在"资料"的链接中。
还有如果你想这样爬，就需要对爬过的微博做下标记，防止死循环。
另外，我发现微博最多只能获取200个关注用户的信息(只能获取20页，每页10个)。
如果你只想爬微博，只需要知道微博用户的主页就可以了，如果还需要用户的详细信息就需要用userid了。本程序是因为既要爬取用户的详细信息，又要爬微博，才用的userid。而且即便只知道微博主页，也可以获取用户的详细信息和微博，只不过多了一些获取userid的代码
