### ISSUE TITLE
微博现已无法在 weibo.cn 通过密码登陆，只能通过短信验证码登陆，cookie获取失效

### ISSUE THREAD

**Issue by litanyue** [dataabc/weiboSpider#511]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：GitHub

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：cookie错误或已过期,请按照README中方法重新获取

**Comment by dataabc** [comment]
感谢反馈。我最近不方便调试，您可以先使用免cookie版。

**Comment by litanyue** [comment]
谢谢，免cookie版很好用。
