### ISSUE TITLE
win11 python3.10版本 运行python3 -m weibo_spider 没有任何反映

### ISSUE THREAD

**Issue by wzgrx** [dataabc/weiboSpider#512]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：全部

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：无法运行

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：电脑只安装了py3.10环境，cookie什么的设置好了，没啥问题，D:\weiboSpider\weibo_spider这个文件夹运行python3 -m weibo_spider能创建，设置填好后，再次运行，一点反映没有，down文件夹也没有下载的东西，是需要什么环境吗还是啥问题？

**Comment by wzgrx** [comment]
__main__.py用Python3.10打开运行，闪一下就没了，不知道啥问题

**Comment by dataabc** [comment]
建议卸载pip版本再运行，如果还不行，运行_main_.py看看。

**Comment by dataabc** [comment]
@axxxs0 需要先安装Python。

**Comment by axxxs0** [comment]
我在pycharm里面打开的，引用了anaconda配置的python环境啊，在gitbash里运行python3 -m pip install weispider就报错。如果这样配置python不行，该怎么安装呢，直接下载一个python版本安装吗



---- 回复的原邮件 ----
| 发件人 | Chen ***@***.***> |
| 日期 | 2023年03月24日 00:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dataabc/weiboSpider] win11 python3.10版本 运行python3 -m weibo_spider 没有任何反映 (Issue #512) |

@axxxs0 需要先安装Python。

**Comment by dataabc** [comment]
@axxxs0 单独安装Python。
