### ISSUE TITLE
请问可以只读取csv文件第一列的user_id信息，并在最后一列写入认证信息吗？（不需要爬取用户微博）

### ISSUE THREAD

**Issue by zhouyuwei-989** [dataabc/weiboSpider#514]
之前用大神的另一个代码，搜索关键词爬取了大量微博，获得了用户id和发布的相关关键词的微博的csv文件。目前还需要获取用户认证信息，想问问大神应该如何读取上一个csv文件中的第一列用户id，并在最后几列写入用户认证信息呢？

**Comment by dataabc** [comment]
可以手动批量复制csv列数据，然后粘贴到txt文件，txt文件路径作为参数，使用免cookie版获取。

**Comment by zhouyuwei-989** [comment]
感谢大神！我的数据已经快爬完了！真的超级感谢！
