### ISSUE TITLE
为什么我的 cookie 总是一天就过期了

### ISSUE THREAD

**Issue by u2takey** [dataabc/weiboSpider#515]
如题，文档说 cookie一般有效期是一个月，但是我的 cookie总是一天就过期了，有什么办法解决吗

为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：

- 问：您使用的是否是最新的程序（是/否）？

答：

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by dataabc** [comment]
这个可能和账号有关系吧，具体我也不清楚。您也可以使用免cookie版，不过这个部分微博也需要cookie。

**Comment by zdbpython** [comment]
我的也是一天，甚至怀疑是24小时

**Comment by qazhw** [comment]
> 我的也是一天，甚至怀疑是24小时

我也是24小时
