### ISSUE TITLE
请问在weiboSpider目录运行 python3 -m weibo_spider 的时候没反应，没有在当前目录创建config.json配置文件是什么问题？

### ISSUE THREAD

**Issue by xpywhq** [dataabc/weiboSpider#516]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：源码安装的

- 问：您使用的是否是最新的程序（是/否）？

答：我前期在Git Bash中运行安装的，相关log如下

Xing Poyaun@LAPTOP-0HTFA64B MINGW64 /d/Users/Xing Poyaun/GitDatabase (master)
$ git clone https://github.com/dataabc/weiboSpider.git
Cloning into 'weiboSpider'...
remote: Enumerating objects: 1680, done.
remote: Counting objects: 100% (255/255), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 1680 (delta 144), reused 176 (delta 118), pack-reused 1425
Receiving objects: 100% (1680/1680), 574.85 KiB | 523.00 KiB/s, done.
Resolving deltas: 100% (940/940), done.

Xing Poyaun@LAPTOP-0HTFA64B MINGW64 /d/Users/Xing Poyaun/GitDatabase (master)
$ cd weiboSpider

Xing Poyaun@LAPTOP-0HTFA64B MINGW64 /d/Users/Xing Poyaun/GitDatabase/weiboSpider (master)
$ pip install -r requirements.txt
Requirement already satisfied: lxml==4.9.1 in d:\softwares\programming_softwares\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (4.9.1)
Collecting requests==2.23.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     -------------------------------------- 58.4/58.4 kB 140.0 kB/s eta 0:00:00
Collecting tqdm==4.46.1
  Downloading tqdm-4.46.1-py2.py3-none-any.whl (63 kB)
     -------------------------------------- 63.7/63.7 kB 568.4 kB/s eta 0:00:00
Collecting absl-py==0.12.0
  Downloading absl_py-0.12.0-py3-none-any.whl (129 kB)
     ------------------------------------ 129.4/129.4 kB 763.7 kB/s eta 0:00:00
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     ---------------------------------------- 58.8/58.8 kB 1.0 MB/s eta 0:00:00
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     -------------------------------------- 133.4/133.4 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in d:\softwares\programming_softwares\anaconda3\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (2022.9.14)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     -------------------------------------- 128.0/128.0 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: six in d:\softwares\programming_softwares\anaconda3\lib\site-packages (from absl-py==0.12.0->-r requirements.txt (line 4)) (1.16.0)
Installing collected packages: chardet, urllib3, tqdm, idna, absl-py, requests
  Attempting uninstall: chardet
    Found existing installation: chardet 4.0.0
    Uninstalling chardet-4.0.0:
      Successfully uninstalled chardet-4.0.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.11
    Uninstalling urllib3-1.26.11:
      Successfully uninstalled urllib3-1.26.11
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.64.1
    Uninstalling tqdm-4.64.1:
      Successfully uninstalled tqdm-4.64.1
  Attempting uninstall: idna
    Found existing installation: idna 3.3
    Uninstalling idna-3.3:
      Successfully uninstalled idna-3.3
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.2.2 requires pyqt5<5.13, which is not installed.
spyder 5.2.2 requires pyqtwebengine<5.13, which is not installed.
panel 0.13.1 requires tqdm>=4.48.0, but you have tqdm 4.46.1 which is incompatible.
conda-repo-cli 1.0.20 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.20 requires nbformat==5.4.0, but you have nbformat 5.5.0 which is incompatible.
conda-repo-cli 1.0.20 requires requests==2.28.1, but you have requests 2.23.0 which is incompatible.
anaconda-client 1.11.0 requires tqdm>=4.56.0, but you have tqdm 4.46.1 which is incompatible.
anaconda-client 1.11.0 requires urllib3>=1.26.4, but you have urllib3 1.25.11 which is incompatible.
Successfully installed absl-py-0.12.0 chardet-3.0.4 idna-2.10 requests-2.23.0 tqdm-4.46.1 urllib3-1.25.11

Xing Poyaun@LAPTOP-0HTFA64B MINGW64 /d/Users/Xing Poyaun/GitDatabase/weiboSpider (master)
对照spyder 5.22 需要的库，我在pycharm中对应下载了最新版本的，因为第一个库要求版本不能安装上。所以索性全部所需库安装了最新版的。

这是我运行了python3 -m weibo_spider后没有反应的文件夹截图

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by xpywhq** [comment]
> 
![image](https://user-images.githubusercontent.com/75655783/228261747-530f4ed8-5a60-44bc-b806-d17fac8968b8.png)
大佬，还是不行

**Comment by dataabc** [comment]
您可以单独运行__main__.py，效果一样。

**Comment by xpywhq** [comment]
大佬师，我直接单独运行__main__.py。如图1所示，是否要更换urllib3和chardet的版本，如图2所示，文件夹中在29日新增了config.json。是否可以直接尝试配置config.json使用，谢谢
![image](https://user-images.githubusercontent.com/75655783/228375179-157f8bba-82ad-4db7-9e6b-7aeeb634ffe5.png)
![image](https://user-images.githubusercontent.com/75655783/228375611-1f19da2f-2c69-43b3-a4e1-c41c7a26ca39.png)

**Comment by xpywhq** [comment]
大佬师，继续运行下面的命令python3 -m weibo_spider --config_path="config.json"没有任何变化，以下是图示。是否自行在config.json配置相关参数即可？谢谢
![image](https://user-images.githubusercontent.com/75655783/228998610-02d00103-4de9-4999-bdf0-249ecb349336.png)

**Comment by dataabc** [comment]
运行__main__.py

**Comment by xpywhq** [comment]
大佬，可以部分运行了，谢谢
![image](https://user-images.githubusercontent.com/75655783/229259809-ecfab850-600d-4bd9-ad94-2dd2d0add9fe.png)

**Comment by xpywhq** [comment]
谢谢

**Comment by dataabc** [comment]
不客气。

**Comment by xpywhq** [comment]
大佬，复盘了下之前的操作，还想请教您一下：为何cmd直接调用python3 -m weibo_spider等的命令都不work，再次感谢。

**Comment by dataabc** [comment]
这个我也不清楚，可能软件环境没配置好。

**Comment by xpywhq** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | Chen ***@***.***> |
| 日期 | 2023年04月03日 00:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dataabc/weiboSpider] 请问在weiboSpider目录运行 python3 -m weibo_spider 的时候没反应，没有在当前目录创建config.json配置文件是什么问题？ (Issue #516) |

这个我也不清楚，可能软件环境没配置好。
