### ISSUE TITLE
输入指令时显示错误

### ISSUE THREAD

**Issue by FuEafan** [dataabc/weiboSpider#517]
在terminal窗口中输入scrapy crawl search -s JOBDIR=crawls/search，会显示以下报错，请问是怎么回事？
Scrapy 2.8.0 - no active project

Unknown command: crawl

Use "scrapy" to see available commands

**Comment by dataabc** [comment]
在项目目录下运行就可以了。

**Comment by songzy12** [comment]
另外该项目并没有使用 scrapy，题主是不是问错地方了 lol

**Comment by dataabc** [comment]
@songzy12 他问的应该是我的weibo-search项目，这个是用来搜索关键词的。
