### ISSUE TITLE
cookie错误或已过期,请按照README中方法重新获取

### ISSUE THREAD

**Issue by udterry** [dataabc/weiboSpider#519]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？

答：是

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。

答：清理cookie或者退出重新登陆都会提示，现在cookie开头是XSRF-TOKEN是不是微博已经修改？

**Comment by dataabc** [comment]
我最近没有调试过，不清楚。不过有网友反馈，说cookie获取方式失效了，不确定，您搜索一下其它的cookie获取方法，也可以使用免cookie版。

**Comment by songzy12** [comment]
我刚试了一下cookie获取方式是有效的；

不过要特别注意
- 在不设置`config_path`参数的情况下，`config.json`的位置是否与运行命令时所在的目录相同
- 在设置`config_path`参数的情况下，是否`config_path`的值指向了正确的`config.json`的位置
