### ISSUE TITLE
遇到Emoji停止

### ISSUE THREAD

**Issue by taichifox95** [dataabc/weiboSpider#52]
似乎每一条weibo content遇到emoji就自动停止截取了，有没有办法解决？

比如@共青团中央 （用户id: 3937348351）的最近几条：
2:【厉害！青岛港工人装载车开酒瓶创世界纪录
微博位置: 无
发布时间: 2019-04-14 22:02
点赞数: 764   转发数: 127   评论数: 154
发布工具: 帅团的Android

3:【小学生上电视控诉校门口交通乱，原因为何？
微博位置: 无
发布时间: 2019-04-14 21:19
点赞数: 632   转发数: 71   评论数: 183
发布工具: 帅团的Android

但是没有emoji的就可以比较完整：
5:【郑州车主遇奔驰故障维权受阻：逼我也坐引擎盖哭？】继西安#奔驰车主漏油维权#后，郑州的王女士也遇到类似的情况，她在郑州之星奔驰4S店花了40万买了一辆奔驰C260，提车不到24小时，车在行驶中方向盘助力系统突然失效。根据“三包”法，王女士可以要求退换车，没想到却遭维权难。大参考的秒拍视频 
微博位置: 无
发布时间: 2019-04-14 19:47
点赞数: 2019   转发数: 445   评论数: 760
发布工具: 帅团的Android

谢谢啦！

**Comment by dataabc** [comment]
感谢反馈，问题解决了，代码已更新
