### ISSUE TITLE
有关长微博获取

### ISSUE THREAD

**Issue by kadima221** [dataabc/weiboSpider#524]
你好

非常感谢免费上传这个爬虫程序。有关长微博获取，我照着常见问题里的解决方法，修改了循环次数到500，但似乎仍然无法获取完整的长微博，很多条还是只省略显示。我想问一下还有什么办法能解决这个问题吗？谢谢。

**Comment by dataabc** [comment]
您可以尝试使用免cookie版，这个应该能获取。

**Comment by kadima221** [comment]
感谢回复，我尝试一下
