### ISSUE TITLE
为什么按照说明，第一次运行后没有生成config.json呢？之后自己配置了config.json运行程序也没有反应

### ISSUE THREAD

**Issue by Ascending111** [dataabc/weiboSpider#531]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by Ascending111** [comment]
> 感谢反馈。文件默认生成在当前运行目录，是不是找错了目录？
就是当前目录，但是没有哎。台式和笔记本都试了。

**Comment by Ascending111** [comment]
![image](https://github.com/dataabc/weiboSpider/assets/109414798/6c1de460-921b-48ce-99cd-8a27ee115312)

**Comment by dataabc** [comment]
还可能是你之前安装了pip版，这样默认运行的是pip版，需要将它卸载。

**Comment by Ascending111** [comment]
> 还可能是你之前安装了pip版，这样默认运行的是pip版，需要将它卸载。

确实误操作安装了pip版，但是uninstall后还是没反应呢。

**Comment by dataabc** [comment]
单独运行__main__.py看看。
