### ISSUE TITLE
关于微博页码获取

### ISSUE THREAD

**Issue by kadima221** [dataabc/weiboSpider#537]
你好，我设置了爬取2020年1月1日-2020年5月31日的微博，但只能爬取到1月6日-1月18日，5月22日-5月31日的微博内容。我看了一下别的issue，您提到过如果end date不设置为now可能会出现漏爬取的问题，然后给出了修改spider.py里的页码的解决方案。
但我看了一下微博似乎现在采用的是无限滚动的浏览形式，找不到哪里可以看页码，想请教一下这该怎么解决，如果从2020年一直爬到现在的话实在是太多了

**Comment by dataabc** [comment]
看看log文件，应该有页码。
