### ISSUE TITLE
好像不能获取原创微博

### ISSUE THREAD

**Issue by wwwwa8** [dataabc/weiboSpider#54]
您好，我把filter=0改成了=1 但还是获取了全部微博 包括转发的(._.)

**Comment by wwwwa8** [comment]
而且而且导出来没有横杠分开诶 全在一块儿 是哪里出错了吗

**Comment by wwwwa8** [comment]
啊知道怎么弄原创了 但导出来没有横杠的问题还是有

**Comment by dataabc** [comment]
能否提供微博id，谢谢

**Comment by wwwwa8** [comment]
今天试了一下可以出现了 打扰到您啦 谢谢!
