### ISSUE TITLE
cookie错误或已过期,请按照README中方法重新获取

### ISSUE THREAD

**Issue by ttZhang0512** [dataabc/weiboSpider#551]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：不是爬取的用户，爬取的是搜索关键词界面

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：https://s.weibo.com/weibo?q=ChatGPT%20%E6%95%99%E8%82%B2

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：since_date=2022-12-01

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：cookie错误或已过期,请按照README中方法重新获取

**Comment by dataabc** [comment]
应该就是cookie无效。您使用的是weibo-search项目吗？

**Comment by ttZhang0512** [comment]
> 应该就是cookie无效。您使用的是weibo-search项目吗？

是的，我在微博上搜索了关键词后把cookie数据传入，一直不太行

**Comment by dataabc** [comment]
有可能是cookie不对，或者可能修改了settings.py的COOKIES_ENABLED参数，这个要用程序默认值。

**Comment by ttZhang0512** [comment]
> 有可能是cookie不对，或者可能修改了settings.py的COOKIES_ENABLED参数，这个要用程序默认值。

好的，谢谢
