### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by lcj12414** [dataabc/weiboSpider#568]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是
- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：
[error.log](https://github.com/dataabc/weiboSpider/files/14902107/error.log)
这个错误的日志，我在weibo_spider目录下cmd运行了python3 -m weibo_spider
![image](https://github.com/dataabc/weiboSpider/assets/140908339/9c5a19b3-7d65-4576-95be-add20eced0fd)
就运行main.py。

**Comment by dataabc** [comment]
在weiboSpider-master这个目录运行。

**Comment by lcj12414** [comment]
那录入数据库的部分呢，运行main函数我看数据库后台没有数据

**Comment by lcj12414** [comment]
那录入数据库的部分呢，运行main函数我看数据库后台没有数据

**Comment by lcj12414** [comment]
> 那录入数据库的部分呢，运行main函数我看数据库后台没有数据

全在writer，不好意思，写论文写的脑子有点昏了

**Comment by lcj12414** [comment]
![image](https://github.com/dataabc/weiboSpider/assets/140908339/fed4c881-3e84-45af-8652-71a866a6109d)
大佬，这个错误不太明白，查出来也有各种各样的方法，但是都不太对得上

**Comment by lcj12414** [comment]
![image](https://github.com/dataabc/weiboSpider/assets/140908339/c42f6e26-b9ee-4145-8167-26e3c59fd413)
yi已解决，是这里出错了，这个是运行生成的以为不会出错，看了半天
