### ISSUE TITLE
建议：在requests.get中添加user agent参数

### ISSUE THREAD

**Issue by trioKun** [dataabc/weiboSpider#57]
过往issue中还是有不少同学遇到了out of range错误，这通常是由于网页未响应403错误，经过实验添加随机user agent机制后403率显著降低。
最后，感谢这个项目。基于本项目，我能够实现自己的分析爬虫。比心~

**Comment by dataabc** [comment]
感谢建议，我是通过在爬取若干页后sleep随机时间来解决这个问题的，不过基于一些原因没有加到现在代码里。我考虑下是否加入user agent，再次感谢建议。
