### ISSUE TITLE
辛苦大佬，可否出个保存xls文件的版本？

### ISSUE THREAD

**Issue by vincentlee5** [dataabc/weiboSpider#58]

**Comment by dataabc** [comment]
感谢提议，非常好的建议。考虑了xls、xlsx和csv格式，暂时决定添加保存csv文件的功能，后续可能会添加xls和xlsx的支持。代码已更新，可以保存csv文件，不知道能否满足你的要求。

**Comment by gongqingkui** [comment]
另存为xlsx不就行了嘛
