### ISSUE TITLE
超出范围...

### ISSUE THREAD

**Issue by twobi** [dataabc/weiboSpider#59]
一直报这个错，有点看不明白，老版本也是这样，才来复制了份新版本用， 还是不行0.0

让我去翻起我的 python 课程慢慢学吧...看不懂就改不了 -_-

line 77, in get_user_info
    "//div[@class='tip2']/span[@class='tc']/text()")[0]
IndexError: list index out of range

**Comment by dataabc** [comment]
这很可能是因为你的user_id没有设置正确。如果方便，能否提供目标用户昵称和user_id，谢谢

**Comment by ZhangHanAA** [comment]
一直超出范围错误。user_id 为1402400261 用户昵称为爱可可-爱生活

**Comment by dataabc** [comment]
@ZhangHanAA  程序是否为最新版本?出错后测试过其它用户吗，是只有"爱可可-爱生活"出错还是都出错?如果都出错，可能是账号被限制了,导致无法爬取信息，原因可能是爬取太频繁了。解决方法是减慢爬取速度，如在爬取几页后sleep一段时间。账号限制在一段时间后会自动解除。
我刚刚测试了"爱可可-爱生活"，爬取了前100页，可以正确爬取。所以我认为代码没有问题，可能是账号被限制了。

**Comment by ZhangHanAA** [comment]
> @ZhangHanAA 程序是否为最新版本?出错后测试过其它用户吗，是只有"爱可可-爱生活"出错还是都出错?如果都出错，可能是账号被限制了,导致无法爬取信息，原因可能是爬取太频繁了。解决方法是减慢爬取速度，如在爬取几页后sleep一段时间。账号限制在一段时间后会自动解除。
> 我刚刚测试了"爱可可-爱生活"，爬取了前100页，可以正确爬取。所以我认为代码没有问题，可能是账号被限制了。

可能是Cookie设置的问题，我再看一下，是所有的用户都无法爬取，谢谢。

**Comment by ZhangHanAA** [comment]
已解决，是Cookie设置的问题，导致无法爬取，谢谢！
