### ISSUE TITLE
抓取不全自动停止

### ISSUE THREAD

**Issue by Tan-Haoyi** [dataabc/weiboSpider#595]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：PyPi版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\weibo_spider\spider.py", line 180, in get_weibo_info
    self.user_config, page, self.filter).get_one_page(
  File "D:\Python\lib\site-packages\weibo_spider\parser\page_parser.py", line 47, in __init__
    info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'

已经尝试了加大时间间隔，还是会中途停止，有什么解决或者补救方法？

**Comment by dataabc** [comment]
被暂时限制了，一般过一段时间限制会自动解除。

**Comment by Tan-Haoyi** [comment]
明白，那有没有办法从断开的地方开始呢？

**Comment by dataabc** [comment]
修改spider.py的179行，把第一个1改成上次失败的页数。
