### ISSUE TITLE
爬虫被限制

### ISSUE THREAD

**Issue by Weiyangxu** [dataabc/weiboSpider#60]
每一次大概拍了几十页就被微博限制结束爬虫了，请问怎么增加每一次的访问时间或者怎么暂停爬虫任务一会再接着爬？

**Comment by dataabc** [comment]
在get_weibo_info中
```python
for page in tqdm(range(1, page_num + 1), desc=u"进度"):
      .....
```
page 代表页码，每循环一次代表爬一页，可以在每次循环后sleep几秒，如:
先在程序中加入from time import sleep，然后修改get_weibo_info。
```python
def get_weibo_info(self):
      ......
      for page in tqdm(range(1, page_num + 1), desc=u"进度"):
            ......
            sleep(3)     # 暂停3秒，具体几秒你自己决定
      ......
```
当然，你也可以每爬几页，sleep随机时间，这种方法可以参考#8

**Comment by Weiyangxu** [comment]
好的谢谢您！亲测有效！

**Comment by Weiyangxu** [comment]
您好，我sleep之后确实不会被微博关掉了，但是我想下载某一段时间的数据，如果我直接关闭cmd数据就不会保存，请问应该怎么处理？并不需要下载所有的微博数据，只需要一段时间的就可以了。

**Comment by dataabc** [comment]
还是要改get_weibo_info，
```python
for page in tqdm(range(1, page_num + 1), desc=u"进度"):
```
page_num代表微博页数，默认是爬所有微博。如果你想爬某一段时间的微博，可以先看一下起始时间微博在第几页，终止时间微博在第几页，比如开始于m页，终止于n页，则程序修改为:
```python
for page in tqdm(range(m, n + 1), desc=u"进度"):
'''

**Comment by Weiyangxu** [comment]
好的，谢谢您！
