### ISSUE TITLE
命令行模块化运行代码 python -m weibo_spider 参数问题

### ISSUE THREAD

**Issue by Znull-1220** [dataabc/weiboSpider#608]
作者您好，
       我想请教一下命令行下运行`python -m weibo_spider`时 如果添加`--output_dir=xxx` `--u=xxx`这些参数，参数是在哪里解析的？ 我没有在除README以外的地方搜索到这些参数以及argparse. 
       因为我需要爬取大量用户的历史博文，稍微爬一些就被反爬了，想写一个出现exception 等待后再继续爬取的logic，但是我找不到这些参数解析的地方

**Comment by dataabc** [comment]
在这里https://github.com/dataabc/weiboSpider/blob/master/weibo_spider/spider.py

**Comment by Znull-1220** [comment]
感谢大佬， 才发现不是用argparse解析的 全局搜索'--u'去了
