### ISSUE TITLE
无法爬取数据

### ISSUE THREAD

**Issue by WangLei1002** [dataabc/weiboSpider#61]
cookie和id都设置了，爬时出现问题如下:
Connected to pydev debugger (build 171.4163.6)
用户名: 新浪
Traceback (most recent call last):
  File "C:/Users/11067/Downloads/Compressed/weiboSpider-master/weiboSpider-master/weiboSpider.py", line 78, in get_user_info
    self.weibo_num = int(weibo_footer[0][3:-1])
IndexError: list index out of range
('Error: ', IndexError('list index out of range',))
进度:   0%|          | 0/1 [00:00<?, ?it/s]

**Comment by dataabc** [comment]
出现这个问题一般是因为cookie没设置正确，按照README说的方法重新获取就可以了

**Comment by WangLei1002** [comment]
cookie今天修改后好使了，谢谢
