### ISSUE TITLE
优化建议 : 程序启动即创建文件, 爬取数据的同时为文件追加数据

### ISSUE THREAD

**Issue by PLQin** [dataabc/weiboSpider#62]
1. 场景 : 爬取 `uid=2839635900` 的微博用户,  因为有大量的微博, 导致爬取时间过长, 直到爬取完毕才生成文件 ;
> 建议 :  在启动程序时, 即生成文件, 在爬取数据的同时为文件追加数据

2. 场景 : 爬取 `uid=2839635900` 的微博用户,  因为有大量的微博, 导致爬取时间过长, 在进度为 80% 时, 被微博反爬, 程序报错, 耗时耗力结果文件还没有生成 ;
> 建议 :  同第一个场景

**Comment by dataabc** [comment]
感谢建议，非常好的提议。已经修改为每20页写一次文件，也可以改成自己认为合适的页数。如果微博被反爬，可以通过"减小随机等待页数"和"延长随机等待时间"来降低反爬风险。

**Comment by PLQin** [comment]
Well done!
