### ISSUE TITLE
执行browser_cookie3.chrome(domain_name='weibo.cn')获取cookie报错, 没有权限

### ISSUE THREAD

**Issue by tzk007** [dataabc/weiboSpider#621]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：
2024-12-11 18:55:24,808 - ERROR - config_util.py[:185] - Failed to obtain weibo.cn cookie from Chrome browser: [Errno 13] Permission denied: 'xxxxxxx'

**Comment by dataabc** [comment]
可能程序运行时同时运行了chrome，您可以参考<https://blog.csdn.net/weixin_43667972/article/details/132197618>。

**Comment by tzk007** [comment]
感谢指导, 确实是这个原因导致, 现在已经解决.
希望能帮到其他同仁!
