### ISSUE TITLE
需求：获取评论

### ISSUE THREAD

**Issue by wqingqing** [dataabc/weiboSpider#64]
请问后续会增加获取评论的功能吗

**Comment by dataabc** [comment]
正在考虑这个问题，想要增加获取评论的功能。不过，没想好具体细节，也可能要和本项目分开写，最终如何还不一定。

**Comment by wqingqing** [comment]
感谢回复~~期待评论功能

**Comment by scratlzj** [comment]
增加评论可以参考这个仓库：https://github.com/python3xxx/weibo_spider
