### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by alexischiang** [dataabc/weiboSpider#66]
想通过xpath在m.weibo.cn下做爬取各种微博信息可行吗

**Comment by dataabc** [comment]
我没在m.weibo.cn爬过，不知道可不可以xpath，你可以试下。我刚刚试了下，没成功。不过爬m.weibo.cn需要用api好像

**Comment by alexischiang** [comment]
> 我没在m.weibo.cn爬过，不知道可不可以xpath，你可以试下。我刚刚试了下，没成功。不过爬m.weibo.cn需要用api好像

对的 我也是这个问题 感谢指导
