### ISSUE TITLE
需求：大佬可以增加更新功能吗？而不是每次重新开始下载！

### ISSUE THREAD

**Issue by Evifly** [dataabc/weiboSpider#67]
请教下大佬，能不能增加一个判断功能，就是之后当下载完一次以后，第二次再爬同一个账户的更新内容的话可以不需要重新下载文件夹里已经存在的内容。
或者说做成定时的模式！

**Comment by dataabc** [comment]
好主意，可以考虑下，感谢提议，后续应该会增加此功能

**Comment by Evifly** [comment]
嗯嗯，谢谢大佬！！
另外还有一个，能不能请求大佬看看能不能把转发的微博的原文也摘录进来？
很多时候如果是转发的微博的话，只有博主的评论，看不到原文，有点一头雾水欸！！！

**Comment by Evifly** [comment]
另外大佬可以提醒下大家，如果编辑的时候总是乱码，可以考虑下是不是系统编码的问题，必须是UTF-8，今天弄了一天，总算成功了。
对

**Comment by dataabc** [comment]
> 嗯嗯，谢谢大佬！！
> 另外还有一个，能不能请求大佬看看能不能把转发的微博的原文也摘录进来？
> 很多时候如果是转发的微博的话，只有博主的评论，看不到原文，有点一头雾水欸！！！

感谢建议，你的意思是爬取转发微博的正文？这个本来就有，现在只是把它合并了，变成了下面的形式:
```
转发理由：xxx
原始用户：xxx
转发内容：xxx
```
其中转发内容就是转发微博的原文，现在在考虑要不要把上面的形式分成三个属性：1、转发微博的微博正文，即转发理由，因为只有它是用户所发；2、原始用户；3、原始微博，即转发内容。还有原始微博的点赞数、转发数、评论数等要不要也提取出来。这些也需要考虑

**Comment by Evifly** [comment]
求问大佬，怎么开启这个功能，还是说默认的，因为我只改了cookie id picdownload 三个属性，下载的内容如果是转发的话，只能看到博主的评论，而都看不到原文~

**Comment by dataabc** [comment]
改filter，filter=0表示爬全部微博(原创+转发)，filter=1表示爬全部原创微博。没有遇到过“转发的话，只能看到博主的评论”的情况，不知道是不是看错了还是bug，如果是bug，希望给出具体user_id和微博，方便测试，感谢

**Comment by Evifly** [comment]
成功了！！！！
是的大佬，按照大佬的设置修改以后就没有问题了，但是我之前的设置是 没有改变gilter，直接默认是 self.filter = filter ，那么这样的话出来的内容就直接只有博主转发的评论，没有被评论的原文，也没有是否是转发的提示，每一个账户都是，所以大佬可以看看是不是这个原因，然后就不列出具体的ID了！！！出来的内容大概是如下的样子！
`微博位置: 无
发布时间: 2019-06-12 21:35
点赞数: 2   转发数: 0   评论数: 0
发布工具: Android`

**Comment by Evifly** [comment]
或者说，默认的才是只爬去原创微博！

**Comment by dataabc** [comment]
程序默认是爬取全部微博。因为我在main函数里为了展示filter用法，让filter=1，使得程序变成爬取全部原创微博了。

**Comment by Evifly** [comment]
对对对,但是大佬,我用的时候,我刚刚仔细看了一下,发现所有的结果都是原创微博,但是我这时候的filter是默认值 filter,是不是这里逻辑出问题了?

**Comment by dataabc** [comment]
因为有两个有默认值的参数:filter和pic_download，如果都不写就是下载全部微博并且下载图片，如果只写两个，如
```python
Weibo(user_id, 1)
```
就是下载原创微博。是不是你把pic_download赋值为1，然后又Weibo(user_id, pic_download)？如果你想控制爬原创，可以只写两个参数，如果想下图片，必需写三个参数，像这样Weibo(user_id, filter, pic_download),当只有两个参数时，程序会认为第二个参数是控制filter的。

**Comment by Evifly** [comment]
哈哈哈哈哈，原来是这样~~~明白了！！！！
谢谢大佬！@！！！
我应该就是差在这一步上了！
只写了两个参数！！！filter没动~

**Comment by Evifly** [comment]
不过这样的话，建议大佬可以换个表达方式，多增加几种方案，比如说
1 原创+图片
2原创
3 所有+图片
4 所有
我个人觉得的话，个人呀，只会用的小白，像我这种，到这，如果没有大佬这么好心的解释的话，可能理解上会有些误差的！
大佬可以做个投票试试！

**Comment by dataabc** [comment]
感谢建议，只是这样两个选择就被绑到了一块，变成了一个有四个取值的选择。如果以后再加一个参数，就必需有8个取值方案。n个参数需要有2的n次方个取值方案，取值太多，这样就乱了。因为不确定以后会不会增加参数，所以需要每个参数分开写，还是非常感谢建议的

**Comment by Evifly** [comment]
> 感谢建议，只是这样两个选择就被绑到了一块，变成了一个有四个取值的选择。如果以后再加一个参数，就必需有8个取值方案。n个参数需要有2的n次方个取值方案，取值太多，这样就乱了。因为不确定以后会不会增加参数，所以需要每个参数分开写，还是非常感谢建议的

好的！~

**Comment by bubblesran** [comment]
是否可以增加一个发布时间的判定，比如只下载某个发布时间之后的微博之类的？

**Comment by dataabc** [comment]
已添加按时间爬取，更新的话，你可以把上次爬到的时间作为起始时间，这样程序就只会爬取该时间及之后的微博。比如，since_date = '2019-01-01'表示爬取2019年1月1日到现在的微博。如果你是第一次爬，想爬全部微博，可以设置一个较早的时间，比如since_date = '1900-01-01'
