### ISSUE TITLE
为什么无法爬取爬虫自己的微博

### ISSUE THREAD

**Issue by upupming** [dataabc/weiboSpider#68]
爬取自己的微博的时候，会出现总页数『50』，但是爬取完之后，没有任何信息的现象。这是为什么呢？希望作者解答一下，谢谢您！

**Comment by dataabc** [comment]
因为自己微博显示的格式和别人微博显示的格式不同，程序是以爬别人微博为目的写的，所以目前只能爬别人的微博，不能爬自己的

**Comment by upupming** [comment]
嗯，感谢解答！我目前也在尝试修改您的爬虫，我发现 m.weibo.cn 和 weibo.com 都[是用 Ajax 来获取数据的](https://zhuanlan.zhihu.com/p/35682031)：
![image](https://user-images.githubusercontent.com/24741764/59548183-b4e37400-8f7d-11e9-9eea-b2a086716786.png)

作者有没有打算改用 API 的方式进行爬取呢，感觉这样会简单一些。

**Comment by dataabc** [comment]
感谢提议，有这个打算，后续应该会用API，不过可能是在另外的项目里，因为改动的太大了

**Comment by upupming** [comment]
嗯嗯，谢谢大佬详细解答。
