### ISSUE TITLE
部分表情在抓取结果中没有

### ISSUE THREAD

**Issue by upupming** [dataabc/weiboSpider#69]
被抓取用户：https://weibo.cn/at/weibo?uid=5349576923
对于下面的微博：
![image](https://user-images.githubusercontent.com/24741764/59548404-7a7bd600-8f81-11e9-9833-16d2bd5e0b08.png)
前面的表情都没有被抓取到：

```txt
2:转发理由:转发微博  
原始用户: upupming
转发内容: 微博表情测试：[左哼哼][加油]→_→🙃🤓🤗[惊恐][妖怪][幽灵][大便]🙈🙉🙊[瑜伽一]🙋[祈祷][圣诞树][闪电][西瓜]🍗[药丸][炸弹][带着微博去旅行][胖丁微笑]                     
微博位置: 无
发布时间: 2019-06-15 11:44
点赞数: 0   转发数: 0   评论数: 0
发布工具: 微博手机版

```

**Comment by upupming** [comment]
这个也是：
![image](https://user-images.githubusercontent.com/24741764/59548439-29b8ad00-8f82-11e9-8a07-7405cc97b4bd.png)
![image](https://user-images.githubusercontent.com/24741764/59548450-448b2180-8f82-11e9-9cf3-5289ccc025f7.png)

这是 `lxml` 解析的原因吗？

**Comment by dataabc** [comment]
和lxml没关。这是因为提取微博正文时只提取了文本内容，大部分表情都不是文本内容，如:
```
<img alt="[可爱]" src="//h5.sinaimg.cn/m/emoticon/icon/default/d_keai-7a5bf88086.png" style="width:1em; height:1em;">
```
这是一个"可爱"表情，不属于文本，所以没有提取。之所以有"[加油]"这样的内容可以提取到，是因为它在源码里就是
```
[加油]
```
这种形式

**Comment by upupming** [comment]
我建议可以把 `alt` 属性保留，这样即使是图片表情也可以很好地抓取了。

**Comment by upupming** [comment]
那『生日』那个怎么解释呢？我看它好像并不是图片，而是一个 Unicode 表情。

**Comment by upupming** [comment]
感谢作者的解答，我看 weibo.com 对表情的处理还是要好一些，我尝试自己模仿您的用 API 请求写看看。

**Comment by dataabc** [comment]
> 那『生日』那个怎么解释呢？我看它好像并不是图片，而是一个 Unicode 表情。

是“27岁[红桃]️第一次有这么多人陪我一起过生日我真的特别特别感谢台前幕后的所有工作人员，还有你们我的阿丝儿，有人问为啥27岁要办生日会，因为2.7～只有87你们会懂[红桃]️ ”这条吗？里面的生日是文本，那个蛋糕表情是图片

**Comment by upupming** [comment]
不是，在文本之后还有一个表情：
![image](https://user-images.githubusercontent.com/24741764/59550394-d43dc980-8f9c-11e9-9e28-ffdfd1b476d4.png)
但是抓取结果中并没有。

**Comment by upupming** [comment]
我又尝试对这一篇微博进行抓取：https://weibo.cn/comment/Hz1TLDIlW?ckAll=1

里面也有这个Unicode生日表情，但是就可以抓取成功：
![image](https://user-images.githubusercontent.com/24741764/59550425-49110380-8f9d-11e9-8a11-c8a5f0a7b2e1.png)

**Comment by upupming** [comment]
哦！这是一个图片，抱歉是我搞错啦：

![image](https://user-images.githubusercontent.com/24741764/59550444-7d84bf80-8f9d-11e9-9f7d-712144451056.png)


那就可以解释的通了。
