### ISSUE TITLE
请教一个关于xpath的问题

### ISSUE THREAD

**Issue by minweny** [dataabc/weiboSpider#71]
大佬, 我想问一下. `get_page_num`这个方法中的xpath路径`("//input[@name='mp']")`, 为什么我用Chrome的inspect element看不到这个路径呢? 
我在Chrome concole里运行, `$x("//input[@name='mp']")`, 返回的居然也是个空list! 这是为啥呢?

**Comment by upupming** [comment]
建议google一下xpath的tutorial，自行学习一下，很简单的

**Comment by minweny** [comment]
我最近一直在用selenium和xpath爬FB的数据, 也没出过啥问题啊. 那, 我还是再想想吧...

**Comment by dataabc** [comment]
可以返回数据啊，试试
···
$x("//input[@name='mp']")[0]
···

**Comment by minweny** [comment]
> 可以返回数据啊，试试
> 
> ```
> $x("//input[@name='mp']")[0]
> ```

谢谢作者回复! 我找到原因了: **我把weibo.cn输错成weibo.com了**. 一个非常蠢的错误. weibo.com里面好像没有关于页码的数据, xpath也选不出来任何东西. weibo.cn没有任何问题. 

ps: 你的爬虫代码我每行都读了, 写得真的不错!

**Comment by dataabc** [comment]
@minweny 
谢谢夸奖，哈哈
