### ISSUE TITLE
需求：爬取某个微博的关注列表中的内容！

### ISSUE THREAD

**Issue by Evifly** [dataabc/weiboSpider#73]
大佬可以试试看新功能吗？
比如说我账号里关注了多少人，然后就爬取我的主页，然后把关注的对象发的微博爬取下来，定期爬取这样！
一个小小的愿望！

**Comment by dataabc** [comment]
很有想法。因为本程序是爬取一个账号的微博，你想要的是爬取你关注列表中的微博，这很可能是要爬多个微博账号，这与本程序的宗旨不一致，所以又新建了一个项目，刚刚完成了基础的代码，[项目地址](https://github.com/dataabc/weibo-follow)。有两个主要文件，一个就是本程序，另一个是weibo_follow.py，weibo_follow.py的目的是爬你关注列表微博账号的user_id。思路是先爬关注列表的user_id，然后再对每个user_id调用本程序，爬对应user_id的微博。
你要做的就是：
- 1.把你的cookie分别填到两个py文件里；
- 2.把你爬虫的user_id填到weibo_follow.py的对应位置，具体位置程序里有写；
- 3.运行weibo_follow.py程序，它会自动爬取关注列表，爬完后，遍历爬取每个user_id

其实如果要爬你自己关注的账号的微博可以不用写爬虫的user_id，程序能够自动获取。然而，我的想法是想让他不只可以爬你关注的用户微博，还可以爬指定user_id用户关注的微博，所以需要手动填这个user_id。只是爬指定微博关注列表的微博功能还没有实现，具体什么时候实现看有没有时间吧

**Comment by upupming** [comment]
我也对 following 的爬取进行了尝试，使用 MySQL 存储数据，使用 BFS 搜索~
https://github.com/upupming/weiboAPI

**Comment by Evifly** [comment]
> 很有想法。因为本程序是爬取一个账号的微博，你想要的是爬取你关注列表中的微博，这很可能是要爬多个微博账号，这与本程序的宗旨不一致，所以又新建了一个项目，刚刚完成了基础的代码，[项目地址](https://github.com/dataabc/weibo-follow)。有两个主要文件，一个就是本程序，另一个是weibo_follow.py，weibo_follow.py的目的是爬你关注列表微博账号的user_id。思路是先爬关注列表的user_id，然后再对每个user_id调用本程序，爬对应user_id的微博。
> 你要做的就是：
> 
> * 1.把你的cookie分别填到两个py文件里；
> * 2.把你爬虫的user_id填到weibo_follow.py的对应位置，具体位置程序里有写；
> * 3.运行weibo_follow.py程序，它会自动爬取关注列表，爬完后，遍历爬取每个user_id
> 
> 其实如果要爬你自己关注的账号的微博可以不用写爬虫的user_id，程序能够自动获取。然而，我的想法是想让他不只可以爬你关注的用户微博，还可以爬指定user_id用户关注的微博，所以需要手动填这个user_id。只是爬指定微博关注列表的微博功能还没有实现，具体什么时候实现看有没有时间吧

收到呀！！谢谢大佬！！！！！理解了！！！！
不过大佬有个问题是。。。。关注列表过大怎么破。。。。比如说，1000以上的关注，
所以又回到了之前的老问题，大佬能不能设置爬取制定周期里，比如从2019年6月1日开始，到最新日期的微博，或者是判断微博是否已经存在～

**Comment by dataabc** [comment]
试了下微博移动版和网页版，发现微博最多只显示200个关注，如果只通过关注页，最多只能获取200个关注账号。当然，如果你爬了微博所的账号，就可以通过“已关注”判断某用户是否在关注列表里，进而获取用户的全部关注账号。不过，这样需要你爬大量账号，难度大。
一个偷懒的做法是分析用户的全部微博，找出他转发过或@过的账号，这些账号很可能也是他关注的用户，再用一些手段判断它们是否被用户关注就行了。不过，这样也无法保证获取用户的所有关注的微博。因为用户可能仅仅关注了他而没有转发他的微博也没有@过他。

关于设置爬取周期，这个说难也难说容易也容易。你的需求是只有起始时间，结束时间是最新日期。我认为加上起始时间和结束时间这样适用范围更广。说容易是因为程序可以获取微博的时间，如果时间不在周期里就跳过，很容易。难的是如何保证效率。比如某账号有10000条微博，我想爬他2018年的微博。如果这些微博在他5000条微博以后出现。为了爬这些微博就必需遍历他的所有微博，判断这些是否满足条件。前5000条也是需要遍历的，非常浪费时间。所以需要提高效率，这才是重点。我目前想到的是二分查找，10000条微博应该有1000页，先去爬第500页的第一条和最后一条，如果第一条比这个周期的最早时间早，说明目标在前500页，如果最后一条比周期最晚时间晚，说明目标在后500页，如果它们都在周期内，又要重新搜索，等等。这样可以大大提高效率，需要写更多代码，逻辑更复杂。
有一个偷懒的做法。微博移动版有一个筛选的功能，可以按照关键词和时间范围筛选。本程序爬微博是通过遍历爬<https://weibo.cn/1669879400?page=页数>实现的。现在你可以通过遍历爬取<https://weibo.cn/1669879400?keyword=的&starttime=20190101&endtime=20190714&advancedfilter=1&page=页数>实现，它的功能是爬迪丽热巴2019-01-01到2019-07-14所有包含的的微博。优点是不需要搜索判断微博是否在周期内，因为通过这个链接爬到的微博都在周期内。缺点是一些在周期内不包含“的”的微博没有爬取。

还有关于自动更新的功能，与上面这个有类似的地方。比如某微博在更新爬取时，操作与它以前的爬取有关系，可能它上一次已经被爬完了，这次更新爬取，先读取以前爬取微博的id列表，然后从最新的爬取，判断微博id是否在id列表里，如果在说明最新的微博已经爬了，爬虫就可以结束了。然而，问题是，他上一次不一定爬完了，可能只爬了一部分。这时候所有微博对他来说可能就变成了这种形式：未爬+已爬+未爬。甚至，在极少数情况会出现：未爬+已爬+未爬+已爬+未爬，这可能是用户曾经因为某些原因，专门爬了某几页。如何让这些情况都可以在高效率下更新是重点，也是一直没有加这个功能的原因。

**Comment by Evifly** [comment]
哈哈哈哈！好嘞！！！谢谢大佬！！！！！！
