### ISSUE TITLE
问题反馈：变量 user_id 错误！

### ISSUE THREAD

**Issue by Evifly** [dataabc/weiboSpider#75]
请教下大佬，按照大佬新更新的类的用法，设置了一个类，然后用了一个列表变量，用　ｆｏｒ　ｉｎ　循环，爬取的时候就显示非数字形式，尝试绕过判断，成功运行，但是爬到特定ID的时候又出现了这样的ｂｕｇ，　ｌｉｓｔ　 index out of  range !!!
求问如何破解！！！

**Comment by dataabc** [comment]
是说的在爬关注列表微博[项目](https://github.com/dataabc/weibo-follow)时，出现错误了吗？还是其他项目。能否提供出错的id，方便调试，谢谢。另外如果爬取的时候显示非数字形式，说明那个出错的id不是数字形式，正确的user_id都是数字形式的。可能是误把个性域名当初user_id了

**Comment by Evifly** [comment]
😂，ID有些羞耻，能邮件发给大佬代码吗？

**Comment by dataabc** [comment]
看你的描述，应该是修改了代码。好像是自己设置了一个list，包含要爬的user_id。如果是这样，出现非数字形式，可能就是list里有非数值形式的值。正确的user_id值是数值形式的，按照README获取正确的user_id就可以了。index out of range很多时候是因为使用时索引大于或等于list的长度。比如一个list为id_list，假设它有3个元素，id_list[0]、id_list[1]、id_list[2]都没问题，id_list[3]就会出现index out of range，因为它试图使用id_list的第四个元素，而id_list只有三个。我怀疑你是这样用的：
for i  in range(len(id_list)):
    ...
    id_list[i]  # 或者其它包含id_list[i]的操作，如 xx(id_list[i]) 
    ...
如果是这样，代码改成for id in id_list，其它代码作相应修改就可以了

**Comment by Evifly** [comment]
终于找到原因了。。。原来是被销号了！！！谢谢大佬！！！
`
代码结构是
user_id = [1, 2, 3, ]
for i in user id
....
....
`
不过多亏了大佬，学会了类的运用！超级感觉！
不过有个问题，就是如何些行内注释，这个可以请教下大佬吗。
好想些list的时候，在id后面加上对应的名字，结果发现似乎没有行内注释的功能！！！
顺便还想问下，list的话，如何一行一个数值呢
user_id = [
1, \n
2,\n
....
]
这样写是对的吗大佬！

**Comment by dataabc** [comment]
你可以这样写注释
```
user_id = [
    1,  # 注释
    2,  # 注释
    3  # 注释
]
```

**Comment by Evifly** [comment]
s

> 你可以这样写注释
> 
> ```
> user_id = [
>     1,  # 注释
>     2,  # 注释
>     3  # 注释
> ]
> ```

哈哈哈哈 谢谢大佬！！！
然后还有个问题，就是如果我用自己的cookie 爬取自己的微博，那么我能不能爬取到仅自己可见的微博。（已实验，出现了如下BUG）
然后还有个很奇怪的是，当我用mac chrome 上的cookie 爬取微博的时候，爬取到的微博显示为零，这个可能原因是什么呢？

**Comment by dataabc** [comment]
爬虫微博不能爬自己的微博。因为程序的原理是解析目标微博列表页，提取微博信息。在爬虫看来，自己微博页和别人微博列表页的格式是不同的，程序是为了提取别人微博而写的，如果要爬自己的微博，肯定要修改代码的。
如果你说的是在爬仅自己可见的微博时爬到的微博显示0，是因为0是初始化时设置的，当爬微博时，会解析微博真实的数目替换0。因为你爬自己的微博，格式与期望不符，程序出错，原先的0没有被修改，所以会出现这样的现象。如果你要自己的微博，建议使用[免cookie版](https://github.com/dataabc/weibo-crawler)，功能更强大，爬到的信息更多，代码更简单，不过这个应该也不能爬仅自己可见的内容

**Comment by Preshire** [comment]
一个跟踪问题，有一些官方号所使用的userid是纯英文，因此再导入id的时候就出现了

> Error:  'statuses_count'
> Traceback (most recent call last):
>   File "weibo.py", line 739, in start
>     self.get_pages()
>   File "weibo.py", line 694, in get_pages
>     page_count = self.get_page_count()
>   File "weibo.py", line 475, in get_page_count
>     weibo_count = self.user['statuses_count']
> KeyError: 'statuses_count'

的问题，想问下这个该怎么解决呢？谢谢！

**Comment by dataabc** [comment]
@Preshire 
已经在另一个issue里回复了，可以尝试下按照README<https://github.com/dataabc/weiboSpider#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96user_id>获取数字形式的id。如果你就是按照README获取的user_id，希望可以通过出错的id，方便调试
