### ISSUE TITLE
问题反馈：argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by PandGnone** [dataabc/weiboSpider#78]
描述：
![image](https://user-images.githubusercontent.com/50006370/62852527-38220b80-bd1c-11e9-82a2-d4967ae7b7a5.png)

Error:  argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "f:\spider\weiboSpider\weiboSpider.py", line 378, in download_pictures
    if ',' in w['original_pictures']:
TypeError: argument of type 'NoneType' is not iterable

**Comment by dataabc** [comment]
感谢反馈，问题应该已经解决，如果还有问题，欢迎继续反馈
