### ISSUE TITLE
BUG： 爬下来的文件无法追加

### ISSUE THREAD

**Issue by Ccccche** [dataabc/weiboSpider#79]
当我第二次爬同一个id的微博的时候，爬下来的csv,txt文件内并没有追加新的内容。建议每次爬之前检查是否存在同名文件，如果存在则替换

**Comment by dataabc** [comment]
无法追加是第二次爬的时候，文件没有增加新内容吗？程序有报错吗？
本程序的思路是，每一次爬都会写文件，第一次爬是先创建文件，然后在写；以后爬如果上次的结果文件存在，就在上次文件的基础上增加，如果不存在，程序就会像第一次爬一样操作。
所以，当第二次爬的时候，文件会追加的。如果你指的是第二次爬的时候程序没有进行任何文件操作，可能的原因是在第二次爬的时候，第一次的文件打开了没有关闭，程序对打开的文件没有操作权限，因此没有修改文件，这时候程序应该会报错。
如果不是这个原因，如果方便的话，能否给出出错微博id方便调试，感谢反馈

**Comment by Ccccche** [comment]
再测试一了遍这个情况消失了。
