### ISSUE TITLE
可爬微博限制

### ISSUE THREAD

**Issue by zhangyics** [dataabc/weiboSpider#8]
您好！请问这个代码在爬取时不能获取用户的全部微博怎么办，只能爬取前一百多页，后面的微博有办法获取吗？期待您的解答！

**Comment by dataabc** [comment]
可以爬取全部微博。本程序爬取的是手机版的微博，只要你手动可以浏览手机版的用户微博，程序就可以爬取该用户的微博，本代码模拟的就是这个手动的过程。可能是你的程序或微博账号爬取的太频繁了，可以让爬虫每爬完一页微博暂停一段时间再爬下一页。

**Comment by xnzmc** [comment]
我在网上查到隐约的回答是：访问次数限制为1000次 /hour。但没有直接的文件解释
我自己设置延迟是每页（10条微博）延迟5秒，每10页再延迟30秒，最终每400页再延迟10min。然而结果和不设置延迟是一样的 爬取人民日报总共爬取1700条左右。
目前打算设置1000条后延迟一小时。。。。

**Comment by xnzmc** [comment]
我这边设置每页（10条）延迟1.5 s；每300页延迟300 s。效果不错。

**Comment by cjmmya** [comment]
我在获取cookie的时候微博登陆不进去，总是说系统繁忙，这是什么情况了？

**Comment by knightReigh** [comment]
@xnzmc 请问这个在哪里设置啊？没有找到。

**Comment by xnzmc** [comment]
哦，是这样，我自己加入`time.sleep(1.5)`来实现每页延迟1.5s ，具体插入的位置你可以自己选择

**Comment by cutelittleturtle** [comment]
@xnzmc　谢谢

**Comment by Twinklingcode** [comment]
#持续爬取会被禁止访问，request会返回403
解决方法引入随机sleep,每访问（5,10）页，sleep（5,10）秒。模拟人的真实请求。

![image](https://user-images.githubusercontent.com/12522270/37573486-6539acec-2b53-11e8-81c7-543f0b708e41.png)
![image](https://user-images.githubusercontent.com/12522270/37573503-7dd9fc16-2b53-11e8-9eab-5c790fbc4396.png)

**Comment by ntyxj** [comment]
@Twinklingcode ，您好，麻烦您一下。我是小白，试图按照图片https://user-images.githubusercontent.com/12522270/37573503-7dd9fc16-2b53-11e8-9eab-5c790fbc4396.png中显示的那样复制代码，使程序能够随机sleep。因为没有在程序中发现self.weibo_content.append(user_info)，所以将第二部分的插入代码插在了 if not self.filter:的前面，代码复制好了后，程序中的timedelta被自动黄色显示，运行下来报错：NameError: global name 'sleep' is not defined。请问：是不是需要定义一下 sleep，写在哪里呢？

**Comment by Twinklingcode** [comment]
@dataabc 我没有设置代理池，单纯只是模拟人的操作行为来规避反爬
规则是：访问随机页休息随机秒

**Comment by Twinklingcode** [comment]
@ntyxj  只要在函数前面定义好就好了，这个sleep是随机的，看你自己找到一个舒服的值，我是2-10s

**Comment by sunbat** [comment]
> #持续爬取会被禁止访问，request会返回403
> 解决方法引入随机sleep,每访问（1,5）页，sleep（6,10）秒。模拟人的真实请求。
> 
> ![image](https://user-images.githubusercontent.com/12522270/37573511-95c49e44-2b53-11e8-8029-f1ea6b26e4b2.png)
> 
> ![image](https://user-images.githubusercontent.com/12522270/37573503-7dd9fc16-2b53-11e8-9eab-5c790fbc4396.png)
> 
> 包的依赖：
> numpy
> #pip install numpy
> 
> #代码正文：
> import numpy as np
> #第一部分的插入代码：
> page1=0
> random_pages=2
> #第二部分的插入代码：
> random_sleep= np.random.randint (6,10)
> if page-page1==random_pages:
> sleep(random_sleep)
> page1=page
> random_pages = np.random.randint (1, 5)

按照您这个添加以后提示如下：
  File "weibospider.py", line 235
    random pages = 2
               ^
SyntaxError: invalid syntax

请问这个是什么原因呢，numpy我已经装上的

**Comment by dataabc** [comment]
@sunbat 添加from time import sleep就可以了
