### ISSUE TITLE
需求：可否增加一个发布时间判定的功能，使爬虫只会爬取这个时间之前或者之后的微博内容？

### ISSUE THREAD

**Issue by bubblesran** [dataabc/weiboSpider#80]
请教大佬，能否增加这样的功能呢？

**Comment by dataabc** [comment]
感谢提议。我的想法是让用户提供一个**时间段**，起始时间和结束时间，程序只爬这个时间内的微博，这样比只爬某个**时间点**之前或之后的微博适用范围更广，只是这样需要一种高效的方法来确定起始时间和结束时间对应的微博页数。所以，目前还没有添加该功能，以后应该会添加

**Comment by dataabc** [comment]
已经添加根据时间爬取功能，设定一个参数since_date，形式为"yyyy-mm-dd"，比如since_date='2019-01-01'就是爬取2019年1月1日到现在的微博，如果想爬全部微博，可以设置一个较早的时间，如1900-01-01。最终还是按时间点实现的，因为我发现按时间段可能会花费很多时间，感谢建议

**Comment by bubblesran** [comment]
感谢大佬。功能很实用。

**Comment by Evifly** [comment]
> 已经添加根据时间爬取功能，设定一个参数since_date，形式为"yyyy-mm-dd"，比如since_date='2019-01-01'就是爬取2019年1月1日到现在的微博，如果想爬全部微博，可以设置一个较早的时间，如1900-01-01。最终还是按时间点实现的，因为我发现按时间段可能会花费很多时间，感谢建议

大佬请教下现在如果下载的话，多次执行的结果是不是源文件添加内容，而不是替换前一次执行结果的文档呢？

**Comment by dataabc** [comment]
如果你多次爬相同的账户，信息会追加在上一次的csv结果文件中，而不会替换。追加时，为了与上一次的内容区分，还是会添加表头的，即微博id、正文、图片url等等内容

**Comment by Evifly** [comment]
> @Evifly
> 如果你多次爬相同的账户，信息会追加在上一次的csv结果文件中，而不会替换。追加时，为了与上一次的内容区分，还是会添加表头的，即微博id、正文、图片url等等内容

啊哈哈哈！谢谢大佬！！我又来提问了！！
现在在尝试用大佬的user_id_list功能，
发现了几个BUG，所以来请教下大佬
遇到的第一个问题是如果是直接从浏览器复制到代码文档里的ID都会显示错误，抓取失败，非数字形式，如果是手动输入的倒是没这个问题，所以是不是复制过程中从UTF-8转换成了ANIT之类的格式，还是判定的问题
遇到的第二个问题是，ID文档里只能输入ID，如果像备注加个“#用户昵称”，就会爬取错误！似乎是把ID文档里所有的行看作是纯数字的形式，如果里面夹杂了任何其它内容就会失败。
所以弱弱地向大佬提一个新的可以直接被无视的需求！！如果大佬有空的话，那就拜托了，感激不尽！！！
希望的代码形式是
```
#原来的形式
123123123
希望能够被识别的新的格式
12312312312312 #用户昵称
或者是
#段注释
123123123123123

```
第三个问题，就是想问下大佬对user_id_list 文档的读取是在正式开始爬虫前一次性读取所有的待爬取账号还是读一个爬一个！！（—__+)(爬取的账户体积太大，自己测试困扰中，所以打扰下大佬可以吗！！！)
以上，谢谢大佬一直来的维护和更新，太感谢了咩！！！！！！

**Comment by dataabc** [comment]
@Evifly 
第一个问题，id应该都是数字形式的。你说的非数字形式，我怀疑是自定义的域名，用户可以自定义域名，之后用户主页自定义域名就替代了id形式。要获取正确的id请参考<https://github.com/dataabc/weiboSpider#4%E8%AE%BE%E7%BD%AEuser_id>；
第二个问题，其实是一个比较好的建议。加上注释更容易区分微博账号，这几天应该会加上此功能；
第三个问题，user_id_list是一次把所以id都读取，然后再一个一个账户的爬信息。
另外，如果只是测试的话，其实你设置一个比较新的since_date，比如今天，程序就只爬取今天的微博。这样，不管微博账户体积多大，应该都可以很快爬完，毕竟一天时间一个微博账号发的微博数量不会太多

**Comment by dataabc** [comment]
@Evifly 
已支持user_id注释功能，user_id文件可以为如下形式：
```
1223178222 胡歌
1669879400 迪丽热巴
1729370543 郭碧婷
```
注意user_id和注释之间必需要有空格，
也可以为如下形式：
```
#胡歌
1223178222

#迪丽热巴
1669879400

#郭碧婷
1729370543
```
第一种注释不用加#，第二种最好加上#。因为程序是默认读取每行开始的第一个字符串，如果该字符串的每个字符都是数字，就认为它是user_id。如果第二种不加#,若有一个昵称或注释内容全是数字，该注释会被误认为user_id，加#就是为了避免这种情况

**Comment by Evifly** [comment]
> @Evifly
> 已支持user_id注释功能，user_id文件可以为如下形式：
> 
> ```
> 1223178222 胡歌
> 1669879400 迪丽热巴
> 1729370543 郭碧婷
> ```
> 
> 注意user_id和注释之间必需要有空格，
> 也可以为如下形式：
> 
> ```
> #胡歌
> 1223178222
> 
> #迪丽热巴
> 1669879400
> 
> #郭碧婷
> 1729370543
> ```
> 
> 第一种注释不用加#，第二种最好加上#。因为程序是默认读取每行开始的第一个字符串，如果该字符串的每个字符都是数字，就认为它是user_id。如果第二种不加#,若有一个昵称或注释内容全是数字，该注释会被误认为user_id，加#就是为了避免这种情况

收到~谢谢大佬！！！感激不尽！！！心满意足！！

**Comment by Evifly** [comment]
> @Evifly
> 第一个问题，id应该都是数字形式的。你说的非数字形式，我怀疑是自定义的域名，用户可以自定义域名，之后用户主页自定义域名就替代了id形式。要获取正确的id请参考https://github.com/dataabc/weiboSpider#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96user_id；
> 第二个问题，其实是一个比较好的建议。加上注释更容易区分微博账号，这几天应该会加上此功能；
> 第三个问题，user_id_list是一次把所以id都读取，然后再一个一个账户的爬信息。
> 另外，如果只是测试的话，其实你设置一个比较新的since_date，比如今天，程序就只爬取今天的微博。这样，不管微博账户体积多大，应该都可以很快爬完，毕竟一天时间一个微博账号发的微博数量不会太多

关于第一个问题的继续讨论~
大佬，我是同一串ID号，一个是自己从浏览器的地址栏里复制过来的，然后另一个是自己手动输入的，复制的 显示判定失败，自己手动输入的就成功了。。。难道遇到了薛定谔问题？？

**Comment by dataabc** [comment]
@Evifly 
能否提供user_id，如果方便的话，我调试下。user_id是字符串形式，user_id两边一定要加引号。如：
```python
user_id_list = ['1669879400', '1729370543']
```
还有程序出错时有什么提示吗？如果有，希望提供具体的出错信息，谢谢

**Comment by Evifly** [comment]
> @Evifly
> 能否提供user_id，如果方便的话，我调试下。user_id是字符串形式，user_id两边一定要加引号。如：
> 
> ```python
> user_id_list = ['1669879400', '1729370543']
> ```
> 
> 还有程序出错时有什么提示吗？如果有，希望提供具体的出错信息，谢谢

。。。。
暂时没能复现错误。。
大佬稍等一阵子！！

**Comment by dataabc** [comment]
> > @Evifly
> > 能否提供user_id，如果方便的话，我调试下。user_id是字符串形式，user_id两边一定要加引号。如：
> > ```python
> > user_id_list = ['1669879400', '1729370543']
> > ```
> > 
> > 
> > 还有程序出错时有什么提示吗？如果有，希望提供具体的出错信息，谢谢
> 
> 。。。。
> 暂时没能复现错误。。
> 大佬稍等一阵子！！

好
