### ISSUE TITLE
问题反馈：进度条走但是不读取微博

### ISSUE THREAD

**Issue by AureliusDeng** [dataabc/weiboSpider#81]
大佬我这有个问题，就是程序跑起来过后，进度条的百分数和后边的页数都在走，但就是没有读取到新的微博

我昨天晚上放着电脑跑了一晚上，早上起来3w条微博只跑了200多条

**Comment by dataabc** [comment]
能否提供微博id方便调试，谢谢。
出现这种情况，个人猜测，可能的原因是该微博有大量转发微博，而你设置的可能是爬取原创微博(filter=1)，所以虽然读取了很多微博很多页，只是它们都是转发微博，所以没有保存。
这只是我的猜测，如果不是，如果你方便的话，能否告诉我该微博的id，我测试一下

**Comment by AureliusDeng** [comment]
> 能否提供微博id方便调试，谢谢。
> 出现这种情况，个人猜测，可能的原因是该微博有大量转发微博，而你设置的可能是爬取原创微博(filter=1)，所以虽然读取了很多微博很多页，只是它们都是转发微博，所以没有保存。
> 这只是我的猜测，如果不是，如果你方便的话，能否告诉我该微博的id，我测试一下

我觉得有可能是我自己笨了，等我再跑一次，然后给你反馈

**Comment by dataabc** [comment]
感谢反馈。更新了代码，添加了一个参数since_date。如果只是为了找出错误，不一定要爬全部数量的微博，可以只爬一部分，比如只爬2019年1月1日之后的，设置since_date = '2019-01-01'就可以，这样速度应该快很多，如果想爬全部的微博，可以设置since_date一个较早的时间，比如since_date = '1900-01-01'。而且，下次更新爬取同一个微博的时候，如果你设置since_date为上一次爬取的时间，程序就不会重复爬以前爬过的微博了，而且以前爬过的微博也会保留，效率更高

**Comment by AureliusDeng** [comment]
> 感谢反馈。更新了代码，添加了一个参数since_date。如果只是为了找出错误，不一定要爬全部数量的微博，可以只爬一部分，比如只爬2019年1月1日之后的，设置since_date = '2019-01-01'就可以，这样速度应该快很多，如果想爬全部的微博，可以设置since_date一个较早的时间，比如since_date = '1900-01-01'。而且，下次更新爬取同一个微博的时候，如果你设置since_date为上一次爬取的时间，程序就不会重复爬以前爬过的微博了，而且以前爬过的微博也会保留，效率更高

我以前都是用anaconda带的那个spyder跑的，上上个月还蛮顺利抓了三千多条（非cookie），昨天一开始直接跑不动，是那个status的问题，改换cookie版，能跑，但是就像我一开始说的，跑一会就只有进度条动不抓微博。今天直接用Python.exe跑，刚刚跑到一千多条的时候也停下来了，估计是403的问题被反爬了。

准备调一下流程，先抓最早的，停下来了就重新设定日期换cookie继续抓，但是照这速度3w条微博得停停动动十好几次，过于麻烦了。

或者我应该用你提到过的加什么time_sleep？可是我完全不知道该怎么加啊，我是社科的，对编程完全 不懂

哎主要是我抓的是 习五一 的微博，她的号被新浪压制的厉害，不上cookie估计都看不到

**Comment by AureliusDeng** [comment]
我看了下你新发的版本，里边已经有sleep了啊，还是被限制，只有看看时间调长一点可不可以了

**Comment by dataabc** [comment]
刚刚看了下，这个账号确实需要cookie，可能是因为她的账号特殊吧。可以通过增加暂停时间避免改错误。你可以修改下这段代码：
```
                if page - page1 == random_pages and page < page_num:
                    sleep(random.randint(6, 10))
                    page1 = page
                    random_pages = random.randint(1, 5)
```
random_pages = random.randint(1, 5)表示每1到5页暂停一次，sleep(random.randint(6, 10))表示每次暂停6秒到10秒不等，你可以增加sleep时间，也可以增加暂停的频率

**Comment by AureliusDeng** [comment]
> 刚刚看了下，这个账号确实需要cookie，可能是因为她的账号特殊吧。可以通过增加暂停时间避免改错误。你可以修改下这段代码：
> 
> ```
>                 if page - page1 == random_pages and page < page_num:
>                     sleep(random.randint(6, 10))
>                     page1 = page
>                     random_pages = random.randint(1, 5)
> ```
> 
> random_pages = random.randint(1, 5)表示每1到5页暂停一次，sleep(random.randint(6, 10))表示每次暂停6秒到10秒不等，你可以增加sleep时间，也可以增加暂停的频率

谢谢大佬回复，我已经把暂停时间调长了。希望这次不会被限，不然就只有从头开始一截一截地爬了。
