### ISSUE TITLE
问题反馈：如何爬取userid是纯英文的用户?

### ISSUE THREAD

**Issue by Preshire** [dataabc/weiboSpider#86]
失败后进行调查，发现可能是用户id是纯英文导致。请问能否解决这个问题呢？谢谢！

> Error:  'statuses_count'
> Traceback (most recent call last):
>   File "weibo.py", line 739, in start
>     self.get_pages()
>   File "weibo.py", line 694, in get_pages
>     page_count = self.get_page_count()
>   File "weibo.py", line 475, in get_page_count
>     weibo_count = self.user['statuses_count']
> KeyError: 'statuses_count'

**Comment by dataabc** [comment]
能否提供出错的用户id，如果方便的话。
你说的纯英文id不知道是不是指的用户的个性域名，用户的id应该是一串数字，他如果设置了个性域名，默认显示的就是个性域名，如胡歌的<https://weibo.cn/hu_ge>，点击“资料”，链接就是<https://weibo.cn/user_id/info>的形式，此时的user_id就是数字。你可以把出错id换成数字的id，看看会不会出错。README里也有user_id的获取方法，如果还出错，可以再给我反馈

**Comment by Preshire** [comment]
> 能否提供出错的用户id，如果方便的话。
> 你说的纯英文id不知道是不是指的用户的个性域名，用户的id应该是一串数字，他如果设置了个性域名，默认显示的就是个性域名，如胡歌的https://weibo.cn/hu_ge，点击“资料”，链接就是https://weibo.cn/user_id/info的形式，此时的user_id就是数字。你可以把出错id换成数字的id，看看会不会出错。README里也有user_id的获取方法，如果还出错，可以再给我反馈

原来是这样...已经搞定,非常感谢.是我自己的疏忽,不好意思打搅了
