### ISSUE TITLE
[问题]关于cookies版和无cookies版本爬取数量不一致

### ISSUE THREAD

**Issue by Preshire** [dataabc/weiboSpider#87]
测试过多个微博爬取，都会发生爬取数量会有不一致的情况，且每次都是cookies版多于无cookies版本。内容包括转发已经删除的微博、纯文字等。比较好奇是怎么回事？谢谢

**Comment by dataabc** [comment]
感谢反馈。
这和具体某条微博或微博账号有关。对于<https://m.weibo.cn>，大部分微博可以免登录查看，如<https://m.weibo.cn/detail/4421549346407648>,少量微博需要登录才能查看，如<https://m.weibo.cn/detail/4402254083394033>，所以这部分微博在没有cookie的情况下无法获取。
以迪丽热巴的微博为例，它有1000多条微博，只有30条左右需要登录才能查看，免登录可以获取她的97%左右的微博。很多微博都大致是这个比例。然而，有一些微博账号比较特殊，比如某些zz相关的微博，具体用户名就不说了，这种微博比较特殊，需要登录才能查看，免登录版也就无法获取其内容。
如果不需要爬敏感的微博账号，免cookie版其实完全可以满足要求。如果你也需要爬这些比较zz敏感的微博账号，可以给免cookie版添加cookie，具体方法参考本程序。二者的cookie是通用的，只是免cookie版不管cookie正确与否都可以运行，很难判断cookie是否正确。所以你可以先在本程序中测试下cookie是否正确，如果本程序运行时没有提示cookie错误，cookie就是正确的，就可以把本程序的cookie应用到免cookie版了。
添加cookie的免cookie版就可以获取和本程序一样多的微博了。因为免cookie版的目的之一是免cookie，所以暂时没有添加cookie选项。

**Comment by Preshire** [comment]
> 感谢反馈。
> 这和具体某条微博或微博账号有关。对于https://m.weibo.cn，大部分微博可以免登录查看，如https://m.weibo.cn/detail/4421549346407648,少量微博需要登录才能查看，如https://m.weibo.cn/detail/4402254083394033，所以这部分微博在没有cookie的情况下无法获取。
> 以迪丽热巴的微博为例，它有1000多条微博，只有30条左右需要登录才能查看，免登录可以获取她的97%左右的微博。很多微博都大致是这个比例。然而，有一些微博账号比较特殊，比如某些zz相关的微博，具体用户名就不说了，这种微博比较特殊，需要登录才能查看，免登录版也就无法获取其内容。
> 如果不需要爬敏感的微博账号，免cookie版其实完全可以满足要求。如果你也需要爬这些比较zz敏感的微博账号，可以给免cookie版添加cookie，具体方法参考本程序。二者的cookie是通用的，只是免cookie版不管cookie正确与否都可以运行，很难判断cookie是否正确。所以你可以先在本程序中测试下cookie是否正确，如果本程序运行时没有提示cookie错误，cookie就是正确的，就可以把本程序的cookie应用到免cookie版了。
> 添加cookie的免cookie版就可以获取和本程序一样多的微博了。因为免cookie版的目的之一是免cookie，所以暂时没有添加cookie选项。

非常感谢解惑，其实是因为需要获取具体发布时间然后数据对齐的时候发现数目不一致，以及同样的内容上会有几个符号的不同导致无法快速匹配后才发现的问题。如果能够标注出是否是登录才能看到的微博的话就再好不过了。

说到功能，其实直接将cookie的代码放到无cookie版本上即可实现同样的爬取时间功能，对么？

**Comment by dataabc** [comment]
本程序是通过
```
requests.get(url, cookies='yourcookie')
```
这样的方式爬取指定url的信息的，免cookie版是通过
```
requests.get(url)
```
实现的。要想为免cookie添加cookie，只需要在免cookie的所有requests.get内添加cookie参数和对应的cookie值即可让免cookie版爬取全部微博。
其实免cookie版有一个值没有获取，它在免cookie版获中叫bid，和cookie版中的微博id值是相同的，有了它两者匹配起来会更容易。这两天应该会在免cookie版添加获取bid的功能

**Comment by dataabc** [comment]
已在免cookie版添加了获取微博bid功能，免cookie版的bid与本程序的微博id值相同，你可以通过本程序获取到的微博id与免cookie的bid快速匹配，这样更容易
