### ISSUE TITLE
不能同时爬取多个ID

### ISSUE THREAD

**Issue by aeip2010** [dataabc/weiboSpider#88]
每次只爬取第一个id,如下只爬取了第一个
user_id_list = ['1669879400', '1729370543']

**Comment by dataabc** [comment]
感谢反馈，我测试了下，发现可以爬取多个id。
请问有修改过代码吗？具体改了哪些东西。
还有，如果要爬取的微博账号在日期since_date之后没有发布过微博，这个账号的结果自然就为空。
我怀疑是不是since_date设置的太新了，以上面两个微博为例，如果设置since_date='2019-10-01',则第二个微博爬取为空，因为她2019年10月1日之后就没发过微博，自然没有东西。
不知道是不是这个原因
