### ISSUE TITLE
可以爬取粉丝列表吗？

### ISSUE THREAD

**Issue by lawlawlawJ** [dataabc/weiboSpider#89]
我想找一个微博用户，但是我只知道他的关注列表，所以我想爬以下这些关注用户的followers，然后再把共同followers筛出来，看看能不能找到这个人。
我是个小白，这样能实现吗？

**Comment by Bazinga-QMZ** [comment]
那怎么只爬到前200个用户啊

**Comment by dataabc** [comment]
@Bazinga-QMZ 
以迪丽热巴为例，她的粉丝列表页为<https://weibo.cn/1669879400/fans?page=1>，page=1为第一页，最多有20页，可以用xpath提取每个粉丝的信息。具体可以参考<https://github.com/dataabc/weibo-follow>，这个是爬用户关注列表的信息，与爬粉丝列表类似。

**Comment by Bazinga-QMZ** [comment]
谢谢大佬

**Comment by luckyporo** [comment]
@dataabc 
大佬，我想请教一下如果是自己的粉丝列表有办法可以全部拿到吗？我看了下官方api文档，发现也只能拿到一部分粉丝。

**Comment by dataabc** [comment]
@luckyporo 
这个我也不知道，因为我微博粉丝很少，没有超过200:worried:
