### ISSUE TITLE
要是能加个监控功能就好了

### ISSUE THREAD

**Issue by hui99995** [dataabc/weiboSpider#90]
再服务器上跑个cron定时任务 一但用户有更新就邮件通知

**Comment by dataabc** [comment]
感谢建议，自动更新的功能暂时还没想好。如果只是想监控某些微博，一有更新就发邮件提醒，ifttt可能有类似的功能，可以搜索下；chrome的Distill插件也可以监控网页变化，不过如果你想监控很多微博账号会略麻烦

**Comment by hui99995** [comment]
我现在写了一个感觉不是很完美 就是关注一个用户 这个用户的微博一旦更新 就把他更新的微博通过邮件推送

**Comment by dataabc** [comment]
想法很好。如果需要爬这个用户的微博，在用户更新的时候，自动把新的微博写入结果文件或者数据库也可以，这样就不用重新爬取了

**Comment by hui99995** [comment]
感觉你这个只要只要改一下爬取最新id的那条微博即可 爬取只后把id保存，然后定时执行的时候对id进行比对，当id对不上的时候就爬取id为最新的一条微博即可。

**Comment by dataabc** [comment]
你的思路是对的，现在的程序只需要改很少的代码就能实现类似的功能。
需要改两个地方：
1.添加读文件，读取以前结果文件中的id；
2.爬微博时，判断当前微博id是否在1中读取的id中，若不在，就是新微博，添加到结果文件中；若在，再判断是否为置顶微博，如果是，跳过，否则终止程序。
程序假设第一次你已经把微博全部爬取了。因为微博的发布时间是越来越旧，如果遇到一条非置顶微博，那它之后的微博都是以前爬过的了，所有就可以暂停了。
这是我大致的思路，这样就不用监控微博是否更新了，只需要定期执行程序，如果有更新就加入结果文件，没有就终止，效率很高。

只是，还有一些问题，比如，第一次没有把全部微博爬完（如只爬2017-01-01以后的），以后更新时，也只是更新最新的微博，2017以前的微博还是不会爬。解决办法就是把2中遇到非置顶微博且爬过的情况下，去掉终止代码。只是，如果第一次如果爬完了，这样效率会很低。
也可以已加一个参数，让使用者告诉程序遇到非置顶微博且爬过的情况下，是否终止代码，只是这样参数就变多了，对小白使用者不友好

**Comment by hui99995** [comment]
我不是程序员，我是非常业务的python爱好者，你的代码有的地方我看不懂，这个功能你以后会添加么？应该还要加一个函数把，用来输出最新的一条微博。

**Comment by dataabc** [comment]
是否添加还不确定，因为添加后:
1.对小白使用者可能不友好。因为很多使用者可能只需要把某些微博爬下来，增加参数和功能也会增加学习成本;
2.如果微博量很多，读数据库效率会更高，然而不是每个用户都安装了数据库，这些是我纠结的地方。
不需要输出最新的微博，因为用户可能在短时间更新了多条微博，只考虑最新的可能把其它新微博漏了。所以，程序要从文件中读取以前爬过的id，然后再爬微博，如果id没有出现过，说明是新微博，保存，然后再爬下一条。否则说明微博已经爬过了，那些发布比它早的也就不用爬了，因为之前已经爬过了，程序就退出。
如果要实现此功能，具体要做的是：
1.增加一个读文件的函数，读取结果文件的微博id，以列表形式保存在变量（如self.id_list）里，如果结果文件不存在，说明是第一次爬，变量为空(self.id_list=[])；
2.修改get_one_page方法，修改成如下形式：
```python
    def get_one_page(self, page):
        """获取第page页的全部微博"""
        try:
            url = 'https://weibo.cn/u/%s?page=%d' % (self.user_id, page)
            selector = self.deal_html(url)
            info = selector.xpath("//div[@class='c']")
            is_exist = info[0].xpath("div/span[@class='ctt']")
            if is_exist:
                for i in range(0, len(info) - 2):
                    weibo = self.get_one_weibo(info[i])
                    if weibo:
                        if weibo['id'] in self.weibo_id_list:
                            continue
                        publish_time = datetime.strptime(
                            weibo['publish_time'][:10], "%Y-%m-%d")
                        since_date = datetime.strptime(self.since_date,
                                                       "%Y-%m-%d")
                        if (publish_time <
                                since_date) or (weibo['id'] in self.id_list):
                            if self.is_pinned_weibo(info[i]):
                                continue
                            else:
                                return True
                        self.print_one_weibo(weibo)
                        self.weibo.append(weibo)
                        self.weibo_id_list.append(weibo['id'])
                        self.got_num += 1
                        print('-' * 100)
        except Exception as e:
            print('Error: ', e)
            traceback.print_exc()
```
大致思路就是这样

**Comment by dataabc** [comment]
如果你监控的目的只是更新微博，还有一个很简单的方法：
更改since_date参数，比如你想爬用户从2017-01-01到现在的微博，设置since_date='2017-01-01'就好，下一次更新，只需要把since_date设置成上一次爬取的时间就好了，程序会爬取从上一次到现在的微博，也就是更新了。
例如，你上一次爬取时间是2019-10-01,现在你想更新，只需要since_date='2019-10-01'就好，2019-10-2到现在的微博肯定是新微博，程序也会爬所有2019-10-01发布的微博，如果上一次没有爬过，这次就保存，否则就跳过。这样就能把上次爬取以来所有的新微博获取下来，非常方便。
