### ISSUE TITLE
怎么爬每条微博的所有评论

### ISSUE THREAD

**Issue by skywingfs** [dataabc/weiboSpider#95]
怎么爬每条微博的所有评论~

**Comment by dataabc** [comment]
每条微博都要一个评论页，比如这条<https://weibo.cn/comment/IeUVyhA7a?ckAll=1&page=1>，page=1代表第一页，page=2代表第二页。思路是先获取每一页的内容，然后解析内容中的评论。

不过，评论有限制，爬到一定页数就不显示评论了。这种方法对于有少量评论的微博很实用，对于有大量评论的微博就有限制了，只能爬部分评论。

**Comment by tangbotony** [comment]
@skywingfs 我可以拿到全部的评价数据，非爬虫手段

**Comment by songzy12** [comment]
Duplicate of #64

**Comment by arrogant-create** [comment]
上面有大佬发的评论的运行不了
