### ISSUE TITLE
提个建议，可以把是否爬取微博内容、转发数、点赞数、评论数都设置为可选项

### ISSUE THREAD

**Issue by maoturing** [dataabc/weiboSpider#96]

**Comment by dataabc** [comment]
感谢建议。

你的意思是不是把这些内容都设置成可选项，用户可以选择爬某项，也可以选择不爬，就像图片下载的设置那样。

我起初的想法是尽可能多的爬更多项信息，至少多了某项比少了某项要好，所以不管三七二十一，感觉不错的属性都爬了。

你的建议可以让不需要某些属性的使用者精简内容，让程序更灵活，更自由，是一个非常好的建议。不过这样就多了几个参数需要使用者设置，会增加使用成本。我的想法是，需要使用者设置的参数越少越好，越简单越好。其实这样也不会增加太多使用成本，只是肯定会增加一点。我确实有点纠结:joy:

我再想想是否要这样实现，再次感谢建议。

**Comment by gongqingkui** [comment]
没必要开发这个功能。这些数据你可以不看啊，或者在文件数据库里删掉这些列嘛。

**Comment by BenjaminRen** [comment]
获取这些内容没有额外开销（比如增加一个访问连接等等），都是抓取基本信息同时获取到的，没必要设选项，觉得繁杂的，导出后把相关列删了就是。既然爬了，当然是把所有信息都存下来，至于怎么用怎么筛选，有的是方法。
