### ISSUE TITLE
只能够爬取6个用户？

### ISSUE THREAD

**Issue by Vansir01** [dataabc/weiboSpider#97]
请问大佬，为什么用你的代码只能爬取六个用户 第七个就出现KeyError: 'statuses_count'
是因为api的限制吗  求解答

**Comment by Vansir01** [comment]
感谢大佬的回复 我试了一下改变sleep时间还是同样的问题；每次放五个id进去是可以爬的，超过五个就不行了，很苦恼。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chen Lei <notifications@github.com&gt;
发送时间: 2019年11月22日 16:06
收件人: dataabc/weiboSpider <weiboSpider@noreply.github.com&gt;
抄送: Vansir01 <670708655@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dataabc/weiboSpider] 只能够爬取6个用户？ (#97)




可以爬多于6个用户。
 
看着出错信息，你使用的应该是免cookie版。
 
出现上述错误我怀疑有两个可能的原因，一个是爬的速度太快了，被限制了；另一个就是网络原因，比如网络太慢或者不稳定，导致在获取某一页的时候，没有获取到应有的信息，出错。
 
解决爬取过快的方法是降低爬取速度，具体是修改get_pages方法中的如下代码：
             # 通过加入随机等待避免被限制。爬虫速度过快容易被系统限制(一段时间后限             # 制会自动解除)，加入随机等待模拟人的操作，可降低被系统限制的风险。默             # 认是每爬取1到5页随机等待6到10秒，如果仍然被限，可适当增加sleep时间             if page - page1 == random_pages and page < page_count:                 sleep(random.randint(6, 10))                 page1 = page                 random_pages = random.randint(1, 5)
 
代码含义注释里有，你可以通过增加等待时间，加快等待频率修复错误。

**Comment by dataabc** [comment]
修改random_pages了吗，可以尝试下。

我刚刚尝试爬了8个用户，都没有出错，可能是since_date设的太新，所以平均每个账号只爬了最近的上百条微博。

我怀疑，可能是短时间内爬了过多的微博，所以被限制。因为我连续爬8个用户自11月份以来的微博都没问题，所以应该不会是限制用户数，可能是限制爬的微博的总数。

**如果减慢爬取速度没有效果，可以尝试cookie版本。
其实免cookie版也是可以添加cookie的，添加cookie也可能会避免被限制。**

**Comment by dataabc** [comment]
如果实在不行，你也可以几个几个的爬。

过几天再增量爬取。因为第一次爬，如果要爬用户的全部微博，可能比较耗时。几天之后，用户可能会发新的微博，数量可能比第一次要少的多。这次爬取不需要爬全部微博，只需要爬用户新发布的那些微博就好，因为数量较少，可能不会出现上面的错误了。

增量爬取有两者方式实现，一种是手动，即以后爬的时候把since_date设置成第一次爬的日期。程序就会从那个日期往后爬，直到最新的微博。txt、csv可能会爬到重复的微博，因为上一次爬取的日期爬过一次了。不过这样也保证了不会漏掉微博，而且mysql和mongodb遇到爬过的微博会执行更新而非插入操作，所以数据库是不会重复的。

另一种方式是自动爬。只有第一次爬全部微博，比较费时。以后爬取时，把since_date设置成一个变量，如“当前日期减10”，代表爬取最近10天的微博。然后可以借助第三方软件如crontab定时执行程序，每10天执行一次。这样每次爬的数量都不多，可能不会出现上述错误。

增量爬取以后应该会添加到README里。

**Comment by Vansir01** [comment]
十分感谢大佬的耐心解答。我尝试修改random_page但没用，我现在情况是这样的，我有三万多个用户的id，我把它们放到列表里面依次爬取，但总是爬到第五个就出现statuses的问题了，我想问一下你刚刚说爬了8个用户，是一次性放进去9个用户吗？我不需要他们的全部微博，只需要近一个月的就行。。我好难啊，不过你的代码写的好棒。

如图，我的这个user_id_list里面有三万多个id




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 晚上7:07
收件人:&nbsp;"dataabc/weiboSpider"<weiboSpider@noreply.github.com&gt;;
抄送:&nbsp;"慢慢"<670708655@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weiboSpider] 只能够爬取6个用户？ (#97)




修改random_pages了吗，可以尝试下。
 
我刚刚尝试爬了8个用户，都没有出错，可能是since_date设的太新，所以平均每个账号只爬了最近的上百条微博。
 
我怀疑，可能是短时间内爬了过多的微博，所以被限制。因为我连续爬8个用户自11月份以来的微博都没问题，所以应该不会是限制用户数，可能是限制爬的微博的总数。
 
如果减慢爬取速度没有效果，可以尝试cookie版本。
 其实免cookie版也是可以添加cookie的，添加cookie也可能会避免被限制。

**Comment by dataabc** [comment]
我是一次把8个user_id放到txt里，然后设置了比较新的since_date，可以正确运行。

你可以测试下，比如设置since_date='2019-11-23'之类的，应该可以连续爬超过5个。

如果你想爬近一个月的，可以设置since_date='2019-11-01'，这样程序就只爬11月的了。不过，我担心，你这些user_id中，有的user_id可能发了很多微博，导致虽然只有不到一个月，但是要爬的微博却非常多，导致被限制。

我是建议试试cookie版，看看是否能解决问题。

你也可以试试，先不爬微博，只爬这些user_id的用户信息，把它们存到数据库里，然后按照微博数作个排序，微博数最高的说明改微博发布频率高，即便最近一个月也可能是这些用户中微博最多的，它最后爬，依此类推，微博数最少的最先爬。因为微博数少，很可能它还没达到限制就爬完了，而那些数量大的，可能只爬它一个账号就能达到限制，出错。我的想法是：
1.先爬用户信息，按微博数排序；
2.然后再分组，比如10user_id个或100个1组；
3.从微博数最少的那组爬，如果出错说明每组user_id数量太多，然后减少每组id的数量；
4.对于那些数量特别大的微博可以单独爬，控制下速度；
这样一点点，应该可以爬完，就是速度不快。

只爬微博账号信息不爬微博的方法是为since_date设置一个未来的时间，如since_date='2020-01-01'，因为微博都不满足要求，所以每个微博都只爬了账号信息。当然也要设置写mysql，数据库操作方便点。即便这样，程序也要爬3万多个页面，我估计也可能会被限制，所以如果你想这样爬最好仿照上面控制微博速度的方法，减慢爬账号信息的速度。

我也只想到这些，没有连续爬过这么多账号。真的建议试试cookie版，因为免cookie版好像是统计的ip，如果同一个ip爬的速度过快数量过多就可能被限制。
