### ISSUE TITLE
下载视频失败

### ISSUE THREAD

**Issue by yangzhuang92** [dataabc/weiboSpider#98]
使用一个ID进行了测试，发现只下载成功了10%的视频。主要是访问过于频繁，个人觉得应该把下载图片和视频分开做2个方法，下载视频这块设置更多的sleep时间。或者使用代理去下载视频。

**Comment by dataabc** [comment]
感谢反馈。
这个问题我也遇到过，同样是下载，图片比视频要快的多，即便图片比视频容量大的时候。所以，修改过文件下载的代码，比以前下载视频成功率要的好多，只是时间比较长。而且有时候还会出现视频下载失败的情况，所以又添加了将下载失败的文件写入not_downloaded.txt，里面包含了微博id和文件链接。
你如果想下载视频成功率更高，可以尝试修改下下载的参数
https://github.com/dataabc/weiboSpider/blob/master/weiboSpider.py#L487
前两行代码分别表示下载失败重试的次数和超时的时间，设置更大的数值可以提高下载成功率，但是下载时间可能非常长。
