### ISSUE TITLE
爬虫过程中卡死问题

### ISSUE THREAD

**Issue by purenjie** [dataabc/weiboSpider#99]
你好，我在服务器上爬取央视体育10万+数量微博的时候中途既不会更新爬取也不会报错，会卡在一个地方不动，是不是因为 requests 没有设置 timeout 的问题？卡死这个问题该怎么解决？
如果杀死进程重新下的话是不是会重复爬取数据？

**Comment by dataabc** [comment]
感谢反馈，可能是网络原因，比如网络过慢等，导致程序等待，也可能是被限制了。一般来说，等待一段时间就可以了。

如果你不修改代码，重新爬取会重复，可以通过修改代码解决这个问题。因为目前程序为了防止这类问题，一般都是每爬20页保存一次数据。你可以查看已经保存的结果文件如csv等，查看发布时间最早的那条微博，手动查找它所在的页码，然后修改get_weibo_info方法的如下代码：
```
for page in tqdm(range(1, page_num + 1), desc='Progress'):
```
现在默认是从第一页爬，而你已经爬了很多页了，所以第二次爬时，把range(1, page_num + 1)中的第一个参数换成刚刚手动获取的页码就可以了，程序会从那一页开始爬。

**Comment by purenjie** [comment]
好的，谢谢解答！
